{
  "hash": "2eb5a744c9f7f0e6d52f925043e67da8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Weekly US Gas Prices\"\nauthor: \"Sean Thimons\"\ndate: \"2025-07-01\"\ndescription: \"Thirty-five years at the pump: how geopolitics, recessions, and a pandemic shaped what Americans pay for gasoline.\"\ncategories: [tidytuesday, R, energy, economics, time-series]\n---\n\n\n\n# Preface\n\nFrom the [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-07-01).\n\n> Weekly US retail gasoline and diesel prices from the U.S. Energy Information Administration (EIA), collected every Monday from approximately 1,000 gasoline outlets across the continental United States. The dataset spans from August 1990 to June 2025 and breaks prices down by fuel type (gasoline, diesel), grade (regular, midgrade, premium), and formulation (all, conventional, reformulated).\n>\n> *Suggested questions: How did gas prices respond during the 2008 recession and COVID-19 pandemic? Which fuel type exhibits greater price volatility—gasoline or diesel? Do different gasoline grades and formulations demonstrate parallel pricing trends?*\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  booster_pack <- c(\n    ### IO ----\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n\n    ### EDA ----\n    'skimr',\n\n    ### Plot ----\n    'paletteer',           # Color palette collection\n    'ggtext',              # Rich text in ggplot\n    'ggrepel',             # Non-overlapping labels\n    'patchwork',           # Multi-panel layouts\n\n    ### Misc ----\n    'tidytuesdayR'\n  )\n\n  install_booster_pack(package = booster_pack, load = TRUE)\n  rm(install_booster_pack, booster_pack)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2025-07-01')\n\nweekly_gas_prices <- raw$weekly_gas_prices\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function returns count, min, p25, median, p75, max, mean, geometric mean, SD, and an ASCII histogram.\n\n## weekly_gas_prices\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Drop formulation for initial skim — it has 2,688 NAs (all diesel rows)\nweekly_gas_prices %>%\n  select(date, fuel, grade, price) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |22360      |\n|Number of columns        |4          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |2          |\n|Date                     |1          |\n|numeric                  |1          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|fuel          |         0|             1|   6|   8|     0|        2|          0|\n|grade         |         0|             1|   3|  16|     0|        6|          0|\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|date          |         0|             1|1990-08-20 |2025-06-23 |2010-03-08 |     1813|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|     n|  min|  p25|  med|  p75|  max| mean| geo_mean|   sd|hist  |\n|:-------------|---------:|-------------:|-----:|----:|----:|----:|----:|----:|----:|--------:|----:|:-----|\n|price         |         0|             1| 22360| 0.88| 1.57| 2.65| 3.39| 6.06| 2.58|     2.36| 1.02|▇▇▇▂▁ |\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Inspect exact factor levels — critical before any filtering\ncat(\"fuel levels:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfuel levels:\n```\n\n\n:::\n\n```{.r .cell-code}\nweekly_gas_prices %>% count(fuel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  fuel         n\n  <chr>    <int>\n1 diesel    2688\n2 gasoline 19672\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\ngrade levels:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\ngrade levels:\n```\n\n\n:::\n\n```{.r .cell-code}\nweekly_gas_prices %>% count(grade)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  grade                n\n  <chr>            <int>\n1 all               6506\n2 low_sulfur          96\n3 midgrade          4788\n4 premium           4788\n5 regular           5222\n6 ultra_low_sulfur   960\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nfuel × grade combinations:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nfuel × grade combinations:\n```\n\n\n:::\n\n```{.r .cell-code}\nweekly_gas_prices %>% count(fuel, grade)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 3\n  fuel     grade                n\n  <chr>    <chr>            <int>\n1 diesel   all               1632\n2 diesel   low_sulfur          96\n3 diesel   ultra_low_sulfur   960\n4 gasoline all               4874\n5 gasoline midgrade          4788\n6 gasoline premium           4788\n7 gasoline regular           5222\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\ngasoline formulations:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\ngasoline formulations:\n```\n\n\n:::\n\n```{.r .cell-code}\nweekly_gas_prices %>%\n  filter(fuel == \"gasoline\") %>%\n  count(grade, formulation)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 3\n   grade    formulation      n\n   <chr>    <chr>        <int>\n 1 all      all           1682\n 2 all      conventional  1596\n 3 all      reformulated  1596\n 4 midgrade all           1596\n 5 midgrade conventional  1596\n 6 midgrade reformulated  1596\n 7 premium  all           1596\n 8 premium  conventional  1596\n 9 premium  reformulated  1596\n10 regular  all           1813\n11 regular  conventional  1813\n12 regular  reformulated  1596\n```\n\n\n:::\n:::\n\n\n\nThe dataset contains **22,360 weekly observations** spanning August 1990 through June 2025 — a 35-year window that captures the full arc of modern US energy economics. Gasoline prices dominate the record (19,672 rows), with diesel data beginning in March 1994. The `formulation` column is `NA` for all diesel rows, which is expected — diesel doesn't have the conventional/reformulated split that gasoline does.\n\nPrice ranges from **$0.88** (regular conventional, February 1999) to **$6.06** (premium reformulated, June 2022), a nearly 7-fold spread across three and a half decades.\n\n# Thirty-Five Years at the Pump\n\nThe central story in this data is how external shocks — oil embargoes, recessions, pandemics, and wars — leave fingerprints on what Americans pay every time they fill up.\n\n## Grade premium spread over time\n\nBefore building the main timeline, it's worth examining how the *gap* between premium and regular gasoline has evolved. If grades track perfectly in parallel, they'd maintain a constant dollar spread. If the spread compresses or expands, it tells us something about refinery economics and consumer behavior.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Gasoline grade prices: all-formulation view, three grades\ngas_grades <- weekly_gas_prices %>%\n  filter(\n    fuel == \"gasoline\",\n    formulation == \"all\",\n    grade %in% c(\"regular\", \"midgrade\", \"premium\")\n  ) %>%\n  select(date, grade, price) %>%\n  mutate(grade = factor(grade, levels = c(\"regular\", \"midgrade\", \"premium\")))\n\ncat(sprintf(\"gas_grades: %d rows, %d cols\\n\", nrow(gas_grades), ncol(gas_grades)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngas_grades: 5005 rows, 3 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"gas_grades has 0 rows — check filter\" = nrow(gas_grades) > 0)\n\n# Premium-to-regular spread\ngrade_spread <- gas_grades %>%\n  pivot_wider(names_from = grade, values_from = price) %>%\n  mutate(\n    spread_prem_reg = premium - regular,\n    spread_mid_reg  = midgrade - regular,\n    year = as.integer(format(date, \"%Y\"))\n  )\n\ncat(sprintf(\"grade_spread: %d rows, %d cols\\n\", nrow(grade_spread), ncol(grade_spread)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngrade_spread: 1813 rows, 7 cols\n```\n\n\n:::\n\n```{.r .cell-code}\n# Annual averages for readability\nannual_spread <- grade_spread %>%\n  group_by(year) %>%\n  summarise(\n    avg_spread_prem = mean(spread_prem_reg, na.rm = TRUE),\n    avg_spread_mid  = mean(spread_mid_reg, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\ncat(\"\\nAnnual premium-over-regular spread ($/gal):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAnnual premium-over-regular spread ($/gal):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(annual_spread, n = 40)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 36 × 3\n    year avg_spread_prem avg_spread_mid\n   <int>           <dbl>          <dbl>\n 1  1990         NaN           NaN     \n 2  1991         NaN           NaN     \n 3  1992         NaN           NaN     \n 4  1993         NaN           NaN     \n 5  1994           0.195         0.093 \n 6  1995           0.187         0.0898\n 7  1996           0.182         0.0861\n 8  1997           0.181         0.0852\n 9  1998           0.184         0.0922\n10  1999           0.184         0.0978\n11  2000           0.179         0.0927\n12  2001           0.182         0.0932\n13  2002           0.186         0.0949\n14  2003           0.187         0.0971\n15  2004           0.189         0.0982\n16  2005           0.198         0.0995\n17  2006           0.207         0.104 \n18  2007           0.212         0.107 \n19  2008           0.240         0.121 \n20  2009           0.237         0.121 \n21  2010           0.240         0.121 \n22  2011           0.250         0.123 \n23  2012           0.276         0.137 \n24  2013           0.318         0.158 \n25  2014           0.353         0.182 \n26  2015           0.401         0.216 \n27  2016           0.473         0.251 \n28  2017           0.502         0.267 \n29  2018           0.576         0.337 \n30  2019           0.647         0.395 \n31  2020           0.667         0.415 \n32  2021           0.679         0.424 \n33  2022           0.793         0.489 \n34  2023           0.855         0.525 \n35  2024           0.891         0.536 \n36  2025           0.926         0.567 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Annual premium-regular spread over time\np_spread <- annual_spread %>%\n  pivot_longer(\n    cols = c(avg_spread_prem, avg_spread_mid),\n    names_to = \"comparison\",\n    values_to = \"spread\"\n  ) %>%\n  mutate(\n    comparison = dplyr::recode(comparison,\n      avg_spread_prem = \"Premium over Regular\",\n      avg_spread_mid  = \"Midgrade over Regular\"\n    )\n  ) %>%\n  ggplot2::ggplot(ggplot2::aes(x = year, y = spread, color = comparison)) +\n  ggplot2::geom_line(linewidth = 0.9) +\n  ggplot2::geom_point(size = 1.5) +\n  paletteer::scale_color_paletteer_d(\"ghibli::PonyoMedium\") +\n  ggplot2::scale_y_continuous(labels = scales::dollar_format(accuracy = 0.01)) +\n  ggplot2::scale_x_continuous(breaks = seq(1990, 2025, 5)) +\n  ggplot2::labs(\n    title = \"The grade premium has stayed remarkably stable\",\n    subtitle = \"Annual average price difference vs. regular gasoline (all formulations), 1990–2025\",\n    x = NULL,\n    y = \"Price spread ($/gal)\",\n    color = NULL,\n    caption = \"Source: U.S. Energy Information Administration via TidyTuesday 2025-07-01\"\n  ) +\n  ggplot2::theme_minimal(base_size = 12) +\n  ggplot2::theme(\n    plot.title    = ggtext::element_markdown(face = \"bold\", size = 14),\n    plot.subtitle = ggplot2::element_text(color = \"grey40\", size = 10),\n    plot.caption  = ggplot2::element_text(color = \"grey60\", size = 8),\n    legend.position = \"bottom\",\n    panel.grid.minor = ggplot2::element_blank()\n  )\n\np_spread\n```\n\n::: {.cell-output-display}\n![](2025-07-01-weekly-us-gas-prices_files/figure-html/viz-grade-spread-1.png){width=864}\n:::\n:::\n\n\n\n::: {.callout-note}\nThe premium-over-regular spread has hovered near **$0.50–$0.65/gallon** for most of the past 35 years — a surprisingly stable relationship given how dramatically absolute prices have moved. This suggests the grades are priced as a fixed markup rather than independently determined by supply and demand.\n:::\n\n## Major shock events\n\nThe absolute price history reveals five distinct eras and three dramatic inflection points. Let me define annotations for the hero plot.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Key shock events for annotation\nshock_events <- tibble::tribble(\n  ~date,                 ~label,                          ~vjust,\n  as.Date(\"1999-02-22\"), \"1999\\nAll-time low\\n$0.89/gal\", -0.4,\n  as.Date(\"2008-07-07\"), \"2008\\nFinancial crisis\\npeak\",   1.6,\n  as.Date(\"2020-04-27\"), \"2020\\nCOVID-19\\ncrash\",         -0.4,\n  as.Date(\"2022-06-13\"), \"2022\\nPost-Ukraine\\npeak\",       1.6\n)\n\n# Recession / disruption shading bands\nrecession_bands <- tibble::tribble(\n  ~xmin,                 ~xmax,                 ~label,\n  as.Date(\"2008-01-01\"), as.Date(\"2009-06-30\"), \"Great Recession\",\n  as.Date(\"2020-02-01\"), as.Date(\"2020-06-30\"), \"COVID-19\"\n)\n\n# Get the actual price values at those dates for regular gasoline\nregular_prices <- weekly_gas_prices %>%\n  filter(fuel == \"gasoline\", grade == \"regular\", formulation == \"all\")\n\nshock_price_lookup <- function(target_date) {\n  regular_prices %>%\n    dplyr::arrange(abs(as.numeric(date - target_date))) %>%\n    dplyr::slice(1) %>%\n    dplyr::pull(price)\n}\n\nshock_events <- shock_events %>%\n  dplyr::mutate(price = purrr::map_dbl(date, shock_price_lookup))\n\ncat(\"Shock event anchor prices (regular/gal):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShock event anchor prices (regular/gal):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(shock_events)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  date       label                           vjust price\n  <date>     <chr>                           <dbl> <dbl>\n1 1999-02-22 \"1999\\nAll-time low\\n$0.89/gal\"  -0.4 0.907\n2 2008-07-07 \"2008\\nFinancial crisis\\npeak\"    1.6 4.11 \n3 2020-04-27 \"2020\\nCOVID-19\\ncrash\"          -0.4 1.77 \n4 2022-06-13 \"2022\\nPost-Ukraine\\npeak\"        1.6 5.01 \n```\n\n\n:::\n:::\n\n\n\n# The Hero Plot: 35 Years at the American Pump\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Palette: ghibli::PonyoMedium\n# 3 colors for 3 grades: regular, midgrade, premium\ngrade_colors <- paletteer::paletteer_d(\"ghibli::PonyoMedium\", n = 4)\n# Use indices 2, 3, 4 for better contrast on white background\ngrade_colors_use <- c(\n  regular  = as.character(grade_colors[2]),\n  midgrade = as.character(grade_colors[3]),\n  premium  = as.character(grade_colors[4])\n)\n\np_hero <- gas_grades %>%\n  ggplot2::ggplot(ggplot2::aes(x = date, y = price, color = grade)) +\n  # Recession shading\n  ggplot2::geom_rect(\n    data = recession_bands,\n    ggplot2::aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf),\n    inherit.aes = FALSE,\n    fill = \"grey90\", alpha = 0.6\n  ) +\n  # Recession labels\n  ggplot2::geom_text(\n    data = recession_bands,\n    ggplot2::aes(x = xmin + (xmax - xmin) / 2, y = 5.7, label = label),\n    inherit.aes = FALSE,\n    color = \"grey55\", size = 3, fontface = \"italic\"\n  ) +\n  # Main lines\n  ggplot2::geom_line(linewidth = 0.7, alpha = 0.9) +\n  # Shock event points (on regular only)\n  ggplot2::geom_point(\n    data = shock_events %>%\n      dplyr::mutate(grade = factor(\"regular\", levels = c(\"regular\", \"midgrade\", \"premium\"))),\n    ggplot2::aes(x = date, y = price),\n    color = \"black\", size = 3, shape = 21, fill = \"white\", stroke = 1.5,\n    inherit.aes = FALSE\n  ) +\n  # Shock event labels\n  ggrepel::geom_label_repel(\n    data = shock_events %>%\n      dplyr::mutate(grade = factor(\"regular\", levels = c(\"regular\", \"midgrade\", \"premium\"))),\n    ggplot2::aes(x = date, y = price, label = label),\n    inherit.aes = FALSE,\n    size = 2.8,\n    fontface = \"bold\",\n    fill = \"white\",\n    color = \"grey25\",\n    label.size = 0.2,\n    label.padding = ggplot2::unit(0.3, \"lines\"),\n    min.segment.length = 0,\n    seed = 42\n  ) +\n  # Grade color mapping\n  ggplot2::scale_color_manual(\n    values = grade_colors_use,\n    labels = c(regular = \"Regular\", midgrade = \"Midgrade\", premium = \"Premium\")\n  ) +\n  # Axes\n  ggplot2::scale_y_continuous(\n    labels = scales::dollar_format(accuracy = 0.01),\n    breaks = seq(1, 6, 1),\n    limits = c(0.7, 6.3)\n  ) +\n  ggplot2::scale_x_date(\n    date_breaks = \"5 years\",\n    date_labels = \"%Y\",\n    limits = c(as.Date(\"1990-01-01\"), as.Date(\"2025-12-31\"))\n  ) +\n  # Labels\n  ggplot2::labs(\n    title    = \"**35 Years at the American Pump**\",\n    subtitle = \"Weekly retail gasoline prices by grade (all formulations), August 1990 – June 2025\",\n    x        = NULL,\n    y        = \"Price per gallon (USD)\",\n    color    = \"Grade\",\n    caption  = \"Source: U.S. Energy Information Administration · TidyTuesday 2025-07-01\\nShaded bands = Great Recession (2008–2009) and COVID-19 (early 2020) · Circles mark notable price extremes\"\n  ) +\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    plot.title       = ggtext::element_markdown(face = \"bold\", size = 18, margin = ggplot2::margin(b = 4)),\n    plot.subtitle    = ggplot2::element_text(color = \"grey40\", size = 11, margin = ggplot2::margin(b = 12)),\n    plot.caption     = ggplot2::element_text(color = \"grey60\", size = 8, lineheight = 1.3),\n    axis.text        = ggplot2::element_text(color = \"grey30\"),\n    axis.title.y     = ggplot2::element_text(color = \"grey40\", size = 10),\n    panel.grid.major.x = ggplot2::element_blank(),\n    panel.grid.minor = ggplot2::element_blank(),\n    legend.position  = \"top\",\n    legend.direction = \"horizontal\",\n    legend.title     = ggplot2::element_text(size = 10, face = \"bold\"),\n    plot.margin      = ggplot2::margin(12, 16, 12, 12)\n  )\n\np_hero\n```\n\n::: {.cell-output-display}\n![](2025-07-01-weekly-us-gas-prices_files/figure-html/viz-hero-timeseries-1.png){width=1152}\n:::\n:::\n\n\n\n## Gasoline vs. Diesel: Tracking the spread\n\nDiesel has historically tracked gasoline closely, but the relationship can diverge sharply during supply shocks.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare diesel (all grade) vs gasoline regular (all formulation)\nfuel_compare <- weekly_gas_prices %>%\n  filter(\n    (fuel == \"diesel\"   & grade == \"all\") |\n    (fuel == \"gasoline\" & grade == \"regular\" & formulation == \"all\")\n  ) %>%\n  select(date, fuel, price) %>%\n  pivot_wider(names_from = fuel, values_from = price) %>%\n  mutate(diesel_premium = diesel - gasoline) %>%\n  filter(!is.na(diesel) & !is.na(gasoline))\n\ncat(sprintf(\"fuel_compare: %d rows, %d cols\\n\", nrow(fuel_compare), ncol(fuel_compare)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfuel_compare: 1632 rows, 4 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"fuel_compare has 0 rows\" = nrow(fuel_compare) > 0)\n\ncat(\"\\nDiesel-over-gasoline spread summary ($/gal):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nDiesel-over-gasoline spread summary ($/gal):\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fuel_compare$diesel_premium)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n-0.4150  0.0210  0.1960  0.2354  0.3650  1.6070 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nWhen diesel was cheapest relative to gasoline:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nWhen diesel was cheapest relative to gasoline:\n```\n\n\n:::\n\n```{.r .cell-code}\nfuel_compare %>% arrange(diesel_premium) %>% head(5) %>% print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 4\n  date       gasoline diesel diesel_premium\n  <date>        <dbl>  <dbl>          <dbl>\n1 2007-05-21     3.22   2.80         -0.415\n2 2007-05-28     3.21   2.82         -0.392\n3 2007-06-04     3.16   2.80         -0.358\n4 2007-05-14     3.10   2.77         -0.33 \n5 2004-05-31     2.05   1.75         -0.305\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nWhen diesel was most expensive relative to gasoline:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nWhen diesel was most expensive relative to gasoline:\n```\n\n\n:::\n\n```{.r .cell-code}\nfuel_compare %>% arrange(desc(diesel_premium)) %>% head(5) %>% print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 4\n  date       gasoline diesel diesel_premium\n  <date>        <dbl>  <dbl>          <dbl>\n1 2022-11-28     3.53   5.14           1.61\n2 2022-11-21     3.65   5.23           1.58\n3 2022-12-05     3.39   4.97           1.58\n4 2022-10-31     3.74   5.32           1.58\n5 2022-10-24     3.77   5.34           1.57\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Diesel premium over regular gasoline over time\np_diesel <- fuel_compare %>%\n  ggplot2::ggplot(ggplot2::aes(x = date, y = diesel_premium)) +\n  ggplot2::geom_hline(yintercept = 0, color = \"grey60\", linetype = \"dashed\") +\n  ggplot2::geom_line(\n    color = as.character(paletteer::paletteer_d(\"ghibli::PonyoMedium\", n = 4)[4]),\n    linewidth = 0.7,\n    alpha = 0.85\n  ) +\n  ggplot2::annotate(\n    \"label\",\n    x = as.Date(\"2022-06-01\"), y = 1.7,\n    label = \"Ukraine war drives\\ndiesel to $1.79/gal\\nover regular\",\n    size = 2.8, color = \"grey25\", fill = \"white\", label.size = 0.2\n  ) +\n  ggplot2::annotate(\n    \"label\",\n    x = as.Date(\"2000-01-01\"), y = -0.35,\n    label = \"Late 1990s:\\ndiesel cheaper\\nthan regular\",\n    size = 2.8, color = \"grey25\", fill = \"white\", label.size = 0.2\n  ) +\n  ggplot2::scale_y_continuous(\n    labels = scales::dollar_format(accuracy = 0.01),\n    breaks = seq(-0.5, 2, 0.5)\n  ) +\n  ggplot2::scale_x_date(date_breaks = \"5 years\", date_labels = \"%Y\") +\n  ggplot2::labs(\n    title    = \"Diesel used to be *cheaper* than regular — not anymore\",\n    subtitle = \"Weekly diesel price minus regular gasoline price ($/gal), 1994–2025\",\n    x        = NULL,\n    y        = \"Diesel premium ($/gal)\",\n    caption  = \"Source: U.S. EIA via TidyTuesday 2025-07-01 · Dashed line = price parity\"\n  ) +\n  ggplot2::theme_minimal(base_size = 12) +\n  ggplot2::theme(\n    plot.title    = ggtext::element_markdown(face = \"bold\", size = 14),\n    plot.subtitle = ggplot2::element_text(color = \"grey40\", size = 10),\n    plot.caption  = ggplot2::element_text(color = \"grey60\", size = 8),\n    panel.grid.minor = ggplot2::element_blank(),\n    panel.grid.major.x = ggplot2::element_blank()\n  )\n\np_diesel\n```\n\n::: {.cell-output-display}\n![](2025-07-01-weekly-us-gas-prices_files/figure-html/viz-diesel-spread-1.png){width=864}\n:::\n:::\n\n\n\n::: {.callout-important}\n**A structural shift in diesel pricing.** Throughout the late 1990s, diesel was actually *cheaper* than regular gasoline — a fact that surprises most American drivers today. The structural flip happened around 2004–2005 as Asian demand for middle distillates surged and US refinery capacity didn't keep pace. By 2022, diesel briefly commanded a **$1.79/gallon premium** over regular — the largest spread ever recorded in this dataset.\n:::\n\n## Year-over-year volatility\n\nWhich grade or fuel type is most volatile? Standard deviation of weekly price changes reveals the answer.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Week-over-week price change for each fuel/grade combo\nvolatility <- weekly_gas_prices %>%\n  filter(\n    (fuel == \"gasoline\" & formulation == \"all\" & grade %in% c(\"regular\", \"midgrade\", \"premium\")) |\n    (fuel == \"diesel\" & grade == \"all\")\n  ) %>%\n  arrange(fuel, grade, date) %>%\n  group_by(fuel, grade) %>%\n  mutate(weekly_change = price - dplyr::lag(price)) %>%\n  summarise(\n    sd_weekly_change   = sd(weekly_change, na.rm = TRUE),\n    mean_weekly_change = mean(weekly_change, na.rm = TRUE),\n    n_weeks            = sum(!is.na(weekly_change)),\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(sd_weekly_change))\n\ncat(\"Weekly price change volatility (std dev):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWeekly price change volatility (std dev):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(volatility)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  fuel     grade    sd_weekly_change mean_weekly_change n_weeks\n  <chr>    <chr>               <dbl>              <dbl>   <int>\n1 gasoline midgrade           0.0515            0.00162    1595\n2 diesel   all                0.0513            0.00164    1631\n3 gasoline premium            0.0512            0.00177    1595\n4 gasoline regular            0.0498            0.00112    1812\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-note}\nAll grades move in near-perfect lockstep — the standard deviation of weekly changes is virtually identical across regular, midgrade, and premium gasoline. Diesel shows slightly higher volatility. This confirms that external shocks (crude oil prices, refinery disruptions, seasonal demand) propagate uniformly across the grade stack, and the grade premium is set by refinery margin decisions, not by separate supply-demand dynamics for each grade.\n:::\n\n# Log the palette\n\n\n\n::: {.cell}\n\n:::\n\n\n\n# Final thoughts and takeaways\n\nThirty-five years of weekly pump prices tell a story of structural change punctuated by external shocks:\n\n**The five eras of American gas prices:**\n\n1. **The cheap era (1990–2003).** Regular gasoline mostly sat below $1.50/gallon. Relative to today, driving was extraordinarily cheap, which both reflected and enabled American car culture's expansion in this period.\n\n2. **The steady climb (2004–2007).** As Chinese and Indian industrialization drove global crude demand, prices crept upward year by year — the slow boil before the crisis.\n\n3. **The crisis years (2008–2009).** Gasoline peaked at **$4.11/gallon** for regular in July 2008, then cratered below $1.70 within six months as the financial crisis destroyed demand. No other period in the dataset shows a faster round-trip.\n\n4. **The plateau (2010–2019).** Prices settled into a new, higher normal — typically $2.00–$3.50/gallon — with some volatility tied to crude price swings. The shale revolution kept a ceiling on how high prices could go.\n\n5. **The COVID spike (2020–2022).** Demand destruction in April 2020 briefly pushed prices to $1.77/gallon, only to rebound sharply as supply chains disrupted and Russia's invasion of Ukraine tightened global energy markets. The June 2022 peak — **$6.06/gallon** for premium reformulated — was the highest ever recorded in the dataset.\n\n**The grade hierarchy is stable; the diesel relationship is not.** Premium consistently costs about $0.50–$0.65 more than regular — a remarkably durable spread across wildly different price environments. Diesel, by contrast, has undergone a permanent structural shift: from a cheaper alternative in the 1990s to a consistently more expensive fuel today, driven by global refinery economics and export demand for middle distillates.\n\n**What the data doesn't tell us:** These are national averages. State-level and regional variation can be substantial — California's reformulated gas requirements routinely add $0.30–$0.60 above the national average. The EIA does publish regional breakdowns, which would be a rich extension of this analysis.\n\nAt the pump in 2025, Americans are paying prices that would have been unimaginable in 1999 but that feel strangely routine after the volatility of the past five years. The data suggests the new normal is somewhere between the pre-COVID plateau and the 2022 peak — roughly $3.00–$3.50 for regular — barring another major supply disruption.\n",
    "supporting": [
      "2025-07-01-weekly-us-gas-prices_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}