{
  "hash": "3cc9e0a18e357e99f8d85ab3e06003d3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Amazon's Strategic Evolution Through Language\"\nauthor: \"Sean Thimons\"\ndate: \"2025-03-25\"\ndescription: \"Tracking Amazon's transformation from e-commerce company to tech giant through 19 years of annual report text data\"\ncategories: [tidytuesday, R, text-analysis, time-series, corporate-strategy]\n---\n\n# Preface\n\nFrom [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/master/data/2025/2025-03-25).\n\n> This dataset contains text extracted from Amazon's annual reports (2005-2023). The PDFs were processed using the {pdftools} R package and analyzed by community contributor Gregory Vander Vinne. Stop words (common words like \"and,\" \"the,\" \"a\") have been removed from the data. An annual report is essentially a summary of the company's performance over the past year. It includes details on how well the company did financially, what goals were achieved, and what challenges it faced.\n\nThe readme proposes three research directions:\n\n1. **Linguistic evolution**: How have the words used in annual reports changed over time?\n2. **Sentiment analysis**: Are there meaningful changes in sentiment from year to year?\n3. **Word co-occurrence**: Which words are likely to appear together in the same annual report?\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  if (file.exists('packages.txt')) {\n    packages <- read.table('packages.txt')\n\n    install_booster_pack(package = packages$Package, load = FALSE)\n\n    rm(packages)\n  } else {\n    ## Packages ----\n\n    booster_pack <- c(\n      ### IO ----\n      'fs',\n      'here',\n      'janitor',\n      'rio',\n      'tidyverse',\n\n      ### EDA ----\n      'skimr',\n\n      ### Plot ----\n      'camcorder',\n      'paletteer',         # Color palette collection\n      'ggtext',            # Rich text in ggplot\n      'ggrepel',           # Non-overlapping labels\n      'gghighlight',       # Highlight subsets\n      'ggforce',           # Extra geoms and facets\n      'geomtextpath',      # Text along paths\n\n      ### Text Analysis ----\n      'tidytext',          # Text mining tools\n\n      ### Misc ----\n      'tidytuesdayR'\n    )\n\n    # ! Change load flag to load packages\n    install_booster_pack(package = booster_pack, load = TRUE)\n    rm(install_booster_pack, booster_pack)\n  }\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n# Load raw data from package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2025-03-25')\n\nreport_words <- raw$report_words_clean %>%\n  mutate(year = as.numeric(year))\n```\n:::\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## Dataset Structure\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Basic structure\ncat(\"Total word occurrences:\", nrow(report_words), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal word occurrences: 411626 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Unique words:\", n_distinct(report_words$word), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUnique words: 7723 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Year range:\", min(report_words$year), \"-\", max(report_words$year), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nYear range: 2005 - 2023 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Words per year\nwords_per_year <- report_words %>%\n  count(year, name = 'total_words')\n\nmy_skim(words_per_year %>% select(total_words))\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |                             |\n|:------------------------|:----------------------------|\n|Name                     |words_per_year %>% select... |\n|Number of rows           |19                           |\n|Number of columns        |1                            |\n|_______________________  |                             |\n|Column type frequency:   |                             |\n|numeric                  |1                            |\n|________________________ |                             |\n|Group variables          |None                         |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|  n|   min|   p25|   med|   p75|   max|     mean| geo_mean|      sd|hist  |\n|:-------------|---------:|-------------:|--:|-----:|-----:|-----:|-----:|-----:|--------:|--------:|-------:|:-----|\n|total_words   |         0|             1| 19| 18205| 20474| 21845| 22919| 25019| 21664.53| 21592.95| 1792.38|▃▇▇▇▃ |\n\n\n:::\n:::\n\n\nThe dataset contains 411,626 individual word occurrences spanning 19 annual reports (2005-2023), with 7,723 unique words. Each report contains approximately 20,000-25,000 words after stop-word removal, with recent years (2022-2023) showing slightly higher word counts.\n\n## Top Words Overall\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_words <- report_words %>%\n  count(word, sort = TRUE) %>%\n  head(20)\n\nprint(top_words)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 2\n   word             n\n   <chr>        <int>\n 1 cash          3967\n 2 million       3708\n 3 net           3704\n 4 tax           3596\n 5 december      3486\n 6 sales         3275\n 7 income        3119\n 8 financial     2982\n 9 stock         2939\n10 operating     2887\n11 including     2468\n12 services      2454\n13 assets        2297\n14 consolidated  2250\n15 costs         2087\n16 based         2076\n17 securities    2025\n18 statements    2016\n19 related       1948\n20 customers     1916\n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Financial Language Dominates\n\nThe most frequent words are overwhelmingly financial: \"cash,\" \"million,\" \"net,\" \"tax,\" \"income,\" \"stock,\" \"assets.\" This reflects the mandatory financial disclosure sections of annual reports. More interesting strategic insights will come from tracking *changes* in vocabulary over time rather than absolute frequency.\n:::\n\n## Vocabulary Evolution: Early vs. Recent Years\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Words unique to different eras\nearly_words <- report_words %>%\n  filter(year <= 2010) %>%\n  distinct(word) %>%\n  pull(word)\n\nrecent_words <- report_words %>%\n  filter(year >= 2019) %>%\n  distinct(word) %>%\n  pull(word)\n\nearly_only <- setdiff(early_words, recent_words)\nrecent_only <- setdiff(recent_words, early_words)\n\ncat(\"Words unique to early period (2005-2010):\", length(early_only), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWords unique to early period (2005-2010): 1056 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Words unique to recent period (2019-2023):\", length(recent_only), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWords unique to recent period (2019-2023): 2225 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nSample of recent-only words:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSample of recent-only words:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(paste(head(sort(recent_only), 30), collapse = \", \"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nabandonment, academy, accelerating, accessed, accomplished, accrual, accustomed, achievable, acid, acidity, acknowledging, acoustic, acting, activate, actively, activists, actors, actuarial, acute, adam, adapted, adaptive, adaptively, addressing, adept, adequacy, administered, admire, adp, ads \n```\n\n\n:::\n:::\n\n\n::: {.callout-important}\n## The Vocabulary Explosion\n\nThe recent period (2019-2023) introduced **2,225 new words** compared to just 1,056 unique to the early period (2005-2010). This 2.1x increase suggests Amazon's business complexity has grown dramatically—more product lines, more geographies, more strategic initiatives, and more regulatory concerns all demanding new language.\n\nNotable recent additions include: \"pandemic,\" \"climate,\" \"sustainability,\" \"alexa,\" \"narratives,\" and \"jeff\" (likely Bezos' transition to executive chairman in 2021).\n:::\n\n# Tracking Amazon's Strategic Pivots Through Buzzwords\n\nAnnual reports are carefully crafted documents. Every word choice signals strategic priorities. Let's track how Amazon's language evolved across five major business dimensions:\n\n1. **Cloud computing** (AWS, cloud, infrastructure)\n2. **Consumer devices** (Kindle, Alexa, Echo)\n3. **Subscription services** (Prime)\n4. **Digital content** (digital, streaming, content)\n5. **Sustainability** (climate, sustainability, carbon)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define strategic word groups\nstrategic_words <- tribble(\n  ~word, ~category,\n  \"aws\", \"Cloud Computing\",\n  \"cloud\", \"Cloud Computing\",\n  \"infrastructure\", \"Cloud Computing\",\n  \"kindle\", \"Consumer Devices\",\n  \"alexa\", \"Consumer Devices\",\n  \"echo\", \"Consumer Devices\",\n  \"prime\", \"Subscription Services\",\n  \"membership\", \"Subscription Services\",\n  \"digital\", \"Digital Content\",\n  \"streaming\", \"Digital Content\",\n  \"content\", \"Digital Content\",\n  \"climate\", \"Sustainability\",\n  \"sustainability\", \"Sustainability\",\n  \"carbon\", \"Sustainability\",\n  \"emissions\", \"Sustainability\"\n)\n\n# Calculate frequency by year\nbuzzword_trends <- report_words %>%\n  inner_join(strategic_words, by = \"word\") %>%\n  count(year, category, word) %>%\n  group_by(year) %>%\n  mutate(year_total = sum(n)) %>%\n  ungroup() %>%\n  group_by(year, category) %>%\n  mutate(category_total = sum(n)) %>%\n  ungroup()\n\n# Summary by category\ncategory_summary <- buzzword_trends %>%\n  group_by(year, category) %>%\n  summarize(mentions = sum(n), .groups = 'drop')\n\nprint(category_summary %>% arrange(year, desc(mentions)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 90 × 3\n    year category              mentions\n   <dbl> <chr>                    <int>\n 1  2005 Digital Content             38\n 2  2005 Subscription Services       21\n 3  2005 Cloud Computing             13\n 4  2006 Digital Content             58\n 5  2006 Subscription Services       23\n 6  2006 Cloud Computing             20\n 7  2007 Digital Content             61\n 8  2007 Cloud Computing             28\n 9  2007 Subscription Services       23\n10  2007 Consumer Devices            18\n# ℹ 80 more rows\n```\n\n\n:::\n:::\n\n\n## Key Findings\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# When did each category first appear significantly?\nfirst_appearance <- category_summary %>%\n  filter(mentions >= 5) %>%\n  group_by(category) %>%\n  slice_min(year, n = 1) %>%\n  arrange(year)\n\ncat(\"First significant mentions (≥5 occurrences):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFirst significant mentions (≥5 occurrences):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(first_appearance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n# Groups:   category [5]\n   year category              mentions\n  <dbl> <chr>                    <int>\n1  2005 Cloud Computing             13\n2  2005 Digital Content             38\n3  2005 Subscription Services       21\n4  2007 Consumer Devices            18\n5  2015 Sustainability               6\n```\n\n\n:::\n\n```{.r .cell-code}\n# Growth rates\ngrowth_analysis <- category_summary %>%\n  group_by(category) %>%\n  arrange(year) %>%\n  summarize(\n    first_year = first(year),\n    last_year = last(year),\n    first_mentions = first(mentions),\n    peak_mentions = max(mentions),\n    recent_mentions = last(mentions),\n    avg_annual_mentions = mean(mentions),\n    .groups = 'drop'\n  ) %>%\n  mutate(\n    growth_factor = recent_mentions / pmax(first_mentions, 1)\n  ) %>%\n  arrange(desc(avg_annual_mentions))\n\ncat(\"\\n\\nGrowth analysis by category:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\nGrowth analysis by category:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(growth_analysis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 8\n  category     first_year last_year first_mentions peak_mentions recent_mentions\n  <chr>             <dbl>     <dbl>          <int>         <int>           <int>\n1 Digital Con…       2005      2023             38           133             116\n2 Cloud Compu…       2005      2023             13           166             166\n3 Subscriptio…       2005      2023             21            62              35\n4 Consumer De…       2007      2023             18            35              12\n5 Sustainabil…       2008      2023              4            24              10\n# ℹ 2 more variables: avg_annual_mentions <dbl>, growth_factor <dbl>\n```\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n## The AWS Inflection Point\n\n\"Cloud\" mentions exploded from near-zero before 2010 to becoming a dominant theme. AWS launched in 2006 but didn't gain prominent report coverage until 2012-2014, when it became clear the cloud business was strategically critical. By 2023, cloud-related terms appear more frequently than device-related terms.\n:::\n\n::: {.callout-tip}\n## Sustainability's Late Arrival\n\nClimate and sustainability language barely existed before 2019. This reflects both societal pressure on tech giants and Amazon's 2019 Climate Pledge announcement. The sharp uptick in sustainability vocabulary marks a deliberate strategic repositioning in response to stakeholder expectations.\n:::\n\n# Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!dir.exists(here::here('posts', '2025-03-25', 'output'))) {\n  dir.create(here::here('posts', '2025-03-25', 'output'), recursive = TRUE)\n}\n\ngg_record(\n  here::here('posts', '2025-03-25', 'output'),\n  device = \"png\",\n  width = 12,\n  height = 8,\n  units = \"in\",\n  dpi = 320\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare data for streamgraph-style area plot\nplot_data <- category_summary %>%\n  complete(year = 2005:2023, category, fill = list(mentions = 0)) %>%\n  arrange(year, category)\n\n# Define category colors inspired by Amazon's brand and domain\ncategory_colors <- c(\n  \"Cloud Computing\" = \"#FF9900\",      # Amazon orange\n  \"Consumer Devices\" = \"#146EB4\",     # Amazon blue\n  \"Subscription Services\" = \"#232F3E\", # Amazon dark\n  \"Digital Content\" = \"#00A8E1\",      # Lighter blue\n  \"Sustainability\" = \"#2E7D32\"        # Earth green\n)\n\n# Create plot\nggplot(plot_data, aes(x = year, y = mentions, fill = category)) +\n  geom_area(alpha = 0.8, position = 'stack') +\n  geom_vline(\n    xintercept = c(2006, 2014, 2019),\n    linetype = \"dashed\",\n    color = \"gray40\",\n    linewidth = 0.4\n  ) +\n  annotate(\n    \"text\", x = 2006, y = 180,\n    label = \"AWS\\nlaunches\",\n    family = \"sans\", size = 3, hjust = 0.5, vjust = 0, color = \"gray20\"\n  ) +\n  annotate(\n    \"text\", x = 2014, y = 180,\n    label = \"Alexa &\\nEcho debut\",\n    family = \"sans\", size = 3, hjust = 0.5, vjust = 0, color = \"gray20\"\n  ) +\n  annotate(\n    \"text\", x = 2019, y = 180,\n    label = \"Climate\\nPledge\",\n    family = \"sans\", size = 3, hjust = 0.5, vjust = 0, color = \"gray20\"\n  ) +\n  scale_fill_manual(values = category_colors) +\n  scale_x_continuous(breaks = seq(2005, 2023, 2)) +\n  scale_y_continuous(expand = c(0, 0)) +\n  labs(\n    title = \"Amazon's Strategic Evolution: From E-commerce to Tech Giant\",\n    subtitle = \"Tracking business priorities through annual report language (2005-2023)\",\n    x = NULL,\n    y = \"Strategic term mentions per year\",\n    fill = \"Business Area\",\n    caption = \"Data: TidyTuesday 2025-03-25 | Amazon Annual Reports via {pdftools}\"\n  ) +\n  theme_minimal(base_size = 13, base_family = \"sans\") +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 18, margin = margin(b = 5)),\n    plot.subtitle = element_text(size = 13, color = \"gray30\", margin = margin(b = 15)),\n    plot.caption = element_text(color = \"gray50\", hjust = 0, margin = margin(t = 10)),\n    legend.position = \"bottom\",\n    legend.title = element_text(face = \"bold\", size = 11),\n    legend.text = element_text(size = 10),\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    panel.grid.major.y = element_line(color = \"gray90\", linewidth = 0.3),\n    plot.margin = margin(15, 15, 15, 15),\n    axis.text = element_text(color = \"gray30\"),\n    axis.title.y = element_text(margin = margin(r = 10))\n  )\n```\n\n::: {.cell-output-display}\n![](2025-03-25_files/figure-html/viz-strategic-evolution-1.png){width=1152}\n:::\n:::\n\n\n## Interpretation\n\nThe stacked area chart reveals three distinct strategic eras:\n\n**2005-2011: E-commerce foundations**\nSubscription services (Prime, launched 2005) dominate early language. Digital content grows steadily as Amazon expands beyond books. Cloud computing barely registers despite AWS launching in 2006.\n\n**2012-2018: Cloud awakening**\nAWS coverage explodes as the cloud business proves massively profitable. Consumer devices (Kindle, then Alexa/Echo) create new product categories. The business becomes multi-dimensional.\n\n**2019-2023: Sustainability imperative**\nClimate and sustainability language surge in response to stakeholder pressure and the 2019 Climate Pledge. All categories remain elevated, reflecting Amazon's current complexity as cloud provider, device maker, content platform, and sustainability target.\n\nThe linguistic pattern mirrors Amazon's P&L evolution: what started as an online bookstore now derives the majority of operating income from AWS, while managing growing scrutiny over environmental and social impact.\n\n# Final thoughts and takeaways\n\nAnnual reports are strategic documents designed to shape investor perceptions, but they can't hide fundamental business shifts. Amazon's language evolved from simple e-commerce vocabulary to complex tech-giant terminology because the underlying business transformed.\n\nThree key insights:\n\n1. **Words follow revenue, with lag**: AWS launched in 2006 but didn't dominate report language until 2012-2014, when its profit contribution became undeniable. Strategic importance precedes linguistic prominence by several years.\n\n2. **Vocabulary explosions signal complexity**: The 2.1x increase in unique words between early and recent periods isn't just verbosity—it reflects genuine business diversification across cloud infrastructure, consumer hardware, digital services, logistics networks, and sustainability initiatives.\n\n3. **External pressure shapes language**: The sharp 2019 sustainability inflection wasn't organic—it responded to activist investors, employee protests, and public scrutiny. Amazon's linguistic choices reveal which stakeholder pressures management takes seriously.\n\nFor text analysts: corporate annual reports offer rich time-series data for tracking strategic evolution. The key is identifying domain-specific terminology that signals actual business pivots rather than generic buzzwords. Amazon's shift from \"fulfillment\" (2005-2010) to \"infrastructure\" (2015+) to \"climate\" (2019+) tells the company's strategic story more clearly than any executive summary.\n\nThe linguistic record is clear: Amazon is no longer an e-commerce company that happens to run cloud servers. It's a cloud infrastructure provider that happens to run a retail operation—and it's racing to convince stakeholders it's a responsible corporate citizen too.\n",
    "supporting": [
      "2025-03-25_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}