{
  "hash": "2e7a0348fa07928c5ef22a1f183c36b5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: One Million Digits of Pi\"\nauthor: \"Sean Thimons\"\ndate: \"2026-03-24\"\ndescription: \"Are pi's digits truly random? Exploring digit frequency, uniformity tests, and convergence across one million decimal places.\"\ncategories: [tidytuesday, R, mathematics, statistics]\n---\n\n\n\n# Preface\n\nFrom the [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2026/2026-03-24).\n\n> This week's dataset contains the first one million digits of pi (π), released in honor of Pi Day (March 14). The data includes each digit's position in the decimal expansion and the digit itself (0–9). A longstanding open question in number theory is whether pi is a **normal number** — meaning every digit (and every finite string of digits) appears with equal frequency in the long run. While this has never been formally proven, empirical evidence from millions of digits strongly suggests it is true.\n>\n> **Suggested questions:** Are all ten digits equally represented? Do digits follow each other uniformly (i.e., is there no \"memory\" in pi's decimal expansion)? Where in pi's expansion do frequencies stabilize near 10%?\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  booster_pack <- c(\n    ### IO ----\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n\n    ### EDA ----\n    'skimr',\n\n    ### Plot ----\n    'paletteer',           # Color palette collection (includes vapoRwave palettes)\n    'ggrepel',             # Non-overlapping labels\n\n    ### Misc ----\n    'tidytuesdayR'\n  )\n\n  install_booster_pack(package = booster_pack, load = TRUE)\n  rm(install_booster_pack, booster_pack)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load(\"2026-03-24\")\n\npi_digits <- raw$pi_digits\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## Pi digits\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Drop digit_position for skim (it's just a row index)\npi_digits %>%\n  select(digit) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |1000001    |\n|Number of columns        |1          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|numeric                  |1          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|       n| min| p25| med| p75| max| mean| geo_mean|   sd|hist  |\n|:-------------|---------:|-------------:|-------:|---:|---:|---:|---:|---:|----:|--------:|----:|:-----|\n|digit         |         0|             1| 1000001|   0|   2|   4|   7|   9|  4.5|     4.15| 2.87|▇▇▇▇▇ |\n\n\n:::\n:::\n\n\n\nThe digit column is a single integer (0–9), with a perfectly centered distribution around 4.5. The near-uniform spread from 0 to 9 — and a symmetrically shaped ASCII histogram — is exactly what we'd expect from a normal number. But \"looks like a uniform distribution\" is a long way from statistical confirmation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Digit frequency table\nfreq_table <- pi_digits %>%\n  count(digit) %>%\n  mutate(\n    pct      = n / sum(n) * 100,\n    expected = nrow(pi_digits) / 10,\n    deviation = n - expected\n  )\n\nfreq_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 5\n   digit      n   pct expected deviation\n   <dbl>  <int> <dbl>    <dbl>     <dbl>\n 1     0  99959 10.00  100000.     -41.1\n 2     1  99758  9.98  100000.    -242. \n 3     2 100026 10.0   100000.      25.9\n 4     3 100230 10.0   100000.     230. \n 5     4 100230 10.0   100000.     230. \n 6     5 100359 10.0   100000.     359. \n 7     6  99548  9.95  100000.    -452. \n 8     7  99800  9.98  100000.    -200. \n 9     8  99985 10.00  100000.     -15.1\n10     9 100106 10.0   100000.     106. \n```\n\n\n:::\n:::\n\n\n\nAcross one million digits, every digit appears between 99,548 times (digit 6) and 100,359 times (digit 5). The expected count under perfect uniformity is 100,000.1. No digit deviates by more than 360 occurrences — a fraction of a percent.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Chi-square test of uniformity\nchi_result <- chisq.test(freq_table$n, p = rep(0.1, 10))\nchi_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  freq_table$n\nX-squared = 5.5137, df = 9, p-value = 0.7874\n```\n\n\n:::\n:::\n\n\n\nThe chi-square statistic is **X² = 5.51** on 9 degrees of freedom, with **p = 0.787**. We emphatically fail to reject uniformity. One million digits in, the evidence for pi being a \"normal number\" — where each digit appears in equal proportion — is strong.\n\n::: {.callout-note}\n## What is a normal number?\n\nA **normal number** is one where, in any base, every finite sequence of digits appears with equal frequency. Pi has never been *proven* normal, but decades of computation have found no evidence against it. The first million digits offer a compelling empirical case.\n:::\n\n# Pi's Hidden Uniformity: Digit Frequency and Convergence\n\n## Overall digit frequency\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npi_palette <- paletteer::paletteer_d(\"vapoRwave::vapoRwave\", n = 10)\n\np_freq <- freq_table %>%\n  mutate(\n    digit   = factor(digit),\n    label   = sprintf(\"%+.0f\", deviation)\n  ) %>%\n  ggplot2::ggplot(ggplot2::aes(x = digit, y = pct, fill = digit)) +\n  ggplot2::geom_col(width = 0.7, color = \"grey15\", linewidth = 0.3) +\n  ggplot2::geom_hline(\n    yintercept = 10,\n    linetype = \"dashed\",\n    color = \"white\",\n    linewidth = 0.8,\n    alpha = 0.7\n  ) +\n  ggplot2::geom_text(\n    ggplot2::aes(label = label, y = pct + 0.08),\n    color = \"white\",\n    size = 3.2,\n    fontface = \"bold\"\n  ) +\n  ggplot2::scale_fill_manual(values = pi_palette) +\n  ggplot2::scale_y_continuous(\n    limits = c(0, 11),\n    breaks = c(0, 5, 10),\n    labels = c(\"0%\", \"5%\", \"10%\")\n  ) +\n  ggplot2::labs(\n    title    = \"All ten digits appear almost exactly 10% of the time\",\n    subtitle = \"Deviation from expected 100,000 occurrences shown above each bar\",\n    x        = \"Digit\",\n    y        = \"Frequency (%)\",\n    caption  = \"Source: TidyTuesday 2026-03-24 · One Million Digits of Pi\"\n  ) +\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    plot.background  = ggplot2::element_rect(fill = \"#0d0d1a\", color = NA),\n    panel.background = ggplot2::element_rect(fill = \"#0d0d1a\", color = NA),\n    panel.grid.major.y = ggplot2::element_line(color = \"#2a2a4a\", linewidth = 0.4),\n    panel.grid.major.x = ggplot2::element_blank(),\n    panel.grid.minor   = ggplot2::element_blank(),\n    text               = ggplot2::element_text(color = \"white\"),\n    plot.title         = ggplot2::element_text(color = \"white\", face = \"bold\", size = 14),\n    plot.subtitle      = ggplot2::element_text(color = \"#aaaacc\", size = 11),\n    plot.caption       = ggplot2::element_text(color = \"#666699\", size = 9),\n    axis.text          = ggplot2::element_text(color = \"#ccccdd\"),\n    axis.title         = ggplot2::element_text(color = \"#aaaacc\"),\n    legend.position    = \"none\"\n  )\n\np_freq\n```\n\n::: {.cell-output-display}\n![](2026-03-24-one-million-digits-of-pi_files/figure-html/digit-freq-plot-1.png){width=864}\n:::\n:::\n\n\n\n## The convergence story: running digit frequencies\n\nThe real drama in pi's digits is the *journey* to uniformity, not just the destination. At position 10, we've only seen a handful of digits — frequencies are wildly variable. But as we march deeper into the decimal expansion, each digit's running frequency inexorably converges toward the 10% mark.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute running cumulative frequency for each digit at evenly-spaced checkpoints.\n# Efficient approach: extract the ordered digit vector, then use cumsum per digit.\ncheckpoints <- seq(500, 1000000, by = 500)   # 2,000 checkpoints\n\ndigits_vec <- pi_digits %>%\n  arrange(digit_position) %>%\n  pull(digit)\n\nrunning_freq <- lapply(0:9, function(d) {\n  cum_d <- cumsum(as.integer(digits_vec == d))\n  data.frame(\n    checkpoint  = checkpoints,\n    digit       = factor(d, levels = 0:9),\n    cum_count   = cum_d[checkpoints],\n    running_pct = cum_d[checkpoints] / checkpoints * 100\n  )\n}) %>%\n  bind_rows()\n\ncat(sprintf(\"running_freq: %d rows, %d cols\\n\", nrow(running_freq), ncol(running_freq)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrunning_freq: 20000 rows, 4 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"running_freq has 0 rows\" = nrow(running_freq) > 0)\n\n# Sanity check: at position 1,000,000, all digits should be ~10%\ntail_check <- running_freq %>%\n  filter(checkpoint == max(checkpoint))\ncat(\"Final frequencies at position 1,000,000:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFinal frequencies at position 1,000,000:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(tail_check)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   checkpoint digit cum_count running_pct\n1       1e+06     0     99959      9.9959\n2       1e+06     1     99757      9.9757\n3       1e+06     2    100026     10.0026\n4       1e+06     3    100230     10.0230\n5       1e+06     4    100230     10.0230\n6       1e+06     5    100359     10.0359\n7       1e+06     6     99548      9.9548\n8       1e+06     7     99800      9.9800\n9       1e+06     8     99985      9.9985\n10      1e+06     9    100106     10.0106\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Endpoint labels for annotation\nendpoints <- running_freq %>%\n  group_by(digit) %>%\n  filter(checkpoint == max(checkpoint)) %>%\n  ungroup()\n\np_convergence <- running_freq %>%\n  ggplot2::ggplot(ggplot2::aes(\n    x     = checkpoint / 1000,\n    y     = running_pct,\n    color = digit,\n    group = digit\n  )) +\n  # Reference band: +/- 0.5% around 10%\n  ggplot2::annotate(\n    \"rect\",\n    xmin = -Inf, xmax = Inf,\n    ymin = 9.5, ymax = 10.5,\n    fill = \"white\", alpha = 0.06\n  ) +\n  # Perfect uniformity line\n  ggplot2::geom_hline(\n    yintercept = 10,\n    linetype = \"dashed\",\n    color = \"white\",\n    linewidth = 0.6,\n    alpha = 0.5\n  ) +\n  ggplot2::geom_line(linewidth = 0.65, alpha = 0.9) +\n  # Endpoint dots\n  ggplot2::geom_point(\n    data = endpoints,\n    ggplot2::aes(x = checkpoint / 1000, y = running_pct),\n    size = 2.5\n  ) +\n  # Digit labels at the end\n  ggrepel::geom_text_repel(\n    data = endpoints,\n    ggplot2::aes(\n      x     = checkpoint / 1000,\n      y     = running_pct,\n      label = paste0(\"π[\", digit, \"]\"),\n      color = digit\n    ),\n    parse         = TRUE,\n    size          = 3.5,\n    fontface      = \"bold\",\n    direction     = \"y\",\n    nudge_x       = 15,\n    segment.size  = 0.3,\n    segment.alpha = 0.5,\n    min.segment.length = 0.2,\n    box.padding   = 0.2,\n    max.overlaps  = 20,\n    show.legend   = FALSE\n  ) +\n  ggplot2::scale_color_manual(values = pi_palette) +\n  ggplot2::scale_x_continuous(\n    limits = c(0, 1150),\n    breaks = c(0, 200, 400, 600, 800, 1000),\n    labels = c(\"0\", \"200K\", \"400K\", \"600K\", \"800K\", \"1M\")\n  ) +\n  ggplot2::scale_y_continuous(\n    breaks = c(9, 9.5, 10, 10.5, 11),\n    labels = c(\"9%\", \"9.5%\", \"10%\", \"10.5%\", \"11%\")\n  ) +\n  ggplot2::labs(\n    title    = \"π converges to uniformity — one million digits at a time\",\n    subtitle = \"Running frequency of each digit (0–9) as we move through π's decimal expansion.\\nThe dashed line marks perfect uniformity at 10%. All ten digits converge tightly by ~100,000 positions.\",\n    x        = \"Position in π's decimal expansion\",\n    y        = \"Running frequency (%)\",\n    caption  = \"Source: TidyTuesday 2026-03-24 · One Million Digits of Pi\"\n  ) +\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    plot.background    = ggplot2::element_rect(fill = \"#0d0d1a\", color = NA),\n    panel.background   = ggplot2::element_rect(fill = \"#0d0d1a\", color = NA),\n    panel.grid.major   = ggplot2::element_line(color = \"#1e1e38\", linewidth = 0.4),\n    panel.grid.minor   = ggplot2::element_blank(),\n    text               = ggplot2::element_text(color = \"white\"),\n    plot.title         = ggplot2::element_text(\n      color = \"white\", face = \"bold\", size = 15, margin = ggplot2::margin(b = 6)\n    ),\n    plot.subtitle      = ggplot2::element_text(\n      color = \"#9999bb\", size = 10.5, lineheight = 1.4,\n      margin = ggplot2::margin(b = 12)\n    ),\n    plot.caption       = ggplot2::element_text(color = \"#555577\", size = 8.5),\n    axis.text          = ggplot2::element_text(color = \"#aaaacc\"),\n    axis.title         = ggplot2::element_text(color = \"#8888aa\"),\n    legend.position    = \"none\",\n    plot.margin        = ggplot2::margin(16, 16, 12, 16)\n  )\n\np_convergence\n```\n\n::: {.cell-output-display}\n![](2026-03-24-one-million-digits-of-pi_files/figure-html/hero-convergence-plot-1.png){width=1056}\n:::\n:::\n\n\n\nThe wild swings in the early positions give way to a tight cluster hovering within a quarter-percentage-point of 10% by the time we reach the million-digit mark. This is the empirical fingerprint of a normal number.\n\n## Digit transition heatmap: no memory in π\n\nIf pi's digits carry any structure or \"memory\" — if certain digits tend to follow others — we'd see asymmetry in a transition matrix. Let's check.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntransition_matrix <- pi_digits %>%\n  arrange(digit_position) %>%\n  mutate(next_digit = lead(digit)) %>%\n  filter(!is.na(next_digit)) %>%\n  count(digit, next_digit) %>%\n  group_by(digit) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ungroup() %>%\n  mutate(\n    digit      = factor(digit,      levels = 9:0),\n    next_digit = factor(next_digit, levels = 0:9)\n  )\n\ncat(sprintf(\"transition_matrix: %d rows, %d cols\\n\", nrow(transition_matrix), ncol(transition_matrix)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntransition_matrix: 100 rows, 4 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Transition matrix has 0 rows\" = nrow(transition_matrix) > 0)\n\n# Expected: each cell ~10%. Check for any notable deviation\ncat(\"Range of transition percentages:\", range(transition_matrix$pct), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRange of transition percentages: 9.74468 10.22816 \n```\n\n\n:::\n\n```{.r .cell-code}\np_transition <- transition_matrix %>%\n  ggplot2::ggplot(ggplot2::aes(\n    x    = next_digit,\n    y    = digit,\n    fill = pct\n  )) +\n  ggplot2::geom_tile(color = \"#0d0d1a\", linewidth = 0.5) +\n  ggplot2::geom_text(\n    ggplot2::aes(label = sprintf(\"%.1f\", pct)),\n    color = \"white\",\n    size  = 3.5,\n    fontface = \"bold\"\n  ) +\n  paletteer::scale_fill_paletteer_c(\n    \"grDevices::Purple-Green\",\n    limits = c(9.0, 11.0),\n    breaks = c(9, 9.5, 10, 10.5, 11),\n    labels = c(\"9%\", \"9.5%\", \"10%\", \"10.5%\", \"11%\"),\n    guide  = ggplot2::guide_colorbar(\n      title.position = \"top\",\n      barwidth = 12,\n      barheight = 0.8\n    )\n  ) +\n  ggplot2::labs(\n    title    = \"No memory: every digit follows every other digit ~10% of the time\",\n    subtitle = \"Transition frequencies across all 1,000,000 consecutive digit pairs.\\nExpected frequency under independence: 10.0% per cell.\",\n    x        = \"Following digit\",\n    y        = \"Preceding digit\",\n    fill     = \"Transition frequency (%)\",\n    caption  = \"Source: TidyTuesday 2026-03-24 · One Million Digits of Pi\"\n  ) +\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    plot.background    = ggplot2::element_rect(fill = \"#0d0d1a\", color = NA),\n    panel.background   = ggplot2::element_rect(fill = \"#0d0d1a\", color = NA),\n    panel.grid         = ggplot2::element_blank(),\n    text               = ggplot2::element_text(color = \"white\"),\n    plot.title         = ggplot2::element_text(color = \"white\", face = \"bold\", size = 14),\n    plot.subtitle      = ggplot2::element_text(color = \"#9999bb\", size = 10.5, lineheight = 1.4),\n    plot.caption       = ggplot2::element_text(color = \"#555577\", size = 8.5),\n    axis.text          = ggplot2::element_text(color = \"#ccccdd\", size = 11),\n    axis.title         = ggplot2::element_text(color = \"#8888aa\"),\n    legend.position    = \"bottom\",\n    legend.title       = ggplot2::element_text(color = \"#aaaacc\", size = 9),\n    legend.text        = ggplot2::element_text(color = \"#aaaacc\", size = 9),\n    plot.margin        = ggplot2::margin(16, 16, 12, 16)\n  )\n\np_transition\n```\n\n::: {.cell-output-display}\n![](2026-03-24-one-million-digits-of-pi_files/figure-html/transition-matrix-1.png){width=768}\n:::\n:::\n\n\n\nEvery one of the 100 cells in this 10×10 matrix falls within a tight band around 10.0%. The lowest observed transition is around 9.6%, the highest around 10.4%. There is no digit that \"likes\" to follow another — pi's decimal expansion shows no discernible sequential memory.\n\n## Log palette entry\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npalette_log_path <- here::here(\"posts\", \"palette-log.csv\")\npalette_log <- read.csv(palette_log_path)\nnew_entry <- data.frame(\n  post_date = \"2026-03-24\",\n  palette   = \"vapoRwave\",\n  package   = \"vapoRwave\",\n  type      = \"discrete\"\n)\nif (!any(palette_log$post_date == new_entry$post_date &\n         palette_log$palette   == new_entry$palette)) {\n  write.table(\n    new_entry,\n    palette_log_path,\n    append = TRUE, sep = \",\", row.names = FALSE, col.names = FALSE\n  )\n}\n```\n:::\n\n\n\n# Final thoughts and takeaways\n\nOne million digits of pi tells a quiet but profound story: **randomness can emerge from an entirely deterministic object**. Pi is calculated, not drawn from any distribution, yet its decimal expansion is indistinguishable from a fair die rolled a million times.\n\nThe key findings:\n\n- **Digit uniformity holds up.** Every digit appears within 0.4% of its expected 10% share. A chi-square test (p = 0.787) finds no evidence of imbalance across the full million digits.\n- **Convergence is fast.** By around 100,000 positions, all ten digit frequencies have settled to within ~0.3% of each other. The chaotic early variability gives way to stability faster than intuition might suggest.\n- **No pairwise memory.** The 10×10 transition matrix shows no pair of consecutive digits that deviates meaningfully from the 10% independence benchmark. Knowing the current digit tells you nothing about the next.\n\nTogether, these observations are strong empirical support for pi's normality — even if formal proof remains one of mathematics' most famous open problems. The punchline: if you need a stream of pseudo-random digits and you've memorized enough of pi, it'll serve you just as well as most PRNGs.\n\n::: {.callout-tip}\n## Want to find yourself in pi?\n\nThe sequence `031491` (March 14, 1991, a birthday format) appears somewhere in the first million digits of pi. Websites like [piday.org](https://www.piday.org/million/) let you search for any string of digits — a fun reminder that in an infinite (or at least very long) sequence of uniform digits, every birthday is in there somewhere.\n:::\n",
    "supporting": [
      "2026-03-24-one-million-digits-of-pi_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}