{
  "hash": "876ef6249e6fd24a22901c5cd2c115a6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Scottish Munros\"\nauthor: \"Sean Thimons\"\ndate: \"2025-08-19\"\ndescription: \"130 years of measuring, debating, and reclassifying Scotland's highest peaks — tracking which mountains have made, lost, or regained Munro status across 11 official revisions of the Tables.\"\ncategories: [tidytuesday, R, mountains, Scotland, history]\n---\n\n\n\n# Preface\n\nFrom the [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-08-19).\n\n> A Munro is any Scottish mountain with a height of 3,000 feet (914.4 metres) or more. The list, compiled by Sir Hugh Munro in 1891, has been revised many times as surveying technology has improved and as the committee responsible for maintaining the list has reconsidered what counts as a distinct, separate summit. This dataset tracks every mountain across all 11 official revisions of the Munro Tables from 1891 to 2021, recording whether each peak was classified as a \"Munro\" (a full summit) or a \"Munro Top\" (a subsidiary high point) in each edition.\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  booster_pack <- c(\n    ### IO ----\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n\n    ### EDA ----\n    'skimr',\n\n    ### Plot ----\n    'paletteer',           # Color palette collection\n    'patchwork',           # Multi-panel layouts\n    'ggrepel',             # Non-overlapping labels\n\n    ### Misc ----\n    'tidytuesdayR'\n  )\n\n  install_booster_pack(package = booster_pack, load = TRUE)\n  rm(install_booster_pack, booster_pack)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load(\"2025-08-19\")\n\nscottish_munros <- raw$scottish_munros %>% janitor::clean_names()\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## Scottish Munros\n\nThe year columns (1891 through 2021) contain each mountain's classification in that edition of the Tables — either `\"Munro\"` (a full, distinct summit) or `\"Munro Top\"` (a subsidiary high point). A mountain with `NA` for a given year simply wasn't listed in that edition. I'll drop the `Comments` free-text column and the coordinate columns from the skim since they don't carry distributional meaning here.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscottish_munros %>%\n  select(height_m, height_ft) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |604        |\n|Number of columns        |2          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|numeric                  |2          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|   n|  min|    p25|  med|  p75|     max|    mean| geo_mean|     sd|hist  |\n|:-------------|---------:|-------------:|---:|----:|------:|----:|----:|-------:|-------:|--------:|------:|:-----|\n|height_m      |         1|             1| 604|  899|  944.5|  986| 1051| 1344.53| 1008.22|  1005.10|  81.51|▇▅▂▁▁ |\n|height_ft     |         1|             1| 604| 2949| 3098.5| 3235| 3448| 4411.00| 3307.81|  3297.58| 267.43|▇▅▂▁▁ |\n\n\n:::\n:::\n\n\n\nThe height distribution is right-skewed — most mountains cluster between 940–1,050 m, with Ben Nevis towering at 1,344.5 m. The 1st quartile sits at 944.5 m, just 30 metres above the 914.4 m qualifying threshold. That proximity matters enormously: it means a large share of listed mountains are close enough to the borderline that improved surveying or revised definitions can bump them in or out.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Year columns\nyear_cols <- c(\"x1891\", \"x1921\", \"x1933\", \"x1953\", \"x1969\",\n               \"x1974\", \"x1981\", \"x1984\", \"x1990\", \"x1997\", \"x2021\")\n\n# Clean year labels (janitor adds x prefix to numeric column names)\nyear_labels <- c(\"1891\", \"1921\", \"1933\", \"1953\", \"1969\",\n                 \"1974\", \"1981\", \"1984\", \"1990\", \"1997\", \"2021\")\n\n# Verify actual values in the year columns\nscottish_munros %>%\n  select(all_of(year_cols)) %>%\n  pivot_longer(everything(), names_to = \"year\", values_to = \"status\") %>%\n  filter(!is.na(status)) %>%\n  count(year, status) %>%\n  mutate(year = factor(year, levels = year_cols, labels = year_labels)) %>%\n  print(n = 30)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 22 × 3\n   year  status        n\n   <fct> <chr>     <int>\n 1 1891  Munro       283\n 2 1891  Munro Top   255\n 3 1921  Munro       276\n 4 1921  Munro Top   267\n 5 1933  Munro       276\n 6 1933  Munro Top   267\n 7 1953  Munro       276\n 8 1953  Munro Top   267\n 9 1969  Munro       276\n10 1969  Munro Top   267\n11 1974  Munro       279\n12 1974  Munro Top   262\n13 1981  Munro       276\n14 1981  Munro Top   241\n15 1984  Munro       277\n16 1984  Munro Top   240\n17 1990  Munro       277\n18 1990  Munro Top   240\n19 1997  Munro       284\n20 1997  Munro Top   227\n21 2021  Munro       282\n22 2021  Munro Top   226\n```\n\n\n:::\n:::\n\n\n\nThe totals are remarkably stable. After a first-pass reduction in 1921 (−7 Munros), the list held at 276 Munros for five consecutive editions. The 1997 revision pushed the count to its historical high of 284. The 2021 revision trimmed it back to 282 — one more than the original 1891 figure of 283, but arrived at through very different measurements.\n\n# The Shifting Peaks: Classification Changes Across 130 Years\n\nThe stability of the total count masks genuine churn at the individual mountain level. Across all 11 revisions, **62 mountains changed their classification at least once** — bouncing between \"Munro\" and \"Munro Top\" as surveyors refined their measurements and committees reconsidered what qualifies as a distinct summit.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Classify each mountain's journey across all editions\nmunro_journey <- scottish_munros %>%\n  select(do_bih_number, name, height_m, all_of(year_cols)) %>%\n  rowwise() %>%\n  mutate(\n    status_1891    = x1891,\n    status_2021    = x2021,\n    ever_munro     = any(c_across(all_of(year_cols)) == \"Munro\",     na.rm = TRUE),\n    ever_top       = any(c_across(all_of(year_cols)) == \"Munro Top\", na.rm = TRUE),\n    n_editions     = sum(!is.na(c_across(all_of(year_cols)))),\n    changed        = ever_munro & ever_top\n  ) %>%\n  ungroup()\n\n# Classify the direction of change for mountains present in both 1891 and 2021\nmunro_compare <- munro_journey %>%\n  filter(!is.na(status_1891), !is.na(status_2021)) %>%\n  mutate(\n    change_type = case_when(\n      status_1891 == \"Munro\"     & status_2021 == \"Munro Top\" ~ \"Demoted\",\n      status_1891 == \"Munro Top\" & status_2021 == \"Munro\"     ~ \"Promoted\",\n      TRUE                                                     ~ \"Stable\"\n    )\n  )\n\ncat(sprintf(\"Total mountains with 1891 & 2021 records: %d\\n\", nrow(munro_compare)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal mountains with 1891 & 2021 records: 467\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Demoted (Munro → Munro Top): %d\\n\", sum(munro_compare$change_type == \"Demoted\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDemoted (Munro → Munro Top): 26\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Promoted (Munro Top → Munro): %d\\n\", sum(munro_compare$change_type == \"Promoted\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPromoted (Munro Top → Munro): 22\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Stable: %d\\n\", sum(munro_compare$change_type == \"Stable\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStable: 419\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Build a long-format dataset for the timeline chart\ncounts_timeline <- scottish_munros %>%\n  select(all_of(year_cols)) %>%\n  pivot_longer(everything(), names_to = \"year_col\", values_to = \"status\") %>%\n  filter(!is.na(status)) %>%\n  count(year_col, status) %>%\n  mutate(\n    year  = as.integer(factor(year_col, levels = year_cols, labels = year_labels)),\n    year_label = factor(year_col, levels = year_cols, labels = year_labels),\n    status = factor(status, levels = c(\"Munro Top\", \"Munro\"))\n  )\n\ncat(sprintf(\"Timeline rows: %d\\n\", nrow(counts_timeline)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTimeline rows: 22\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Timeline data is empty\" = nrow(counts_timeline) > 0)\n```\n:::\n\n\n\n::: {.callout-note}\n**What separates a Munro from a Munro Top?**\nA \"Munro\" is a summit considered sufficiently distinct and separate from its neighbours — it needs to feel like its own mountain, not just a shoulder of a higher peak. A \"Munro Top\" is a high point (also above 914.4 m) but subordinate to a full Munro. The criteria are partly objective (drop in ridge height, distance) but partly subjective — which is why the committee keeps revising the list.\n:::\n\n## How the counts have shifted across editions\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check palette log before selecting\npalette_log <- read.csv(here::here(\"posts\", \"palette-log.csv\"))\nused_palettes <- palette_log$palette\ncat(\"Previously used palettes:\", paste(used_palettes, collapse = \", \"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPreviously used palettes: hardcoded (red/blue binary), hardcoded (clinical_palette), default_jco, hardcoded (outcome_colors), hardcoded (franchise colors), hardcoded (palette_palms), hardcoded (Amazon brand colors), hardcoded (inline red/blue), hardcoded (Olympic gradient), hardcoded (city colors), Hiroshige, Starfish, vik, Juarez, Zissou1, Vivid, Alacena, lajolla, berlin, Redon, milkmaid, Bold, PonyoMedium, VanGogh1, Arches, aurora, bamako, bright, samarqand, Hokusai3, Klimt, Austria, MarnieMedium1, Kandinsky, lapaz, Hokusai2, vapoRwave, Blue-Red 3, PonyoLight, J_M_W_Turner, muted, bamako, Atentado, Acadia, MononokeMedium \n```\n\n\n:::\n\n```{.r .cell-code}\n# Using nord::aurora — not previously used. Cool Nordic tones evoke highland mist.\n\ntimeline_colors <- c(\n  \"Munro\"     = paletteer::paletteer_d(\"nord::aurora\")[5],  # muted purple\n  \"Munro Top\" = paletteer::paletteer_d(\"nord::aurora\")[4]   # muted green\n)\n\np_timeline <- counts_timeline %>%\n  ggplot2::ggplot(ggplot2::aes(x = year_label, y = n, fill = status)) +\n  ggplot2::geom_col(width = 0.7, position = ggplot2::position_stack()) +\n  ggplot2::geom_text(\n    ggplot2::aes(label = n),\n    position = ggplot2::position_stack(vjust = 0.5),\n    color = \"white\", size = 3.2, fontface = \"bold\"\n  ) +\n  ggplot2::scale_fill_manual(\n    values = timeline_colors,\n    name   = NULL,\n    guide  = ggplot2::guide_legend(reverse = TRUE)\n  ) +\n  ggplot2::labs(\n    title    = \"The Munro count has stayed remarkably stable — but who's in the club has changed\",\n    subtitle = \"Total Munros and Munro Tops listed in each official revision of the Munro Tables, 1891–2021\",\n    x        = \"Revision year\",\n    y        = \"Number of peaks\",\n    caption  = \"Data: TidyTuesday 2025-08-19 · Scottish Munros dataset\"\n  ) +\n  ggplot2::theme_minimal(base_size = 12) +\n  ggplot2::theme(\n    plot.title       = ggplot2::element_text(face = \"bold\", size = 13),\n    plot.subtitle    = ggplot2::element_text(color = \"grey40\", size = 10),\n    panel.grid.major.x = ggplot2::element_blank(),\n    panel.grid.minor   = ggplot2::element_blank(),\n    legend.position  = \"bottom\",\n    plot.caption     = ggplot2::element_text(color = \"grey60\", size = 8)\n  )\n\np_timeline\n```\n\n::: {.cell-output-display}\n![](2025-08-19-scottish-munros_files/figure-html/plot-timeline-1.png){width=960}\n:::\n:::\n\n\n\nThe 1921 revision was the first major correction after Sir Hugh Munro's original list. The biggest structural shift came in 1997 when the committee pushed the Munro count to 284 — its highest ever — primarily by elevating several disputed Tops. The 2021 revision nudged it back down to 282, where it stands today.\n\n## Which mountains changed, and by how much?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Contested mountains: present in both 1891 and 2021 with a status change\ncontested <- munro_compare %>%\n  filter(change_type != \"Stable\") %>%\n  arrange(height_m) %>%\n  mutate(\n    name_short = stringr::str_trunc(name, 50, ellipsis = \"…\"),\n    change_label = case_when(\n      change_type == \"Demoted\"  ~ \"Munro → Top\",\n      change_type == \"Promoted\" ~ \"Top → Munro\"\n    )\n  )\n\ncat(sprintf(\"Contested mountains for hero plot: %d rows\\n\", nrow(contested)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nContested mountains for hero plot: 48 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Hero plot data is empty\" = nrow(contested) > 0)\n\n# Pre-compute the ordered factor for the y-axis (avoids ggplot2 4.x scale conflicts)\ncontested <- contested %>%\n  mutate(name_ordered = factor(name_short, levels = name_short[order(height_m)]))\n\ncat(\"\\nHeight range of contested mountains:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nHeight range of contested mountains:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(summary(contested$height_m))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  916.8   932.8   956.2   983.9  1047.1  1117.1 \n```\n\n\n:::\n:::\n\n\n\n::: {.callout-important}\n**The borderline is thin.** The median height of contested mountains is around 970 m — well above the 914.4 m threshold — yet they still got reclassified. Height alone doesn't determine Munro status; topographic prominence (how much the ridge drops before rising again) is the real deciding factor. Early surveyors couldn't measure this precisely, so the revisions corrected for it.\n:::\n\n# Hero Visualization: Promoted and Demoted Peaks\n\nOf the 283 mountains listed as Munros in 1891, 26 had been demoted to \"Munro Top\" status by 2021. In the other direction, 22 mountains originally classified as Tops have since been elevated to full Munro status. The dot plot below shows all 48 mountains whose fate changed, sorted by elevation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Colors from nord::aurora\ndemoted_color  <- as.character(paletteer::paletteer_d(\"nord::aurora\")[1])  # muted red\npromoted_color <- as.character(paletteer::paletteer_d(\"nord::aurora\")[4])  # muted green\n\n# Annotation helper: find the tallest promoted and shortest demoted\ntallest_promoted <- contested %>% filter(change_type == \"Promoted\") %>% slice_max(height_m, n = 1)\nlowest_demoted   <- contested %>% filter(change_type == \"Demoted\")  %>% slice_min(height_m, n = 1)\n\n# Main hero plot\np_hero <- contested %>%\n  ggplot2::ggplot(ggplot2::aes(\n    x     = height_m,\n    y     = name_ordered,\n    color = change_type,\n    shape = change_type\n  )) +\n  # Faint reference line at 914.4 m threshold\n  ggplot2::geom_vline(\n    xintercept = 914.4,\n    linetype = \"dashed\", color = \"grey70\", linewidth = 0.5\n  ) +\n  ggplot2::annotate(\n    \"text\", x = 914.4, y = levels(contested$name_ordered)[2],\n    label = \"3,000 ft\\nthreshold\",\n    hjust = -0.05, vjust = 0, size = 3, color = \"grey60\"\n  ) +\n  # Segment from threshold to actual height (visual \"reach\")\n  ggplot2::geom_segment(\n    ggplot2::aes(x = 914.4, xend = height_m,\n                 y = name_ordered,\n                 yend = name_ordered),\n    alpha = 0.25, linewidth = 0.7\n  ) +\n  ggplot2::geom_point(size = 3.5, alpha = 0.9) +\n  # Label the extremes\n  ggrepel::geom_text_repel(\n    data = bind_rows(tallest_promoted, lowest_demoted),\n    ggplot2::aes(label = paste0(name_short, \"\\n\", round(height_m), \" m\")),\n    size = 3, fontface = \"bold\", direction = \"x\",\n    nudge_x = 25, segment.color = \"grey60\", segment.size = 0.4,\n    box.padding = 0.4\n  ) +\n  ggplot2::scale_color_manual(\n    values = c(\"Demoted\" = demoted_color, \"Promoted\" = promoted_color),\n    labels = c(\"Demoted\" = \"Demoted: Munro → Munro Top\", \"Promoted\" = \"Promoted: Top → Munro\"),\n    name   = NULL\n  ) +\n  ggplot2::scale_shape_manual(\n    values = c(\"Demoted\" = 16, \"Promoted\" = 17),\n    labels = c(\"Demoted\" = \"Demoted: Munro → Munro Top\", \"Promoted\" = \"Promoted: Top → Munro\"),\n    name   = NULL\n  ) +\n  ggplot2::scale_x_continuous(\n    labels = function(x) paste0(x, \" m\"),\n    limits = c(900, 1300),\n    expand = ggplot2::expansion(mult = c(0.01, 0.05))\n  ) +\n  ggplot2::labs(\n    title    = \"130 years of second-guessing Sir Hugh\",\n    subtitle = \"Mountains that changed between Munro and Munro Top status from 1891 to 2021,\\nsorted by elevation. Segments extend from the 914.4 m qualifying threshold.\",\n    x        = \"Height (metres)\",\n    y        = NULL,\n    caption  = \"Data: TidyTuesday 2025-08-19 · Scottish Munros dataset\\nPalette: nord::aurora\"\n  ) +\n  ggplot2::theme_minimal(base_size = 11) +\n  ggplot2::theme(\n    plot.title       = ggplot2::element_text(face = \"bold\", size = 14, hjust = 0),\n    plot.subtitle    = ggplot2::element_text(color = \"grey40\", size = 10, hjust = 0),\n    axis.text.y      = ggplot2::element_text(size = 8.5),\n    axis.text.x      = ggplot2::element_text(size = 9),\n    panel.grid.major.y = ggplot2::element_line(color = \"grey93\", linewidth = 0.4),\n    panel.grid.major.x = ggplot2::element_line(color = \"grey90\", linewidth = 0.4),\n    panel.grid.minor   = ggplot2::element_blank(),\n    legend.position  = \"top\",\n    legend.text      = ggplot2::element_text(size = 9),\n    plot.caption     = ggplot2::element_text(color = \"grey60\", size = 8),\n    plot.margin      = ggplot2::margin(12, 20, 12, 12)\n  )\n\np_hero\n```\n\n::: {.cell-output-display}\n![](2025-08-19-scottish-munros_files/figure-html/hero-plot-1.png){width=960}\n:::\n\n```{.r .cell-code}\n# Log the palette (idempotent)\npalette_log_path <- here::here(\"posts\", \"palette-log.csv\")\npalette_log_current <- read.csv(palette_log_path)\nnew_entry <- data.frame(\n  post_date = \"2025-08-19\",\n  palette   = \"aurora\",\n  package   = \"nord\",\n  type      = \"discrete\"\n)\nif (!any(palette_log_current$post_date == new_entry$post_date &\n         palette_log_current$palette   == new_entry$palette)) {\n  write.table(\n    new_entry,\n    palette_log_path,\n    append = TRUE, sep = \",\", row.names = FALSE, col.names = FALSE\n  )\n}\n```\n:::\n\n\n\nA few things stand out. First, the promoted mountains aren't uniformly low-elevation: An Stuc (1,117 m), Stob Coire Raineach (1,072 m), and Stob Dubh (1,072 m) are well above the zone of ambiguity — their original \"Top\" status reflected a judgment about topographic independence, not height. Second, the demoted mountains include several that exceed 1,000 m: Sgor Iutharn (1,052 m), Leabaidh an Daimh Bhuidhe (1,089 m), and Carn Sgulain (1,017 m) were stripped of full Munro status not because they shrank, but because revised definitions deemed them subsidiary to a neighbouring summit.\n\n# Final thoughts and takeaways\n\nThe Munro Tables are often assumed to be a fixed, objective list — you just measure the mountains and count the ones taller than 914.4 m. The data tells a more interesting story. In 130 years, 11 committees have looked at the same hills and reached subtly different conclusions 11 times.\n\nThe total number of Munros has barely budged (283 in 1891, 282 in 2021), which creates a misleading impression of consensus. Underneath that stable headline number, 62 individual mountains have changed classification at least once. The revisions aren't random: they track the arc of survey technology, from theodolite measurements in the late Victorian era to GPS-precise elevations after 2000. As measurements got more accurate, the list didn't grow — it *reorganised*, with some disputed peaks clarified into full Munros and others clarified out.\n\nWhat the data can't capture is the culture around it. \"Bagging\" all 282 Munros is a serious pursuit in Scotland — roughly 6,000 people have completed the round. Every time the committee reclassifies a mountain, it invalidates or extends some completions. The 1997 revision, which pushed the count to a record 284, is remembered by long-time hill walkers with a mix of affection and exasperation.\n\nThe lesson might be that any list claiming to objectively enumerate natural features is at least partly a social construction. The mountains haven't moved. The humans measuring and arguing about them have.\n",
    "supporting": [
      "2025-08-19-scottish-munros_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}