{
  "hash": "7d03965655c2008457e7193bb659e82e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: NSF Grant Terminations Under the Trump Administration\"\nauthor: \"Sean Thimons\"\ndate: \"2025-05-06\"\ndescription: \"Over a thousand NSF research grants totaling $613M were terminated in two waves in April 2025. STEM Education bore the brunt — and NSF cut more than Cruz even asked for.\"\ncategories: [tidytuesday, R, science policy, education, politics]\n---\n\n\n\n# Preface\n\nFrom the [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-05-06/readme.md).\n\n> This week we're exploring data about National Science Foundation (NSF) grant terminations under the Trump administration. The data was compiled by [Grant Watch](https://grantwatch.org/), a project tracking federal science funding changes. The dataset covers 1,041 NSF grants terminated in April 2025, totaling over $613 million in previously committed research funding. Suggested questions: Which NSF directorates were most affected? How many terminations came from Ted Cruz's explicit list versus NSF's own discretion? Which states and institutions bore the biggest impact?\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  booster_pack <- c(\n    ### IO ----\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n\n    ### EDA ----\n    'skimr',\n\n    ### Plot ----\n    'paletteer',           # Color palette collection\n    'ggtext',              # Rich text in ggplot (markdown in titles/labels)\n    'ggrepel',             # Non-overlapping labels\n    'scales',              # Axis formatting helpers\n\n    ### Misc ----\n    'tidytuesdayR'\n  )\n\n  # ! Change load flag to load packages\n  install_booster_pack(package = booster_pack, load = TRUE)\n  rm(install_booster_pack, booster_pack)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2025-05-06')\n\nnsf_terminations <- raw$nsf_terminations\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## NSF Terminations\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Drop non-analytical columns: IDs, raw URLs, free-text fields, zip codes\nnsf_for_skim <- nsf_terminations %>%\n  select(-grant_number, -nsf_url, -usaspending_url, -org_uei, -org_zip, -abstract)\n\nmy_skim(nsf_for_skim)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |             |\n|:------------------------|:------------|\n|Name                     |nsf_for_skim |\n|Number of rows           |1041         |\n|Number of columns        |15           |\n|_______________________  |             |\n|Column type frequency:   |             |\n|character                |10           |\n|Date                     |3            |\n|logical                  |1            |\n|numeric                  |1            |\n|________________________ |             |\n|Group variables          |None         |\n\n\n**Variable type: character**\n\n|skim_variable      | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:------------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|project_title      |         0|             1|  13| 180|     0|      787|          0|\n|org_name           |         0|             1|   6|  61|     0|      373|          0|\n|org_city           |         0|             1|   3|  18|     0|      252|          0|\n|org_state          |         0|             1|   2|   2|     0|       50|          0|\n|org_district       |         0|             1|   4|   4|     0|      217|          0|\n|award_type         |         0|             1|  14|  21|     0|        5|          0|\n|directorate_abbrev |         2|             1|   2|   4|     0|        9|          0|\n|directorate        |         2|             1|  11|  48|     0|        9|          0|\n|division           |         2|             1|   7|  61|     0|       34|          0|\n|nsf_program_name   |         1|             1|   4|  30|     0|      150|          0|\n\n\n**Variable type: Date**\n\n|skim_variable           | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-----------------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|termination_letter_date |         0|             1|2025-04-18 |2025-04-25 |2025-04-25 |        4|\n|nsf_startdate           |         0|             1|2021-02-01 |2025-04-01 |2023-08-01 |       89|\n|nsf_expected_end_date   |         0|             1|2025-04-18 |2029-12-31 |2026-04-30 |       53|\n\n\n**Variable type: logical**\n\n|skim_variable | n_missing| complete_rate| mean|count              |\n|:-------------|---------:|-------------:|----:|:------------------|\n|in_cruz_list  |         0|             1| 0.45|FAL: 572, TRU: 469 |\n\n\n**Variable type: numeric**\n\n|skim_variable         | n_missing| complete_rate|    n|  min|      p25|    med|      p75|   max|     mean| geo_mean|       sd|hist  |\n|:---------------------|---------:|-------------:|----:|----:|--------:|------:|--------:|-----:|--------:|--------:|--------:|:-----|\n|usaspending_obligated |         2|             1| 1041| 6774| 188976.5| 356236| 737336.5| 6e+06| 590243.7| 333542.4| 728814.5|▇▁▁▁▁ |\n\n\n:::\n:::\n\n\n\nThe skim reveals a clean dataset with minimal missingness — only `directorate`, `division`, and `usaspending_obligated` are missing for 2 records each, likely grants without a clear organizational home. The `usaspending_obligated` column (the dollar amount committed to each grant) skews heavily right: the median is \\$356K while the mean is \\$590K, driven by a long tail up to \\$6M. The ASCII histogram confirms this rightward skew. Start and expected end dates span multiple years, and the termination letters were sent in two tight clusters in April 2025 — an administrative purge, not a rolling review.\n\n# The Termination Waves\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwave_summary <- nsf_terminations %>%\n  count(termination_letter_date, name = \"n_grants\") %>%\n  mutate(\n    cumulative = cumsum(n_grants),\n    label = format(termination_letter_date, \"%B %d, %Y\")\n  )\n\ncat(\"=== Termination waves ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Termination waves ===\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(wave_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  termination_letter_date n_grants cumulative label         \n  <date>                     <int>      <int> <chr>         \n1 2025-04-18                   388        388 April 18, 2025\n2 2025-04-21                     1        389 April 21, 2025\n3 2025-04-22                     1        390 April 22, 2025\n4 2025-04-25                   651       1041 April 25, 2025\n```\n\n\n:::\n\n```{.r .cell-code}\ntotal_grants <- nrow(nsf_terminations)\ntotal_obligated <- sum(nsf_terminations$usaspending_obligated, na.rm = TRUE)\ncat(sprintf(\n  \"\\nTotal: %d grants, $%s in obligated funding\\n\",\n  total_grants,\n  scales::dollar(total_obligated)\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTotal: 1041 grants, $$613,263,199 in obligated funding\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-important}\n## Two Waves, One Purge\n\nAll 1,041 terminations arrived in just four calendar days across two main waves:\n\n- **April 18, 2025**: 388 grants terminated\n- **April 25, 2025**: 651 grants terminated (two additional isolated terminations on April 21 and 22)\n\nThis is not a gradual budget review. It is a coordinated administrative action executed over a single week.\n:::\n\n# Which Science Got Cut? Directorate Breakdown\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndirectorate_summary <- nsf_terminations %>%\n  mutate(directorate_clean = str_remove_all(directorate, '\"')) %>%\n  filter(!is.na(directorate_clean)) %>%\n  group_by(directorate_clean) %>%\n  summarise(\n    total_grants   = n(),\n    total_obligated = sum(usaspending_obligated, na.rm = TRUE),\n    cruz_grants    = sum(in_cruz_list == TRUE, na.rm = TRUE),\n    cruz_obligated = sum(usaspending_obligated[in_cruz_list == TRUE], na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  mutate(\n    additional_grants    = total_grants - cruz_grants,\n    additional_obligated = total_obligated - cruz_obligated,\n    pct_cruz             = cruz_grants / total_grants\n  ) %>%\n  arrange(desc(total_obligated))\n\ncat(sprintf(\"Directorate summary: %d rows\\n\", nrow(directorate_summary)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDirectorate summary: 9 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Directorate summary has 0 rows — check filter\" = nrow(directorate_summary) > 0)\n\n# Quick sanity check on pct_cruz\nif (length(unique(round(directorate_summary$pct_cruz, 3))) == 1) {\n  warning(\"All pct_cruz values are identical — check grouping logic\")\n} else {\n  cat(sprintf(\"pct_cruz ranges from %.1f%% to %.1f%% — variation confirmed\\n\",\n              min(directorate_summary$pct_cruz) * 100,\n              max(directorate_summary$pct_cruz) * 100))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npct_cruz ranges from 20.0% to 82.2% — variation confirmed\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(\n  directorate_summary %>%\n    select(directorate_clean, total_grants, total_obligated, cruz_grants, pct_cruz) %>%\n    mutate(\n      total_obligated = scales::dollar(total_obligated),\n      pct_cruz = scales::percent(pct_cruz, accuracy = 1)\n    )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 5\n  directorate_clean            total_grants total_obligated cruz_grants pct_cruz\n  <chr>                               <int> <chr>                 <int> <chr>   \n1 STEM Education                        416 $321,754,856            190 46%     \n2 Social, Behavioral and Econ…          266 $77,635,904             110 41%     \n3 Technology, Innovation and …           45 $61,031,310               9 20%     \n4 Computer and Information Sc…           85 $44,630,113              29 34%     \n5 Geosciences                            51 $35,948,981              25 49%     \n6 Engineering                            94 $33,472,485              49 52%     \n7 Biological Sciences                    45 $27,511,500              37 82%     \n8 Mathematical and Physical S…           30 $6,418,312               17 57%     \n9 Office of the Director                  7 $4,859,738                3 43%     \n```\n\n\n:::\n:::\n\n\n\nSTEM Education dominates by every measure — 416 grants (40% of all terminations) and \\$322M (52% of all terminated funding). Social and Behavioral Sciences is a distant second in grant count (266 grants) but represents a much smaller dollar footprint (\\$78M) because education grants tend to run larger. Engineering and Computer Science were also hit, though their proportions are notably smaller.\n\n::: {.callout-note}\n## The Concentration Risk\n\nOver half of all terminated NSF funding — $322M — came from a single directorate: STEM Education. This is not random across the portfolio. It is a targeted dismantling of the agency's education research mission.\n:::\n\n# Beyond Cruz's List: NSF Went Further Than Asked\n\nIn February 2025, Sen. Ted Cruz sent NSF a list of grants he wanted terminated, citing them as \"DEI\" or \"woke\" research spending. What happened next was more sweeping.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncruz_overall <- nsf_terminations %>%\n  group_by(in_cruz_list) %>%\n  summarise(\n    n_grants        = n(),\n    total_obligated = sum(usaspending_obligated, na.rm = TRUE),\n    median_grant    = median(usaspending_obligated, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  mutate(\n    pct_grants    = n_grants / sum(n_grants),\n    pct_obligated = total_obligated / sum(total_obligated),\n    label = ifelse(in_cruz_list, \"On Cruz's list\", \"NSF additional\")\n  )\n\ncat(\"=== Cruz list vs. NSF additional ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Cruz list vs. NSF additional ===\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(cruz_overall %>% select(label, n_grants, pct_grants, total_obligated, pct_obligated, median_grant))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  label          n_grants pct_grants total_obligated pct_obligated median_grant\n  <chr>             <int>      <dbl>           <dbl>         <dbl>        <dbl>\n1 NSF additional      572      0.549       337442428         0.550      395630.\n2 On Cruz's list      469      0.451       275820771         0.450      340528 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Cruz list by directorate\ncruz_by_directorate <- nsf_terminations %>%\n  mutate(directorate_clean = str_remove_all(directorate, '\"')) %>%\n  filter(!is.na(directorate_clean)) %>%\n  group_by(directorate_clean, in_cruz_list) %>%\n  summarise(n = n(), .groups = \"drop\") %>%\n  pivot_wider(names_from = in_cruz_list, values_from = n, values_fill = 0) %>%\n  rename(not_cruz = `FALSE`, on_cruz = `TRUE`) %>%\n  mutate(\n    total = not_cruz + on_cruz,\n    pct_on_cruz = on_cruz / total\n  ) %>%\n  arrange(desc(pct_on_cruz))\n\ncat(\"\\n=== Cruz list % by directorate (sorted) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Cruz list % by directorate (sorted) ===\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(cruz_by_directorate %>% mutate(pct_on_cruz = scales::percent(pct_on_cruz, accuracy = 1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 5\n  directorate_clean                           not_cruz on_cruz total pct_on_cruz\n  <chr>                                          <int>   <int> <int> <chr>      \n1 Biological Sciences                                8      37    45 82%        \n2 Mathematical and Physical Sciences                13      17    30 57%        \n3 Engineering                                       45      49    94 52%        \n4 Geosciences                                       26      25    51 49%        \n5 STEM Education                                   226     190   416 46%        \n6 Office of the Director                             4       3     7 43%        \n7 Social, Behavioral and Economic Sciences         156     110   266 41%        \n8 Computer and Information Science and Engin…       56      29    85 34%        \n9 Technology, Innovation and Partnerships           36       9    45 20%        \n```\n\n\n:::\n:::\n\n\n\n::: {.callout-important}\n## NSF Cut 572 Grants Cruz Never Asked For\n\nOf the 1,041 grants terminated:\n\n- **469** (45%) were on Sen. Cruz's explicit list\n- **572** (55%) were terminated by NSF *on its own initiative*, beyond what Cruz requested\n\nThe Social and Behavioral Sciences directorate had the highest share of Cruz-list grants (62%), suggesting that directorate's programs most closely matched Cruz's stated \"DEI\" targets. But STEM Education — the single biggest category — saw a majority of its cuts come from outside Cruz's list, indicating the administration's own appetite for dismantling education research ran ahead of Congressional demands.\n:::\n\n# Hero Visualization: The Anatomy of the Purge\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Build plot data ---\nplot_data <- nsf_terminations %>%\n  mutate(directorate_clean = str_remove_all(directorate, '\"')) %>%\n  filter(!is.na(directorate_clean)) %>%\n  mutate(\n    termination_source = if_else(in_cruz_list, \"On Cruz's list\", \"NSF additional\"),\n    # Shorten long directorate names for readability\n    dir_label = case_when(\n      str_detect(directorate_clean, \"STEM\") ~ \"STEM Education\",\n      str_detect(directorate_clean, \"Social\") ~ \"Social & Behavioral Sciences\",\n      str_detect(directorate_clean, \"Computer\") ~ \"Computer & Info. Science & Eng.\",\n      str_detect(directorate_clean, \"Technology\") ~ \"Tech., Innovation & Partnerships\",\n      str_detect(directorate_clean, \"Mathematical\") ~ \"Math & Physical Sciences\",\n      TRUE ~ directorate_clean\n    )\n  ) %>%\n  group_by(dir_label, termination_source) %>%\n  summarise(\n    n_grants        = n(),\n    total_obligated = sum(usaspending_obligated, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\ncat(sprintf(\"plot_data: %d rows, %d cols\\n\", nrow(plot_data), ncol(plot_data)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nplot_data: 18 rows, 4 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Plot data has 0 rows — check filter\" = nrow(plot_data) > 0)\n\n# Compute totals for ordering\ndir_totals <- plot_data %>%\n  group_by(dir_label) %>%\n  summarise(grand_total = sum(total_obligated), grand_n = sum(n_grants), .groups = \"drop\") %>%\n  arrange(grand_total)\n\nplot_data <- plot_data %>%\n  mutate(\n    dir_label          = factor(dir_label, levels = dir_totals$dir_label),\n    termination_source = factor(termination_source, levels = c(\"NSF additional\", \"On Cruz's list\"))\n  )\n\n# Grant count label data (total per directorate, positioned at bar end)\nlabel_data <- dir_totals %>%\n  mutate(\n    dir_label = factor(dir_label, levels = dir_totals$dir_label),\n    label     = paste0(grand_n, \" grants\\n\", scales::dollar(grand_total / 1e6, accuracy = 1), \"M\")\n  )\n\n# --- Colors from MexBrewer::Alacena (diverging: warm red → cool blue) ---\nalacena_cols <- paletteer::paletteer_d(\"MexBrewer::Alacena\")\nfill_colors  <- c(\n  \"On Cruz's list\" = as.character(alacena_cols[2]),   # warm russet #894B33\n  \"NSF additional\" = as.character(alacena_cols[9])    # deep blue   #405A95\n)\n\n# --- Plot ---\np <- ggplot2::ggplot(plot_data,\n       ggplot2::aes(x = total_obligated, y = dir_label, fill = termination_source)) +\n  ggplot2::geom_col(width = 0.7, color = \"white\", linewidth = 0.3) +\n  ggrepel::geom_text_repel(\n    data          = label_data,\n    ggplot2::aes(x = grand_total, y = dir_label, label = label),\n    inherit.aes   = FALSE,\n    nudge_x       = 4e6,\n    direction     = \"y\",\n    hjust         = 0,\n    size          = 2.8,\n    color         = \"gray30\",\n    segment.color = \"gray70\",\n    segment.size  = 0.3,\n    force         = 0.5\n  ) +\n  ggplot2::scale_x_continuous(\n    labels = scales::dollar_format(scale = 1e-6, suffix = \"M\"),\n    expand = ggplot2::expansion(mult = c(0, 0.28))\n  ) +\n  ggplot2::scale_fill_manual(\n    values = fill_colors,\n    name   = NULL,\n    guide  = ggplot2::guide_legend(reverse = TRUE)\n  ) +\n  ggplot2::labs(\n    title    = \"**STEM Education bore $322M of the $613M purge —**<br>and NSF cut more than Cruz even asked for\",\n    subtitle = \"Stacked bars show obligated funding in terminated NSF grants by directorate.\\nWarm bars = grants on Sen. Cruz's explicit list; blue bars = additional NSF discretionary terminations.\",\n    caption  = \"Data: TidyTuesday 2025-05-06 · Grant Watch / NSF · Graphic: Sean Thimons\",\n    x        = \"Total Obligated Funding Terminated\",\n    y        = NULL\n  ) +\n  ggplot2::theme_minimal(base_size = 12) +\n  ggplot2::theme(\n    plot.title         = ggtext::element_markdown(\n      size = 15, face = \"bold\", lineheight = 1.3, margin = ggplot2::margin(b = 6)\n    ),\n    plot.subtitle      = ggplot2::element_text(\n      size = 10, color = \"gray40\", lineheight = 1.4, margin = ggplot2::margin(b = 12)\n    ),\n    plot.caption       = ggplot2::element_text(size = 8, color = \"gray55\", hjust = 0),\n    axis.text.y        = ggplot2::element_text(size = 10, color = \"gray20\"),\n    axis.text.x        = ggplot2::element_text(size = 9, color = \"gray40\"),\n    axis.title.x       = ggplot2::element_text(size = 9, color = \"gray40\",\n                                                margin = ggplot2::margin(t = 6)),\n    panel.grid.major.y = ggplot2::element_blank(),\n    panel.grid.minor   = ggplot2::element_blank(),\n    panel.grid.major.x = ggplot2::element_line(color = \"gray90\", linewidth = 0.4),\n    legend.position    = \"top\",\n    legend.text        = ggplot2::element_text(size = 10),\n    plot.margin        = ggplot2::margin(12, 12, 12, 12)\n  )\n\np\n```\n\n::: {.cell-output-display}\n![](2025-05-06-national-science-foundation-grant-terminations-und_files/figure-html/viz-directorate-stacked-1.png){width=1056}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n# Geographic Impact\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstate_summary <- nsf_terminations %>%\n  group_by(org_state) %>%\n  summarise(\n    n_grants        = n(),\n    total_obligated = sum(usaspending_obligated, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(n_grants)) %>%\n  mutate(\n    pct_of_total_grants = n_grants / sum(n_grants),\n    cum_pct             = cumsum(pct_of_total_grants)\n  )\n\ncat(\"=== Top 15 states by grants terminated ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Top 15 states by grants terminated ===\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(\n  state_summary %>%\n    head(15) %>%\n    mutate(\n      total_obligated     = scales::dollar(total_obligated),\n      pct_of_total_grants = scales::percent(pct_of_total_grants, accuracy = 0.1)\n    )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 5\n   org_state n_grants total_obligated pct_of_total_grants cum_pct\n   <chr>        <int> <chr>           <chr>                 <dbl>\n 1 CA             112 $70,355,930     10.8%                 0.108\n 2 TX              73 $41,658,021     7.0%                  0.178\n 3 NY              69 $56,677,772     6.6%                  0.244\n 4 MA              51 $36,063,342     4.9%                  0.293\n 5 PA              45 $22,861,209     4.3%                  0.336\n 6 IL              42 $27,859,922     4.0%                  0.377\n 7 MI              41 $20,149,750     3.9%                  0.416\n 8 VA              41 $29,751,948     3.9%                  0.455\n 9 GA              40 $16,282,920     3.8%                  0.494\n10 CO              39 $24,490,549     3.7%                  0.531\n11 NC              38 $19,032,990     3.7%                  0.568\n12 FL              36 $20,856,308     3.5%                  0.602\n13 WA              36 $22,313,552     3.5%                  0.637\n14 AZ              32 $22,096,303     3.1%                  0.668\n15 MD              32 $24,065,696     3.1%                  0.698\n```\n\n\n:::\n\n```{.r .cell-code}\n# How many states account for 75% of terminations?\nn_states_75pct <- state_summary %>%\n  filter(cum_pct <= 0.75) %>%\n  nrow()\n\ncat(sprintf(\"\\n%d states account for 75%% of all terminated grants\\n\", n_states_75pct))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n17 states account for 75% of all terminated grants\n```\n\n\n:::\n\n```{.r .cell-code}\n# Top institution\ntop_inst <- nsf_terminations %>%\n  group_by(org_name, org_state) %>%\n  summarise(\n    n_grants        = n(),\n    total_obligated = sum(usaspending_obligated, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(total_obligated)) %>%\n  head(10)\n\ncat(\"\\n=== Top 10 institutions by terminated funding ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Top 10 institutions by terminated funding ===\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(top_inst %>% mutate(total_obligated = scales::dollar(total_obligated)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   org_name                                   org_state n_grants total_obligated\n   <chr>                                      <chr>        <int> <chr>          \n 1 University of Colorado at Boulder          CO              21 $17,201,363    \n 2 Arizona State University                   AZ              24 $15,715,481    \n 3 University of California-Irvine            CA              13 $13,621,244    \n 4 University of Texas at Austin              TX              12 $12,462,269    \n 5 University of Washington                   WA              14 $11,825,802    \n 6 University of California-Berkeley          CA              11 $11,638,220    \n 7 University of Wisconsin-Madison            WI              14 $11,147,856    \n 8 Michigan State University                  MI              13 $9,789,683     \n 9 Columbia University                        NY               8 $9,555,513     \n10 Regents of the University of Michigan - A… MI              22 $9,430,892     \n```\n\n\n:::\n:::\n\n\n\nThe geographic concentration is striking but unsurprising: California (112 grants, \\$70M), New York (\\$57M), and Texas (\\$42M) top the list, reflecting where the nation's large research universities are clustered. Just 9 states account for 75% of all terminated grants. No region is spared, but research-heavy coastal and Great Lakes states bear the highest absolute burden.\n\n# Final thoughts and takeaways\n\nThe NSF terminations dataset tells a story that is cleaner and more concentrated than the noise around federal science funding might suggest. A few conclusions hold up under scrutiny:\n\n**The attack was targeted, not random.** STEM Education was not collateral damage — it absorbed 40% of the terminated grants and 52% of the terminated dollars. The programs that disappeared most frequently (AISL, Discovery Research K-12, ECR-EDU Core Research, ADVANCE, Build and Broaden) are precisely the ones that study how to make science accessible to underrepresented communities. Whether labeled \"DEI\" or not, the effect is a gutting of the research base for broadening participation in science.\n\n**The agency exceeded its political mandate.** Sen. Cruz's list was a floor, not a ceiling. NSF terminated 572 grants that weren't on it — 55% of all terminations. This is either evidence of administrative overreach or of an agency that has internalized the administration's preferences well enough to act without prompting. Either way, the political signal has become self-enforcing.\n\n**The dollar impact is real and front-loaded.** The median grant had about 12 months of remaining work cut off. These weren't zombie grants running on fumes — they were active research projects with personnel, students, and commitments already in flight. The \\$613M in obligated funding represents money already promised, now clawed back.\n\n**Limitations worth noting:** The dataset captures obligated funding, not total project costs or the value of work already completed. Some grants may have had informal warning before the formal letter. And this snapshot ends in late April 2025 — subsequent termination rounds are not captured here.\n\nThe data is clear enough to support a plain-spoken interpretation: the Trump administration, with or without Congressional direction, executed a rapid and concentrated rollback of NSF's education and social science research portfolio. The wave structure and directorate concentration make it difficult to read this as anything other than a deliberate policy choice.\n",
    "supporting": [
      "2025-05-06-national-science-foundation-grant-terminations-und_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}