{
  "hash": "a0bdd5260597b23510273ce3f8562808",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Pokémon\"\nauthor: \"Sean Thimons\"\ndate: \"2025-04-01\"\ndescription: \"Mapping the combat DNA of all 18 Pokémon types through normalized stat fingerprints.\"\ncategories: [tidytuesday, R, pokemon, gaming]\n---\n\n\n\n# Preface\n\nFrom [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-04-01/readme.md).\n\n> This week we're exploring Pokémon data! The dataset contains information\n> about 949 Pokémon including their types, base stats (HP, Attack, Defense,\n> Special Attack, Special Defense, Speed), physical characteristics (height\n> and weight), color data from game sprites, egg groups, and generation.\n> Suggested questions include: Which types have the highest/lowest base stats?\n> How have stat totals changed across generations? What are the most common\n> type combinations?\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  booster_pack <- c(\n    ### IO ----\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n\n    ### EDA ----\n    'skimr',\n\n    ### Plot ----\n    'paletteer',           # Color palette collection\n    'ggtext',              # Rich text / markdown in ggplot elements\n    'ggrepel',             # Non-overlapping labels\n    'patchwork',           # Multi-panel layouts\n\n    ### Misc ----\n    'tidytuesdayR'\n  )\n\n  # ! Change load flag to load packages\n  install_booster_pack(package = booster_pack, load = TRUE)\n  rm(install_booster_pack, booster_pack)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2025-04-01')\n\npokemon <- raw$pokemon_df\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## Pokémon Stats\n\nBefore skimming, I drop non-analytic columns: `id`, `species_id` (surrogate keys), `url_icon`, `url_image` (external URLs), `color_1`, `color_2`, `color_f` (hex strings from sprite data), and `pokemon` (character name).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npokemon %>%\n  select(\n    height, weight, base_experience,\n    hp, attack, defense,\n    special_attack, special_defense, speed,\n    generation_id\n  ) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |949        |\n|Number of columns        |10         |\n|_______________________  |           |\n|Column type frequency:   |           |\n|numeric                  |10         |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: numeric**\n\n|skim_variable   | n_missing| complete_rate|   n|  min|  p25|   med|   p75|   max|   mean| geo_mean|     sd|hist  |\n|:---------------|---------:|-------------:|---:|----:|----:|-----:|-----:|-----:|------:|--------:|------:|:-----|\n|height          |         0|          1.00| 949|  0.1|  0.5|   1.0|   1.5|  14.5|   1.23|     0.91|   1.27|▇▁▁▁▁ |\n|weight          |         0|          1.00| 949|  0.1|  8.5|  28.8|  66.6| 999.9|  66.21|    23.29| 119.95|▇▁▁▁▁ |\n|base_experience |         0|          1.00| 949| 36.0| 68.0| 157.0| 184.0| 608.0| 150.48|   130.04|  76.39|▇▇▂▁▁ |\n|hp              |         0|          1.00| 949|  1.0| 50.0|  65.0|  80.0| 255.0|  68.95|    64.41|  25.93|▃▇▁▁▁ |\n|attack          |         0|          1.00| 949|  5.0| 55.0|  75.0| 100.0| 190.0|  79.47|    72.55|  31.95|▂▇▆▂▁ |\n|defense         |         0|          1.00| 949|  5.0| 50.0|  70.0|  90.0| 230.0|  74.07|    67.87|  30.76|▃▇▃▁▁ |\n|special_attack  |         0|          1.00| 949| 10.0| 50.0|  65.0|  95.0| 194.0|  72.81|    65.52|  32.63|▅▇▅▂▁ |\n|special_defense |         0|          1.00| 949| 20.0| 50.0|  70.0|  90.0| 230.0|  72.22|    66.99|  27.68|▇▇▂▁▁ |\n|speed           |         0|          1.00| 949|  5.0| 45.0|  65.0|  90.0| 180.0|  69.02|    62.03|  29.21|▃▇▆▂▁ |\n|generation_id   |       147|          0.85| 949|  1.0|  2.0|   4.0|   5.0|   7.0|   3.69|     3.09|   1.93|▇▅▃▅▅ |\n\n\n:::\n:::\n\n\n\nThe numeric stats tell a clear story about the shape of the Pokédex. **HP** and the combat stats (attack through speed) all cluster tightly in the 50–100 range with right-skewed tails — a design choice that keeps most Pokémon playable while leaving room for extreme outliers (the 255 max HP of Blissey, the 230 max defense of Shuckle). **Weight** is the most skewed column, spanning three orders of magnitude from 0.1 kg to over 900 kg; its geometric mean (far below the arithmetic mean) reveals how a handful of enormous legendaries pull the distribution right.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntype_counts <- pokemon %>%\n  count(type_1, name = \"n\") %>%\n  mutate(type_1 = fct_reorder(type_1, n))\n\ncat(sprintf(\"type_counts: %d rows, %d cols\\n\", nrow(type_counts), ncol(type_counts)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntype_counts: 18 rows, 2 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"type_counts is empty\" = nrow(type_counts) > 0)\n\np_types <- ggplot(type_counts, aes(x = n, y = type_1)) +\n  geom_col(fill = \"#4E79A7\", alpha = 0.85) +\n  geom_text(aes(label = n), hjust = -0.3, size = 3.5, color = \"grey30\") +\n  scale_x_continuous(expand = expansion(mult = c(0, 0.12))) +\n  labs(\n    title = \"Pokémon by Primary Type\",\n    subtitle = \"Water and Normal dominate the Pokédex; Flying has only 4 pure-Flying entries\",\n    x = \"Count\",\n    y = NULL,\n    caption = \"n = 949 Pokémon including alternate forms and mega evolutions\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\"),\n    panel.grid.major.y = element_blank(),\n    panel.grid.minor = element_blank()\n  )\n\np_types\n```\n\n::: {.cell-output-display}\n![](2025-04-01-pokemon_files/figure-html/eda-type-counts-1.png){width=768}\n:::\n:::\n\n\n\nWater (126) and Normal (111) are far and away the most common primary types — a pattern that has held since Generation I. Flying appears almost non-existent (only 4 pure Flying-types) because most flying Pokémon list Flying as their *secondary* type. The dataset includes mega evolutions and alternate forms, which skews some type counts upward.\n\n# Domain Analysis: The Combat DNA of Each Type\n\nThe six base stats — HP, Attack, Defense, Special Attack, Special Defense, and Speed — define how a Pokémon fights. Every type has a signature combat identity baked in by Game Freak's design choices: Dragons are all-around powerhouses, Ghosts trade bulk for utility, Steel types wall physical hits, Bugs get shortchanged across the board.\n\nTo surface these signatures, I compute the **median** of each stat for every primary type, then **z-score** those medians against the overall population mean and standard deviation. A z-score of +1.0 means a type's median is one standard deviation above average for that stat; −1.0 means one standard deviation below. This puts all six stats on a comparable scale regardless of their raw magnitudes.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute base_total as sum of the 6 combat stats\npokemon <- pokemon %>%\n  dplyr::mutate(base_total = hp + attack + defense + special_attack + special_defense + speed)\n\ncat(sprintf(\"base_total range: %.0f – %.0f, mean: %.1f\\n\",\n            min(pokemon$base_total), max(pokemon$base_total), mean(pokemon$base_total)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbase_total range: 175 – 780, mean: 436.5\n```\n\n\n:::\n\n```{.r .cell-code}\n# Median stats per primary type, ordered by median total\ntype_medians <- pokemon %>%\n  dplyr::group_by(type_1) %>%\n  dplyr::summarize(\n    n        = dplyr::n(),\n    hp       = median(hp),\n    attack   = median(attack),\n    defense  = median(defense),\n    spa      = median(special_attack),\n    spd      = median(special_defense),\n    spe      = median(speed),\n    total    = median(base_total),\n    .groups  = \"drop\"\n  ) %>%\n  dplyr::arrange(dplyr::desc(total))\n\ncat(\"\\nType medians (ordered by base total):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nType medians (ordered by base total):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(type_medians %>% dplyr::select(type_1, n, total))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 18 × 3\n   type_1       n total\n   <chr>    <int> <dbl>\n 1 dragon      39  600 \n 2 flying       4  558.\n 3 steel       30  515 \n 4 rock        65  487 \n 5 psychic     64  486 \n 6 fire        59  476 \n 7 ghost       40  476 \n 8 water      126  457 \n 9 fighting    31  455 \n10 fairy       19  450 \n11 ice         29  450 \n12 poison      35  448 \n13 dark        37  440 \n14 electric    61  431 \n15 grass       84  430 \n16 ground      36  428.\n17 normal     111  418 \n18 bug         79  400 \n```\n\n\n:::\n:::\n\n\n\n::: {.callout-note}\n**What \"median\" means here:** Because the dataset includes mega evolutions (e.g., Mewtwo-Mega-X has a 780 base total), using the *median* rather than the *mean* is important. The median is more robust to the handful of hyper-powered forms that would otherwise inflate type averages upward.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Overall mean and SD of each stat across all 949 Pokémon\nstat_cols <- c(\"hp\", \"attack\", \"defense\", \"spa\", \"spd\", \"spe\")\n\noverall_means <- sapply(stat_cols, function(col) {\n  mean(pokemon[[dplyr::case_when(\n    col == \"spa\" ~ \"special_attack\",\n    col == \"spd\" ~ \"special_defense\",\n    col == \"spe\" ~ \"speed\",\n    TRUE ~ col\n  )]], na.rm = TRUE)\n})\n\noverall_sds <- sapply(stat_cols, function(col) {\n  sd(pokemon[[dplyr::case_when(\n    col == \"spa\" ~ \"special_attack\",\n    col == \"spd\" ~ \"special_defense\",\n    col == \"spe\" ~ \"speed\",\n    TRUE ~ col\n  )]], na.rm = TRUE)\n})\n\n# Z-score each type's median against the overall distribution\ntype_zscores <- type_medians %>%\n  dplyr::mutate(\n    hp_z  = (hp  - overall_means[\"hp\"])      / overall_sds[\"hp\"],\n    atk_z = (attack - overall_means[\"attack\"]) / overall_sds[\"attack\"],\n    def_z = (defense - overall_means[\"defense\"]) / overall_sds[\"defense\"],\n    spa_z = (spa - overall_means[\"spa\"])       / overall_sds[\"spa\"],\n    spd_z = (spd - overall_means[\"spd\"])       / overall_sds[\"spd\"],\n    spe_z = (spe - overall_means[\"spe\"])       / overall_sds[\"spe\"],\n    type_1 = forcats::fct_reorder(type_1, total)\n  )\n\n# Pivot to long for heatmap\nheatmap_data <- type_zscores %>%\n  dplyr::select(type_1, hp_z, atk_z, def_z, spa_z, spd_z, spe_z) %>%\n  tidyr::pivot_longer(\n    cols      = ends_with(\"_z\"),\n    names_to  = \"stat\",\n    values_to = \"z\"\n  ) %>%\n  dplyr::mutate(\n    stat = dplyr::recode(stat,\n      \"hp_z\"  = \"HP\",\n      \"atk_z\" = \"Atk\",\n      \"def_z\" = \"Def\",\n      \"spa_z\" = \"SpA\",\n      \"spd_z\" = \"SpD\",\n      \"spe_z\" = \"Spe\"\n    ),\n    stat = factor(stat, levels = c(\"HP\", \"Atk\", \"Def\", \"SpA\", \"SpD\", \"Spe\"))\n  )\n\ncat(sprintf(\"heatmap_data: %d rows, %d cols\\n\", nrow(heatmap_data), ncol(heatmap_data)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nheatmap_data: 108 rows, 3 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Plot data has 0 rows — check pipeline\" = nrow(heatmap_data) > 0)\n\n# Sanity check: z-scores should not all be identical\nif (length(unique(round(heatmap_data$z, 4))) == 1) {\n  warning(\"All z values are identical — check z-score computation\")\n} else {\n  cat(sprintf(\"z-score range: %.2f to %.2f\\n\", min(heatmap_data$z), max(heatmap_data$z)))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nz-score range: -0.94 to 1.61\n```\n\n\n:::\n:::\n\n\n\n# The Stat Fingerprint Heatmap\n\nEach row is a Pokémon type; each column is a combat stat. Cells shaded red indicate the type's median is **above** the overall average for that stat; blue cells indicate **below** average. Types are sorted top to bottom from highest to lowest median base total.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Type-level sample sizes for right-side annotation\ntype_n <- type_zscores %>%\n  dplyr::select(type_1, n, total) %>%\n  dplyr::mutate(\n    label = sprintf(\"n=%d | Σ%d\", n, round(total))\n  )\n\np <- ggplot(heatmap_data, aes(x = stat, y = type_1, fill = z)) +\n  geom_tile(color = \"white\", linewidth = 0.7) +\n  geom_text(\n    aes(label = sprintf(\"%+.2f\", z)),\n    size  = 3.2,\n    color = ifelse(abs(heatmap_data$z) > 1.2, \"white\", \"grey20\")\n  ) +\n  # Annotation: sample sizes on the right\n  geom_text(\n    data = type_n,\n    aes(x = 6.7, y = type_1, label = label),\n    inherit.aes = FALSE,\n    size  = 3,\n    color = \"grey45\",\n    hjust = 0\n  ) +\n  paletteer::scale_fill_paletteer_c(\n    \"grDevices::Blue-Red 3\",\n    limits  = c(-1.8, 1.8),\n    oob     = scales::squish,\n    name    = \"z-score\"\n  ) +\n  scale_x_discrete(position = \"top\", expand = expansion(add = c(0.5, 1.8))) +\n  labs(\n    title    = \"**Battle DNA:** How Each Pokémon Type Is Built\",\n    subtitle = \"Normalized (z-scored) median stat values relative to the full Pokédex population.<br>\n                <span style='color:#C34129'>Red = above average</span> ·\n                <span style='color:#3B72B1'>Blue = below average</span> ·\n                Types sorted by median base stat total ↑\",\n    x        = NULL,\n    y        = NULL,\n    caption  = \"Source: TidyTuesday 2025-04-01 · Includes alternate forms & mega evolutions · n = 949\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(\n    plot.title        = ggtext::element_markdown(face = \"bold\", size = 17, margin = margin(b = 4)),\n    plot.subtitle     = ggtext::element_markdown(color = \"grey40\", size = 10.5, lineheight = 1.4,\n                                                  margin = margin(b = 12)),\n    plot.caption      = element_text(color = \"grey55\", size = 9, margin = margin(t = 10)),\n    axis.text.y       = element_text(size = 11.5, face = \"bold\"),\n    axis.text.x.top   = element_text(size = 13, face = \"bold\"),\n    panel.grid        = element_blank(),\n    legend.position   = \"left\",\n    legend.title      = element_text(size = 10, face = \"bold\"),\n    legend.key.height = unit(1.2, \"cm\"),\n    plot.background   = element_rect(fill = \"white\", color = NA),\n    plot.margin       = margin(16, 80, 16, 16)\n  )\n\np\n```\n\n::: {.cell-output-display}\n![](2025-04-01-pokemon_files/figure-html/viz-stat-heatmap-1.png){width=960}\n:::\n:::\n\n\n\n::: {.callout-important}\n**Reading the heatmap:** Each cell shows the z-score for that type's *median* in that stat. A Dragon type Atk of +1.34 means Dragon-types' median Attack is 1.34 standard deviations above the average Pokémon's Attack. Numbers in white appear on the most extreme cells (|z| > 1.2) for legibility.\n:::\n\n## Key Patterns\n\n**Dragon is everything.** Its row is the most uniformly red in the chart — no obvious weaknesses and strong across all six dimensions. This isn't a design accident; Dragon was deliberately made hard to counter in Generation I, a problem Game Freak addressed by introducing Fairy types in Gen VI.\n\n**Steel is the defensive wall.** Its Defense z-score (+1.76) is the single highest value in the entire heatmap. Steel types sacrifice Speed and HP for nearly unbreakable physical bulk — the competitive \"wall\" archetype.\n\n**Psychic is a special attacker.** The Psychic row shows the clearest single-stat spike: Special Attack is well above average while physical Attack lags below. Classic glass cannon for the special side of the damage split.\n\n**Bug carries the floor.** Every stat in the Bug row is negative or near zero. It's the lowest-total type by a meaningful margin (median total: 400 vs. Dragon's 600), a legacy of the early generations when Bug types were filler enemies and didn't receive the design investment of flashier types.\n\n**Speed is the most polarizing stat.** The Spe column has the widest spread — Flying and Electric types are fast; Steel and Fairy are slow. No other stat shows this much stratification across types.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter to Pokémon with a known generation_id (excludes alternate forms with NA gen)\npokemon_gen <- pokemon %>%\n  dplyr::filter(!is.na(generation_id)) %>%\n  dplyr::mutate(generation_id = factor(generation_id, levels = sort(unique(generation_id))))\n\ncat(sprintf(\"pokemon_gen (known generation): %d rows\\n\", nrow(pokemon_gen)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npokemon_gen (known generation): 802 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"No rows after gen filter\" = nrow(pokemon_gen) > 0)\n\ngen_summary <- pokemon_gen %>%\n  dplyr::group_by(generation_id) %>%\n  dplyr::summarize(\n    n      = dplyr::n(),\n    med    = median(base_total),\n    q25    = quantile(base_total, 0.25),\n    q75    = quantile(base_total, 0.75),\n    .groups = \"drop\"\n  )\n\np2 <- ggplot(gen_summary, aes(x = generation_id)) +\n  geom_linerange(aes(ymin = q25, ymax = q75), linewidth = 6, color = \"#4E79A7\", alpha = 0.35) +\n  geom_point(aes(y = med), size = 5, color = \"#C34129\", shape = 18) +\n  geom_text(aes(y = med, label = sprintf(\"%.0f\", med)),\n            vjust = -1.1, size = 3.5, fontface = \"bold\", color = \"grey25\") +\n  labs(\n    title    = \"Power Creep? Median Base Stat Total by Generation\",\n    subtitle = \"Diamond = median · Bar = IQR (25th–75th percentile) · Alternate forms excluded\",\n    x        = \"Generation\",\n    y        = \"Base Stat Total\",\n    caption  = \"Source: TidyTuesday 2025-04-01\"\n  ) +\n  scale_y_continuous(limits = c(280, 600)) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title     = element_text(face = \"bold\", size = 14),\n    plot.subtitle  = element_text(color = \"grey45\", size = 10),\n    panel.grid.major.x = element_blank(),\n    panel.grid.minor   = element_blank()\n  )\n\np2\n```\n\n::: {.cell-output-display}\n![](2025-04-01-pokemon_files/figure-html/viz-generation-powercreep-1.png){width=864}\n:::\n:::\n\n\n\nThe \"power creep\" narrative doesn't hold up under the median. The middle of each generation's distribution has been remarkably stable — Generation V's median (456) is the highest in this dataset, but only marginally. What *has* changed is the upper tail: each generation adds a new cohort of legendaries and pseudo-legendaries that push the maximum upward, widening the IQR without moving the median.\n\n# Palette Log Update\n\n\n\n::: {.cell}\n\n:::\n\n\n\n# Final thoughts and takeaways\n\nThe stat fingerprint heatmap makes a pattern visible that every longtime Pokémon fan has *felt* but maybe never seen quantified: **type identity is real and consistent**. Dragon types aren't just aesthetically cool — their median stats are genuinely elite across every dimension. Steel types aren't just defensively flavored — their Defense z-score of +1.76 is the most extreme single value in the entire chart. The types have coherent combat identities, and the designers have maintained those identities across nine generations of game design.\n\nA few caveats worth noting. First, the dataset includes mega evolutions and alternate forms, which can distort type medians (Dragon gets a slight boost from Mega Rayquaza and the various Kyurem forms). A cleaner analysis would restrict to base-form Pokémon only. Second, the \"primary type\" framing misses dual-type interactions — Charizard is Fire/Flying, not just Fire, and those secondary types matter enormously in competitive play. A network analysis of type combinations would be a natural next step.\n\nThe generation power creep analysis offers a surprising counternarrative: the *median* Pokémon hasn't gotten meaningfully stronger over time. What's grown is the ceiling — each generation adds more ultra-powerful outliers — but the typical new Pokémon you encounter in the wild is about as strong as one from Generation I. That's an impressive bit of design discipline maintained over nearly 30 years.\n",
    "supporting": [
      "2025-04-01-pokemon_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}