{
  "hash": "9a565aa8f1aed6d08b035b61cc3bb1e9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Golem Grad Tortoise Data\"\nauthor: \"Sean Thimons\"\ndate: \"2026-03-03\"\ndescription: \"Long-term monitoring of Hermann's tortoises in the western Balkans reveals a near-perfect relationship between body size and clutch size—and that females consistently outweigh their own shells.\"\ncategories: [tidytuesday, R, ecology, herpetology, wildlife]\n---\n\n\n\n# Preface\n\nFrom the [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2026/2026-03-03).\n\n> This week's dataset comes from a long-term mark-recapture study of Hermann's tortoises (*Testudo hermanni*) monitored across three localities in the western Balkans. Two datasets are included: body condition index (BCI) measurements collected annually from 2008–2023, and clutch size records paired with morphometric measurements from nesting females. The BCI captures how an individual's actual body mass compares to the expected mass given its shell length — a proxy for nutritional condition and fat reserves.\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  booster_pack <- c(\n    ### IO ----\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n\n    ### EDA ----\n    'skimr',\n\n    ### Plot ----\n    'paletteer',           # Color palette collection\n    'patchwork',           # Multi-panel layouts\n    'ggrepel',             # Non-overlapping labels\n    'ggridges',            # Ridge / joy plots\n\n    ### Misc ----\n    'tidytuesdayR'\n  )\n\n  install_booster_pack(package = booster_pack, load = TRUE)\n  rm(install_booster_pack, booster_pack)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2026-03-03')\n\n# Clutch size: nesting females with egg counts and morphometrics\nclutch <- raw$clutch_size_cleaned\n\n# Body condition index: repeated annual measurements, 2008–2023\nbody   <- raw$tortoise_body_condition_cleaned\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of `skimr::skim()` that returns the number of missing data points as well as the inverse, the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram.\n\n## Clutch size data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Drop: individual ID and date (not analytically useful for profiling)\nclutch %>%\n  select(-individual, -date) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |53         |\n|Number of columns        |5          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |1          |\n|numeric                  |4          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|locality      |         0|             1|   5|   7|     0|        3|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable               | n_missing| complete_rate|  n| min|  p25|  med|  p75|  max|    mean| geo_mean|     sd|hist  |\n|:---------------------------|---------:|-------------:|--:|---:|----:|----:|----:|----:|-------:|--------:|------:|:-----|\n|age                         |         0|             1| 53|  15|   20|   22|   30|   30|   24.09|    23.53|   5.19|▃▅▅▁▇ |\n|eggs                        |         0|             1| 53|   1|    3|    5|    6|   11|    4.79|     4.31|   2.11|▇▇▇▁▁ |\n|body_mass_grams             |         0|             1| 53| 541| 1116| 1494| 1712| 2920| 1505.04|  1404.26| 564.60|▆▆▇▃▂ |\n|straight_carapace_length_mm |         0|             1| 53| 142|  176|  192|  206|  260|  191.15|   189.25|  27.33|▅▅▇▂▂ |\n\n\n:::\n:::\n\n\n\nThe clutch dataset is small — 53 observations from nesting females across three localities (Beach, Konjsko, Plateau), ages 15–30 years. Egg counts range from 1 to 11, with a median of 5. Body mass spans from 541 g to nearly 3 kg, and carapace length from 142 mm to 260 mm. The wide ranges across both size measures hint at strong individual variation — and possibly a tight relationship between size and clutch size.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Localities:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLocalities:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(count(clutch, locality))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  locality     n\n  <chr>    <int>\n1 Beach       13\n2 Konjsko     31\n3 Plateau      9\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nAge distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAge distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(count(clutch, age))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 2\n     age     n\n   <dbl> <int>\n 1    15     1\n 2    16     2\n 3    17     3\n 4    18     2\n 5    19     2\n 6    20     6\n 7    21     5\n 8    22     6\n 9    23     2\n10    24     3\n11    30    21\n```\n\n\n:::\n:::\n\n\n\n## Body condition data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Drop: year_recode (redundant with year)\nbody %>%\n  select(-year_recode) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |10174      |\n|Number of columns        |8          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |4          |\n|numeric                  |4          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|individual    |         0|             1|   1|   6|     0|     2139|          0|\n|season        |         0|             1|   6|   6|     0|        2|          0|\n|locality      |         0|             1|   5|   7|     0|        3|          0|\n|sex           |         0|             1|   1|   1|     0|        2|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable               | n_missing| complete_rate|     n|     min|     p25|     med|     p75|    max|    mean| geo_mean|     sd|hist  |\n|:---------------------------|---------:|-------------:|-----:|-------:|-------:|-------:|-------:|------:|-------:|--------:|------:|:-----|\n|year                        |         0|             1| 10174| 2008.00| 2011.00| 2016.00| 2018.00| 2023.0| 2014.90|  2014.90|   4.51|▇▂▆▃▃ |\n|body_mass_grams             |         0|             1| 10174|  528.00|  962.00| 1092.00| 1248.00| 2913.0| 1133.48|  1106.36| 263.52|▅▇▁▁▁ |\n|body_condition_index        |         0|             1| 10174|    3.52|    5.66|    6.19|    6.78|   11.7|    6.31|     6.24|   0.98|▁▇▂▁▁ |\n|straight_carapace_length_mm |         0|             1| 10174|  150.00|  169.00|  177.00|  185.00|  250.0|  177.77|   177.27|  13.36|▅▇▂▁▁ |\n\n\n:::\n:::\n\n\n\nThe longitudinal body condition dataset contains 10,174 measurements across 16 years (2008–2023). No missing values. The BCI ranges from 3.5 to ~11.7, centered around 6.1–6.3. The split between Spring and Summer observations is roughly 55/45. Sex coding is `\"f\"` and `\"m\"` — important to note for filtering later.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Sex values:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSex values:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(count(body, sex))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  sex       n\n  <chr> <int>\n1 f      1435\n2 m      8739\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nLocalities:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLocalities:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(count(body, locality))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  locality     n\n  <chr>    <int>\n1 Beach      618\n2 Konjsko   1616\n3 Plateau   7940\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nSeasons:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSeasons:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(count(body, season))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  season     n\n  <chr>  <int>\n1 Spring  5747\n2 Summer  4427\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nBCI by sex (mean ± SD):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBCI by sex (mean ± SD):\n```\n\n\n:::\n\n```{.r .cell-code}\nbody %>%\n  group_by(sex) %>%\n  summarize(\n    n        = n(),\n    mean_bci = round(mean(body_condition_index), 3),\n    sd_bci   = round(sd(body_condition_index), 3),\n    .groups  = \"drop\"\n  ) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  sex       n mean_bci sd_bci\n  <chr> <int>    <dbl>  <dbl>\n1 f      1435     7.48  1.37 \n2 m      8739     6.12  0.742\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nBCI by locality:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBCI by locality:\n```\n\n\n:::\n\n```{.r .cell-code}\nbody %>%\n  group_by(locality) %>%\n  summarize(\n    n        = n(),\n    mean_bci = round(mean(body_condition_index), 3),\n    .groups  = \"drop\"\n  ) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  locality     n mean_bci\n  <chr>    <int>    <dbl>\n1 Beach      618     5.80\n2 Konjsko   1616     7.46\n3 Plateau   7940     6.12\n```\n\n\n:::\n:::\n\n\n\nThe EDA reveals two striking patterns:\n\n1. **Sex gap**: Females average BCI 7.48 vs. males 6.12 — more than a full unit difference, with females showing substantially wider spread (SD 1.37 vs. 0.74).\n2. **Locality gap**: Konjsko individuals score highest (BCI 7.46), well above Beach (5.80) and Plateau (6.12).\n\nThese patterns motivate the two analytical threads below.\n\n---\n\n# Body condition: who's in the best shape, and where?\n\nThe body condition index here is a residual measure — it captures how much an individual's actual body mass deviates from the expected mass given its shell length. Higher BCI means the animal is carrying more mass relative to its structural size, a proxy for fat reserves and nutritional status.\n\n::: {.callout-note}\nIn reptiles, elevated fat reserves in females are not simply a sign of good health — they're a reproductive necessity. Female tortoises must accumulate substantial lipid stores prior to egg formation. The ~22% BCI advantage females show over males in this dataset is likely a direct reflection of that investment.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Verify sex × locality combination counts before plotting\nbci_plot_data <- body %>%\n  mutate(\n    sex_label = ifelse(sex == \"f\", \"Female\", \"Male\"),\n    sex_label = factor(sex_label, levels = c(\"Female\", \"Male\"))\n  )\n\ncat(sprintf(\"bci_plot_data: %d rows, %d cols\\n\", nrow(bci_plot_data), ncol(bci_plot_data)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbci_plot_data: 10174 rows, 10 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Plot data has 0 rows\" = nrow(bci_plot_data) > 0)\n\n# Check actual BCI range is sensible\nbci_range <- range(bci_plot_data$body_condition_index)\ncat(sprintf(\"BCI range: %.2f – %.2f\\n\", bci_range[1], bci_range[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBCI range: 3.52 – 11.70\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlocality_colors <- paletteer::paletteer_d(\"MetBrewer::Kandinsky\", n = 3)\nnames(locality_colors) <- c(\"Beach\", \"Konjsko\", \"Plateau\")\n\np_bci <- ggplot2::ggplot(\n  bci_plot_data,\n  ggplot2::aes(\n    x    = body_condition_index,\n    y    = locality,\n    fill = locality,\n    color = locality\n  )\n) +\n  ggridges::geom_density_ridges(\n    alpha        = 0.7,\n    scale        = 0.9,\n    quantile_lines = TRUE,\n    quantiles    = 2,        # median line\n    jittered_points = FALSE\n  ) +\n  ggplot2::facet_wrap(~sex_label, ncol = 2) +\n  ggplot2::scale_fill_manual(values = locality_colors) +\n  ggplot2::scale_color_manual(values = locality_colors) +\n  ggplot2::scale_x_continuous(breaks = seq(4, 12, by = 2)) +\n  ggplot2::labs(\n    title    = \"Female tortoises maintain higher body condition across all localities\",\n    subtitle = \"Body Condition Index (BCI) distributions by sex and locality, 2008–2023\\nVertical lines mark median BCI per group\",\n    x        = \"Body Condition Index\",\n    y        = NULL,\n    fill     = \"Locality\",\n    color    = \"Locality\",\n    caption  = \"Source: TidyTuesday 2026-03-03 | Golem Grad Tortoise Data\"\n  ) +\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    plot.title         = ggplot2::element_text(face = \"bold\", size = 15),\n    plot.subtitle      = ggplot2::element_text(color = \"gray40\", size = 11),\n    plot.caption       = ggplot2::element_text(color = \"gray55\", size = 9),\n    strip.text         = ggplot2::element_text(face = \"bold\", size = 13),\n    legend.position    = \"none\",\n    panel.grid.minor   = ggplot2::element_blank(),\n    panel.grid.major.y = ggplot2::element_blank()\n  )\n\np_bci\n```\n\n::: {.cell-output-display}\n![](2026-03-03-golem-grad-tortoise-data_files/figure-html/viz-bci-ridge-1.png){width=960}\n:::\n:::\n\n\n\nThe ridge distributions tell a clear story. For **females**, the Konjsko population is shifted markedly rightward — a heavy right tail reaching past BCI 10. Beach and Plateau females overlap considerably but trail Konjsko by a full unit at the median. For **males**, distributions are tighter and more uniform across localities, all clustering around BCI 5.5–6.5. The male Konjsko advantage disappears in the tight BCI range.\n\nThis locality × sex interaction suggests that Konjsko habitat uniquely enables females to achieve the elevated fat deposits necessary for robust egg production — a pattern we can test directly with the clutch data.\n\n---\n\n# Body size predicts reproductive output\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Verify actual locality values in the clutch dataset\ncat(\"Localities in clutch data:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLocalities in clutch data:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(sort(unique(clutch$locality)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Beach\"   \"Konjsko\" \"Plateau\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Confirm these match the BCI dataset\nstopifnot(all(clutch$locality %in% c(\"Beach\", \"Konjsko\", \"Plateau\")))\n\ncat(sprintf(\"clutch: %d rows, %d cols\\n\", nrow(clutch), ncol(clutch)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclutch: 53 rows, 7 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"clutch has 0 rows\" = nrow(clutch) > 0)\n\n# Correlation statistics\ncor_mass  <- cor.test(clutch$body_mass_grams, clutch$eggs)\ncor_scl   <- cor.test(clutch$straight_carapace_length_mm, clutch$eggs)\n\ncat(sprintf(\"\\nBody mass × eggs:    r = %.3f, p < 2.2e-16\\n\", cor_mass$estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBody mass × eggs:    r = 0.896, p < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Carapace × eggs:     r = %.3f, p < 2.2e-16\\n\", cor_scl$estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCarapace × eggs:     r = 0.882, p < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# Sanity check: are eggs proportional values or counts?\ncat(sprintf(\"\\nEgg count range: %d – %d (should be counts, not proportions)\\n\",\n            min(clutch$eggs), max(clutch$eggs)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEgg count range: 1 – 11 (should be counts, not proportions)\n```\n\n\n:::\n\n```{.r .cell-code}\nif (max(clutch$eggs) <= 1) {\n  warning(\"Eggs column looks like proportions, not counts — check data\")\n}\n```\n:::\n\n\n\nThe Pearson correlation between body mass and clutch size is **r = 0.896** (p < 2.2e–16). For a biological dataset with only 53 observations spanning wild-caught individuals across multiple years, this is a remarkably tight relationship. Carapace length shows nearly identical predictive power (r = 0.882).\n\n::: {.callout-important}\n**What r = 0.896 means in practice**: roughly 80% of the variance in egg count is accounted for by body mass alone. The largest female in the sample (2,920 g) laid 11 eggs; the smallest (541 g) laid 1. That's an 11-fold range in reproductive output explained almost entirely by how big the animal is.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Label outliers: largest clutch per locality, and the minimum\nlabel_pts <- bind_rows(\n  clutch %>%\n    group_by(locality) %>%\n    slice_max(order_by = eggs, n = 1, with_ties = FALSE),\n  clutch %>%\n    slice_min(order_by = eggs, n = 1, with_ties = FALSE)\n) %>%\n  distinct(individual, .keep_all = TRUE) %>%\n  mutate(label = paste0(eggs, \" eggs\\n\", body_mass_grams, \" g\"))\n\ncat(sprintf(\"label_pts: %d rows\\n\", nrow(label_pts)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlabel_pts: 4 rows\n```\n\n\n:::\n\n```{.r .cell-code}\np_scatter <- ggplot2::ggplot(\n  clutch,\n  ggplot2::aes(x = body_mass_grams, y = eggs, color = locality)\n) +\n  ggplot2::geom_smooth(\n    method    = \"lm\",\n    se        = TRUE,\n    color     = \"gray30\",\n    fill      = \"gray85\",\n    linewidth = 0.8,\n    linetype  = \"dashed\"\n  ) +\n  ggplot2::geom_point(\n    ggplot2::aes(size = straight_carapace_length_mm),\n    alpha = 0.85\n  ) +\n  ggrepel::geom_text_repel(\n    data        = label_pts,\n    ggplot2::aes(label = label),\n    size        = 3.2,\n    nudge_y     = 0.4,\n    nudge_x     = 30,\n    color       = \"gray20\",\n    segment.color = \"gray60\",\n    segment.size  = 0.4,\n    box.padding   = 0.4\n  ) +\n  ggplot2::scale_color_manual(values = locality_colors) +\n  ggplot2::scale_size_continuous(\n    name   = \"Carapace length (mm)\",\n    range  = c(2, 8),\n    breaks = c(160, 200, 240)\n  ) +\n  ggplot2::annotate(\n    \"text\",\n    x     = 600,\n    y     = 10.5,\n    label = \"r = 0.896 | p < 0.001\",\n    hjust = 0,\n    size  = 4,\n    color = \"gray20\",\n    fontface = \"bold\"\n  ) +\n  ggplot2::scale_x_continuous(labels = scales::comma) +\n  ggplot2::scale_y_continuous(breaks = 1:11) +\n  ggplot2::labs(\n    title    = \"Bigger tortoises lay more eggs\",\n    subtitle = \"Body mass vs. clutch size in Hermann's tortoises across three localities\\nPoint size scales with straight carapace length\",\n    x        = \"Body mass (g)\",\n    y        = \"Clutch size (eggs)\",\n    color    = \"Locality\",\n    caption  = \"Source: TidyTuesday 2026-03-03 | Golem Grad Tortoise Data\"\n  ) +\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    plot.title       = ggplot2::element_text(face = \"bold\", size = 15),\n    plot.subtitle    = ggplot2::element_text(color = \"gray40\", size = 11),\n    plot.caption     = ggplot2::element_text(color = \"gray55\", size = 9),\n    panel.grid.minor = ggplot2::element_blank(),\n    legend.position  = \"right\"\n  )\n\np_scatter\n```\n\n::: {.cell-output-display}\n![](2026-03-03-golem-grad-tortoise-data_files/figure-html/hero-scatter-1.png){width=960}\n:::\n:::\n\n\n\nThe scatter makes the relationship almost uncomfortable in its linearity — these points want to fall on a line. Konjsko individuals (amber) tend to cluster in the upper-right corner (high mass, high clutch size), consistent with the BCI advantage we saw in the ridge plots. Beach tortoises (teal) appear mostly at mid-mass; the single Plateau point near the top right is a notable outlier.\n\n---\n\n# Log palette\n\n\n\n::: {.cell}\n\n:::\n\n\n\n# Final thoughts and takeaways\n\nThis dataset from a Balkan Hermann's tortoise study turns out to be a compact illustration of two intertwined ecological principles:\n\n**Body condition is sex-stratified by design.** The ~22% BCI gap between females and males isn't a sign that males are unhealthy — it reflects the asymmetric energetic demands of reproduction. Females must mobilize fat reserves to produce calcified eggs; males don't. Konjsko amplifies this effect, suggesting better vegetation cover or food availability that enables females there to achieve the highest pre-nesting condition in the dataset. This locality-level effect has real conservation implications: habitat degradation at Konjsko would disproportionately harm female reproductive success.\n\n**Size is reproductive destiny, at r = 0.896.** This correlation is extremely high for a wild biological dataset. It means that a female tortoise's body mass is, in practice, a near-sufficient predictor of how many eggs she will lay — more than age, year, or locality alone. Since tortoises grow slowly and live for decades, this finding elevates early life conditions (juvenile growth rates, food availability) as critical determinants of lifetime reproductive output. A tortoise that grows slowly in its first decade carries that reproductive penalty for life.\n\n**Limitations**: The clutch size dataset is small (n = 53) and restricted to females who were observed nesting — likely biased toward better-condition individuals who successfully nested. The BCI data is far richer but tracks a narrow three-locality window of a much wider species range. Generalizing these patterns to other *T. hermanni* populations requires caution.\n\nThe overall picture, though, is coherent: take care of the habitat, the females grow bigger, and they lay more eggs. That's a tractable conservation lever.\n",
    "supporting": [
      "2026-03-03-golem-grad-tortoise-data_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}