{
  "hash": "65c44d3cec27a0ede804ba932ef3eea9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: What Have We Been Watching on Netflix?\"\nauthor: \"Sean Thimons\"\ndate: \"2025-07-29\"\ndescription: \"Analyzing Netflix's engagement reports from H2 2023 through H1 2025 to reveal what titles dominated global viewing—and why international content is quietly running the platform.\"\ncategories: [tidytuesday, R, netflix, entertainment, streaming]\n---\n\n\n\n# Preface\n\nFrom [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-07-29).\n\n> Netflix publishes semi-annual \"What We Watched\" engagement reports covering approximately 99% of all viewing activity. This dataset compiles four consecutive reports—H2 2023, H1 2024, H2 2024, and H1 2025—spanning both movies and TV shows, with total hours viewed, runtime, implied view counts, and global availability status for each title.\n\nSuggested questions from the dataset:\n\n- How do older titles compare to newer releases in sustained viewership?\n- Does release timing (month/season) influence engagement?\n- Are globally available titles more popular than regionally restricted ones?\n- Which movie types consistently perform well across reporting periods?\n- How do later seasons of shows perform relative to earlier seasons?\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  if (file.exists('packages.txt')) {\n    packages <- read.table('packages.txt')\n\n    install_booster_pack(package = packages$Package, load = FALSE)\n\n    rm(packages)\n  } else {\n    ## Packages ----\n\n    booster_pack <- c(\n      ### IO ----\n      'fs',\n      'here',\n      'janitor',\n      'rio',\n      'tidyverse',\n\n      ### EDA ----\n      'skimr',\n\n      ### Plot ----\n      'paletteer',           # Color palette collection\n      'ggtext',              # Rich text in ggplot titles/labels\n      'ggrepel',             # Non-overlapping labels\n      'patchwork',           # Multi-panel layouts\n\n      ### Misc ----\n      'tidytuesdayR'\n    )\n\n    # ! Change load flag to load packages\n    install_booster_pack(package = booster_pack, load = TRUE)\n    rm(install_booster_pack, booster_pack)\n  }\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2025-07-29')\n\nmovies <- raw$movies %>%\n  janitor::clean_names() %>%\n  mutate(content_type = \"Movie\")\n\nshows <- raw$shows %>%\n  janitor::clean_names() %>%\n  mutate(content_type = \"Show\")\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## Movies\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Drop source (redundant with report) and runtime (character, parsed separately)\nmovies %>%\n  select(-source, -runtime) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |36121      |\n|Number of columns        |7          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |4          |\n|Date                     |1          |\n|numeric                  |2          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable      | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:------------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|report             |         0|             1|  11|  11|     0|        4|          0|\n|title              |         6|             1|   1| 144|     0|    13551|          0|\n|available_globally |         9|             1|   2|  19|     0|        3|          0|\n|content_type       |         0|             1|   5|   5|     0|        1|          0|\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|release_date  |     29396|          0.19|2013-12-12 |2025-06-30 |2021-08-13 |     1128|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|     n|   min|   p25|   med|     p75|       max|    mean| geo_mean|      sd|hist  |\n|:-------------|---------:|-------------:|-----:|-----:|-----:|-----:|-------:|---------:|-------:|--------:|-------:|:-----|\n|hours_viewed  |        12|             1| 36121| 1e+05| 2e+05| 4e+05| 1900000| 313000000| 2790858| 606805.6| 9054284|▇▁▁▁▁ |\n|views         |        12|             1| 36121| 1e+05| 1e+05| 3e+05| 1100000| 164700000| 1573256| 392923.0| 4974895|▇▁▁▁▁ |\n\n\n:::\n:::\n\n\n\nThe movies dataset spans **36,121 entries** across four semi-annual reporting periods. The median movie earned around **400,000 hours** of viewing—which sounds impressive until you notice the mean is nearly 7× higher at 2.8M hours, signaling a heavily right-skewed distribution. A small number of blockbusters are dragging the mean far above the typical title. Release date is missing for roughly 80% of entries, so temporal analysis will be limited to the report period rather than individual release dates.\n\n## Shows\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshows %>%\n  select(-source, -runtime) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |27803      |\n|Number of columns        |7          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |4          |\n|Date                     |1          |\n|numeric                  |2          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable      | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:------------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|report             |         0|             1|  11|  11|     0|        4|          0|\n|title              |         6|             1|   3| 225|     0|     9913|          0|\n|available_globally |         9|             1|   2|  19|     0|        3|          0|\n|content_type       |         0|             1|   4|   4|     0|        1|          0|\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|release_date  |     14033|           0.5|2010-04-01 |2025-06-30 |2021-04-14 |     1968|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|     n|   min|   p25|     med|     p75|       max|    mean|  geo_mean|       sd|hist  |\n|:-------------|---------:|-------------:|-----:|-----:|-----:|-------:|-------:|---------:|-------:|---------:|--------:|:-----|\n|hours_viewed  |        12|             1| 27803| 1e+05| 8e+05| 2500000| 8200000| 840300000| 9807243| 2621429.5| 26327450|▇▁▁▁▁ |\n|views         |        12|             1| 27803| 1e+05| 2e+05|  400000| 1300000| 144800000| 1414994|  497184.2|  3665090|▇▁▁▁▁ |\n\n\n:::\n:::\n\n\n\nTV shows tell a different story. With **27,803 entries**, the catalog is smaller—but the numbers are much bigger. The median show earns **2.5M hours** (6× a median movie), and the mean climbs to 9.8M hours. The top show in any single period earned 840M hours. Shows are also the \"stickier\" content: binge-watching entire seasons naturally accumulates more total hours than any single film.\n\n::: {.callout-note}\nThe `available_globally` column contains three artifact rows with the literal value `\"Available Globally?\"` (likely header rows from the original Excel export). These are filtered out during analysis.\n:::\n\n# The Netflix Viewing Landscape\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Combine, filter artifacts and missing hour data\nnetflix <- bind_rows(movies, shows) %>%\n  filter(available_globally %in% c(\"Yes\", \"No\")) %>%\n  filter(!is.na(hours_viewed))\n\n# Flag international content: bilingual titles use \" // \" separator (mostly Korean)\n# Flag limited series: explicit format name in title\nnetflix <- netflix %>%\n  mutate(\n    is_international = str_detect(title, \" // \"),\n    is_limited_series = str_detect(title, \"Limited Series\"),\n    title_display = if_else(\n      is_international,\n      str_remove(title, \" //.*\"),\n      title\n    )\n  )\n\ncat(sprintf(\"Combined clean dataset: %d rows, %d cols\\n\", nrow(netflix), ncol(netflix)))\ncat(sprintf(\"Movies: %d rows | Shows: %d rows\\n\",\n            sum(netflix$content_type == \"Movie\"),\n            sum(netflix$content_type == \"Show\")))\n```\n:::\n\n\n\n## Shows vs. Movies: Hours Are Not Created Equal\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregate total hours by content type and report period\ntype_by_period <- netflix %>%\n  group_by(content_type, report) %>%\n  summarise(\n    total_hours_B = sum(hours_viewed, na.rm = TRUE) / 1e9,\n    n_titles = n(),\n    .groups = \"drop\"\n  ) %>%\n  mutate(\n    report = factor(report, levels = c(\"2023Jul-Dec\", \"2024Jan-Jun\", \"2024Jul-Dec\", \"2025Jan-Jun\"),\n                    labels = c(\"H2 2023\", \"H1 2024\", \"H2 2024\", \"H1 2025\"))\n  )\n\ncat(sprintf(\"type_by_period: %d rows, %d cols\\n\", nrow(type_by_period), ncol(type_by_period)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntype_by_period: 8 rows, 4 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"type_by_period has 0 rows\" = nrow(type_by_period) > 0)\n\np_type <- type_by_period %>%\n  ggplot(ggplot2::aes(x = report, y = total_hours_B, fill = content_type, group = content_type)) +\n  ggplot2::geom_col(position = \"dodge\", width = 0.65, alpha = 0.9) +\n  ggplot2::geom_text(\n    ggplot2::aes(label = sprintf(\"%.0fB\", total_hours_B)),\n    position = position_dodge(width = 0.65),\n    vjust = -0.4, size = 3.2, color = \"grey30\"\n  ) +\n  paletteer::scale_fill_paletteer_d(\"nationalparkcolors::Arches\") +\n  ggplot2::scale_y_continuous(\n    labels = scales::label_number(suffix = \"B\"),\n    expand = ggplot2::expansion(mult = c(0, 0.12))\n  ) +\n  ggplot2::labs(\n    title = \"TV shows dwarf movies in total viewing hours\",\n    subtitle = \"Combined hours viewed across all titles per reporting period (billions)\",\n    x = NULL,\n    y = \"Total hours viewed\",\n    fill = NULL,\n    caption = \"Source: Netflix 'What We Watched' Engagement Reports via TidyTuesday\"\n  ) +\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    legend.position = \"top\",\n    plot.title = ggplot2::element_text(face = \"bold\", size = 15),\n    plot.subtitle = ggplot2::element_text(color = \"grey40\", size = 11),\n    panel.grid.major.x = ggplot2::element_blank(),\n    panel.grid.minor = ggplot2::element_blank()\n  )\n\np_type\n```\n\n::: {.cell-output-display}\n![](2025-07-29-what-have-we-been-watching-on-netflix_files/figure-html/type-comparison-1.png){width=864}\n:::\n:::\n\n\n\nAcross every reporting period, TV shows generate **3–4× more total hours** than movies, despite having a smaller catalog. This isn't simply a runtime effect—the `views` column (hours ÷ runtime) tells the same story. People return to shows, finish seasons, and re-watch episodes. Movies, for all their cultural prestige, are inherently one-and-done.\n\n## International Content's Quiet Dominance\n\nNetflix's bilingual title convention—\"Squid Game: Season 2 // 오징어 게임: 시즌 2\"—makes international content easy to identify. These double-named titles are predominantly Korean dramas, though Spanish, Thai, and other language productions also use this format.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintl_summary <- netflix %>%\n  group_by(content_type, is_international) %>%\n  summarise(\n    n_titles = n(),\n    total_hours_B = sum(hours_viewed, na.rm = TRUE) / 1e9,\n    median_hours_M = median(hours_viewed, na.rm = TRUE) / 1e6,\n    .groups = \"drop\"\n  ) %>%\n  mutate(language_label = if_else(is_international, \"International\", \"English / Other\"))\n\ncat(sprintf(\"intl_summary: %d rows\\n\", nrow(intl_summary)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nintl_summary: 4 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(intl_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  content_type is_international n_titles total_hours_B median_hours_M\n  <chr>        <lgl>               <int>         <dbl>          <dbl>\n1 Movie        FALSE               23252          83.8            0.7\n2 Movie        TRUE                12857          17.0            0.3\n3 Show         FALSE               18166         194.             2.9\n4 Show         TRUE                 9625          78.8            2  \n# ℹ 1 more variable: language_label <chr>\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-important}\nInternational shows—identifiable by their bilingual title format—account for a **disproportionately large share of top viewership** relative to their catalog size. Among shows in the top 25 all-time by total hours, roughly half carry a bilingual title.\n:::\n\n# Netflix's Most-Watched Shows, H2 2023–H1 2025\n\nThe central question: after aggregating all four reporting periods, which shows have racked up the most cumulative viewing time?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregate shows across all periods they appear in\ntop_shows <- netflix %>%\n  filter(content_type == \"Show\") %>%\n  group_by(title, title_display, is_international, is_limited_series) %>%\n  summarise(\n    total_hours = sum(hours_viewed, na.rm = TRUE),\n    n_periods = n_distinct(report),\n    peak_hours = max(hours_viewed, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  slice_max(total_hours, n = 25) %>%\n  mutate(\n    hours_B = total_hours / 1e9,\n    content_label = case_when(\n      is_international & is_limited_series ~ \"Intl. Limited Series\",\n      is_international ~ \"International Series\",\n      is_limited_series ~ \"Limited Series\",\n      TRUE ~ \"English Series\"\n    )\n  )\n\ncat(sprintf(\"top_shows: %d rows\\n\", nrow(top_shows)))\nstopifnot(\"top_shows is empty\" = nrow(top_shows) > 0)\n\n# Verify we have variation in content_label\ncat(\"Content label distribution:\\n\")\nprint(table(top_shows$content_label))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Select 4 colors from the Arches palette for 4 content label categories\narch_colors <- as.character(paletteer::paletteer_d(\"nationalparkcolors::Arches\"))\n\n# Map colors to content categories (Arches has 6 colors: light blue, orange, dark red, mauve, slate, warm gray)\ncontent_colors <- c(\n  \"English Series\"       = arch_colors[1],\n  \"Limited Series\"       = arch_colors[2],\n  \"International Series\" = arch_colors[3],\n  \"Intl. Limited Series\" = arch_colors[4]\n)\n\n# If any category isn't present, this won't break — scale_color_manual handles missing levels\n\np_hero <- top_shows %>%\n  mutate(\n    title_display = fct_reorder(title_display, hours_B),\n    label_text = sprintf(\"%.1fB hrs\", hours_B)\n  ) %>%\n  ggplot2::ggplot(ggplot2::aes(x = hours_B, y = title_display, color = content_label)) +\n  # Segment from 0 to dot\n  ggplot2::geom_segment(\n    ggplot2::aes(x = 0, xend = hours_B, yend = title_display),\n    linewidth = 0.7, alpha = 0.6\n  ) +\n  # Point sized by number of reporting periods\n  ggplot2::geom_point(ggplot2::aes(size = n_periods), alpha = 0.95) +\n  # Hours label\n  ggplot2::geom_text(\n    ggplot2::aes(label = label_text),\n    hjust = -0.2, size = 3, color = \"grey25\"\n  ) +\n  ggplot2::scale_color_manual(\n    values = content_colors,\n    name = \"Format\"\n  ) +\n  ggplot2::scale_size_continuous(\n    name = \"Reporting\\nperiods\",\n    range = c(3, 7),\n    breaks = c(1, 2, 3, 4)\n  ) +\n  ggplot2::scale_x_continuous(\n    labels = scales::label_number(suffix = \"B\"),\n    expand = ggplot2::expansion(mult = c(0.01, 0.18))\n  ) +\n  ggplot2::labs(\n    title = \"What the world watched on Netflix\",\n    subtitle = \"Top 25 TV shows by cumulative hours viewed across H2 2023 – H1 2025\\nDot size = number of reporting periods the title appeared in\",\n    x = \"Total hours viewed (billions)\",\n    y = NULL,\n    caption = \"Source: Netflix 'What We Watched' Engagement Reports via TidyTuesday | @seanthimons\"\n  ) +\n  ggplot2::theme_minimal(base_size = 12) +\n  ggplot2::theme(\n    plot.title = ggplot2::element_text(face = \"bold\", size = 17, margin = ggplot2::margin(b = 4)),\n    plot.subtitle = ggplot2::element_text(color = \"grey40\", size = 11, lineheight = 1.3,\n                                          margin = ggplot2::margin(b = 12)),\n    plot.caption = ggplot2::element_text(color = \"grey60\", size = 9, hjust = 0),\n    axis.text.y = ggplot2::element_text(size = 10),\n    axis.text.x = ggplot2::element_text(size = 9, color = \"grey50\"),\n    panel.grid.major.y = ggplot2::element_blank(),\n    panel.grid.minor = ggplot2::element_blank(),\n    panel.grid.major.x = ggplot2::element_line(color = \"grey92\"),\n    legend.position = \"right\",\n    legend.box = \"vertical\",\n    plot.margin = ggplot2::margin(12, 16, 12, 12)\n  )\n\np_hero\n```\n\n::: {.cell-output-display}\n![](2025-07-29-what-have-we-been-watching-on-netflix_files/figure-html/hero-plot-1.png){width=1056}\n:::\n:::\n\n\n\nA few things stand out immediately:\n\n**Squid Game is in a class of its own.** Season 2 alone has accumulated well over a billion cumulative hours across two reporting periods—an almost incomprehensible figure. The franchise's third season also debuted in the top tier within a single period.\n\n**Korean dramas dominate the top 10.** \"Bridgerton\" and a handful of English-language limited series represent the American entries, but Queen of Tears, King the Land, and When Life Gives You Tangerines all rank among the most-watched titles globally. These are not niche imports—they are mainstream Netflix hits.\n\n**The \"Limited Series\" format is winning.** Adolescence (4 episodes, British), Fool Me Once, Zero Day, and Monster are all limited series that outperformed most ongoing scripted shows. The format offers a complete, bingeable arc that maps perfectly onto how people actually consume streaming content.\n\n**Bigger dots = staying power.** Titles appearing in multiple periods (the larger dots) are generally in the upper half of the chart, suggesting that sustained viewership compounds—a show that was big in H2 2024 often continued accumulating hours in H1 2025.\n\n\n\n::: {.cell}\n\n:::\n\n\n\n# Final thoughts and takeaways\n\nNetflix's \"What We Watched\" data is a rare window into global media consumption at scale—and it tells a clear story.\n\n**TV shows are the engine of engagement.** Movies attract cultural conversation and awards attention, but it's serialized television that keeps people logged in. The gap in total hours—roughly 3–4× more for shows each period—is structural, not incidental.\n\n**The global content bet has paid off.** When Netflix invested heavily in Korean, Spanish, and other non-English productions, skeptics worried that local content wouldn't travel. The data says otherwise. Korean dramas now compete directly with Netflix's English-language originals for the top of the global rankings, and in many periods they win outright.\n\n**\"Limited Series\" is the format of the moment.** The binge-completion dynamic is maximized when a show has a defined ending. Adolescence—a 4-episode British drama—accumulated over half a billion hours despite its brevity. That's the power of a show where people tell their friends \"you have to finish it this weekend.\"\n\n**The long tail is very long.** The median movie earns around 400,000 hours in a reporting period. The top movie earns 313M hours. That's a 783× difference. Netflix's catalog strategy—keeping vast amounts of content available—means most titles are filler for the algorithm, present to serve niche moments while a handful of tentpoles do the heavy lifting.\n\nOne important caveat: this data only covers titles Netflix chooses to report. The engagement reports explicitly cover \"~99% of all viewing,\" but the threshold for inclusion (100,000+ hours in a period) still means many niche titles are invisible. The long tail is even longer than it appears here.\n",
    "supporting": [
      "2025-07-29-what-have-we-been-watching-on-netflix_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}