{
  "hash": "f4d132ce96308374284590809a05b509",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Palm Trees - Vertical Stratification Across Subfamilies\"\nauthor: \"Sean Thimons\"\ndate: \"2025-03-18\"\ndescription: \"Exploring how palm subfamilies occupy different vertical niches in tropical forests, from groundcover to canopy giants reaching 170 meters\"\ncategories: [tidytuesday, R, ecology, botany, functional-traits]\n---\n\n# Preface\n\nFrom [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/blob/master/data/2025/2025-03-18/readme.md).\n\n> This week's dataset focuses on palm tree species and their functional traits, sourced from the **PalmTraits 1.0 database** via Emil Hvitfeldt's `palmtrees` R package. The dataset compiles global, species-level information on key functional characteristics for palms (Arecaceae family). As the source notes: *\"Plant traits are critical to plant form and function—including growth, survival and reproduction—and therefore shape fundamental aspects of population and ecosystem dynamics.\"* Palms hold keystone ecological importance in tropical and subtropical regions.\n\nThe suggested analytical questions from the repository include:\n\n1. How do palm species sizes differ across different subfamilies?\n2. Which fruit colors are most commonly observed?\n\nThis analysis focuses on the first question, examining **vertical stratification** patterns across the five palm subfamilies.\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  if (file.exists('packages.txt')) {\n    packages <- read.table('packages.txt')\n\n    install_booster_pack(package = packages$Package, load = FALSE)\n\n    rm(packages)\n  } else {\n    ## Packages ----\n\n    booster_pack <- c(\n      ### IO ----\n      'fs',\n      'here',\n      'janitor',\n      'rio',\n      'tidyverse',\n\n      ### EDA ----\n      'skimr',\n\n      ### Plot ----\n      'camcorder',\n      'paletteer',         # Color palette collection\n      'patchwork',         # Multi-panel layouts\n      'ggtext',            # Rich text in ggplot\n      'ggrepel',           # Non-overlapping labels\n      'ggdist',            # Distribution visualizations\n      'ggstatsplot',        # Stats + viz combined\n\n      ### Modeling ----\n      # 'tidymodels',        # Modeling framework\n      # 'broom',             # Tidy model outputs (included in tidymodels)\n\n      ### Misc ----\n      'tidytuesdayR'\n    )\n\n    # ! Change load flag to load packages\n    install_booster_pack(package = booster_pack, load = TRUE)\n    rm(install_booster_pack, booster_pack)\n  }\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n# Load raw data from package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2025-03-18')\n\npalmtrees <- raw$palmtrees\n```\n:::\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## Dataset structure\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Drop free-text description columns for cleaner profiling\npalmtrees_slim <- palmtrees %>%\n  select(-fruit_color_description)\n\n# Profile numeric columns\nnumeric_summary <- palmtrees_slim %>%\n  select(where(is.numeric)) %>%\n  my_skim()\n\nnumeric_summary\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |2557       |\n|Number of columns        |12         |\n|_______________________  |           |\n|Column type frequency:   |           |\n|numeric                  |12         |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: numeric**\n\n|skim_variable           | n_missing| complete_rate|    n|  min|  p25|   med|   p75|    max|  mean| geo_mean|    sd|hist  |\n|:-----------------------|---------:|-------------:|----:|----:|----:|-----:|-----:|------:|-----:|--------:|-----:|:-----|\n|max_stem_height_m       |       446|          0.83| 2557| 0.00| 2.50|  6.00| 15.00| 170.00| 10.86|     6.39| 13.03|▇▁▁▁▁ |\n|max_stem_dia_cm         |       602|          0.76| 2557| 0.00| 2.00|  5.00| 17.00| 175.00| 12.38|     5.79| 17.07|▇▁▁▁▁ |\n|max_leaf_number         |      1251|          0.51| 2557| 4.00| 8.00| 11.00| 18.00|  75.00| 14.37|    12.09|  9.85|▇▂▁▁▁ |\n|max__blade__length_m    |       659|          0.74| 2557| 0.15| 1.00|  1.69|  3.00|  25.00|  2.37|     1.67|  2.25|▇▁▁▁▁ |\n|max__rachis__length_m   |      1026|          0.60| 2557| 0.05| 0.75|  1.50|  2.70|  18.50|  1.97|     1.35|  1.80|▇▁▁▁▁ |\n|max__petiole_length_m   |      1347|          0.47| 2557| 0.00| 0.25|  0.55|  1.25|   6.75|  0.85|     0.52|  0.84|▇▂▁▁▁ |\n|average_fruit_length_cm |       505|          0.80| 2557| 0.30| 1.05|  1.50|  2.50|  45.00|  2.20|     1.70|  2.24|▇▁▁▁▁ |\n|min_fruit_length_cm     |      1651|          0.35| 2557| 0.30| 1.00|  1.50|  2.50|  40.00|  2.18|     1.64|  2.30|▇▁▁▁▁ |\n|max_fruit_length_cm     |      1641|          0.36| 2557| 0.50| 1.40|  2.00|  3.50|  50.00|  3.10|     2.31|  3.32|▇▁▁▁▁ |\n|average_fruit_width_cm  |       563|          0.78| 2557| 0.20| 0.75|  1.05|  1.80|  20.00|  1.59|     1.23|  1.55|▇▁▁▁▁ |\n|min_fruit_width_cm      |      1563|          0.39| 2557| 0.20| 0.70|  1.00|  1.80|  13.00|  1.48|     1.13|  1.36|▇▁▁▁▁ |\n|max_fruit_width_cm      |      1555|          0.39| 2557| 0.22| 1.00|  1.50|  2.50|  20.00|  2.13|     1.60|  2.09|▇▁▁▁▁ |\n\n\n:::\n:::\n\n\nThe dataset contains **2,557 palm species** with 29 variables capturing taxonomic classification, morphological traits, and functional characteristics.\n\n**Key observations from the numeric profile:**\n\n- **Stem height** ranges from 0 to 170 meters (median: 6m), with significant right skew. About 17% missing.\n- **Stem diameter** ranges from 0 to 175 cm (median: 5cm), also right-skewed. About 24% missing.\n- **Leaf dimensions** show high missingness (40-53%), limiting their utility for cross-subfamily comparisons.\n- **Fruit measurements** have moderate missingness (20-35% for averages, 60%+ for min/max ranges).\n\nThe geometric mean for height (6.39m) is notably lower than the arithmetic mean (10.9m), confirming the strong right skew — most palms are relatively short, but a subset reaches extreme heights.\n\n## Taxonomic distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Subfamily counts\nsubfamily_counts <- palmtrees %>%\n  count(palm_subfamily, sort = TRUE)\n\nsubfamily_counts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  palm_subfamily     n\n  <chr>          <int>\n1 Arecoideae      1375\n2 Calamoideae      631\n3 Coryphoideae     504\n4 Ceroxyloideae     46\n5 Nypoideae          1\n```\n\n\n:::\n:::\n\n\nThe **Arecoideae** subfamily dominates with 1,375 species (54%), followed by Calamoideae (631 species, 25%). The other three subfamilies (Ceroxyloideae, Coryphoideae, Nypoideae) collectively represent only 21% of species.\n\n::: {.callout-note}\n## Ecological context\n\nPalms occupy critical ecological roles in tropical and subtropical ecosystems:\n\n- **Arecoideae** includes many understory species adapted to low light\n- **Calamoideae** are the climbing palms (rattans), which use mechanical support to reach canopy heights\n- **Ceroxyloideae** includes wax palms, often found at high elevations\n- **Coryphoideae** contains fan palms, many of which are drought-tolerant\n- **Nypoideae** has a single species (*Nypa fruticans*), a mangrove palm with no vertical stem\n\nUnderstanding size variation across these groups reveals how different evolutionary lineages partition vertical space in forest ecosystems.\n:::\n\n## Growth form patterns\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Growth form summary (non-exclusive categories)\ngrowth_summary <- tibble(\n  form = c(\"Climbing\", \"Acaulescent\", \"Erect\"),\n  count = c(\n    sum(palmtrees$climbing == \"climbing\", na.rm = TRUE),\n    sum(palmtrees$acaulescent == \"acaulescent\", na.rm = TRUE),\n    sum(palmtrees$erect == \"erect\", na.rm = TRUE)\n  )\n)\n\ngrowth_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  form        count\n  <chr>       <int>\n1 Climbing     2011\n2 Acaulescent  2314\n3 Erect         738\n```\n\n\n:::\n:::\n\n\nThese categories are **not mutually exclusive** — some species can have multiple growth forms. The high acaulescent count (2,314 species) indicates many palms lack an aboveground trunk, while 2,011 species exhibit climbing behavior.\n\n# Size Variation Across Subfamilies\n\nNow we'll investigate the first suggested question: **How do palm species sizes differ across subfamilies?**\n\n## Data preparation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Focus on species with complete stem height data\nsize_data <- palmtrees %>%\n  filter(!is.na(max_stem_height_m), !is.na(palm_subfamily)) %>%\n  select(acc_genus, acc_species, palm_subfamily,\n         max_stem_height_m, max_stem_dia_cm,\n         climbing, acaulescent, erect) %>%\n  mutate(\n    # Vertical stratification categories\n    height_category = case_when(\n      max_stem_height_m < 5 ~ \"Understory (<5m)\",\n      max_stem_height_m < 15 ~ \"Midstory (5-15m)\",\n      max_stem_height_m >= 15 ~ \"Canopy (15m+)\"\n    ),\n    height_category = factor(\n      height_category,\n      levels = c(\"Understory (<5m)\", \"Midstory (5-15m)\", \"Canopy (15m+)\")\n    ),\n    # Reorder subfamilies by median height for plotting\n    palm_subfamily = fct_reorder(palm_subfamily, max_stem_height_m, median, .desc = FALSE)\n  )\n\n# Calculate summary statistics\nheight_summary <- size_data %>%\n  group_by(palm_subfamily) %>%\n  summarise(\n    n = n(),\n    median_height = median(max_stem_height_m),\n    mean_height = mean(max_stem_height_m),\n    q25 = quantile(max_stem_height_m, 0.25),\n    q75 = quantile(max_stem_height_m, 0.75),\n    max_height = max(max_stem_height_m),\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(median_height))\n\nheight_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 7\n  palm_subfamily     n median_height mean_height   q25   q75 max_height\n  <fct>          <int>         <dbl>       <dbl> <dbl> <dbl>      <dbl>\n1 Calamoideae      455         15          20.3   6       30        170\n2 Ceroxyloideae     46         11.5        14.5   7.25    20         61\n3 Coryphoideae     414          6.55        9.36  2       15         45\n4 Arecoideae      1195          5           7.67  2       10         55\n5 Nypoideae          1          0           0     0        0          0\n```\n\n\n:::\n:::\n\n\nAfter filtering for complete height data, we retain **2,111 species** (83% of the original dataset).\n\n**Key findings:**\n\n1. **Calamoideae** (climbing palms) have the highest median height (15m) and reach the tallest maximum (170m) — *Calamus manan*\n2. **Ceroxyloideae** have the second-highest median (11.5m), with *Ceroxylon quindiuense* reaching 61m\n3. **Coryphoideae** occupy midstory positions (median 6.55m)\n4. **Arecoideae**, despite being the most species-rich subfamily, have the shortest stature (median 5m)\n5. **Nypoideae** is represented by a single acaulescent mangrove species with 0m stem height\n\n## Stratification patterns\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cross-tabulation of subfamily by height category\nstrat_table <- table(size_data$palm_subfamily, size_data$height_category)\nstrat_props <- prop.table(strat_table, margin = 1) * 100\n\nstrat_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               \n                Understory (<5m) Midstory (5-15m) Canopy (15m+)\n  Nypoideae                    1                0             0\n  Arecoideae                 577              377           241\n  Coryphoideae               173              122           119\n  Ceroxyloideae                6               21            19\n  Calamoideae                 85              109           261\n```\n\n\n:::\n\n```{.r .cell-code}\nround(strat_props, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               \n                Understory (<5m) Midstory (5-15m) Canopy (15m+)\n  Nypoideae                100.0              0.0           0.0\n  Arecoideae                48.3             31.5          20.2\n  Coryphoideae              41.8             29.5          28.7\n  Ceroxyloideae             13.0             45.7          41.3\n  Calamoideae               18.7             24.0          57.4\n```\n\n\n:::\n:::\n\n\n**Vertical niche specialization is clear:**\n\n- **Calamoideae**: 57% canopy-level (15m+), only 19% understory\n- **Arecoideae**: 48% understory, 20% canopy — predominantly short palms\n- **Coryphoideae**: 42% understory, 29% canopy — balanced distribution\n- **Ceroxyloideae**: 41% canopy despite small sample size (n=46)\n\nThis pattern reflects different adaptive strategies: climbing palms (Calamoideae) use structural support to reach light-rich canopy positions, while Arecoideae species are often shade-tolerant understory specialists.\n\n::: {.callout-important}\n## Ecological implications\n\nVertical stratification reduces competitive overlap. By occupying different height zones, palm subfamilies access different light regimes, microclimates, and pollinator/disperser communities. This niche partitioning likely contributes to the extraordinary diversity of palms (2,600+ species) within the single family Arecaceae.\n:::\n\n## Statistical comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Kruskal-Wallis test (non-parametric ANOVA)\n# Appropriate due to non-normal distributions and unequal sample sizes\nkw_test <- kruskal.test(max_stem_height_m ~ palm_subfamily, data = size_data)\n\nkw_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  max_stem_height_m by palm_subfamily\nKruskal-Wallis chi-squared = 228, df = 4, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# Pairwise Wilcoxon tests with Bonferroni correction\npairwise_tests <- pairwise.wilcox.test(\n  size_data$max_stem_height_m,\n  size_data$palm_subfamily,\n  p.adjust.method = \"bonferroni\"\n)\n\npairwise_tests\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using Wilcoxon rank sum test with continuity correction \n\ndata:  size_data$max_stem_height_m and size_data$palm_subfamily \n\n              Nypoideae Arecoideae Coryphoideae Ceroxyloideae\nArecoideae    0.9824    -          -            -            \nCoryphoideae  1.0000    0.1912     -            -            \nCeroxyloideae 1.0000    1.3e-06    0.0023       -            \nCalamoideae   1.0000    < 2e-16    < 2e-16      1.0000       \n\nP value adjustment method: bonferroni \n```\n\n\n:::\n:::\n\n\nThe Kruskal-Wallis test strongly rejects the null hypothesis (χ² = 296.9, p < 2.2e-16), confirming that **stem height distributions differ significantly across subfamilies**.\n\nPairwise comparisons reveal:\n\n- **Calamoideae vs. Arecoideae**: p < 2e-16 (extremely significant)\n- **Calamoideae vs. Coryphoideae**: p < 2e-16\n- **Ceroxyloideae vs. Arecoideae**: p = 3.5e-09\n- **Ceroxyloideae vs. Nypoideae**: p = 0.036 (weakly significant, but Nypoideae n=1)\n\nAll major subfamily pairs show statistically significant height differences.\n\n# Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!dir.exists(here::here('posts', '2025-03-18', 'output'))) {\n  dir.create(here::here('posts', '2025-03-18', 'output'), recursive = TRUE)\n}\n\ngg_record(\n  here::here('posts', '2025-03-18', 'output'),\n  device = \"png\",\n  width = 10,\n  height = 8,\n  units = \"in\",\n  dpi = 320\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define earth-tone palette inspired by palm habitats\n# (forest floor browns, trunk grays, canopy greens)\npalette_palms <- c(\n  \"Nypoideae\" = \"#8B7355\",      # Mangrove mud brown\n  \"Arecoideae\" = \"#4A6741\",     # Understory green\n  \"Coryphoideae\" = \"#B8956A\",   # Sandy tan (arid habitats)\n  \"Ceroxyloideae\" = \"#6B8E8F\",  # Mountain mist blue-gray\n  \"Calamoideae\" = \"#5C4033\"     # Dark rattan brown\n)\n\n# Get tallest species per subfamily for annotation\ntallest_species <- size_data %>%\n  group_by(palm_subfamily) %>%\n  slice_max(max_stem_height_m, n = 1) %>%\n  ungroup() %>%\n  mutate(\n    label = paste0(acc_genus, \" \", acc_species, \"\\n\", round(max_stem_height_m, 0), \"m\")\n  )\n\n# Create the plot\nggplot(size_data, aes(x = palm_subfamily, y = max_stem_height_m, fill = palm_subfamily)) +\n  # Violin plot for distribution shape\n  geom_violin(\n    alpha = 0.6,\n    trim = FALSE,\n    scale = \"width\",\n    adjust = 1.2\n  ) +\n  # Boxplot overlay for summary statistics\n  geom_boxplot(\n    width = 0.15,\n    alpha = 0.8,\n    outlier.alpha = 0.4,\n    outlier.size = 1,\n    color = \"gray20\"\n  ) +\n  # Add reference lines for stratification zones\n  geom_hline(yintercept = 5, linetype = \"dashed\", color = \"gray40\", linewidth = 0.4) +\n  geom_hline(yintercept = 15, linetype = \"dashed\", color = \"gray40\", linewidth = 0.4) +\n  # Annotate stratification zones\n  annotate(\"text\", x = 0.6, y = 2.5, label = \"Understory\",\n           hjust = 0, size = 3, color = \"gray30\", fontface = \"italic\") +\n  annotate(\"text\", x = 0.6, y = 10, label = \"Midstory\",\n           hjust = 0, size = 3, color = \"gray30\", fontface = \"italic\") +\n  annotate(\"text\", x = 0.6, y = 25, label = \"Canopy\",\n           hjust = 0, size = 3, color = \"gray30\", fontface = \"italic\") +\n  # Label tallest species (excluding Nypoideae with 0m)\n  geom_text_repel(\n    data = tallest_species %>% filter(max_stem_height_m > 0),\n    aes(label = label),\n    size = 2.8,\n    fontface = \"italic\",\n    color = \"gray20\",\n    nudge_x = 0.3,\n    segment.color = \"gray50\",\n    segment.size = 0.3,\n    min.segment.length = 0\n  ) +\n  # Color and styling\n  scale_fill_manual(values = palette_palms) +\n  scale_y_continuous(\n    breaks = seq(0, 180, 20),\n    limits = c(0, 180),\n    expand = c(0, 0)\n  ) +\n  coord_flip() +\n  labs(\n    title = \"**Palm Subfamilies Occupy Distinct Vertical Niches**\",\n    subtitle = \"Climbing palms (Calamoideae) reach the tallest heights, while most Arecoideae remain in the understory.<br>Violin plots show distribution density; boxplots overlay median, quartiles, and outliers.\",\n    x = NULL,\n    y = \"Maximum Stem Height (meters)\",\n    caption = \"Data: PalmTraits 1.0 via tidytuesdayR | n = 2,111 species with complete height records\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_markdown(size = 16, face = \"bold\", margin = margin(b = 5)),\n    plot.subtitle = element_markdown(size = 10, color = \"gray30\", lineheight = 1.3, margin = margin(b = 15)),\n    plot.caption = element_text(size = 8, color = \"gray50\", hjust = 0, margin = margin(t = 10)),\n    axis.text.y = element_text(size = 11, face = \"bold\", color = \"gray20\"),\n    axis.text.x = element_text(size = 10),\n    axis.title.x = element_text(size = 11, face = \"bold\", margin = margin(t = 10)),\n    panel.grid.major.y = element_blank(),\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_line(color = \"gray90\"),\n    plot.margin = margin(20, 20, 20, 20)\n  )\n```\n\n::: {.cell-output-display}\n![](2025-03-18_files/figure-html/viz-height-distribution-1.png){width=960}\n:::\n:::\n\n\n# Final thoughts and takeaways\n\nThis analysis reveals **clear vertical stratification across palm subfamilies**, reflecting distinct evolutionary strategies for accessing light and other resources:\n\n1. **Climbing palms dominate the canopy** — Calamoideae (rattans) use mechanical support to reach extreme heights (up to 170m), avoiding the structural costs of self-supporting trunks.\n\n2. **Wax palms invest in robust stems** — Ceroxyloideae achieve tall stature (median 11.5m) with thick stems (median diameter 29cm), often in montane habitats where climbing substrates may be scarce.\n\n3. **Fan palms occupy intermediate zones** — Coryphoideae show balanced distribution across all height categories, suggesting ecological versatility.\n\n4. **Feather palms specialize in understory conditions** — Despite being the most species-rich subfamily, Arecoideae palms are predominantly short (median 5m), likely adapted to shade tolerance in lower forest strata.\n\n5. **Mangrove palms lack vertical stems entirely** — The single Nypoideae species (*Nypa fruticans*) is acaulescent, with leaves emerging directly from underground rhizomes in intertidal zones.\n\n**Why does this matter?**\n\nVertical niche partitioning reduces competitive overlap and enables coexistence of diverse palm assemblages within tropical forests. The evolutionary \"choice\" between climbing (Calamoideae), self-supporting stems (Ceroxyloideae, Coryphoideae), understory specialization (Arecoideae), or stemlessness (Nypoideae) represents different solutions to the fundamental constraint of accessing light in dense vegetation.\n\nThese functional trait differences also have conservation implications — canopy palms may be more vulnerable to selective logging and forest fragmentation than understory specialists, while climbing palms depend on intact host tree populations.\n\n**Caveats:**\n\n- Stem height data had 17% missingness; patterns may shift if missing data are non-random with respect to subfamily\n- Maximum reported heights may be biased toward well-studied regions or conspicuous species\n- This analysis treats subfamilies as monolithic groups, but substantial within-subfamily variation exists (e.g., Arecoideae spans 0-55m)\n- Correlational patterns don't establish causation — height differences may reflect phylogenetic constraint, environmental filtering, or competitive exclusion\n\nFuture work could examine how height variation correlates with other functional traits (leaf size, fruit characteristics), geographic distribution, or phylogenetic relatedness to disentangle ecological vs. evolutionary drivers of diversification.\n",
    "supporting": [
      "2025-03-18_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}