{
  "hash": "563e5a20cc70804047ed8829c351c386",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: FIDE Chess Player Ratings\"\nauthor: \"Sean Thimons\"\ndate: \"2025-09-23\"\ndescription: \"Mapping the chess title hierarchy across 200,000+ rated players — and tracing India's stunning rise to the top of the game.\"\ncategories: [tidytuesday, R, chess, sports]\n---\n\n\n\n# Preface\n\nFrom the [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-09-23).\n\n> The dataset comes from the Fédération Internationale des Échecs (FIDE), the international governing body of chess. It includes the FIDE ratings list for August and September 2025, with information on over 200,000 rated players worldwide. Each record includes the player's rating, federation (country), sex, official titles (if any), K-factor, and birth year. FIDE ratings use the Elo system, where a player's number represents their expected performance relative to peers — higher is better.\n\nThis data covers the full breadth of the rated chess world, from club beginners to Magnus Carlsen at the summit.\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  booster_pack <- c(\n    ### IO ----\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n\n    ### EDA ----\n    'skimr',\n\n    ### Plot ----\n    'paletteer',           # Color palette collection\n    'ggridges',            # Ridge / density plots\n    'ggrepel',             # Non-overlapping labels\n\n    ### Misc ----\n    'tidytuesdayR'\n  )\n\n  install_booster_pack(package = booster_pack, load = TRUE)\n  rm(install_booster_pack, booster_pack)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load(\"2025-09-23\")\n\naug <- raw$fide_ratings_august\nsep <- raw$fide_ratings_september\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\nWe drop the `id` (an internal FIDE identifier) and free-text `name` column before skimming, since they carry no distributional signal. The `otitle` and `foa` columns are heavily sparse in this snapshot and also excluded from the EDA profile.\n\n## August 2025 Ratings\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naug %>%\n  select(-id, -name, -otitle, -foa) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |201015     |\n|Number of columns        |8          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |4          |\n|numeric                  |4          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|fed           |         0|          1.00|   3|   3|     0|      204|          0|\n|sex           |         0|          1.00|   1|   1|     0|        2|          0|\n|title         |    188366|          0.06|   2|   3|     0|        8|          0|\n|wtitle        |    198756|          0.01|   3|   3|     0|        4|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|      n|  min|  p25|  med|  p75|  max|    mean| geo_mean|     sd|hist  |\n|:-------------|---------:|-------------:|------:|----:|----:|----:|----:|----:|-------:|--------:|------:|:-----|\n|rating        |         0|             1| 201015| 1400| 1564| 1715| 1886| 2839| 1744.63|  1730.78| 225.00|▇▇▂▁▁ |\n|games         |         0|             1| 201015|    0|    0|    0|    0|   45|    1.70|     6.39|   3.79|▇▁▁▁▁ |\n|k             |         0|             1| 201015|   10|   20|   40|   40|   40|   30.73|    28.81|  10.27|▁▆▁▁▇ |\n|bday          |         0|             1| 201015| 1900| 1973| 1998| 2009| 2021| 1990.84|  1990.73|  20.78|▁▁▃▃▇ |\n\n\n:::\n:::\n\n\n\n## September 2025 Ratings\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsep %>%\n  select(-id, -name, -otitle, -foa) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |203191     |\n|Number of columns        |8          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |4          |\n|numeric                  |4          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|fed           |         0|          1.00|   3|   3|     0|      204|          0|\n|sex           |         0|          1.00|   1|   1|     0|        2|          0|\n|title         |    190523|          0.06|   2|   3|     0|        8|          0|\n|wtitle        |    200946|          0.01|   3|   3|     0|        4|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|      n|  min|  p25|  med|  p75|  max|    mean| geo_mean|     sd|hist  |\n|:-------------|---------:|-------------:|------:|----:|----:|----:|----:|----:|-------:|--------:|------:|:-----|\n|rating        |         0|             1| 203191| 1400| 1563| 1713| 1884| 2839| 1743.41|  1729.58| 224.76|▇▇▂▁▁ |\n|games         |         0|             1| 203191|    0|    0|    0|    0|   40|    1.62|     6.20|   3.62|▇▁▁▁▁ |\n|k             |         0|             1| 203191|   10|   20|   40|   40|   40|   30.80|    28.88|  10.26|▁▆▁▁▇ |\n|bday          |         0|             1| 203191| 1900| 1973| 1998| 2009| 2021| 1990.99|  1990.89|  20.79|▁▁▃▃▇ |\n\n\n:::\n:::\n\n\n\n## Quick orientation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sex distribution\ncat(\"=== Sex distribution (August) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Sex distribution (August) ===\n```\n\n\n:::\n\n```{.r .cell-code}\naug %>% count(sex, sort = TRUE) %>% print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  sex        n\n  <chr>  <int>\n1 M     180258\n2 F      20757\n```\n\n\n:::\n\n```{.r .cell-code}\n# Title distribution\ncat(\"\\n=== Title distribution (August) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Title distribution (August) ===\n```\n\n\n:::\n\n```{.r .cell-code}\naug %>% count(title, sort = TRUE) %>% print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 2\n  title      n\n  <chr>  <int>\n1 <NA>  188366\n2 FM      4762\n3 IM      2433\n4 CM      2073\n5 GM      1306\n6 WFM      825\n7 WCM      652\n8 WIM      413\n9 WGM      185\n```\n\n\n:::\n\n```{.r .cell-code}\n# Top 10 federations\ncat(\"\\n=== Top 10 federations by player count ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Top 10 federations by player count ===\n```\n\n\n:::\n\n```{.r .cell-code}\naug %>% count(fed, sort = TRUE) %>% head(10) %>% print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 2\n   fed       n\n   <chr> <int>\n 1 ESP   17858\n 2 IND   16445\n 3 FRA   15958\n 4 GER   13310\n 5 RUS    7228\n 6 ITA    6702\n 7 POL    5946\n 8 CZE    5557\n 9 USA    4495\n10 NED    4227\n```\n\n\n:::\n\n```{.r .cell-code}\n# Rating range\ncat(\"\\n=== Rating range ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Rating range ===\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aug$rating)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   1400    1564    1715    1745    1886    2839 \n```\n\n\n:::\n:::\n\n\n\nThe August 2025 list contains **201,015 rated players** from 167 federations. The vast majority — 188,366 (94%) — are untitled club players, forming the broad base beneath a narrow pyramid of titled masters. Males outnumber females roughly 8.7 to 1, though both sexes span the full rating range. Spain, India, and France lead in raw player count, but as we'll see, player count alone tells a very different story from elite strength.\n\n# The Chess Title Hierarchy\n\nFIDE's title system is one of the clearest examples of credentialing in competitive sport. Titles are earned through a combination of rating thresholds and performance norms in qualifying tournaments:\n\n::: {.callout-note}\n## Title thresholds (simplified)\n\n| Title | Meaning | Approx. rating threshold |\n|-------|---------|-------------------------|\n| **GM** | Grandmaster | 2500+ (plus 3 GM norms) |\n| **IM** | International Master | 2400+ (plus 3 IM norms) |\n| **FM** | FIDE Master | 2300+ |\n| **CM** | Candidate Master | 2200+ |\n| **WGM** | Woman Grandmaster | 2300+ (women's norm circuit) |\n| **WIM** | Woman International Master | 2200+ |\n| **WFM** | Woman FIDE Master | 2100+ |\n| **WCM** | Woman Candidate Master | 2000+ |\n\nOnce earned, titles are permanent — which is why some players' current ratings sit below the threshold they originally crossed.\n:::\n\n## Rating distributions by title tier\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define the canonical ordering by descending median rating\ntitle_order <- c(\"GM\", \"IM\", \"FM\", \"WGM\", \"WIM\", \"CM\", \"WFM\", \"WCM\", \"Untitled\")\n\nplot_data_tiers <- aug %>%\n  mutate(title_clean = ifelse(is.na(title), \"Untitled\", title)) %>%\n  filter(title_clean %in% title_order) %>%\n  mutate(title_factor = factor(title_clean, levels = rev(title_order)))\n\ncat(sprintf(\"plot_data_tiers: %d rows, %d cols\\n\", nrow(plot_data_tiers), ncol(plot_data_tiers)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nplot_data_tiers: 201015 rows, 14 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Plot data has 0 rows — check filter values\" = nrow(plot_data_tiers) > 0)\n\n# Sanity check: medians per tier\ntier_medians <- plot_data_tiers %>%\n  group_by(title_clean) %>%\n  summarise(n = n(), median_rating = median(rating), .groups = \"drop\") %>%\n  arrange(desc(median_rating))\n\nprint(tier_medians)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 3\n  title_clean      n median_rating\n  <chr>        <int>         <dbl>\n1 GM            1306          2484\n2 IM            2433          2342\n3 FM            4762          2224\n4 WGM            185          2208\n5 WIM            413          2090\n6 CM            2073          2089\n7 WFM            825          2004\n8 WCM            652          1833\n9 Untitled    188366          1696\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check for all-identical medians (would indicate bad grouping)\nif (length(unique(tier_medians$median_rating)) == 1) {\n  warning(\"All tier medians identical — check grouping logic\")\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# NatParksPalettes::Acadia — 9 colors, navy-to-orange gradient\n# Mapping: Untitled (cool navy) → GM (warm orange-red)\nacadia_pal <- paletteer::paletteer_d(\"NatParksPalettes::Acadia\")\n\n# Map palette in ascending order of title prestige\n# title_order = c(\"GM\", \"IM\", ..., \"Untitled\") = high to low\n# rev(title_order) = c(\"Untitled\", ..., \"GM\") = factor levels (bottom to top of ridge)\n# acadia_pal[1] = navy → \"Untitled\", acadia_pal[9] = orange-red → \"GM\"\ntier_colors <- setNames(as.character(acadia_pal), rev(title_order))\n\np_ridges <- ggplot2::ggplot(\n  plot_data_tiers,\n  ggplot2::aes(x = rating, y = title_factor, fill = title_factor)\n) +\n  ggridges::geom_density_ridges(\n    alpha = 0.88,\n    scale = 1.35,\n    color = \"white\",\n    linewidth = 0.35,\n    quantile_lines = TRUE,\n    quantiles = 2,\n    quantile_fun = median\n  ) +\n  ggplot2::scale_fill_manual(values = tier_colors) +\n  ggplot2::scale_x_continuous(\n    limits = c(1350, 2900),\n    breaks = seq(1400, 2800, 200),\n    expand = ggplot2::expansion(mult = c(0, 0.02))\n  ) +\n  ggplot2::annotate(\n    \"text\", x = 2484, y = 9.8,\n    label = \"Carlsen\\n2839\", size = 2.8, color = \"#D8511D\",\n    fontface = \"bold\", hjust = 0.5, lineheight = 0.9\n  ) +\n  ggplot2::annotate(\n    \"segment\", x = 2839, xend = 2839, y = 9, yend = 9.6,\n    color = \"#D8511D\", linewidth = 0.5, linetype = \"dashed\"\n  ) +\n  ggplot2::labs(\n    title = \"The Chess Title Hierarchy\",\n    subtitle = \"FIDE Elo rating distributions by title tier, August 2025 (201,015 players)\\nWhite line = median | Titles are permanent once earned — ratings can drift below the threshold\",\n    x = \"FIDE Elo Rating\",\n    y = NULL,\n    caption = \"Data: FIDE / TidyTuesday 2025-09-23 | Palette: NatParksPalettes::Acadia\"\n  ) +\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    legend.position = \"none\",\n    plot.title = ggplot2::element_text(face = \"bold\", size = 18, margin = ggplot2::margin(b = 4)),\n    plot.subtitle = ggplot2::element_text(color = \"grey40\", size = 10.5, lineheight = 1.3),\n    plot.caption = ggplot2::element_text(color = \"grey60\", size = 8, margin = ggplot2::margin(t = 10)),\n    axis.text.y = ggplot2::element_text(face = \"bold\", size = 11),\n    axis.text.x = ggplot2::element_text(size = 10),\n    panel.grid.minor = ggplot2::element_blank(),\n    panel.grid.major.y = ggplot2::element_blank(),\n    panel.grid.major.x = ggplot2::element_line(color = \"grey90\"),\n    plot.margin = ggplot2::margin(15, 20, 10, 15)\n  )\n\np_ridges\n```\n\n::: {.cell-output-display}\n![](2025-09-23-fide-chess-player-ratings_files/figure-html/hero-ridge-plot-1.png){width=1056}\n:::\n:::\n\n\n\nA few things jump out immediately:\n\n- **The GM distribution is remarkably tight** — the interquartile range runs from roughly 2409 to 2550, a span of only 141 points. Grandmasters are densely clustered near the top of the rating scale.\n- **Untitled players have the widest spread** by far. This tier encompasses every club player from absolute beginner (1400, the FIDE floor) to talented unregistered-norm players near 2480. The long right tail reveals many strong players who simply never pursued formal title norms.\n- **Women's titles interleave with open titles.** The WGM median (2208) sits between FM (2224) and WIM (2090), while WIM overlaps almost exactly with CM. This reflects FIDE's design — women's titles carry lower rating requirements, allowing the system to recognize female achievement at equivalent competitive standards within women's events.\n- **The gap between IM and GM is the largest between adjacent tiers** — roughly 140 Elo points separating medians, compared to ~120 between FM and IM. Earning the final GM title is, by reputation, the hardest step in chess.\n\n::: {.callout-tip}\n## What's the K-factor?\n\nThe `k` column (values: 10, 20, 40) is FIDE's sensitivity dial for rating changes. Players with K=40 are new to the rating list or under 18, and their ratings adjust quickly after each game. K=20 is the standard for established players. K=10 applies to elite players rated 2400+ who have played 30+ rated games — their ratings change very slowly, as they've \"earned\" stability.\n:::\n\n# India's Chess Revolution\n\nThe title hierarchy tells us *what* the system looks like globally. But hidden within the federation data is one of the most remarkable stories in modern chess: **India's ascent to the pinnacle of the game**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Federation GM analysis — top federations by GM count\nfed_gm_stats <- aug %>%\n  filter(title == \"GM\") %>%\n  group_by(fed) %>%\n  summarise(\n    n_gm = n(),\n    avg_gm_rating = mean(rating, na.rm = TRUE),\n    avg_gm_bday = mean(bday, na.rm = TRUE),   # proxy for GM corps age\n    .groups = \"drop\"\n  ) %>%\n  filter(n_gm >= 10) %>%\n  arrange(desc(n_gm))\n\ncat(sprintf(\"fed_gm_stats: %d rows, %d cols\\n\", nrow(fed_gm_stats), ncol(fed_gm_stats)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfed_gm_stats: 42 rows, 4 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Federation GM data has 0 rows\" = nrow(fed_gm_stats) > 0)\n\n# Sanity check: ratings should vary by federation\nif (length(unique(round(fed_gm_stats$avg_gm_rating))) == 1) {\n  warning(\"All avg GM ratings identical — check grouping logic\")\n}\n\n# Exclude FID (FIDE stateless players — international citizens w/o federation)\nfed_gm_stats <- fed_gm_stats %>% filter(fed != \"FID\")\n\n# Add India flag for highlighting\nfed_gm_stats <- fed_gm_stats %>%\n  mutate(is_india = fed == \"IND\")\n\nprint(fed_gm_stats %>% arrange(desc(n_gm)) %>% head(15))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 5\n   fed    n_gm avg_gm_rating avg_gm_bday is_india\n   <chr> <int>         <dbl>       <dbl> <lgl>   \n 1 GER      77         2477.       1977. FALSE   \n 2 USA      75         2507.       1984. FALSE   \n 3 IND      67         2522.       1996. TRUE    \n 4 RUS      64         2473.       1982. FALSE   \n 5 UKR      52         2507.       1983. FALSE   \n 6 FRA      50         2484.       1980. FALSE   \n 7 SRB      47         2405.       1976. FALSE   \n 8 ESP      46         2478.       1980. FALSE   \n 9 ISR      43         2467.       1979. FALSE   \n10 POL      42         2498.       1987. FALSE   \n11 HUN      40         2492.       1985. FALSE   \n12 CHN      39         2558.       1992. FALSE   \n13 NED      33         2513.       1982. FALSE   \n14 ENG      30         2474.       1974. FALSE   \n15 CZE      26         2437.       1977. FALSE   \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Top 20 federations by GM count\nplot_data_feds <- fed_gm_stats %>%\n  arrange(desc(n_gm)) %>%\n  head(20)\n\ncat(sprintf(\"plot_data_feds: %d rows\\n\", nrow(plot_data_feds)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nplot_data_feds: 20 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Federation scatter data has 0 rows\" = nrow(plot_data_feds) > 0)\n\np_feds <- ggplot2::ggplot(\n  plot_data_feds,\n  ggplot2::aes(\n    x = avg_gm_bday,\n    y = avg_gm_rating,\n    size = n_gm,\n    color = is_india\n  )\n) +\n  ggplot2::geom_point(alpha = 0.82) +\n  ggrepel::geom_text_repel(\n    ggplot2::aes(label = fed),\n    size = 3.2,\n    fontface = \"bold\",\n    min.segment.length = 0.2,\n    box.padding = 0.5,\n    color = \"grey20\",\n    show.legend = FALSE\n  ) +\n  ggplot2::scale_color_manual(\n    values = c(\"TRUE\" = \"#D8511D\", \"FALSE\" = \"#8087AA\"),\n    guide = \"none\"\n  ) +\n  ggplot2::scale_size_continuous(\n    name = \"Number of GMs\",\n    range = c(3, 14),\n    breaks = c(10, 25, 50, 75)\n  ) +\n  ggplot2::scale_x_continuous(\n    name = \"Average GM birth year\",\n    breaks = seq(1975, 2000, 5),\n    labels = function(x) paste0(x)\n  ) +\n  ggplot2::scale_y_continuous(\n    name = \"Average GM Elo rating\",\n    breaks = seq(2420, 2560, 20)\n  ) +\n  ggplot2::annotate(\n    \"text\",\n    x = 1995.8, y = 2530,\n    label = \"India: youngest & strongest\\nGM corps among major nations\",\n    color = \"#D8511D\", size = 3.3, fontface = \"bold\",\n    hjust = 0, lineheight = 1.1\n  ) +\n  ggplot2::labs(\n    title = \"India's GMs are younger — and stronger\",\n    subtitle = \"Average Elo rating vs. average birth year of Grandmasters, by federation (top 20 by GM count)\\nBubble size = number of GMs | India highlighted in orange\",\n    caption = \"Data: FIDE / TidyTuesday 2025-09-23 | Palette: NatParksPalettes::Acadia (accent colors)\"\n  ) +\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    plot.title = ggplot2::element_text(face = \"bold\", size = 16, margin = ggplot2::margin(b = 4)),\n    plot.subtitle = ggplot2::element_text(color = \"grey40\", size = 10, lineheight = 1.3),\n    plot.caption = ggplot2::element_text(color = \"grey60\", size = 8, margin = ggplot2::margin(t = 10)),\n    panel.grid.minor = ggplot2::element_blank(),\n    legend.position = \"bottom\",\n    plot.margin = ggplot2::margin(15, 20, 10, 15)\n  )\n\np_feds\n```\n\n::: {.cell-output-display}\n![](2025-09-23-fide-chess-player-ratings_files/figure-html/india-scatter-plot-1.png){width=960}\n:::\n:::\n\n\n\nThe scatter tells a clear story. India sits in the **upper-right quadrant** — its GMs average a birth year around 1996 (the youngest cohort among any major chess nation) while also carrying the highest average rating among the top-ten GM-producing countries. Germany and the USA have more GMs, but their cohorts are older (averaging birth years of 1977 and 1984 respectively). England's GMs, for context, average a birth year of 1974.\n\n::: {.callout-important}\n## The Indian Chess Boom in context\n\nIn 2024, **D. Gukesh** (born 2006) became the youngest World Chess Champion in history, defeating Ding Liren in Singapore. At the time of this dataset, **Praggnanandhaa R** (born 2005) and **Erigaisi Arjun** (born 2003) ranked 4th and 5th in the world respectively — alongside Gukesh at 6th. Three of the world's top six players are Indian teenagers or early-twenty-somethings.\n\nIndia's current GM corps (avg. birth year 1996) is strikingly young because the pipeline is recent: FIDE-rated chess only reached mass participation in India in the 2000s, catalyzed by Viswanathan Anand's world title and government investment in chess coaching infrastructure. The country is now producing grandmasters faster than any other nation.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Verify: top 10 players in September ratings\ncat(\"=== Top 10 players, September 2025 ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Top 10 players, September 2025 ===\n```\n\n\n:::\n\n```{.r .cell-code}\nsep %>%\n  arrange(desc(rating)) %>%\n  select(name, fed, title, rating, games) %>%\n  head(10) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 5\n   name              fed   title rating games\n   <chr>             <chr> <chr>  <dbl> <dbl>\n 1 Carlsen, Magnus   NOR   GM      2839     0\n 2 Nakamura, Hikaru  USA   GM      2807     0\n 3 Caruana, Fabiano  USA   GM      2789     9\n 4 Praggnanandhaa R  IND   GM      2785     9\n 5 Erigaisi Arjun    IND   GM      2771     9\n 6 Gukesh D          IND   GM      2767     9\n 7 So, Wesley        USA   GM      2756     9\n 8 Firouzja, Alireza FRA   GM      2754     9\n 9 Wei, Yi           CHN   GM      2753     0\n10 Keymer, Vincent   GER   GM      2751     9\n```\n\n\n:::\n\n```{.r .cell-code}\n# India's share of top 100\nindia_top100 <- sep %>%\n  arrange(desc(rating)) %>%\n  mutate(rank = row_number()) %>%\n  filter(rank <= 100) %>%\n  count(fed, name = \"n_top100\") %>%\n  arrange(desc(n_top100)) %>%\n  head(10)\n\ncat(\"\\n=== Federations represented in top 100 (September) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Federations represented in top 100 (September) ===\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(india_top100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 2\n   fed   n_top100\n   <chr>    <int>\n 1 USA         12\n 2 IND         11\n 3 CHN          6\n 4 RUS          6\n 5 UZB          5\n 6 AZE          4\n 7 ENG          4\n 8 FID          4\n 9 GER          4\n10 ESP          3\n```\n\n\n:::\n:::\n\n\n\n# Palette log update\n\n\n\n::: {.cell}\n\n:::\n\n\n\n# Final thoughts and takeaways\n\nThe FIDE rating database, at first glance, is just a giant spreadsheet of numbers. But structurally it's a map of a global competitive meritocracy — one of the few human domains where rank is both objectively computed and universally legible.\n\nA few takeaways from this analysis:\n\n**The title system is a clear hierarchy.** The ridge plot shows that FIDE titles genuinely carve the player population into meaningful skill tiers, not arbitrary labels. The gaps between adjacent title medians are real and significant — crossing each threshold represents a qualitatively different level of play. The GM boundary, in particular, sits at a rating level that fewer than 1-in-150 rated players ever reach.\n\n**India is the dominant story in elite chess right now.** The combination of the youngest and highest-rated GM corps among major nations is not a coincidence. It reflects a pipeline effect: when Anand's world titles inspired a generation in the late 1990s and 2000s, coaching infrastructure followed. That cohort is now in its prime — and the next wave is already here.\n\n**Most of the chess world is untitled — and that's fine.** The 188,000+ untitled players in this dataset aren't failures of the system. They represent the actual community that makes competitive chess viable: people who play in local clubs, online arenas, and weekend tournaments for the love of the game. Their spread across the 1400–2400 range shows that recreational chess and elite chess coexist on the same rating axis, connected by a shared numeric language.\n\nOne caveat: this dataset only covers the FIDE-registered universe. An enormous number of casual chess.com and Lichess players never enter the FIDE system at all — the 1400 floor here is not the true floor of global chess participation.\n",
    "supporting": [
      "2025-09-23-fide-chess-player-ratings_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}