{
  "hash": "7746e691da5207b79fc4d29f9c4dbca4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Papal Encyclicals and Technological Revolutions\"\nauthor: \"Sean Thimons\"\ndate: \"2026-06-23\"\ndescription: \"Comparing two papal encyclicals written 135 years apart — one confronting the Industrial Revolution, the other confronting artificial intelligence — through paragraph structure, scripture references, and the longer history of papal communication.\"\ncategories:\n  - tidytuesday\n  - R\n  - text-analysis\n  - religion\n  - history\n---\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](2026-06-23-papal-encyclicals-industrial-revolution-vs-ai-revolution_files/figure-html/pseudo-hero-palette-1.png){width=100%}\n:::\n:::\n\n\n# Preface\n\nFrom [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2026/2026-06-23).\n\n> This week we're exploring papal encyclicals — the most authoritative form of papal teaching in the Catholic Church. The primary dataset contains the full paragraph-level text of two encyclicals that bookend 135 years of technological revolution: Pope Leo XIII's *Rerum Novarum* (*Of New Things*, 1891), which addressed the Industrial Revolution's impact on workers, and Pope Leo XIV's *Magnifica Humanitas* (*Magnificent Humanity*, 2026), which addresses artificial intelligence's impact on human dignity.\n\nThe obvious trap with this dataset is to turn two documents into a grand theory of history. That would be too much weight for the data. Instead, I am treating this as a comparative reading exercise with just enough quantification to make the contrast visible: how long the arguments are, how scripture is distributed, and how these two documents sit inside the longer historical record of papal encyclicals.\n\n## Loading the project booster pack\n\nThis post uses the project-local `tidytuesday-post` booster pack in `boosters.toml`. The pack owns the package setup, TidyTuesday loading guards, palette helpers, and lightweight plotting theme used below.\n\n# Load raw data from package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tt_load_clean(\n  \"2026-06-23\",\n  required = c(\"encyclicals\", \"papal_encyclicals\", \"scripture_references\")\n)\n\nencyclicals <- raw$encyclicals\npapal_encyclicals <- raw$papal_encyclicals\nscripture_references <- raw$scripture_references\n```\n:::\n\n\n# Exploratory Data Analysis\n\nThe primary data has three useful layers: paragraph-level text from two encyclicals, scripture citations extracted from those texts, and a historical metadata table for 213 encyclicals from 1878 through 2026.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventory <- tt_inventory(raw[c(\"encyclicals\", \"papal_encyclicals\", \"scripture_references\")])\n\ninventory\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  table                 rows columns fields                                     \n  <chr>                <int>   <int> <chr>                                      \n1 encyclicals            309       7 encyclical, pope, year, paragraph, text, w…\n2 papal_encyclicals      213       9 title, pope, year, papal_number, birth_nam…\n3 scripture_references    50       7 encyclical, pope, year, paragraph, referen…\n```\n\n\n:::\n:::\n\n\nThe `my_skim()` function is a modified version of `skimr::skim()` that returns missingness, non-missing counts, count, minimum, quartiles, median, maximum, mean, geometric mean, standard deviation, and a compact ASCII histogram. Neat!\n\n## Primary encyclical text\n\n\n::: {.cell}\n\n```{.r .cell-code}\nencyclicals %>%\n  my_skim(.)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |309        |\n|Number of columns        |7          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |3          |\n|numeric                  |4          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min|  max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|----:|-----:|--------:|----------:|\n|encyclical    |         0|             1|  13|   19|     0|        2|          0|\n|pope          |         0|             1|   7|    8|     0|        2|          0|\n|text          |         0|             1| 183| 3091|     0|      309|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable  | n_missing| complete_rate|   n|  min|  p25|  med|  p75|  max|    mean| geo_mean|    sd|hist  |\n|:--------------|---------:|-------------:|---:|----:|----:|----:|----:|----:|-------:|--------:|-----:|:-----|\n|year           |         0|             1| 309| 1891| 2026| 2026| 2026| 2026| 1998.04|  1997.27| 54.80|▂▁▁▁▇ |\n|paragraph      |         0|             1| 309|    1|   39|   91|  168|  245|  104.26|    69.74| 73.48|▇▅▃▃▃ |\n|word_count     |         0|             1| 309|   33|  120|  154|  190|  570|  165.77|   153.36| 70.37|▆▇▂▁▁ |\n|sentence_count |         0|             1| 309|    1|    4|    5|    7|   18|    5.71|     5.20|  2.58|▇▇▃▁▁ |\n\n\n:::\n:::\n\n\n## Historical encyclical metadata\n\n\n::: {.cell}\n\n```{.r .cell-code}\npapal_encyclicals %>%\n  my_skim(.)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |213        |\n|Number of columns        |9          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |4          |\n|Date                     |2          |\n|numeric                  |3          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|title         |         0|             1|   7|  32|     0|      213|          0|\n|pope          |         0|             1|   6|  12|     0|       11|          0|\n|birth_name    |         0|             1|  13|  30|     0|       11|          0|\n|birth_country |         0|             1|   5|  13|     0|        5|          0|\n\n\n**Variable type: Date**\n\n|skim_variable     | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-----------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|pontificate_start |         0|             1|1878-02-20 |2025-05-08 |1914-09-03 |       11|\n|pontificate_end   |         1|             1|1903-07-20 |2025-04-21 |1922-01-22 |       10|\n\n\n**Variable type: numeric**\n\n|skim_variable    | n_missing| complete_rate|   n|  min|  p25|  med|  p75|  max|    mean| geo_mean|    sd|hist  |\n|:----------------|---------:|-------------:|---:|----:|----:|----:|----:|----:|-------:|--------:|-----:|:-----|\n|year             |         0|             1| 213| 1878| 1894| 1919| 1951| 2026| 1925.30|  1924.96| 36.23|▇▃▅▁▁ |\n|papal_number     |         0|             1| 213|  256|  256|  258|  260|  267|  258.52|   258.51|  2.79|▇▅▁▁▁ |\n|pontificate_year |         0|             1| 213|    1|    5|   10|   16|   26|   11.09|     8.60|  6.71|▇▇▆▅▂ |\n\n\n:::\n:::\n\n\n## Scripture references\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscripture_references %>%\n  my_skim(.)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |50         |\n|Number of columns        |7          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |5          |\n|numeric                  |2          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|encyclical    |         0|             1|  13|  19|     0|        2|          0|\n|pope          |         0|             1|   7|   8|     0|        2|          0|\n|reference     |         0|             1|   6|  13|     0|       46|          0|\n|book          |         0|             1|   4|  13|     0|       20|          0|\n|testament     |         0|             1|  13|  13|     0|        2|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|  n|  min|  p25|    med|    p75|  max|    mean| geo_mean|    sd|hist  |\n|:-------------|---------:|-------------:|--:|----:|----:|------:|------:|----:|-------:|--------:|-----:|:-----|\n|year          |         0|             1| 50| 1891| 1891| 1891.0| 2026.0| 2026| 1950.40|  1949.25| 67.69|▇▁▁▁▆ |\n|paragraph     |         0|             1| 50|    3|   21|   28.5|   73.5|  236|   58.62|    34.86| 66.40|▇▃▁▁▂ |\n\n\n:::\n:::\n\n\nThe comparison is intentionally narrow: *Rerum Novarum* and *Magnifica Humanitas* are not random samples of papal writing. They are two curated documents selected because they rhyme historically: industrial labor in 1891 and artificial intelligence in 2026.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntext_summary <- encyclicals %>%\n  group_by(encyclical, pope, year) %>%\n  summarise(\n    paragraphs = n(),\n    total_words = sum(word_count, na.rm = TRUE),\n    median_words_per_paragraph = median(word_count, na.rm = TRUE),\n    total_sentences = sum(sentence_count, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  arrange(year)\n\ntext_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  encyclical          pope    year paragraphs total_words median_words_per_par…¹\n  <chr>               <chr>  <dbl>      <int>       <dbl>                  <dbl>\n1 Rerum Novarum       Leo X…  1891         64       13961                    188\n2 Magnifica Humanitas Leo X…  2026        245       37261                    148\n# ℹ abbreviated name: ¹​median_words_per_paragraph\n# ℹ 1 more variable: total_sentences <dbl>\n```\n\n\n:::\n:::\n\n\nOne immediate structural difference: the AI-era text is much longer in total, but *Rerum Novarum* has the larger median paragraph. That is a useful distinction. Length here is not just volume; it is also pacing.\n\n# Two Leos, two technological crises\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleo_colors <- c(\"Rerum Novarum\" = plot_colors[2], \"Magnifica Humanitas\" = plot_colors[5])\n\nparagraph_plot_data <- encyclicals %>%\n  mutate(\n    encyclical = factor(encyclical, levels = c(\"Rerum Novarum\", \"Magnifica Humanitas\")),\n    paragraph_band = case_when(\n      word_count < 100 ~ \"<100 words\",\n      word_count < 200 ~ \"100–199 words\",\n      TRUE ~ \"200+ words\"\n    ),\n    paragraph_band = factor(paragraph_band, levels = c(\"<100 words\", \"100–199 words\", \"200+ words\"))\n  )\n\nstopifnot(\"paragraph_plot_data has rows\" = nrow(paragraph_plot_data) > 0)\n\np <- ggplot(paragraph_plot_data, aes(x = encyclical, y = word_count, fill = encyclical)) +\n  geom_violin(alpha = 0.35, color = NA, trim = FALSE) +\n  geom_boxplot(width = 0.18, outlier.shape = NA, alpha = 0.85, color = \"grey20\") +\n  geom_jitter(aes(color = encyclical), width = 0.08, alpha = 0.38, size = 1.4, show.legend = FALSE) +\n  scale_fill_manual(values = leo_colors, guide = \"none\") +\n  scale_color_manual(values = leo_colors, guide = \"none\") +\n  scale_y_continuous(labels = scales::comma) +\n  labs(\n    title = \"The AI-era encyclical is longer; the industrial-era paragraphs are denser\",\n    subtitle = \"Paragraph-level word counts from Rerum Novarum (1891) and Magnifica Humanitas (2026)\",\n    x = NULL,\n    y = \"Words per paragraph\",\n    caption = \"Source: TidyTuesday 2026-06-23, Vatican.va\"\n  ) +\n  tt_theme(base_size = 13, legend_position = \"none\") +\n  theme(axis.text.x = element_text(face = \"bold\"))\n\np\n```\n\n::: {.cell-output-display}\n![](2026-06-23-papal-encyclicals-industrial-revolution-vs-ai-revolution_files/figure-html/paragraph-length-comparison-1.png){width=960}\n:::\n:::\n\n\nThe paragraph distribution puts a check on the easy narrative. *Magnifica Humanitas* is the larger document by total word count, but it is not simply “more verbose paragraph by paragraph.” It moves through more paragraphs. *Rerum Novarum* spends more words in a typical paragraph, which gives it a denser argumentative cadence.\n\n## Scripture as an argumentative scaffold\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscripture_summary <- scripture_references %>%\n  count(encyclical, pope, testament, name = \"references\") %>%\n  group_by(encyclical) %>%\n  mutate(share = references / sum(references)) %>%\n  ungroup() %>%\n  arrange(encyclical, desc(references))\n\nscripture_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  encyclical          pope     testament     references share\n  <chr>               <chr>    <chr>              <int> <dbl>\n1 Magnifica Humanitas Leo XIV  New Testament         13 0.591\n2 Magnifica Humanitas Leo XIV  Old Testament          9 0.409\n3 Rerum Novarum       Leo XIII New Testament         19 0.679\n4 Rerum Novarum       Leo XIII Old Testament          9 0.321\n```\n\n\n:::\n:::\n\n\nBoth documents draw more from the New Testament than the Old Testament. The contrast is not “one biblical, one not.” It is subtler: the 2026 text distributes its citations across the Tower of Babel, Nehemiah, Matthew, John, Acts, and Pauline material, while *Rerum Novarum* leans heavily into Genesis and Matthew.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbook_plot_data <- scripture_references %>%\n  count(encyclical, testament, book, name = \"references\") %>%\n  group_by(encyclical) %>%\n  slice_max(references, n = 7, with_ties = FALSE) %>%\n  ungroup() %>%\n  mutate(\n    book = forcats::fct_reorder(book, references),\n    encyclical = factor(encyclical, levels = c(\"Rerum Novarum\", \"Magnifica Humanitas\"))\n  )\n\nstopifnot(\"book_plot_data has rows\" = nrow(book_plot_data) > 0)\n\np <- ggplot(book_plot_data, aes(x = references, y = book, fill = testament)) +\n  geom_col(width = 0.72) +\n  facet_wrap(~ encyclical, scales = \"free_y\") +\n  scale_fill_manual(values = c(\"Old Testament\" = plot_colors[3], \"New Testament\" = plot_colors[6])) +\n  scale_x_continuous(breaks = scales::breaks_pretty()) +\n  labs(\n    title = \"Matthew and Genesis anchor both documents, but the citation mix spreads differently\",\n    subtitle = \"Top cited biblical books within each encyclical\",\n    x = \"Citation count\",\n    y = NULL,\n    fill = NULL,\n    caption = \"Source: TidyTuesday 2026-06-23, scripture_references.csv\"\n  ) +\n  tt_theme(base_size = 13) +\n  theme(strip.text = element_text(face = \"bold\"))\n\np\n```\n\n::: {.cell-output-display}\n![](2026-06-23-papal-encyclicals-industrial-revolution-vs-ai-revolution_files/figure-html/scripture-books-1.png){width=960}\n:::\n:::\n\n\nThat is the more interesting reading: the shared books mark continuity, but the spread of references suggests different problems being worked through. In this dataset, the industrial labor question and the artificial intelligence question both get mapped onto older theological grammar. The point is not that the grammar stayed unchanged. The point is that the new problem is being translated into a recognizable institutional language.\n\n## The longer history is uneven\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_popes <- papal_encyclicals %>%\n  count(pope, birth_country, name = \"encyclicals\") %>%\n  slice_max(encyclicals, n = 10, with_ties = FALSE) %>%\n  mutate(pope = forcats::fct_reorder(pope, encyclicals))\n\nstopifnot(\"top_popes has rows\" = nrow(top_popes) > 0)\n\np <- ggplot(top_popes, aes(x = encyclicals, y = pope, fill = birth_country)) +\n  geom_col(width = 0.72) +\n  scale_fill_manual(values = rep_len(plot_colors, length(unique(top_popes$birth_country)))) +\n  labs(\n    title = \"The historical encyclical record is dominated by a few prolific popes\",\n    subtitle = \"Top ten popes by number of encyclicals in the 1878–2026 metadata table\",\n    x = \"Number of encyclicals\",\n    y = NULL,\n    fill = \"Birth country\",\n    caption = \"Source: TidyTuesday 2026-06-23, papal_encyclicals.csv\"\n  ) +\n  tt_theme(base_size = 13)\n\np\n```\n\n::: {.cell-output-display}\n![](2026-06-23-papal-encyclicals-industrial-revolution-vs-ai-revolution_files/figure-html/historical-output-1.png){width=960}\n:::\n:::\n\n\nLeo XIII is not just one endpoint of the two-document comparison. He dominates the metadata table, with 86 of the 213 encyclicals. That matters because it keeps the comparison from becoming too symmetric. *Rerum Novarum* comes from a papacy that used encyclicals frequently. *Magnifica Humanitas* appears in a communications environment where encyclicals are only one instrument among many.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncentury_summary <- papal_encyclicals %>%\n  mutate(\n    century = case_when(\n      year < 1901 ~ \"19th century\",\n      year < 2001 ~ \"20th century\",\n      TRUE ~ \"21st century\"\n    ),\n    century = factor(century, levels = c(\"19th century\", \"20th century\", \"21st century\"))\n  ) %>%\n  count(century, name = \"encyclicals\")\n\ncentury_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  century      encyclicals\n  <fct>              <int>\n1 19th century          76\n2 20th century         128\n3 21st century           9\n```\n\n\n:::\n:::\n\n\nThe metadata table is therefore a reminder about institutional form. The question is not only what each document says about labor or artificial intelligence. It is also what kind of medium the encyclical is at each historical moment: a frequent teaching instrument in the late nineteenth and twentieth centuries, and a rarer intervention in the twenty-first.\n\n# Final thoughts and takeaways\n\nThe strongest result here is structural, not predictive. *Magnifica Humanitas* is a larger document, but *Rerum Novarum* carries longer median paragraphs. Both texts cite scripture, especially the New Testament, but they arrange that shared inheritance differently. And the historical metadata makes Leo XIII unusually prominent: the industrial-era endpoint is not an arbitrary pope in the archive, but the single most prolific encyclical writer in the table.\n\nFor a dataset about technological revolutions, that is a useful lesson. The “new” problem does not arrive in a new language. It is pulled through old institutions, old genres, and old citational habits. The machinery changes. The argument has to pass through the chapel door anyway.\n",
    "supporting": [
      "2026-06-23-papal-encyclicals-industrial-revolution-vs-ai-revolution_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}