{
  "hash": "a8713542b9e82b26567a9ac376b9f507",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Films Based on Video Games\"\nauthor: \"Sean Thimons\"\ndate: \"2026-06-09\"\ndescription: \"Tracking three decades of video game adaptations from the Uwe Boll trough to the Super Mario Bros. Movie surge.\"\ncategories:\n  - tidytuesday\n  - R\n  - film\n  - video games\n  - reviews\n---\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](2026-06-09-films-based-on-video-games_files/figure-html/pseudo-hero-palette-1.png){width=100%}\n:::\n:::\n\n\n# Preface\n\nFrom [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2026/2026-06-09).\n\n> The dataset this week comes from the Wikipedia article [List of films based on video games](https://en.wikipedia.org/wiki/List_of_films_based_on_video_games). It covers theatrical releases, direct-to-video productions, television films, short films, and documentaries adapted from video games, spanning from the early 1990s to upcoming releases. Each row is a film, with box office figures, critic scores, budgets, and release dates where available.\n\nSuggested angles from the curators:\n\n- Which video game franchise has generated the most film adaptations, and which has earned the most at the box office?\n- Which video game publishers have the most film adaptations, and how have they performed at the box office?\n- Do audiences and critics agree? Compare CinemaScore grades against Rotten Tomatoes scores.\n\nThanks to [Georgios Karamanis](https://github.com/gkaramanis) for curating this week's dataset.\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\"pak\", repos = \"https://cloud.r-project.org\")\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  core_packages <- c(\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n    'skimr',\n    'paletteer',\n    'tidytuesdayR'\n  )\n\n  optional_packages <- c('ggrepel', 'ggtext', 'scales')\n\n  install_booster_pack(package = unique(c(core_packages, optional_packages)), load = TRUE)\n  rm(install_booster_pack, core_packages, optional_packages)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n# Load raw data from package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2026-06-09')\n\ngame_films <- raw$game_films\n```\n:::\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse, the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram.\n\n## Shape of the catalogue\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(sprintf(\"rows: %d   cols: %d\\n\", nrow(game_films), ncol(game_films)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrows: 439   cols: 20\n```\n\n\n:::\n\n```{.r .cell-code}\ngame_films %>%\n  count(category, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  category                         n\n  <chr>                        <int>\n1 Theatrical releases            246\n2 Documentaries on video games    67\n3 Direct-to-video                 54\n4 Short films                     46\n5 Television films                26\n```\n\n\n:::\n\n```{.r .cell-code}\ngame_films %>%\n  filter(category == \"Theatrical releases\") %>%\n  count(subcategory, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  subcategory            n\n  <chr>              <int>\n1 English              136\n2 Japanese              92\n3 Mandarin/Cantonese    18\n```\n\n\n:::\n:::\n\n\nTheatrical releases dominate (246 of 439 rows). Documentaries and direct-to-video each take a sizeable slice, but they live in a different world from the wide-release theatrical adaptations that drive cultural attention.\n\n## Numeric profile\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngame_films %>%\n  select(release_date, worldwide_box_office, rotten_tomatoes, metacritic, budget_low, budget_high) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |439        |\n|Number of columns        |6          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|Date                     |1          |\n|numeric                  |5          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|release_date  |        89|           0.8|1986-07-20 |2028-12-22 |2013-11-09 |      296|\n\n\n**Variable type: numeric**\n\n|skim_variable        | n_missing| complete_rate|   n|     min|        p25|      med|         p75|      max|         mean|    geo_mean|           sd|hist  |\n|:--------------------|---------:|-------------:|---:|-------:|----------:|--------:|-----------:|--------:|------------:|-----------:|------------:|:-----|\n|worldwide_box_office |       343|          0.22| 439|   61511| 18270676.0| 84366422| 340357739.2| 5.02e+09| 674816191.00| 73086527.87| 1.346590e+09|▇▁▁▁▁ |\n|rotten_tomatoes      |       366|          0.17| 439|       0|       16.0|       30|        51.0| 1.00e+02|        35.18|       25.88| 2.452000e+01|▇▅▅▃▁ |\n|metacritic           |       376|          0.14| 439|       9|       28.5|       36|        46.5| 8.80e+01|        37.37|       34.52| 1.403000e+01|▃▇▆▁▁ |\n|budget_low           |       372|          0.15| 439| 1800000| 23500000.0| 45000000|  92500000.0| 3.00e+08|  63632835.82| 39286793.05| 6.023746e+07|▇▃▁▁▁ |\n|budget_high          |       372|          0.15| 439| 1800000| 23500000.0| 45000000|  97500000.0| 3.00e+08|  65901492.54| 41079088.11| 6.215781e+07|▇▃▂▁▁ |\n\n\n:::\n:::\n\n\nThree honest realities:\n\n- **Sparse scores.** Most films have neither a Rotten Tomatoes score nor a CinemaScore. The graded universe is small enough that you can almost name every film in it.\n- **Currency mix.** Box office reports come in `$` (82 films) and `¥` (14 films). I'll keep the analysis to USD so the y-axis is interpretable.\n- **Heavy right tail.** Box office is hugely skewed — the median USD gross is ~$84M but the max is $5B (when both Mario films are added together). One blockbuster can drag every aggregate.\n\n# The video game movie curse — and the moment it broke\n\nThe cultural story of video game movies has a familiar shape: a wave of cheap, critically panned adaptations through the 1990s and 2000s (the [Uwe Boll](https://en.wikipedia.org/wiki/Uwe_Boll) era), then a slow re-engineering through the 2010s, and finally a commercial breakout starting with *Sonic the Hedgehog* (2020) and culminating in *The Super Mario Bros. Movie* in 2023.\n\nLet me check whether the data actually supports that arc.\n\n## Era table\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheatrical <- game_films %>%\n  filter(category == \"Theatrical releases\") %>%\n  mutate(\n    year = lubridate::year(release_date),\n    era = case_when(\n      year < 2000 ~ \"1990s\",\n      year < 2010 ~ \"2000s\",\n      year < 2020 ~ \"2010s\",\n      year >= 2020 ~ \"2020s\",\n      TRUE        ~ NA_character_\n    ),\n    era = factor(era, levels = c(\"1990s\", \"2000s\", \"2010s\", \"2020s\"))\n  )\n\nstopifnot(\n  \"theatrical has 0 rows\" = nrow(theatrical) > 0,\n  \"era never matched\" = sum(!is.na(theatrical$era)) > 0\n)\n\nera_summary <- theatrical %>%\n  filter(!is.na(era)) %>%\n  group_by(era) %>%\n  summarise(\n    n_films       = n(),\n    n_with_rt     = sum(!is.na(rotten_tomatoes)),\n    median_rt     = median(rotten_tomatoes, na.rm = TRUE),\n    mean_rt       = round(mean(rotten_tomatoes, na.rm = TRUE), 1),\n    median_bo_usd = median(worldwide_box_office[worldwide_box_office_currency == \"$\"], na.rm = TRUE),\n    .groups       = \"drop\"\n  )\n\nera_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 6\n  era   n_films n_with_rt median_rt mean_rt median_bo_usd\n  <fct>   <int>     <int>     <dbl>   <dbl>         <dbl>\n1 1990s      17         9      17      25.4      51376861\n2 2000s      43        23      18      20.7      28023563\n3 2010s      88        22      37.5    41.7      75706238\n4 2020s      38        19      51      49.7      50102224\n```\n\n\n:::\n:::\n\n\nThe pattern is real. The median critic score climbs from **17%** (1990s) to **51%** (2020s), and median worldwide gross — for the USD-denominated subset — roughly triples between the 2000s and the 2020s. The 2000s were genuinely the trough of both quality *and* commercial pull.\n\n## Publisher league table\n\n\n::: {.cell}\n\n```{.r .cell-code}\npublishers_usd <- game_films %>%\n  filter(\n    worldwide_box_office_currency == \"$\",\n    !is.na(original_game_publisher),\n    !is.na(worldwide_box_office)\n  ) %>%\n  group_by(original_game_publisher) %>%\n  summarise(\n    n_films  = n(),\n    total_bo = sum(worldwide_box_office),\n    median_rt = median(rotten_tomatoes, na.rm = TRUE),\n    .groups  = \"drop\"\n  ) %>%\n  arrange(desc(total_bo))\n\nstopifnot(\"publishers_usd empty\" = nrow(publishers_usd) > 0)\n\npublishers_usd %>%\n  slice_head(n = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   original_game_publisher        n_films   total_bo median_rt\n   <chr>                            <int>      <dbl>     <dbl>\n 1 Nintendo                             3 2231390409      43  \n 2 Capcom                              15 1448524033      36  \n 3 Sega                                 5 1240895284      66.5\n 4 Nintendo | The Pokémon Company      10 1013338759      20  \n 5 Mojang Studios                       1  957802316      47  \n 6 Ubisoft                              4  578605421      37  \n 7 ScottGames                           2  533512069      24.5\n 8 Eidos                                3  532485046      20  \n 9 Warner Bros. Games                   2  511629246      53  \n10 Rovio Entertainment                  2  500125976      57.5\n```\n\n\n:::\n:::\n\n\nNintendo's three theatrical releases — the original 1993 *Super Mario Bros.*, the 2023 *Super Mario Bros. Movie*, and the upcoming *Super Mario Galaxy Movie* — together gross more than Capcom's fifteen films combined. The Pokémon Company joint adds another billion. The catalogue is profoundly top-heavy.\n\n# Visualizing the curse breaking\n\nThe plot below puts every USD-denominated theatrical release on a release-date × Rotten-Tomatoes plane. Point area is worldwide box office, colour is era, and a loess trend tracks the long arc of critical reception.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_df <- theatrical %>%\n  filter(\n    worldwide_box_office_currency == \"$\",\n    !is.na(release_date),\n    !is.na(rotten_tomatoes),\n    !is.na(worldwide_box_office),\n    !is.na(era)\n  )\n\ncat(sprintf(\"plot_df: %d rows\\n\", nrow(plot_df)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nplot_df: 71 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"plot_df has 0 rows — check filter values\" = nrow(plot_df) > 0)\n\nlabel_titles <- c(\n  \"Super Mario Bros.\",\n  \"Mortal Kombat\",\n  \"Lara Croft: Tomb Raider\",\n  \"Warcraft\",\n  \"Pokémon Detective Pikachu\",\n  \"Sonic the Hedgehog\",\n  \"The Super Mario Bros. Movie\",\n  \"Sonic the Hedgehog 3\",\n  \"A Minecraft Movie\"\n)\n\nlabel_df <- plot_df %>%\n  filter(title %in% label_titles)\n\ncat(sprintf(\"label_df: %d / %d hits\\n\", nrow(label_df), length(label_titles)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlabel_df: 10 / 9 hits\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nera_colors <- paletteer::paletteer_d(\"NineteenEightyR::cobra\", n = 5)[c(1, 2, 3, 5)]\nnames(era_colors) <- c(\"1990s\", \"2000s\", \"2010s\", \"2020s\")\n\np <- ggplot(plot_df, aes(x = release_date, y = rotten_tomatoes)) +\n  geom_hline(yintercept = 60, linetype = \"dashed\", color = \"grey50\", linewidth = 0.4) +\n  annotate(\n    \"text\",\n    x = as.Date(\"1993-06-01\"),\n    y = 62.5,\n    label = \"Fresh threshold (60%)\",\n    hjust = 0, vjust = 0,\n    size = 3.1, color = \"grey35\", fontface = \"italic\"\n  ) +\n  geom_smooth(\n    method = \"loess\",\n    se = TRUE,\n    color = \"grey20\",\n    fill = \"grey80\",\n    alpha = 0.35,\n    linewidth = 0.7\n  ) +\n  geom_point(\n    aes(size = worldwide_box_office, fill = era),\n    shape = 21, color = \"white\", stroke = 0.4, alpha = 0.9\n  ) +\n  ggrepel::geom_text_repel(\n    data = label_df,\n    aes(label = title),\n    size = 3.1,\n    family = \"sans\",\n    color = \"grey15\",\n    box.padding = 0.55,\n    point.padding = 0.35,\n    min.segment.length = 0,\n    segment.color = \"grey50\",\n    segment.size = 0.3,\n    max.overlaps = Inf,\n    seed = 42\n  ) +\n  scale_fill_manual(values = era_colors, name = \"Release era\") +\n  scale_size_area(\n    name = \"Worldwide gross\",\n    max_size = 16,\n    breaks = c(5e7, 2e8, 5e8, 1e9),\n    labels = scales::label_dollar(scale = 1e-6, suffix = \"M\", accuracy = 1)\n  ) +\n  scale_x_date(date_breaks = \"5 years\", date_labels = \"%Y\") +\n  scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, 20), labels = function(x) paste0(x, \"%\")) +\n  guides(\n    fill = guide_legend(override.aes = list(size = 5)),\n    size = guide_legend(override.aes = list(fill = \"grey60\"))\n  ) +\n  labs(\n    title    = \"The video game movie curse is finally breaking\",\n    subtitle = \"Theatrical adaptations by release date, Rotten Tomatoes score, and worldwide box office (USD)\",\n    x = NULL,\n    y = \"Rotten Tomatoes critic score\",\n    caption = \"Source: Wikipedia via TidyTuesday 2026-06-09 · Theatrical releases priced in USD only\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title          = element_text(face = \"bold\", size = 16, margin = margin(b = 4)),\n    plot.subtitle       = element_text(color = \"grey30\", margin = margin(b = 14)),\n    plot.caption        = element_text(color = \"grey45\", size = 8.5, hjust = 0, margin = margin(t = 12)),\n    panel.grid.minor    = element_blank(),\n    panel.grid.major    = element_line(color = \"grey92\"),\n    legend.position     = \"bottom\",\n    legend.box          = \"horizontal\",\n    legend.title        = element_text(face = \"bold\", size = 9),\n    legend.text         = element_text(size = 9),\n    plot.background     = element_rect(fill = \"white\", color = NA),\n    panel.background    = element_rect(fill = \"white\", color = NA)\n  )\n\np\n```\n\n::: {.cell-output-display}\n![](2026-06-09-films-based-on-video-games_files/figure-html/hero-plot-1.png){width=1056}\n:::\n:::\n\n\nThe loess line spends nearly two decades parked in the low 20s — the genre genuinely earned its reputation as critic-proof shovelware. Around 2018 it lifts off, and *Sonic the Hedgehog 3* (86%) is the first adaptation in the dataset to clear 80% Fresh while also clearing $400M worldwide. *The Super Mario Bros. Movie* did not need critical love to make $1.36B; it broke the commercial half of the curse all on its own.\n\n## A second look: era distributions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nviolin_df <- theatrical %>%\n  filter(!is.na(rotten_tomatoes), !is.na(era))\n\nstopifnot(\"violin_df has 0 rows\" = nrow(violin_df) > 0)\n\np2 <- ggplot(violin_df, aes(x = era, y = rotten_tomatoes, fill = era)) +\n  geom_violin(alpha = 0.55, color = NA, trim = FALSE) +\n  geom_boxplot(width = 0.18, outlier.shape = NA, color = \"grey15\", fill = \"white\", alpha = 0.9) +\n  geom_jitter(width = 0.08, alpha = 0.55, size = 1.4, color = \"grey20\") +\n  geom_hline(yintercept = 60, linetype = \"dashed\", color = \"grey50\", linewidth = 0.4) +\n  scale_fill_manual(values = era_colors, guide = \"none\") +\n  scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, 20), labels = function(x) paste0(x, \"%\")) +\n  labs(\n    title    = \"Critics warmed up one decade at a time\",\n    subtitle = \"Distribution of Rotten Tomatoes scores for theatrical video game adaptations\",\n    x = NULL,\n    y = \"Rotten Tomatoes critic score\",\n    caption = \"Source: Wikipedia via TidyTuesday 2026-06-09\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title       = element_text(face = \"bold\", size = 15, margin = margin(b = 4)),\n    plot.subtitle    = element_text(color = \"grey30\", margin = margin(b = 14)),\n    plot.caption     = element_text(color = \"grey45\", size = 8.5, hjust = 0, margin = margin(t = 12)),\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank(),\n    panel.grid.major.y = element_line(color = \"grey92\"),\n    plot.background  = element_rect(fill = \"white\", color = NA),\n    panel.background = element_rect(fill = \"white\", color = NA)\n  )\n\np2\n```\n\n::: {.cell-output-display}\n![](2026-06-09-films-based-on-video-games_files/figure-html/era-violin-1.png){width=864}\n:::\n:::\n\n\nThe 2000s violin is the worst of the bunch — a fat cluster of films below 30% with no upper tail to speak of. The 2020s violin is wider and taller: the failures still happen (*Borderlands* and *Five Nights at Freddy's* both undershot), but the ceiling has lifted enough that a *Sonic 3* or *Detective Pikachu* outcome is now plausible rather than freakish.\n\n# Final thoughts and takeaways\n\nThree readings of the data feel defensible:\n\n1. **The curse is real, but it was a quality curse before it was a commercial one.** Box office crept up through the 2010s while critics still hated almost everything. The critical turn — median RT going from 18% in the 2000s to 51% in the 2020s — is the bigger structural change.\n2. **Nintendo plays a different game.** Three theatrical films, $2.2B in worldwide gross, with the *Super Mario Bros. Movie* alone clearing a billion. Nothing else in the catalogue scales like that, and it skews every per-publisher aggregate.\n3. **Sample sizes are tiny.** Only ~70 theatrical releases have both a USD box office figure and a Rotten Tomatoes score. The era trend is suggestive, not a clinical demonstration, and any one studio's slate (Sony's PlayStation Productions, Legendary's *Detective Pikachu* / *Pokémon* line, Paramount's *Sonic* franchise) can move the medians more than a genuine industry-wide shift would.\n\nThe next decade should tell us whether *Sonic 3* and the upcoming *Super Mario Galaxy Movie* (already $832M with a 43% RT) are the new normal, or whether 2023–2026 was the surge before the cycle resets.\n\n\n::: {.cell}\n\n:::\n\n",
    "supporting": [
      "2026-06-09-films-based-on-video-games_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}