{
  "hash": "2711f82c52abfd2a0a84fc7d0aa3c753",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Ecotourism\"\nauthor: \"Sean Thimons\"\ndate: \"2026-07-28\"\ndescription: \"Gouldian finch records line up with a dry-season observation pattern, but the table records sightings, not bird abundance.\"\ncategories:\n  - tidytuesday\n  - R\n  - ecology\n  - australia\n  - weather\nexecute:\n  freeze: auto\n---\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](2026-07-28-ecotourism_files/figure-html/pseudo-hero-palette-1.svg){width=100%}\n:::\n:::\n\n\n# Preface\n\nFrom the [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2026/2026-07-28).\n\nThis week's files join ecological occurrences, Australian weather stations, and regional tourism estimates. I stayed with the Gouldian finch records because the date and nearest weather-station ID make a useful first question possible: what kind of weather sits behind the records that can be matched? The answer is mostly dry-season weather. It is not a claim about what finches prefer. A sighting is the result of a bird, a person or instrument, and a reporting system all meeting in one row.\n\n## Loading the data\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nif (!requireNamespace(\"pak\", quietly = TRUE)) {\n  install.packages(\"pak\", repos = \"https://cloud.r-project.org\")\n}\n\ninstall_booster_pack <- function(package, load = TRUE) {\n  for (pkg in package) {\n    if (!requireNamespace(pkg, quietly = TRUE)) {\n      pak::pkg_install(pkg)\n    }\n    if (load) {\n      library(pkg, character.only = TRUE)\n    }\n  }\n}\n\ninstall_booster_pack(c(\"tidyverse\", \"tidytuesdayR\", \"paletteer\", \"scales\"))\nrm(install_booster_pack)\n\nraw <- tidytuesdayR::tt_load(\"2026-07-28\")\noccurrences <- raw$occurrences\nweather <- raw$weather\n```\n:::\n\n\n## What is in the table\n\nThe occurrence file has 40,051 records. Orchids account for 35,052 of them, while the 3,922 Gouldian finch rows come from 57 nearest-station IDs. The weather file covers station days, not every observation. Joining by station and date leaves 2,117 finch records with usable temperature and rain fields.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Measure                                            |  Value|\n|:--------------------------------------------------|------:|\n|All occurrence records                             | 40,051|\n|Gouldian finch records                             |  3,922|\n|Finch records matched to usable daily weather      |  2,117|\n|Distinct station-date pairs in the matched records |  1,100|\n\n\n:::\n:::\n\n\n## The dry-season observation pattern\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth_order <- month.name\n\nmonthly_records <- finch_weather %>%\n  mutate(\n    month_name = factor(month.name[month], levels = month_order),\n    weather = if_else(rainy == 1, \"Rainy day\", \"Dry day\")\n  ) %>%\n  count(month_name, weather) %>%\n  complete(month_name, weather, fill = list(n = 0))\n\nfinch_weather %>%\n  summarise(\n    matched_records = n(),\n    dry_records = sum(rainy == 0),\n    dry_share = mean(rainy == 0),\n    median_temperature = median(temp)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  matched_records dry_records dry_share median_temperature\n            <int>       <int>     <dbl>              <dbl>\n1            2117        1997     0.943               27.2\n```\n\n\n:::\n\n```{.r .cell-code}\nmonthly_records %>%\n  ggplot(aes(month_name, n, fill = weather)) +\n  geom_col(width = 0.76) +\n  scale_fill_manual(values = c(\"Dry day\" = \"#80521C\", \"Rainy day\" = \"#EBC174\")) +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.08))) +\n  labs(x = NULL, y = \"Occurrence records\", fill = NULL) +\n  theme_minimal(base_size = 12) +\n  theme(\n    panel.grid.major.x = element_blank(),\n    panel.grid.minor = element_blank(),\n    axis.text.x = element_text(angle = 40, hjust = 1),\n    legend.position = \"top\"\n  )\n```\n\n::: {.cell-output-display}\n![Gouldian finch occurrence records with a matching weather row, by month and whether the nearest station recorded more than 5 mm of rain. These are record counts, not an estimate of finch abundance or a weather preference.](2026-07-28-ecotourism_files/figure-html/fig-finch-monthly-weather-1.png){#fig-finch-monthly-weather width=864}\n:::\n:::\n\n\nSeptember has the largest count in the matched subset, with 405 records. July and August follow with 315 and 364. Across the full matched set, 94.3% of records fall on days the nearest station marks dry, and the median temperature is 27.2 C. That sounds tidy until you compare it with the raw calendar: the records also cluster around a handful of stations and years, especially 2022. Reporting effort has fingerprints.\n\n## A comparison that keeps the denominator visible\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinch_station_days <- weather %>%\n  filter(\n    ws_id %in% unique(occurrences$ws_id[occurrences$organism_name == \"Gouldian finch\"]),\n    !is.na(temp),\n    !is.na(rainy)\n  ) %>%\n  transmute(temp, source = \"All usable station days\")\n\nrecord_days <- finch_weather %>%\n  transmute(temp, source = \"Matched finch records\")\n\nbind_rows(finch_station_days, record_days) %>%\n  ggplot(aes(temp, after_stat(density), fill = source, color = source)) +\n  geom_density(alpha = 0.26, linewidth = 0.9) +\n  geom_vline(xintercept = median(finch_weather$temp), color = \"#3B2319\", linewidth = 0.55, linetype = \"22\") +\n  annotate(\n    \"text\",\n    x = median(finch_weather$temp) + 0.35,\n    y = 0.072,\n    label = paste0(\"record median: \", round(median(finch_weather$temp), 1), \" C\"),\n    hjust = 0,\n    color = \"#3B2319\",\n    size = 3.4\n  ) +\n  scale_fill_manual(values = c(\"All usable station days\" = \"#D29C44\", \"Matched finch records\" = \"#80521C\")) +\n  scale_color_manual(values = c(\"All usable station days\" = \"#D29C44\", \"Matched finch records\" = \"#80521C\")) +\n  labs(x = \"Daily average temperature (C)\", y = \"Density\", fill = NULL, color = NULL) +\n  theme_minimal(base_size = 12) +\n  theme(\n    panel.grid.minor = element_blank(),\n    legend.position = \"top\"\n  )\n```\n\n::: {.cell-output-display}\n![Temperature distribution for matched Gouldian finch records compared with all usable weather days at the 57 nearest stations represented in the finch file. The contrast gives context for the records, but it still cannot separate weather from observer effort, location, or season.](2026-07-28-ecotourism_files/figure-html/fig-temperature-context-1.png){#fig-temperature-context width=864}\n:::\n:::\n\n\nThe weather-station comparison is useful because it prevents a familiar mistake: treating the records alone as the available conditions. Matched records have a mean temperature of 26.7 C, below the 27.9 C mean across usable days at those stations. Their rainy-day share is 5.7%, compared with 12.9% for the station-day file. Those differences describe the records in this dataset. They do not show that rain suppresses finch activity, or that 26.7 C is a biological optimum.\n\n## Takeaway\n\nThe ecotourism package makes a tempting promise: line up sightings, weather, and visitors, then tell a clean story about nature and travel. The joins are real, but the denominators are thin. This first pass finds a dry-season pattern among matched Gouldian finch records and shows why that pattern needs restraint. The next credible step would add observation effort or a survey design, then ask whether the same pattern survives.\n",
    "supporting": [
      "2026-07-28-ecotourism_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}