{
  "hash": "9bd00637d287e824c8b9dc90c0011082",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Pixar's Critical Consensus\"\nauthor: \"Sean Thimons\"\ndate: \"2025-03-11\"\ndescription: \"Exploring how different rating systems evaluate Pixar's 27-film catalog, from Toy Story to Elemental\"\ncategories: [tidytuesday, R, film-analysis, data-visualization]\n---\n\n\n\n# Preface\n\nFrom [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/master/data/2025/2025-03-11).\n\n> This week's data explores Pixar films and public reception. The datasets come from the {pixarfilms} R package by Eric Leung, which provides information about Pixar's film catalog, including production details and critical/audience scores.\n>\n> **Suggested Questions:**\n> 1. Why are certain values missing across datasets?\n> 2. Which films receive the highest scores in each rating system, and do different rating sources diverge significantly?\n> 3. How do box office figures correlate with critical ratings and audience scores?\n> 4. Are there patterns between domestic versus worldwide box office performance and critical reception?\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  if (file.exists('packages.txt')) {\n    packages <- read.table('packages.txt')\n\n    install_booster_pack(package = packages$Package, load = FALSE)\n\n    rm(packages)\n  } else {\n    ## Packages ----\n\n    booster_pack <- c(\n      ### IO ----\n      'fs',\n      'here',\n      'janitor',\n      'rio',\n      'tidyverse',\n\n      ### EDA ----\n      'skimr',\n\n      ### Plot ----\n      'paletteer',         # Color palette collection\n      'patchwork',         # Multi-panel layouts\n      'ggtext',            # Rich text in ggplot\n      'ggrepel',           # Non-overlapping labels\n\n      ### Misc ----\n      'tidytuesdayR'\n    )\n\n    # ! Change load flag to load packages\n    install_booster_pack(package = booster_pack, load = TRUE)\n    rm(install_booster_pack, booster_pack)\n  }\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2025-03-11')\n\npixar_films <- raw$pixar_films\npublic_response <- raw$public_response\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## Pixar Films Dataset\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_skim(pixar_films)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |            |\n|:------------------------|:-----------|\n|Name                     |pixar_films |\n|Number of rows           |27          |\n|Number of columns        |5           |\n|_______________________  |            |\n|Column type frequency:   |            |\n|character                |2           |\n|Date                     |1           |\n|numeric                  |2           |\n|________________________ |            |\n|Group variables          |None        |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|film          |         1|          0.96|   2|  19|     0|       26|          0|\n|film_rating   |         0|          1.00|   1|   9|     0|        4|          0|\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|release_date  |         0|             1|1995-11-22 |2023-06-16 |2013-06-21 |       27|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|  n| min|  p25| med|   p75| max|   mean| geo_mean|    sd|hist  |\n|:-------------|---------:|-------------:|--:|---:|----:|---:|-----:|---:|------:|--------:|-----:|:-----|\n|number        |         0|          1.00| 27|   1|  7.5|  14|  20.5|  27|  14.00|    10.92|  7.94|▇▇▇▇▇ |\n|run_time      |         2|          0.93| 27|  81| 95.0| 100| 106.0| 155| 104.84|   103.73| 16.78|▅▇▂▁▁ |\n\n\n:::\n:::\n\n\n\nThe `pixar_films` dataset contains 27 films spanning from 1995 (Toy Story) to 2023 (Elemental). Runtime is remarkably consistent — the median runtime is 100 minutes with most films falling between 95-106 minutes. Only two films are missing runtime data. Most films are rated G or PG, with a handful rated \"Not Rated\" or showing \"N/A\" (likely for recent releases where ratings weren't finalized at data collection time).\n\nOne film title is missing entirely, which we'll need to investigate when joining with the public response data.\n\n## Public Response Dataset\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npublic_response %>%\n  select(-film, -cinema_score) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |24         |\n|Number of columns        |3          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|numeric                  |3          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: numeric**\n\n|skim_variable   | n_missing| complete_rate|  n| min| p25| med|  p75| max|  mean| geo_mean|    sd|hist  |\n|:---------------|---------:|-------------:|--:|---:|---:|---:|----:|---:|-----:|--------:|-----:|:-----|\n|rotten_tomatoes |         1|          0.96| 24|  40|  84|  96| 97.5| 100| 89.17|    87.71| 14.15|▁▁▂▂▇ |\n|metacritic      |         1|          0.96| 24|  57|  71|  81| 90.0|  96| 79.96|    78.99| 12.32|▃▃▆▆▇ |\n|critics_choice  |         3|          0.88| 24|  66|  81|  89| 93.0| 100| 87.14|    86.62|  9.40|▂▂▂▇▅ |\n\n\n:::\n:::\n\n\n\nThe `public_response` dataset contains critical scores from three professional rating aggregators: Rotten Tomatoes, Metacritic, and Critics' Choice Awards. All three show Pixar films performing exceptionally well:\n\n- **Rotten Tomatoes**: Mean of 89.2, with most films in the 84-97.5 range\n- **Metacritic**: Mean of 80.0, slightly more critical with a 71-90 range\n- **Critics' Choice**: Mean of 87.1, most consistent with a tight 81-93 range\n\nThe `cinema_score` variable contains audience grades (all A+, A, or A-), reflecting strong public reception across the board.\n\n::: {.callout-note}\n## Missing Data Patterns\n\nThe public response dataset contains 24 films compared to 27 in the production data. Additionally, one film in each dataset is missing a Rotten Tomatoes score, one is missing a Metacritic score, and three are missing Critics' Choice scores. This likely reflects:\n\n1. **Recent releases** — Turning Red (2022) and Lightyear (2022) may have been excluded from critical aggregation due to direct-to-streaming releases or data collection timing\n2. **Incomplete critical coverage** — Some films didn't receive Critics' Choice Awards consideration in their release year\n:::\n\n## Data Integration\n\nLet's join the two datasets and create some useful derived variables:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npixar_combined <- pixar_films %>%\n  left_join(public_response, by = 'film') %>%\n  mutate(\n    year = lubridate::year(release_date),\n    decade = paste0(floor(year / 10) * 10, 's'),\n    # Flag franchise films\n    is_cars = str_detect(film, \"^Cars\"),\n    is_toy_story = str_detect(film, \"^Toy Story\"),\n    is_finding = str_detect(film, \"^Finding\"),\n    is_incredibles = str_detect(film, \"^The Incredibles\"),\n    # Categorize as franchise or standalone\n    franchise = case_when(\n      is_cars ~ \"Cars\",\n      is_toy_story ~ \"Toy Story\",\n      is_finding ~ \"Finding Nemo/Dory\",\n      is_incredibles ~ \"The Incredibles\",\n      TRUE ~ \"Standalone\"\n    )\n  )\n\n# Quick check on missing films\ncat(\"Films missing from public_response data:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFilms missing from public_response data:\n```\n\n\n:::\n\n```{.r .cell-code}\npixar_combined %>%\n  filter(is.na(rotten_tomatoes) & is.na(metacritic)) %>%\n  select(film, release_date) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  film        release_date\n  <chr>       <date>      \n1 Luca        2021-06-18  \n2 Turning Red 2022-03-11  \n3 Lightyear   2022-06-17  \n4 <NA>        2023-06-16  \n```\n\n\n:::\n:::\n\n\n\n# Rating System Convergence Analysis\n\nNow we can address one of the core questions: **Do different rating sources diverge significantly in their evaluation of Pixar films?**\n\n## Correlation Between Rating Systems\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor_matrix <- pixar_combined %>%\n  select(rotten_tomatoes, metacritic, critics_choice) %>%\n  cor(use = 'pairwise.complete.obs')\n\ncat(\"Correlation matrix:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCorrelation matrix:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(round(cor_matrix, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                rotten_tomatoes metacritic critics_choice\nrotten_tomatoes           1.000      0.803          0.852\nmetacritic                0.803      1.000          0.865\ncritics_choice            0.852      0.865          1.000\n```\n\n\n:::\n:::\n\n\n\nThe three rating systems show **strong positive correlation** (r = 0.80-0.87), indicating substantial agreement on which Pixar films are exceptional and which fall short. However, the correlations aren't perfect, suggesting some interesting divergences worth exploring.\n\n## Variance Across Rating Systems\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npixar_combined %>%\n  select(film, rotten_tomatoes, metacritic, critics_choice) %>%\n  filter(!is.na(rotten_tomatoes)) %>%\n  pivot_longer(cols = c(rotten_tomatoes, metacritic, critics_choice),\n               names_to = 'source', values_to = 'score') %>%\n  filter(!is.na(score)) %>%\n  group_by(source) %>%\n  summarise(\n    mean = round(mean(score), 1),\n    sd = round(sd(score), 1),\n    min = min(score),\n    max = max(score),\n    range = max - min\n  ) %>%\n  arrange(desc(range))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n  source           mean    sd   min   max range\n  <chr>           <dbl> <dbl> <dbl> <dbl> <dbl>\n1 rotten_tomatoes  89.2  14.2    40   100    60\n2 metacritic       80    12.3    57    96    39\n3 critics_choice   87.1   9.4    66   100    34\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-important}\n## Rating System Characteristics\n\n- **Rotten Tomatoes** has the widest range (60 points from 40 to 100), making it the most discriminating system for Pixar films\n- **Metacritic** occupies the middle ground with a 39-point range and lowest mean (80.0), suggesting slightly more critical standards\n- **Critics' Choice** shows the tightest distribution (34-point range), rarely deviating far from its 87.1 mean — the most \"generous\" or consistent rating source\n:::\n\n## Best and Worst Performers\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Top 3 films by Rotten Tomatoes:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTop 3 films by Rotten Tomatoes:\n```\n\n\n:::\n\n```{.r .cell-code}\npixar_combined %>%\n  filter(!is.na(rotten_tomatoes)) %>%\n  select(film, year, rotten_tomatoes) %>%\n  arrange(desc(rotten_tomatoes)) %>%\n  head(3) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  film          year rotten_tomatoes\n  <chr>        <dbl>           <dbl>\n1 Toy Story     1995             100\n2 Toy Story 2   1999             100\n3 Finding Nemo  2003              99\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nBottom 3 films by Rotten Tomatoes:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBottom 3 films by Rotten Tomatoes:\n```\n\n\n:::\n\n```{.r .cell-code}\npixar_combined %>%\n  filter(!is.na(rotten_tomatoes)) %>%\n  select(film, year, rotten_tomatoes) %>%\n  arrange(rotten_tomatoes) %>%\n  head(3) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  film    year rotten_tomatoes\n  <chr>  <dbl>           <dbl>\n1 Cars 2  2011              40\n2 Cars 3  2017              69\n3 Cars    2006              74\n```\n\n\n:::\n:::\n\n\n\nThe **Toy Story** franchise and **Finding Nemo** dominate the top spots, while the **Cars** franchise occupies all three bottom positions. This pattern holds across rating systems — the Cars films consistently underperform relative to Pixar's overall critical standing.\n\n# Visualization: Rating System Agreement\n\nNow let's visualize how the three rating systems compare. I'll create a scatter plot matrix showing pairwise comparisons, with films color-coded by franchise and labeled for outliers.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare data for plotting\nplot_data <- pixar_combined %>%\n  filter(!is.na(rotten_tomatoes) | !is.na(metacritic) | !is.na(critics_choice)) %>%\n  select(film, year, franchise, rotten_tomatoes, metacritic, critics_choice) %>%\n  mutate(\n    # Label only outliers and top performers\n    label = case_when(\n      franchise == \"Cars\" ~ film,\n      film %in% c(\"Toy Story\", \"Toy Story 2\", \"WALL-E\", \"Ratatouille\",\n                  \"Finding Nemo\", \"Inside Out\") ~ film,\n      TRUE ~ \"\"\n    ),\n    # Color by franchise\n    franchise_color = case_when(\n      franchise == \"Cars\" ~ \"Cars\",\n      franchise == \"Toy Story\" ~ \"Toy Story\",\n      franchise %in% c(\"Finding Nemo/Dory\", \"The Incredibles\") ~ \"Other Franchise\",\n      TRUE ~ \"Standalone\"\n    )\n  )\n\n# Create three scatter plots\np1 <- plot_data %>%\n  ggplot(aes(x = rotten_tomatoes, y = metacritic)) +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\",\n              color = \"gray50\", linewidth = 0.5, alpha = 0.6) +\n  geom_point(aes(color = franchise_color), size = 3, alpha = 0.8) +\n  geom_text_repel(aes(label = label, color = franchise_color),\n                  size = 3, max.overlaps = 20,\n                  box.padding = 0.5, force = 2) +\n  scale_color_manual(\n    values = c(\n      \"Cars\" = \"#DC143C\",              # Crimson red for underperformers\n      \"Toy Story\" = \"#4169E1\",         # Royal blue for top franchise\n      \"Other Franchise\" = \"#32CD32\",   # Lime green\n      \"Standalone\" = \"#808080\"         # Gray\n    )\n  ) +\n  labs(\n    x = \"Rotten Tomatoes Score\",\n    y = \"Metacritic Score\",\n    color = NULL\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(\n    legend.position = \"none\",\n    panel.grid.minor = element_blank(),\n    plot.margin = margin(10, 10, 10, 10)\n  )\n\np2 <- plot_data %>%\n  ggplot(aes(x = rotten_tomatoes, y = critics_choice)) +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\",\n              color = \"gray50\", linewidth = 0.5, alpha = 0.6) +\n  geom_point(aes(color = franchise_color), size = 3, alpha = 0.8) +\n  geom_text_repel(aes(label = label, color = franchise_color),\n                  size = 3, max.overlaps = 20,\n                  box.padding = 0.5, force = 2) +\n  scale_color_manual(\n    values = c(\n      \"Cars\" = \"#DC143C\",\n      \"Toy Story\" = \"#4169E1\",\n      \"Other Franchise\" = \"#32CD32\",\n      \"Standalone\" = \"#808080\"\n    )\n  ) +\n  labs(\n    x = \"Rotten Tomatoes Score\",\n    y = \"Critics' Choice Score\",\n    color = NULL\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(\n    legend.position = \"none\",\n    panel.grid.minor = element_blank(),\n    plot.margin = margin(10, 10, 10, 10)\n  )\n\np3 <- plot_data %>%\n  ggplot(aes(x = metacritic, y = critics_choice)) +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\",\n              color = \"gray50\", linewidth = 0.5, alpha = 0.6) +\n  geom_point(aes(color = franchise_color), size = 3, alpha = 0.8) +\n  geom_text_repel(aes(label = label, color = franchise_color),\n                  size = 3, max.overlaps = 20,\n                  box.padding = 0.5, force = 2) +\n  scale_color_manual(\n    values = c(\n      \"Cars\" = \"#DC143C\",\n      \"Toy Story\" = \"#4169E1\",\n      \"Other Franchise\" = \"#32CD32\",\n      \"Standalone\" = \"#808080\"\n    ),\n    name = NULL\n  ) +\n  labs(\n    x = \"Metacritic Score\",\n    y = \"Critics' Choice Score\",\n    color = NULL\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(\n    legend.position = \"bottom\",\n    panel.grid.minor = element_blank(),\n    plot.margin = margin(10, 10, 10, 10)\n  )\n\n# Combine with patchwork\ncombined_plot <- (p1 | p2 | p3) +\n  plot_annotation(\n    title = \"Pixar's Critical Consensus: High Agreement Across Rating Systems\",\n    subtitle = \"Despite using different methodologies, Rotten Tomatoes, Metacritic, and Critics' Choice converge on Pixar's best and worst films.\\nThe Cars franchise consistently underperforms, while Toy Story and early 2000s classics dominate the top tier.\",\n    caption = \"Data: {pixarfilms} R package | #TidyTuesday 2025-03-11 | Visualization: @seanthimons\",\n    theme = theme(\n      plot.title = element_text(size = 16, face = \"bold\", hjust = 0),\n      plot.subtitle = element_text(size = 11, hjust = 0, margin = margin(b = 15)),\n      plot.caption = element_text(size = 9, hjust = 1, color = \"gray50\")\n    )\n  )\n\ncombined_plot\n```\n\n::: {.cell-output-display}\n![](2025-03-11-pixars-critical-consensus_files/figure-html/hero-viz-rating-agreement-1.png){width=1152}\n:::\n:::\n\n\n\n## Interpretation\n\nThe scatter plot matrix reveals several key patterns:\n\n1. **Strong diagonal clustering** — Most films fall near the y=x reference line, confirming the high correlation between rating systems\n\n2. **Cars franchise outlier** — Cars 2 (40% on RT, 57 on Metacritic) sits far below the diagonal across all comparisons, representing Pixar's most universally panned film. Cars and Cars 3 fare better but still underperform the Pixar baseline.\n\n3. **Top-tier consensus** — Toy Story 1 & 2, Finding Nemo, WALL-E, Ratatouille, and Inside Out cluster in the upper-right quadrant across all three panels, receiving consistent acclaim regardless of rating methodology.\n\n4. **Metacritic as \"tough grader\"** — Notice how the Metacritic vs. Critics' Choice panel shows most films *below* the diagonal — Metacritic systematically assigns lower scores than Critics' Choice for the same films.\n\n5. **Rotten Tomatoes variance** — The RT axis shows the widest spread, particularly in the RT vs. Metacritic panel, where films can differ by 20+ points while still maintaining strong correlation.\n\n# Final thoughts and takeaways\n\nThis analysis reveals a **critical consensus** around Pixar's filmography that transcends individual rating methodologies. Despite differences in aggregation techniques, sample composition, and scoring scales, Rotten Tomatoes, Metacritic, and Critics' Choice Awards converge remarkably on which Pixar films represent the studio's creative peaks and valleys.\n\nThe **Cars franchise** emerges as Pixar's only sustained critical disappointment, occupying the bottom tier across all three rating systems. This pattern likely reflects critics' perception that these films prioritize merchandise appeal over the narrative sophistication and emotional depth that define Pixar's brand. In contrast, the original **Toy Story trilogy** and early-to-mid 2000s classics like **Finding Nemo**, **WALL-E**, and **Ratatouille** achieve near-universal acclaim.\n\nThe tight correlation between rating systems (r ≈ 0.80-0.87) suggests that professional critics largely agree on what makes a Pixar film succeed or fail, even when their scoring scales and methodologies differ. **Metacritic's** lower mean scores reflect its weighted-average methodology that privileges \"top critics,\" while **Critics' Choice** shows the least variance, rarely straying from its 87-point baseline. **Rotten Tomatoes**, with its binary fresh/rotten system aggregated into a percentage, exhibits the widest range and serves as the most discriminating metric for this dataset.\n\n::: {.callout-tip}\n## For Further Analysis\n\nThis dataset pairs well with box office data (available in the source {pixarfilms} package). Future analyses could explore:\n\n- Do critical scores predict domestic vs. international box office performance?\n- How do sequels compare to original films in both critical reception and commercial success?\n- Has Pixar's critical standing evolved over its three-decade run?\n:::\n\n**Bottom line**: When critics agree, they *really* agree — and they've consistently agreed that Pixar sets the bar for animated storytelling, with one notable four-wheeled exception.\n",
    "supporting": [
      "2025-03-11-pixars-critical-consensus_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}