{
  "hash": "5d85dd3b5f571aa69e13c0f4bfffa81e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 'Tidy Tuesday: How Likely Is \"Likely\"?'\nauthor: \"Sean Thimons\"\ndate: \"2026-03-10\"\ndescription: \"Mapping the fuzzy space between 'remote chance' and 'will happen' — how 5,000 people assigned numbers to probability words.\"\ncategories: [tidytuesday, R, linguistics, probability, cognitive-science]\n---\n\n\n\n# Preface\n\nFrom the [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2026/2026-03-10).\n\n> This dataset explores how people interpret common probability phrases through an online quiz created by Adam Kucharski, with over 5,000 participants. Respondents were asked to assign numerical probabilities (0–100) to phrases like \"likely,\" \"probable,\" \"remote chance,\" and \"realistic possibility,\" as well as to make pairwise comparisons between phrases. Three tables capture absolute judgements, pairwise comparisons, and respondent demographics (age, education, English-language background, and country).\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  booster_pack <- c(\n    ### IO ----\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n\n    ### EDA ----\n    'skimr',\n\n    ### Plot ----\n    'paletteer',         # Color palette collection\n    'ggridges',          # Ridge/joy plots for distributions\n    'ggtext',            # Rich text in ggplot (title markdown)\n    'ggrepel',           # Non-overlapping labels\n\n    ### Misc ----\n    'tidytuesdayR'\n  )\n\n  # ! Change load flag to load packages\n  install_booster_pack(package = booster_pack, load = TRUE)\n  rm(install_booster_pack, booster_pack)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2026-03-10')\n\nabsolute_judgements  <- raw$absolute_judgements\npairwise_comparisons <- raw$pairwise_comparisons\nrespondent_metadata  <- raw$respondent_metadata\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## Absolute judgements\n\nEach of the 5,174 respondents rated all 19 probability phrases, yielding 98,306 rows. We drop `response_id` (a participant key) and `order` (presentation sequence — useful for order-effects analysis but not our primary focus here) before skimming.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nabsolute_judgements %>%\n  select(term, probability) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |98306      |\n|Number of columns        |2          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |1          |\n|numeric                  |1          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|term          |         0|             1|   6|  21|     0|       19|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|     n| min| p25| med| p75| max|  mean| geo_mean|    sd|hist  |\n|:-------------|---------:|-------------:|-----:|---:|---:|---:|---:|---:|-----:|--------:|-----:|:-----|\n|probability   |         0|             1| 98306|   0|  10|  50|  75| 100| 45.56|    27.79| 32.93|▇▂▅▃▃ |\n\n\n:::\n:::\n\n\n\nThe `probability` column ranges from 0 to 100 with a median right at 50 — unsurprising given the full spectrum of phrases from \"Almost No Chance\" to \"Will Happen.\" The real story is in per-phrase variation.\n\n## Term-level statistics\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nterm_stats <- absolute_judgements %>%\n  group_by(term) %>%\n  summarise(\n    n            = n(),\n    mean_prob    = round(mean(probability, na.rm = TRUE), 1),\n    median_prob  = median(probability, na.rm = TRUE),\n    sd_prob      = round(sd(probability, na.rm = TRUE), 1),\n    p10          = quantile(probability, 0.10, na.rm = TRUE),\n    p90          = quantile(probability, 0.90, na.rm = TRUE),\n    .groups      = \"drop\"\n  ) %>%\n  arrange(median_prob)\n\nprint(term_stats, n = 19)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 19 × 7\n   term                      n mean_prob median_prob sd_prob   p10   p90\n   <chr>                 <int>     <dbl>       <dbl>   <dbl> <dbl> <dbl>\n 1 Almost No Chance       5174       3.9           2     6     1      10\n 2 Highly Unlikely        5174       9.2           5    12.4   1      20\n 3 Remote Chance          5174       8.7           5     9.9   1      20\n 4 Chances are Slight     5174      13            10    10.2   5      25\n 5 Improbable             5174      13.4          10    11.6   1      30\n 6 Little Chance          5174      11.7          10     8.1   5      20\n 7 Unlikely               5174      19            20    11.3   5      30\n 8 Could Happen           5174      39.7          40    18.2  15      60\n 9 May Happen             5174      41.9          40    17    20      60\n10 Might Happen           5174      40            40    17.7  15      60\n11 About Even             5174      50            50     3.7  50      50\n12 Better than Even       5174      58.1          60     6.8  51      65\n13 Realistic Possibility  5174      57            60    20.5  25      80\n14 Likely                 5174      72.6          75    10.3  60      85\n15 Probable               5174      71.4          75    12    60      85\n16 Very Good Chance       5174      79.2          80     9.9  70      90\n17 Highly Likely          5174      85.3          90    10.9  75      95\n18 Almost Certain         5174      94            95     5.8  90      99\n19 Will Happen            5174      97.6         100     6.9  91.3   100\n```\n\n\n:::\n:::\n\n\n\nThe standout outlier is **\"Realistic Possibility\"** with a standard deviation of 20.5 — by far the widest spread of any phrase. Its median sits at 60, but the 10th–90th percentile range spans 25–80: a 55-point gulf. That's not a phrase — that's a Rorschach test.\n\nAt the other extreme, **\"About Even\"** has a standard deviation of just 3.7. Everyone agrees it means 50%. Its histogram will look like a spike.\n\n## Respondent metadata\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrespondent_metadata %>%\n  select(-response_id, -timestamp) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |5174       |\n|Number of columns        |4          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |4          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable        | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:--------------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|age_band             |       437|          0.92|   3|   8|     0|        8|          0|\n|english_background   |       421|          0.92|  28|  52|     0|        3|          0|\n|education_level      |       663|          0.87|   8|  21|     0|        5|          0|\n|country_of_residence |       720|          0.86|   4|  30|     0|       64|          0|\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nAge distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAge distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\ncount(respondent_metadata, age_band, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 2\n  age_band     n\n  <chr>    <int>\n1 35-44     1405\n2 45-54     1163\n3 25-34      868\n4 55-64      734\n5 <NA>       437\n6 65-74      328\n7 18-24      141\n8 75+         79\n9 Under 18    19\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nEnglish background:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nEnglish background:\n```\n\n\n:::\n\n```{.r .cell-code}\ncount(respondent_metadata, english_background, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  english_background                                       n\n  <chr>                                                <int>\n1 English is my first language                          3993\n2 English is not my first language but I am fluent       720\n3 <NA>                                                   421\n4 English is not my first language and I am not fluent    40\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nTop countries:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTop countries:\n```\n\n\n:::\n\n```{.r .cell-code}\ncount(respondent_metadata, country_of_residence, sort = TRUE) %>% head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 2\n   country_of_residence     n\n   <chr>                <int>\n 1 United Kingdom        2018\n 2 United States         1436\n 3 <NA>                   720\n 4 Canada                 161\n 5 Australia              121\n 6 Germany                108\n 7 Norway                  74\n 8 New Zealand             52\n 9 Ireland                 50\n10 Netherlands             48\n```\n\n\n:::\n:::\n\n\n\nThe sample skews toward English-first-language, UK/US, and highly educated respondents — worth noting when interpreting results. These are people who likely encounter probability language professionally (policy, science, finance). Their intuitions may differ from a general population sample.\n\n# Mapping the probability spectrum\n\nThe central question: how does language map onto numbers? And where does it fall apart?\n\nEach phrase was rated by 5,174 respondents. Plotting the full distribution of estimates for each phrase — ordered from lowest to highest median — reveals both the consensus and the disagreement embedded in everyday probability language.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Build ordered factor for y-axis\nterm_order <- term_stats %>%\n  arrange(median_prob) %>%\n  pull(term)\n\nplot_data <- absolute_judgements %>%\n  mutate(\n    term = factor(term, levels = term_order),\n    median_prob = term_stats$median_prob[match(term, term_stats$term)]\n  )\n\ncat(sprintf(\"plot_data: %d rows, %d cols\\n\", nrow(plot_data), ncol(plot_data)))\nstopifnot(\"Plot data has 0 rows\" = nrow(plot_data) > 0)\n\n# Build annotation data: median + SD label per term\nannot_data <- term_stats %>%\n  mutate(\n    term   = factor(term, levels = term_order),\n    label  = sprintf(\"med=%g, sd=%g\", median_prob, sd_prob),\n    # flag the most ambiguous term\n    is_ambiguous = term == \"Realistic Possibility\"\n  )\n\ncat(sprintf(\"annot_data: %d rows\\n\", nrow(annot_data)))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np <- ggplot2::ggplot(plot_data,\n       ggplot2::aes(\n         x    = probability,\n         y    = term,\n         fill = ggplot2::after_stat(x)\n       )\n     ) +\n\n  # Ridge plot with gradient fill — each ridge's color encodes the x-value\n  ggridges::geom_density_ridges_gradient(\n    scale         = 2.2,\n    rel_min_height = 0.01,\n    color         = \"white\",\n    linewidth     = 0.35,\n    show.legend   = FALSE\n  ) +\n\n  # Median tick marks\n  ggplot2::geom_point(\n    data    = annot_data,\n    mapping = ggplot2::aes(x = median_prob, y = term),\n    inherit.aes = FALSE,\n    shape   = 124,       # vertical bar\n    size    = 4,\n    color   = \"white\",\n    alpha   = 0.85\n  ) +\n\n  # SD annotation — right-aligned labels\n  ggplot2::geom_text(\n    data    = annot_data,\n    mapping = ggplot2::aes(\n      x     = 102,\n      y     = term,\n      label = sprintf(\"sd = %g\", sd_prob),\n      color = is_ambiguous\n    ),\n    inherit.aes = FALSE,\n    hjust   = 0,\n    vjust   = 0.5,\n    size    = 2.8,\n    family  = \"mono\",\n    fontface = \"plain\",\n    show.legend = FALSE\n  ) +\n\n  # Highlight \"Realistic Possibility\" annotation\n  ggplot2::annotate(\n    \"text\",\n    x     = 102,\n    y     = \"Realistic Possibility\",\n    label = \"← most ambiguous\",\n    vjust = -0.8,\n    hjust = 0,\n    size  = 2.6,\n    color = \"#E07B54\",\n    fontface = \"italic\"\n  ) +\n\n  # Reference lines at 25 / 50 / 75\n  ggplot2::geom_vline(\n    xintercept = c(25, 50, 75),\n    linetype   = \"dashed\",\n    color      = \"white\",\n    alpha      = 0.3,\n    linewidth  = 0.4\n  ) +\n\n  # Gradient fill using scico::lapaz (unused palette — blue-purple to cream)\n  paletteer::scale_fill_paletteer_c(\"scico::lapaz\", direction = -1) +\n\n  # Color for SD label (highlight ambiguous term)\n  ggplot2::scale_color_manual(\n    values = c(`FALSE` = \"grey70\", `TRUE` = \"#E07B54\")\n  ) +\n\n  # x-axis labels at reference lines\n  ggplot2::scale_x_continuous(\n    limits = c(0, 130),\n    breaks = c(0, 25, 50, 75, 100),\n    labels = c(\"0\", \"25%\", \"50%\", \"75%\", \"100%\"),\n    expand = ggplot2::expansion(mult = c(0, 0))\n  ) +\n\n  ggplot2::labs(\n    title    = \"**What does \\\"likely\\\" actually mean?**\",\n    subtitle = \"Distribution of numerical probability estimates (0–100) assigned to 19 common phrases by 5,174 respondents.\\nVertical bars mark each phrase's median. Labels show standard deviation — a measure of how much people disagree.\",\n    x        = \"Assigned probability\",\n    y        = NULL,\n    caption  = \"Source: Adam Kucharski / TidyTuesday 2026-03-10 · Viz: @seanthimons\"\n  ) +\n\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    plot.background    = ggplot2::element_rect(fill = \"#1a1a2e\", color = NA),\n    panel.background   = ggplot2::element_rect(fill = \"#1a1a2e\", color = NA),\n    panel.grid.major.x = ggplot2::element_blank(),\n    panel.grid.minor   = ggplot2::element_blank(),\n    panel.grid.major.y = ggplot2::element_blank(),\n    axis.text.x        = ggplot2::element_text(color = \"grey70\", size = 10),\n    axis.text.y        = ggplot2::element_text(color = \"white\",  size = 10, hjust = 1),\n    axis.title.x       = ggplot2::element_text(color = \"grey60\", size = 10, margin = ggplot2::margin(t = 8)),\n    plot.title         = ggtext::element_markdown(color = \"white\", size = 18, face = \"bold\", margin = ggplot2::margin(b = 4)),\n    plot.subtitle      = ggplot2::element_text(color = \"grey65\", size = 10, lineheight = 1.4, margin = ggplot2::margin(b = 14)),\n    plot.caption       = ggplot2::element_text(color = \"grey50\", size = 8,  hjust = 1, margin = ggplot2::margin(t = 10)),\n    plot.margin        = ggplot2::margin(16, 90, 10, 16)\n  )\n\np\n```\n\n::: {.cell-output-display}\n![](2026-03-10-how-likely-is-likely_files/figure-html/hero-plot-1.png){width=1152}\n:::\n:::\n\n\n\n::: {.callout-note}\n**Reading the ridges:** Each mountain represents the full distribution of responses for that phrase. A narrow spike means high agreement (everyone assigns similar numbers). A wide, flat ridge means high disagreement. The white bar inside each ridge marks the median.\n:::\n\n::: {.callout-important}\n**\"Realistic Possibility\" is the most contested phrase in the dataset.** Its standard deviation of 20.5 is nearly three times that of \"Likely\" (sd = 10.3) and more than five times that of \"About Even\" (sd = 3.7). Some respondents read it as ~25%; others as ~80%. Yet intelligence analysts, policy documents, and risk reports use it constantly as if its meaning were self-evident.\n:::\n\n# Consensus vs. ambiguity: a closer look\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Rank terms by ambiguity (SD)\nterm_stats %>%\n  select(term, median_prob, sd_prob, p10, p90) %>%\n  mutate(\n    range_80pct = p90 - p10,\n    ambiguity_rank = rank(-sd_prob, ties.method = \"min\")\n  ) %>%\n  arrange(ambiguity_rank) %>%\n  print(n = 19)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 19 × 7\n   term               median_prob sd_prob   p10   p90 range_80pct ambiguity_rank\n   <chr>                    <dbl>   <dbl> <dbl> <dbl>       <dbl>          <int>\n 1 Realistic Possibi…          60    20.5  25      80       55                 1\n 2 Could Happen                40    18.2  15      60       45                 2\n 3 Might Happen                40    17.7  15      60       45                 3\n 4 May Happen                  40    17    20      60       40                 4\n 5 Highly Unlikely              5    12.4   1      20       19                 5\n 6 Probable                    75    12    60      85       25                 6\n 7 Improbable                  10    11.6   1      30       29                 7\n 8 Unlikely                    20    11.3   5      30       25                 8\n 9 Highly Likely               90    10.9  75      95       20                 9\n10 Likely                      75    10.3  60      85       25                10\n11 Chances are Slight          10    10.2   5      25       20                11\n12 Remote Chance                5     9.9   1      20       19                12\n13 Very Good Chance            80     9.9  70      90       20                12\n14 Little Chance               10     8.1   5      20       15                14\n15 Will Happen                100     6.9  91.3   100        8.70             15\n16 Better than Even            60     6.8  51      65       14                16\n17 Almost No Chance             2     6     1      10        9                17\n18 Almost Certain              95     5.8  90      99        9                18\n19 About Even                  50     3.7  50      50        0                19\n```\n\n\n:::\n:::\n\n\n\nThe three \"fuzzy middle\" phrases — **Could Happen**, **May Happen**, and **Might Happen** — all cluster around 40% with nearly identical distributions (SDs of 18.2, 17.0, and 17.7 respectively). They are, for practical purposes, synonyms in how people interpret them numerically, yet writers and speakers treat them as meaningfully distinct.\n\nThe top end of the spectrum is tighter: **Almost Certain** (sd = 5.8) and **Will Happen** (sd = 6.9) leave little room for debate. Certainty turns out to be more legible than near-certainty.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nambig_data <- term_stats %>%\n  mutate(\n    term    = factor(term, levels = term_order),\n    is_high = sd_prob >= 17\n  ) %>%\n  arrange(median_prob)\n\ncat(sprintf(\"ambig_data: %d rows\\n\", nrow(ambig_data)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nambig_data: 19 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"ambig_data is empty\" = nrow(ambig_data) > 0)\n\np2 <- ggplot2::ggplot(ambig_data,\n       ggplot2::aes(x = median_prob, y = term, color = sd_prob, size = sd_prob)\n     ) +\n  ggplot2::geom_segment(\n    ggplot2::aes(x = p10, xend = p90, yend = term),\n    linewidth = 1.5, alpha = 0.6\n  ) +\n  ggplot2::geom_point(size = 3) +\n  ggrepel::geom_text_repel(\n    data = ambig_data %>% dplyr::filter(is_high),\n    ggplot2::aes(label = sprintf(\"sd = %g\", sd_prob)),\n    size = 3,\n    color = \"#E07B54\",\n    nudge_x = 8,\n    segment.color = \"grey50\",\n    segment.size  = 0.3,\n    min.segment.length = 0\n  ) +\n  paletteer::scale_color_paletteer_c(\"scico::lapaz\", direction = -1,\n                                      name = \"Std. dev.\") +\n  ggplot2::scale_size_continuous(range = c(2, 5), guide = \"none\") +\n  ggplot2::scale_x_continuous(\n    limits = c(0, 115),\n    breaks = c(0, 25, 50, 75, 100),\n    labels = c(\"0\", \"25%\", \"50%\", \"75%\", \"100%\")\n  ) +\n  ggplot2::labs(\n    title    = \"Median estimate ± 80% range for each probability phrase\",\n    subtitle = \"Segments span 10th–90th percentile. Wider = more disagreement.\",\n    x        = \"Assigned probability\",\n    y        = NULL,\n    caption  = \"Source: Adam Kucharski / TidyTuesday 2026-03-10\"\n  ) +\n  ggplot2::theme_minimal(base_size = 12) +\n  ggplot2::theme(\n    plot.background  = ggplot2::element_rect(fill = \"#1a1a2e\", color = NA),\n    panel.background = ggplot2::element_rect(fill = \"#1a1a2e\", color = NA),\n    panel.grid.major.x = ggplot2::element_line(color = \"#2d2d4e\", linewidth = 0.4),\n    panel.grid.major.y = ggplot2::element_blank(),\n    panel.grid.minor   = ggplot2::element_blank(),\n    axis.text          = ggplot2::element_text(color = \"grey70\"),\n    axis.title.x       = ggplot2::element_text(color = \"grey60\", margin = ggplot2::margin(t = 8)),\n    plot.title         = ggplot2::element_text(color = \"white\", face = \"bold\", size = 14),\n    plot.subtitle      = ggplot2::element_text(color = \"grey65\", size = 10),\n    plot.caption       = ggplot2::element_text(color = \"grey50\", size = 8, hjust = 1),\n    legend.text        = ggplot2::element_text(color = \"grey70\"),\n    legend.title       = ggplot2::element_text(color = \"grey70\"),\n    plot.margin        = ggplot2::margin(16, 16, 10, 16)\n  )\n\np2\n```\n\n::: {.cell-output-display}\n![](2026-03-10-how-likely-is-likely_files/figure-html/viz-ambiguity-ranking-1.png){width=960}\n:::\n:::\n\n\n\n# Log palette\n\n\n\n::: {.cell}\n\n:::\n\n\n\n# Final thoughts and takeaways\n\nLanguage is imprecise — but we've long known that. What this dataset makes viscerally clear is **which words are imprecise and by how much**.\n\nA few takeaways:\n\n1. **\"Realistic Possibility\" is a linguistic landmine.** Intelligence reports, policy briefs, and scientific summaries lean on it heavily, but 5,000 respondents couldn't agree within 55 percentage points on what it means. Using it to communicate risk is roughly equivalent to shrugging.\n\n2. **The extremes are remarkably stable.** \"Almost Certain\" and \"Will Happen\" show tight distributions (sd ~6–7). When we want to convey near-certainty, our vocabulary is actually quite reliable. The breakdown happens in the middle.\n\n3. **\"Could Happen,\" \"May Happen,\" and \"Might Happen\" are functionally synonymous** in this dataset — same median, same spread. If you're choosing between them for stylistic variety, know that your reader assigns them the same number.\n\n4. **\"About Even\" is the Schelling point of probability language.** Everyone knows 50-50 when they see it. Its sd of 3.7 makes it the most precisely communicated phrase in the entire lexicon.\n\nThe deeper lesson: if precision matters — in medical communications, intelligence assessments, financial disclosures, or risk reporting — probability words should come with numbers attached. The data shows conclusively that \"likely\" to you may mean 60%; to your reader, it may mean 80%. In high-stakes contexts, that gap has consequences.\n",
    "supporting": [
      "2026-03-10-how-likely-is-likely_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}