{
  "hash": "9e6a851b8f94679c9070bdf6ddfc9d49",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Base R Penguins\"\nauthor: \"Sean Thimons\"\ndate: \"2025-04-15\"\ndescription: \"Exploring the Palmer Penguins dataset—now shipped in base R 4.5.0—through stable isotope ecology. What do carbon and nitrogen ratios reveal about species-level feeding niches in Antarctic waters?\"\ncategories: [tidytuesday, R, ecology, penguins, isotopes]\n---\n\n\n\n# Preface\n\nFrom [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-04-15).\n\n> **Base R Penguins** — The beloved Palmer Penguins dataset, originally published by Gorman et al. (2014) and popularized by the `palmerpenguins` R package, is now part of base R as of version 4.5.0 (released April 11, 2025). The dataset documents bill morphology, flipper length, body mass, sex, and stable isotope ratios for three penguin species (*Pygoscelis adeliae*, *P. antarcticus*, *P. papua*) surveyed across three islands in the Palmer Archipelago, Antarctica from 2007–2009.\n\nThe TidyTuesday framing invites reflection: How have visualization practices evolved since the 2020 edition? Here, I take the road less traveled and dig into the **raw** dataset's isotope columns — the δ¹³C and δ¹⁵N measurements that ecologists use to fingerprint diet and trophic position. This angle is almost always overlooked in penguin analyses, but it tells a richer ecological story than bill dimensions alone.\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  booster_pack <- c(\n    ### IO ----\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n\n    ### EDA ----\n    'skimr',\n\n    ### Plot ----\n    'paletteer',           # Color palette collection\n    'patchwork',           # Multi-panel layouts\n    'ggrepel',             # Non-overlapping labels\n    'ggforce',             # geom_mark_ellipse for convex hulls\n    'ggtext',              # Rich text in ggplot (for markdown titles)\n\n    ### Misc ----\n    NULL\n  )\n\n  install_booster_pack(package = booster_pack, load = TRUE)\n  rm(install_booster_pack, booster_pack)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# penguins and penguins_raw are built into base R >= 4.5.0\ndata(penguins, package = \"datasets\")\ndata(penguins_raw, package = \"datasets\")\n\n# Base R 4.5.0 uses shorter column names; rename to match palmerpenguins style\npenguins <- penguins %>%\n  rename(\n    bill_length_mm    = bill_len,\n    bill_depth_mm     = bill_dep,\n    flipper_length_mm = flipper_len,\n    body_mass_g       = body_mass\n  )\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse, the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram.\n\n## Penguins (clean)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Drop any ID or free-text columns — none in the clean version\npenguins %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |344        |\n|Number of columns        |8          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|factor                   |3          |\n|numeric                  |5          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts                  |\n|:-------------|---------:|-------------:|:-------|--------:|:---------------------------|\n|species       |         0|          1.00|FALSE   |        3|Ade: 152, Gen: 124, Chi: 68 |\n|island        |         0|          1.00|FALSE   |        3|Bis: 168, Dre: 124, Tor: 52 |\n|sex           |        11|          0.97|FALSE   |        2|mal: 168, fem: 165          |\n\n\n**Variable type: numeric**\n\n|skim_variable     | n_missing| complete_rate|   n|    min|     p25|     med|    p75|    max|    mean| geo_mean|     sd|hist  |\n|:-----------------|---------:|-------------:|---:|------:|-------:|-------:|------:|------:|-------:|--------:|------:|:-----|\n|bill_length_mm    |         2|          0.99| 344|   32.1|   39.23|   44.45|   48.5|   59.6|   43.92|    43.58|   5.46|▃▇▇▆▁ |\n|bill_depth_mm     |         2|          0.99| 344|   13.1|   15.60|   17.30|   18.7|   21.5|   17.15|    17.04|   1.97|▅▅▇▇▂ |\n|flipper_length_mm |         2|          0.99| 344|  172.0|  190.00|  197.00|  213.0|  231.0|  200.92|   200.43|  14.06|▂▇▃▅▂ |\n|body_mass_g       |         2|          0.99| 344| 2700.0| 3550.00| 4050.00| 4750.0| 6300.0| 4201.75|  4127.79| 801.95|▃▇▆▃▂ |\n|year              |         0|          1.00| 344| 2007.0| 2007.00| 2008.00| 2009.0| 2009.0| 2008.03|  2008.03|   0.82|▇▁▇▁▇ |\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Species distribution\npenguins %>% count(species, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    species   n\n1    Adelie 152\n2    Gentoo 124\n3 Chinstrap  68\n```\n\n\n:::\n\n```{.r .cell-code}\n# Island distribution\npenguins %>% count(island, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     island   n\n1    Biscoe 168\n2     Dream 124\n3 Torgersen  52\n```\n\n\n:::\n\n```{.r .cell-code}\n# Sex breakdown by species\npenguins %>% count(species, sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    species    sex  n\n1    Adelie female 73\n2    Adelie   male 73\n3    Adelie   <NA>  6\n4 Chinstrap female 34\n5 Chinstrap   male 34\n6    Gentoo female 58\n7    Gentoo   male 61\n8    Gentoo   <NA>  5\n```\n\n\n:::\n:::\n\n\n\nThe clean dataset has **344 rows** with 11 missing values spread across the measurement columns. Adelie is the most numerous species (152 birds), followed by Gentoo (124) and Chinstrap (68). Biscoe Island hosts the most observations, primarily Gentoo penguins. Sex is well-balanced within each species, with a small number of individuals with unknown sex (encoded as `NA`).\n\nBody mass spans 2,700–6,300 g across species. The distribution is right-skewed (mean > median), suggesting the heavier Gentoo penguins pull the mean upward. Bill dimensions show two distinct clusters when inspected by species — a well-known pattern in this dataset.\n\n## Penguins raw\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Clean column names and inspect the structure\npenguins_raw_clean <- penguins_raw %>%\n  janitor::clean_names()\n\n# Show all column names — this is essential to verify isotope column names\ncat(\"Columns in penguins_raw_clean:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nColumns in penguins_raw_clean:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(names(penguins_raw_clean))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"study_name\"        \"sample_number\"     \"species\"          \n [4] \"region\"            \"island\"            \"stage\"            \n [7] \"individual_id\"     \"clutch_completion\" \"date_egg\"         \n[10] \"culmen_length_mm\"  \"culmen_depth_mm\"   \"flipper_length_mm\"\n[13] \"body_mass_g\"       \"sex\"               \"delta_15_n_o_oo\"  \n[16] \"delta_13_c_o_oo\"   \"comments\"         \n```\n\n\n:::\n\n```{.r .cell-code}\n# Profile the numeric columns most relevant to our analysis\npenguins_raw_clean %>%\n  select(\n    culmen_length_mm,\n    culmen_depth_mm,\n    flipper_length_mm,\n    body_mass_g,\n    delta_15_n_o_oo,\n    delta_13_c_o_oo\n  ) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |344        |\n|Number of columns        |6          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|numeric                  |6          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: numeric**\n\n|skim_variable     | n_missing| complete_rate|   n|     min|     p25|     med|     p75|     max|    mean| geo_mean|     sd|hist  |\n|:-----------------|---------:|-------------:|---:|-------:|-------:|-------:|-------:|-------:|-------:|--------:|------:|:-----|\n|culmen_length_mm  |         2|          0.99| 344|   32.10|   39.23|   44.45|   48.50|   59.60|   43.92|    43.58|   5.46|▃▇▇▆▁ |\n|culmen_depth_mm   |         2|          0.99| 344|   13.10|   15.60|   17.30|   18.70|   21.50|   17.15|    17.04|   1.97|▅▅▇▇▂ |\n|flipper_length_mm |         2|          0.99| 344|  172.00|  190.00|  197.00|  213.00|  231.00|  200.92|   200.43|  14.06|▂▇▃▅▂ |\n|body_mass_g       |         2|          0.99| 344| 2700.00| 3550.00| 4050.00| 4750.00| 6300.00| 4201.75|  4127.79| 801.95|▃▇▆▃▂ |\n|delta_15_n_o_oo   |        14|          0.96| 344|    7.63|    8.30|    8.65|    9.17|   10.03|    8.73|     8.72|   0.55|▃▇▆▅▂ |\n|delta_13_c_o_oo   |        13|          0.96| 344|  -27.02|  -26.32|  -25.83|  -25.06|  -23.79|  -25.69|      NaN|   0.79|▆▇▅▅▂ |\n\n\n:::\n:::\n\n\n\nThe raw dataset has 17 columns including the two stable isotope measurements: **δ¹⁵N** (`delta_15_n_o_oo`) and **δ¹³C** (`delta_13_c_o_oo`), both expressed in per-mille (‰). These are the ecologically richest variables in the entire dataset.\n\nThe isotope columns have ~14 missing values each — likely the same birds missing body measurements. Both distributions are relatively tight: δ¹⁵N ranges from roughly 7.6 to 10.0‰, and δ¹³C from approximately –28 to –23‰.\n\n# Domain Analysis: Isotopic Niche Space\n\n::: {.callout-note}\n## Stable Isotope Ecology Primer\n\n**δ¹³C** (carbon isotope ratio) reflects the *source* of carbon in an animal's diet. In Antarctic marine systems, more negative values (≈ −27‰) indicate reliance on pelagic (open-water) food webs, while less negative values (≈ −23‰) indicate benthic or shelf-associated food sources.\n\n**δ¹⁵N** (nitrogen isotope ratio) reflects *trophic position*. Each step up the food chain enriches an animal's tissue by approximately 3–4‰. Higher δ¹⁵N = eating things that ate things. Within these three species, a 1‰ difference in δ¹⁵N is biologically meaningful.\n\nTogether, δ¹³C and δ¹⁵N form a two-dimensional **isotopic niche** — a proxy for where an animal feeds and what it eats.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simplify species names from long strings like \"Adelie Penguin (Pygoscelis adeliae)\"\npenguins_iso <- penguins_raw_clean %>%\n  mutate(\n    species_short = case_when(\n      str_detect(species, regex(\"adelie\", ignore_case = TRUE))     ~ \"Adelie\",\n      str_detect(species, regex(\"chinstrap\", ignore_case = TRUE))  ~ \"Chinstrap\",\n      str_detect(species, regex(\"gentoo\", ignore_case = TRUE))     ~ \"Gentoo\",\n      TRUE ~ species\n    ),\n    sex_clean = str_to_title(sex)\n  ) %>%\n  filter(!is.na(delta_15_n_o_oo), !is.na(delta_13_c_o_oo)) %>%\n  select(species_short, island, sex_clean, body_mass_g,\n         delta_15_n_o_oo, delta_13_c_o_oo)\n\n# Guard: must have observations for all three species\ncat(sprintf(\"isotope data: %d rows, %d cols\\n\", nrow(penguins_iso), ncol(penguins_iso)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nisotope data: 330 rows, 6 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\n  \"Isotope data has 0 rows — check filter\" = nrow(penguins_iso) > 0,\n  \"Not all three species present\" = length(unique(penguins_iso$species_short)) == 3\n)\n\n# Quick sanity check on species labels\npenguins_iso %>% count(species_short)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  species_short   n\n1        Adelie 141\n2     Chinstrap  67\n3        Gentoo 122\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Species-level isotope centroids and spread\niso_summary <- penguins_iso %>%\n  group_by(species_short) %>%\n  summarise(\n    n              = n(),\n    mean_d13c      = mean(delta_13_c_o_oo, na.rm = TRUE),\n    sd_d13c        = sd(delta_13_c_o_oo,   na.rm = TRUE),\n    mean_d15n      = mean(delta_15_n_o_oo, na.rm = TRUE),\n    sd_d15n        = sd(delta_15_n_o_oo,   na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\niso_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n  species_short     n mean_d13c sd_d13c mean_d15n sd_d15n\n  <chr>         <int>     <dbl>   <dbl>     <dbl>   <dbl>\n1 Adelie          141     -25.8   0.588      8.86   0.426\n2 Chinstrap        67     -24.6   0.221      9.36   0.369\n3 Gentoo          122     -26.2   0.539      8.25   0.264\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Range of isotope values across all species\ncat(\"δ¹³C range:\", round(range(penguins_iso$delta_13_c_o_oo), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nδ¹³C range: -27.02 -23.89 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"δ¹⁵N range:\", round(range(penguins_iso$delta_15_n_o_oo), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nδ¹⁵N range: 7.63 10.03 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Gentoo vs. Adelie d13C comparison\ngentoo_d13c  <- penguins_iso %>% filter(species_short == \"Gentoo\") %>% pull(delta_13_c_o_oo)\nadelie_d13c  <- penguins_iso %>% filter(species_short == \"Adelie\") %>% pull(delta_13_c_o_oo)\nchinstrap_d13c <- penguins_iso %>% filter(species_short == \"Chinstrap\") %>% pull(delta_13_c_o_oo)\n\ncat(sprintf(\"\\nMean δ¹³C — Adelie: %.2f | Chinstrap: %.2f | Gentoo: %.2f\\n\",\n            mean(adelie_d13c), mean(chinstrap_d13c), mean(gentoo_d13c)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMean δ¹³C — Adelie: -25.80 | Chinstrap: -24.56 | Gentoo: -26.19\n```\n\n\n:::\n\n```{.r .cell-code}\n# t-test: Gentoo vs. pooled Pygoscelis adeliae/antarcticus\nt_result <- t.test(gentoo_d13c, c(adelie_d13c, chinstrap_d13c))\ncat(sprintf(\"Gentoo vs. Adelie+Chinstrap δ¹³C — t = %.2f, p = %.2e\\n\",\n            t_result$statistic, t_result$p.value))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGentoo vs. Adelie+Chinstrap δ¹³C — t = -10.84, p = 1.72e-23\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-important}\n## Key Finding\n\nGentoo penguins have significantly **less negative δ¹³C** values than Adelie and Chinstrap penguins (p < 0.001). This carbon signature is a strong signal that Gentoos forage in more **benthic or shelf-associated** habitats — consistent with their known preference for fish and benthic invertebrates. Adelie and Chinstrap, by contrast, cluster at more negative δ¹³C values, indicating a more **pelagic, krill-dominated** diet.\n\nThe trophic dimension (δ¹⁵N) shows a similar pattern: Chinstrap penguins occupy a slightly *lower* trophic position on average despite being krill specialists, while Gentoos' fish-heavy diet elevates their δ¹⁵N.\n:::\n\n# The Isotopic Niche: Hero Visualization\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Build species centroids for centroid label annotations\niso_centroids <- penguins_iso %>%\n  group_by(species_short) %>%\n  summarise(\n    delta_13_c_o_oo = mean(delta_13_c_o_oo, na.rm = TRUE),\n    delta_15_n_o_oo = mean(delta_15_n_o_oo, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\np_iso <- ggplot2::ggplot(\n  penguins_iso,\n  ggplot2::aes(\n    x     = delta_13_c_o_oo,\n    y     = delta_15_n_o_oo,\n    color = species_short,\n    fill  = species_short\n  )\n) +\n  # Confidence ellipses (95%) per species\n  ggforce::geom_mark_ellipse(\n    ggplot2::aes(label = species_short),\n    alpha        = 0.10,\n    label.fontsize = 10,\n    label.fontface = \"bold\",\n    con.colour   = \"grey60\",\n    expand       = ggplot2::unit(3, \"mm\")\n  ) +\n  # Individual observation points\n  ggplot2::geom_point(\n    size  = 2.5,\n    alpha = 0.70,\n    shape = 16\n  ) +\n  # Crosshair at each species centroid\n  ggplot2::geom_point(\n    data  = iso_centroids,\n    size  = 6,\n    shape = 3,\n    stroke = 1.8,\n    alpha = 1\n  ) +\n  ggplot2::scale_color_manual(values = species_colors, guide = \"none\") +\n  ggplot2::scale_fill_manual(values  = species_colors, guide = \"none\") +\n  # Axis annotations explaining ecological meaning\n  ggplot2::annotate(\n    \"text\",\n    x     = -27.9, y = 7.65,\n    label = \"\\u2190 More pelagic (open water)\",\n    hjust = 0, size = 3.2, color = \"grey40\", fontface = \"italic\"\n  ) +\n  ggplot2::annotate(\n    \"text\",\n    x     = -23.7, y = 7.65,\n    label = \"More benthic (shelf) \\u2192\",\n    hjust = 1, size = 3.2, color = \"grey40\", fontface = \"italic\"\n  ) +\n  ggplot2::annotate(\n    \"text\",\n    x     = -28.1, y = 9.95,\n    label = \"\\u2191 Higher trophic level\",\n    hjust = 0, vjust = 1, size = 3.2, color = \"grey40\", fontface = \"italic\",\n    angle = 90\n  ) +\n  ggplot2::labs(\n    title    = \"Three Penguins, Three Feeding Strategies\",\n    subtitle = paste0(\n      \"Stable isotope ratios reveal distinct ecological niches.\\n\",\n      \"\\u03b4\\u00b9\\u00b3C tracks food-web origin (pelagic vs. benthic); \",\n      \"\\u03b4\\u00b9\\u2075N tracks trophic position.\\n\",\n      \"Crosshairs mark species centroids. Ellipses enclose 95% of each species' isotopic space.\"\n    ),\n    x        = \"\\u03b4\\u00b9\\u00b3C (\\u2030) \\u2014 Carbon isotope ratio\",\n    y        = \"\\u03b4\\u00b9\\u2075N (\\u2030) \\u2014 Nitrogen isotope ratio\",\n    caption  = paste0(\n      \"Data: Gorman et al. (2014) via TidyTuesday 2025-04-15 | \",\n      \"Now in base R 4.5.0 as datasets::penguins\"\n    )\n  ) +\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    plot.title       = ggplot2::element_text(face = \"bold\", size = 17, margin = ggplot2::margin(b = 6)),\n    plot.subtitle    = ggplot2::element_text(color = \"grey35\", size = 11, lineheight = 1.35,\n                                              margin = ggplot2::margin(b = 14)),\n    plot.caption     = ggplot2::element_text(color = \"grey55\", size = 9, margin = ggplot2::margin(t = 10)),\n    axis.title       = ggplot2::element_text(size = 11),\n    panel.grid.minor = ggplot2::element_blank(),\n    panel.grid.major = ggplot2::element_line(color = \"grey90\", linewidth = 0.4),\n    plot.background  = ggplot2::element_rect(fill = \"#FAFAF8\", color = NA),\n    panel.background = ggplot2::element_rect(fill = \"#FAFAF8\", color = NA),\n    plot.margin      = ggplot2::margin(16, 20, 12, 16)\n  )\n\np_iso\n```\n\n::: {.cell-output-display}\n![](2025-04-15-base-r-penguins_files/figure-html/hero-isotope-plot-1.png){width=960}\n:::\n:::\n\n\n\n# Body Mass and Sexual Dimorphism\n\nThe isotopic data tells us *what* penguins eat; body mass tells us *how big* they get. Gentoos, which occupy a higher and more benthic isotopic niche, are also the largest species by a wide margin. Here we look at body mass distributions broken down by species and sex.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use the clean dataset for this section\nbm_data <- penguins %>%\n  filter(!is.na(body_mass_g), !is.na(sex)) %>%\n  mutate(\n    species = factor(species, levels = c(\"Adelie\", \"Chinstrap\", \"Gentoo\")),\n    sex     = str_to_title(sex)\n  )\n\ncat(sprintf(\"body mass data: %d rows\\n\", nrow(bm_data)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbody mass data: 333 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Body mass data is empty\" = nrow(bm_data) > 0)\n\nbm_data %>% count(species, sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    species    sex  n\n1    Adelie Female 73\n2    Adelie   Male 73\n3 Chinstrap Female 34\n4 Chinstrap   Male 34\n5    Gentoo Female 58\n6    Gentoo   Male 61\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np_bm <- ggplot2::ggplot(\n  bm_data,\n  ggplot2::aes(x = species, y = body_mass_g, color = species, fill = species)\n) +\n  ggplot2::geom_violin(alpha = 0.25, trim = FALSE, linewidth = 0.6) +\n  ggplot2::geom_jitter(\n    ggplot2::aes(shape = sex),\n    width = 0.12, alpha = 0.60, size = 1.8\n  ) +\n  ggplot2::stat_summary(\n    fun = median, geom = \"crossbar\",\n    width = 0.35, linewidth = 0.7, fatten = 2,\n    color = \"grey20\"\n  ) +\n  ggplot2::scale_color_manual(values = species_colors, guide = \"none\") +\n  ggplot2::scale_fill_manual(values  = species_colors, guide = \"none\") +\n  ggplot2::scale_shape_manual(values = c(\"Female\" = 16, \"Male\" = 17)) +\n  ggplot2::scale_y_continuous(\n    labels = scales::label_comma(suffix = \" g\"),\n    breaks = seq(2500, 6500, 500)\n  ) +\n  ggplot2::labs(\n    title    = \"Gentoos Dwarf Their Cousins\",\n    subtitle = \"Body mass distribution by species and sex. Crossbar = median. Triangles = male; circles = female.\",\n    x        = NULL,\n    y        = \"Body mass (g)\",\n    shape    = \"Sex\",\n    caption  = \"Data: Gorman et al. (2014) via TidyTuesday 2025-04-15\"\n  ) +\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    plot.title       = ggplot2::element_text(face = \"bold\", size = 15),\n    plot.subtitle    = ggplot2::element_text(color = \"grey35\", size = 10.5),\n    plot.caption     = ggplot2::element_text(color = \"grey55\", size = 9),\n    panel.grid.minor = ggplot2::element_blank(),\n    panel.grid.major.x = ggplot2::element_blank(),\n    plot.background  = ggplot2::element_rect(fill = \"#FAFAF8\", color = NA),\n    panel.background = ggplot2::element_rect(fill = \"#FAFAF8\", color = NA),\n    legend.position  = \"bottom\"\n  )\n\np_bm\n```\n\n::: {.cell-output-display}\n![](2025-04-15-base-r-penguins_files/figure-html/body-mass-plot-1.png){width=960}\n:::\n:::\n\n\n\n# Palette Log Update\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npalette_log_path <- here::here(\"posts\", \"palette-log.csv\")\npalette_log      <- read.csv(palette_log_path)\n\nnew_entry <- data.frame(\n  post_date = \"2025-04-15\",\n  palette   = \"Zissou1\",\n  package   = \"wesanderson\",\n  type      = \"discrete\"\n)\n\n# Only append if this post_date + palette combo isn't already logged\nif (!any(palette_log$post_date == new_entry$post_date &\n         palette_log$palette   == new_entry$palette)) {\n  write.table(\n    new_entry,\n    palette_log_path,\n    append = TRUE, sep = \",\", row.names = FALSE, col.names = FALSE\n  )\n  cat(\"Palette logged: wesanderson::Zissou1\\n\")\n} else {\n  cat(\"Palette already logged — skipping.\\n\")\n}\n```\n:::\n\n\n\n# Final thoughts and takeaways\n\nThe Palmer Penguins dataset is routinely analyzed through bill morphology — the famous length-vs-depth scatter is practically the \"Hello, World!\" of data visualization. But the raw dataset's isotope measurements offer a genuinely richer story, one that connects measurement to mechanism.\n\nThe δ¹³C signal is the most striking finding: **Gentoo penguins occupy a meaningfully different carbon niche** from their *Pygoscelis* relatives. Their less negative δ¹³C (≈ −25.5‰ vs. ≈ −26.5 to −27‰ for Adelie and Chinstrap) is consistent with field studies showing Gentoos are more flexible foragers, diving deeper and targeting fish alongside krill. This dietary breadth may partly explain why Gentoos have expanded their range more successfully under current climate-driven changes to Antarctic sea ice — when krill become patchier, fish remain available.\n\nAdelie and Chinstrap penguins sit in nearly overlapping isotopic space, reflecting their shared krill specialization. Their δ¹⁵N separation is subtle but real, suggesting minor differences in trophic level despite similar carbon sources.\n\nThe body mass data hammers the point home: Gentoos aren't just ecologically distinct — they're physically in a different league, topping out near 6,300 g while Adelie and Chinstrap overlap almost completely between 3,000–4,750 g. Sexual dimorphism (males heavier than females) is visible in all three species but most pronounced in Gentoos.\n\n**Caveats**: Isotope values reflect conditions at the time of feather or blood synthesis, and measurements in this dataset come from tissue samples collected at capture. Individual variation within species is substantial, and the 3-year window (2007–2009) may not capture longer-term dietary shifts. Still, the species-level signal is clear and statistically robust.\n\nOne final note: with `datasets::penguins` now in base R 4.5.0, this dataset has officially graduated from \"the tidyverse's iris replacement\" to part of the canonical R distribution. Future R learners will encounter these three species before they ever install a package — which means the penguin ecology behind the numbers is worth understanding in depth.\n",
    "supporting": [
      "2025-04-15-base-r-penguins_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}