{
  "hash": "972dfec5dd62e17e88193d47b0e0337e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: U.S. Judges and the historydata R Package\"\nauthor: \"Sean Thimons\"\ndate: \"2025-06-10\"\ndescription: \"Two centuries of federal judicial appointments — who made them, how many, and how the face of the federal bench has slowly transformed.\"\ncategories: [tidytuesday, R, history, law, demographics, politics]\n---\n\n\n\n# Preface\n\nFrom [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-06-10).\n\n> This week's dataset comes from the `{historydata}` R package (rOpenSci), which pulls from the [Federal Judicial Center's Biographical Directory of Article III Federal Judges](https://www.fjc.gov/history/judges/biographical-directory-article-iii-federal-judges-export). It covers every appointment to the U.S. federal bench since 1789 — District Courts, Courts of Appeals, the Supreme Court, former Circuit Courts, and special jurisdiction courts. Suggested questions: Which presidents appointed the most judges? How has the demographic makeup of the bench changed over time?\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  booster_pack <- c(\n    ### IO ----\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n\n    ### EDA ----\n    'skimr',\n\n    ### Plot ----\n    'paletteer',           # Color palette collection\n    'patchwork',           # Multi-panel layouts\n    'ggtext',              # Rich text in ggplot (element_markdown)\n    'ggrepel',             # Non-overlapping labels\n\n    ### Misc ----\n    'tidytuesdayR'\n  )\n\n  # ! Change load flag to load packages\n  install_booster_pack(package = booster_pack, load = TRUE)\n  rm(install_booster_pack, booster_pack)\n}\n\n# Custom Functions --------------------------------------------------------\n\n`%ni%` <- Negate(`%in%`)\n\ngeometric_mean <- function(x) {\n  exp(mean(log(x[x > 0]), na.rm = TRUE))\n}\n\nmy_skim <- skim_with(\n  numeric = sfl(\n    n = length,\n    min = ~ min(.x, na.rm = T),\n    p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n    med = ~ median(.x, na.rm = T),\n    p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n    max = ~ max(.x, na.rm = T),\n    mean = ~ mean(.x, na.rm = T),\n    geo_mean = ~ geometric_mean(.x),\n    sd = ~ stats::sd(., na.rm = TRUE),\n    hist = ~ inline_hist(., 5)\n  ),\n  append = FALSE\n)\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2025-06-10')\n\njudges_appointments <- raw$judges_appointments\njudges_people        <- raw$judges_people\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of `skimr::skim()` that returns count, min, p25, median, p75, max, mean, geometric mean, standard deviation, and an ASCII histogram.\n\n## judges_appointments\n\nDate strings (nomination, confirmation, commission, retirement, termination) and predecessor name fields are dropped for the skim — they're character columns encoding dates in MM/DD/YYYY format that need parsing, not summarizing raw.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\njudges_appointments %>%\n  select(\n    -judge_id,\n    -nomination_date,\n    -senate_confirmation_date,\n    -commission_date,\n    -retirement_from_active_service,\n    -termination_date,\n    -predecessor_last_name,\n    -predecessor_first_name\n  ) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |4202       |\n|Number of columns        |7          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |5          |\n|numeric                  |2          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable      | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:------------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|court_name         |         0|          1.00|  14| 108|     0|      169|          0|\n|court_type         |         0|          1.00|   4|  41|     0|       13|          0|\n|president_name     |         0|          1.00|  10|  21|     0|       44|          0|\n|president_party    |        39|          0.99|   4|  23|     0|        7|          0|\n|termination_reason |      1374|          0.67|   5|  40|     0|        8|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable     | n_missing| complete_rate|    n|  min|     p25|    med|     p75|  max|   mean| geo_mean|    sd|hist  |\n|:-----------------|---------:|-------------:|----:|----:|-------:|------:|-------:|----:|------:|--------:|-----:|:-----|\n|chief_judge_begin |      4200|             0| 4202| 1966| 1974.75| 1983.5| 1992.25| 2001| 1983.5|  1983.42| 24.75|▇▁▁▁▇ |\n|chief_judge_end   |      4200|             0| 4202| 1968| 1978.50| 1989.0| 1999.50| 2010| 1989.0|  1988.89| 29.70|▇▁▁▁▇ |\n\n\n:::\n:::\n\n\n\nThe appointments table covers 4202 records across every federal judicial seat since 1789. The `court_type` column is almost entirely clean, with two known truncated entries (`\"U. S. Court of Custo\"` and `\"U. S. Court of Inter\"`) noted in the dataset documentation. `chief_judge_begin` and `chief_judge_end` are populated for only a handful of records. `termination_reason` is NA for many appointments — these are judges still serving or records with unknown termination circumstances.\n\n## judges_people\n\nName fields and birth/death cities are dropped for the skim — they're free-text identifiers with no distributional interpretation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\njudges_people %>%\n  select(\n    -judge_id,\n    -name_first,\n    -name_middle,\n    -name_last,\n    -name_suffix,\n    -birthplace_city,\n    -death_city\n  ) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |3532       |\n|Number of columns        |6          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |4          |\n|numeric                  |2          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable    | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:----------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|birthplace_state |         3|          1.00|   2|  18|     0|       94|          0|\n|death_state      |      2099|          0.41|   2|  11|     0|       60|          0|\n|gender           |         0|          1.00|   1|   1|     0|        2|          0|\n|race             |         9|          1.00|   5|  20|     0|       11|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|    n|  min|  p25|  med|  p75|  max|    mean| geo_mean|    sd|hist  |\n|:-------------|---------:|-------------:|----:|----:|----:|----:|----:|----:|-------:|--------:|-----:|:-----|\n|birth_date    |         1|          1.00| 3532| 1732| 1886| 1923| 1944| 1975| 1908.01|  1907.37| 48.88|▁▁▂▆▇ |\n|death_date    |      1529|          0.57| 3532| 1790| 1927| 1968| 1995| 2014| 1954.41|  1953.73| 51.18|▁▁▂▅▇ |\n\n\n:::\n:::\n\n\n\nThe people table covers 3532 unique individuals. Birth years span from the late 1700s through the early 2000s. The `gender` and `race` columns are as reported by the judiciary — an important caveat, since these categories reflect institutional classification practices that have evolved over time and likely undercount early representation. The `birthplace_state` and `death_state` columns offer some geographic texture.\n\n# The Presidential Appointment Record\n\nThe power to shape the federal judiciary for decades is one of the most consequential — and least perishable — legacies a president leaves behind. Let's look at who appointed the most judges, and what the party breakdown looks like.\n\n## Data Preparation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join appointments with judge biographical info\njudges <- judges_appointments %>%\n  left_join(judges_people, by = \"judge_id\") %>%\n  mutate(\n    nom_date   = lubridate::mdy(nomination_date),\n    nom_year   = lubridate::year(nom_date),\n    nom_decade = floor(nom_year / 10) * 10\n  )\n\n# Verify exact gender category strings before any filtering\ncat(\"=== Gender categories (exact strings) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Gender categories (exact strings) ===\n```\n\n\n:::\n\n```{.r .cell-code}\njudges %>%\n  count(gender, sort = TRUE) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  gender     n\n  <chr>  <int>\n1 M       3777\n2 F        425\n```\n\n\n:::\n\n```{.r .cell-code}\n# Verify exact race category strings\ncat(\"\\n=== Race categories (exact strings) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Race categories (exact strings) ===\n```\n\n\n:::\n\n```{.r .cell-code}\njudges %>%\n  count(race, sort = TRUE) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 2\n   race                     n\n   <chr>                <int>\n 1 White                 3794\n 2 African American       223\n 3 Hispanic               128\n 4 Asian American          35\n 5 <NA>                     9\n 6 American Indian          5\n 7 African Am./Hispanic     2\n 8 Pac. Isl./Asian Am.      2\n 9 Hispanic/Asian Am.       1\n10 Hispanic/White           1\n11 Pac. Isl./White          1\n12 White/Asian Am.          1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Verify court types (check for truncated entries)\ncat(\"\\n=== Court types ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Court types ===\n```\n\n\n:::\n\n```{.r .cell-code}\njudges %>%\n  count(court_type, sort = TRUE) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 13 × 2\n   court_type                                    n\n   <chr>                                     <int>\n 1 USDC                                       3065\n 2 USCA                                        767\n 3 USSC                                        117\n 4 USCC (1869)                                  70\n 5 Court of Claims                              58\n 6 U. S. Customs Court                          36\n 7 U. S. Court of Customs and Patent Appeals    29\n 8 U. S. Court of International Trade           25\n 9 USCC (1801)                                  16\n10 USCC                                         12\n11 Other                                         5\n12 U. S. Court of Custo                          1\n13 U. S. Court of Inter                          1\n```\n\n\n:::\n:::\n\n\n\n## Top Appointing Presidents\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npres_counts <- judges %>%\n  filter(\n    !is.na(president_name),\n    president_name %ni% c(\"Assignment\", \"Reassignment\")\n  ) %>%\n  count(president_name, president_party, sort = TRUE) %>%\n  slice_head(n = 20) %>%\n  mutate(\n    president_name = fct_reorder(president_name, n),\n    party_group = case_when(\n      president_party == \"Republican\" ~ \"Republican\",\n      president_party == \"Democrat\"   ~ \"Democrat\",\n      TRUE                            ~ \"Other/Unaffiliated\"\n    )\n  )\n\ncat(sprintf(\"pres_counts: %d rows\\n\", nrow(pres_counts)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npres_counts: 20 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"pres_counts has 0 rows — check filter\" = nrow(pres_counts) > 0)\n\nparty_colors <- c(\n  \"Republican\"        = \"#C0392B\",\n  \"Democrat\"          = \"#2471A3\",\n  \"Other/Unaffiliated\" = \"#7F8C8D\"\n)\n\np_pres <- pres_counts %>%\n  ggplot(aes(x = n, y = president_name, fill = party_group)) +\n  geom_col(width = 0.7, alpha = 0.9) +\n  geom_text(\n    aes(label = n),\n    hjust = -0.2, size = 3.2, color = \"grey30\"\n  ) +\n  scale_fill_manual(values = party_colors) +\n  scale_x_continuous(expand = expansion(mult = c(0, 0.12))) +\n  labs(\n    title = \"Top 20 presidents by federal judicial appointments\",\n    subtitle = \"Article III appointments (District Courts, Courts of Appeals, Supreme Court, and more)\",\n    x = \"Number of appointments\",\n    y = NULL,\n    fill = \"President's party\",\n    caption = \"Source: historydata R package / Federal Judicial Center | TidyTuesday 2025-06-10\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title    = element_text(face = \"bold\", size = 14),\n    plot.subtitle = element_text(color = \"grey45\", size = 10),\n    legend.position = \"bottom\",\n    panel.grid.major.y = element_blank(),\n    panel.grid.minor   = element_blank(),\n    plot.caption = element_text(color = \"grey60\", size = 8)\n  )\n\np_pres\n```\n\n::: {.cell-output-display}\n![](2025-06-10-u-s-judges-and-the-historydata-r-package_files/figure-html/president-appointments-1.png){width=960}\n:::\n:::\n\n\n\nReagan and Clinton lead all modern presidents in total appointments — each clearing 380+ during their combined 8-year terms. Reagan's figure reflects not only longevity in office but a deliberate strategy to reshape the judiciary ideologically; Clinton matched him almost appointment-for-appointment. Carter's 267 appointments came in just one term, yet his administration's impact on judicial demographics far outweighs the raw count, as we'll see below. Congress periodically authorizes new judgeships to manage caseload growth, which is why high-volume decades cluster around specific legislative expansions (the 1978 Omnibus Judgeship Act, for example, added 152 seats at once).\n\n# The Changing Face of the Federal Bench\n\nThe story of the federal judiciary isn't just about quantity. For most of U.S. history, federal judges were overwhelmingly white men. That began to change slowly — then faster — over the second half of the 20th century.\n\n## Gender Diversification by Decade\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using verified gender strings from EDA above\nfemale_pct_by_decade <- judges %>%\n  filter(\n    !is.na(nom_year),\n    gender %in% c(\"M\", \"F\"),   # verified: actual values are \"M\" and \"F\"\n    nom_year >= 1900\n  ) %>%\n  group_by(nom_decade) %>%\n  summarise(\n    total    = n(),\n    n_female = sum(gender == \"F\"),\n    pct_female = n_female / total,\n    .groups = \"drop\"\n  )\n\ncat(sprintf(\"female_pct_by_decade: %d rows, %d cols\\n\",\n            nrow(female_pct_by_decade), ncol(female_pct_by_decade)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfemale_pct_by_decade: 12 rows, 4 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\n  \"female_pct_by_decade has 0 rows — check filters\" = nrow(female_pct_by_decade) > 0\n)\n\n# Sanity check: proportions should vary across decades\nif (length(unique(round(female_pct_by_decade$pct_female, 4))) == 1) {\n  warning(\"All pct_female values are identical — check grouping logic\")\n}\n\nfemale_pct_by_decade %>%\n  select(nom_decade, total, n_female, pct_female) %>%\n  mutate(pct_female = scales::percent(pct_female, accuracy = 0.1)) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 4\n   nom_decade total n_female pct_female\n        <dbl> <int>    <int> <chr>     \n 1       1900   126        0 0.0%      \n 2       1910   139        0 0.0%      \n 3       1920   171        1 0.6%      \n 4       1930   176        1 0.6%      \n 5       1940   182        0 0.0%      \n 6       1950   240        2 0.8%      \n 7       1960   362        4 1.1%      \n 8       1970   498       35 7.0%      \n 9       1980   460       46 10.0%     \n10       1990   527      137 26.0%     \n11       2000   386       94 24.4%     \n12       2010   249      103 41.4%     \n```\n\n\n:::\n:::\n\n\n\n## Race and Ethnicity Composition\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Inspect race categories\njudges %>%\n  count(race, sort = TRUE) %>%\n  filter(!is.na(race)) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 2\n   race                     n\n   <chr>                <int>\n 1 White                 3794\n 2 African American       223\n 3 Hispanic               128\n 4 Asian American          35\n 5 American Indian          5\n 6 African Am./Hispanic     2\n 7 Pac. Isl./Asian Am.      2\n 8 Hispanic/Asian Am.       1\n 9 Hispanic/White           1\n10 Pac. Isl./White          1\n11 White/Asian Am.          1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Group to broader categories for decade analysis (post-1960 for meaningful signal)\nrace_by_decade <- judges %>%\n  filter(\n    !is.na(nom_year),\n    !is.na(race),\n    nom_year >= 1960\n  ) %>%\n  mutate(\n    # Verified category strings from EDA: \"White\", \"African American\",\n    # \"Hispanic\", \"Asian American\", \"American Indian\", plus multi-race entries\n    race_group = case_when(\n      race == \"White\"                                         ~ \"White\",\n      str_detect(race, \"African Am\")                         ~ \"African American\",\n      str_detect(race, \"Hispanic\") & !str_detect(race, \"/\") ~ \"Hispanic\",\n      str_detect(race, \"Asian Am\")                           ~ \"Asian American\",\n      TRUE                                                   ~ \"Other/Multiple\"\n    )\n  ) %>%\n  group_by(nom_decade, race_group) %>%\n  summarise(n = n(), .groups = \"drop\") %>%\n  group_by(nom_decade) %>%\n  mutate(\n    total = sum(n),\n    pct   = n / total\n  ) %>%\n  ungroup()\n\ncat(sprintf(\"race_by_decade: %d rows\\n\", nrow(race_by_decade)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrace_by_decade: 26 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"race_by_decade has 0 rows\" = nrow(race_by_decade) > 0)\n\n# Sanity check\nif (length(unique(round(race_by_decade$pct, 4))) == 1) {\n  warning(\"All pct values identical — check grouping\")\n}\n```\n:::\n\n\n\n# Hero Visualization\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract palette colors for single-series area chart\nhero_pal <- paletteer::paletteer_d(\"dutchmasters::milkmaid\")\nfill_col  <- hero_pal[4]   # deep blue — primary fill\nline_col  <- hero_pal[5]   # darker tone for line/points\nannot_col <- \"grey35\"\n\n# Annotation data for key administrations\nannotations <- tibble::tribble(\n  ~x,    ~y,    ~label,                              ~hjust,\n  1975,  0.22,  \"Carter (1977–81)\\nlowest % white,\\nhighest % women\\nto that point\", 1,\n  2008,  0.38,  \"Obama (2009–17)\\n42% of appointments\\nwere women\",                   0\n)\n\np_hero <- female_pct_by_decade %>%\n  ggplot(aes(x = nom_decade, y = pct_female)) +\n  # Shaded area under the curve\n  geom_area(fill = fill_col, alpha = 0.55) +\n  # Reference line at 50%\n  geom_hline(\n    yintercept = 0.5,\n    linetype = \"dashed\",\n    color = \"grey60\",\n    linewidth = 0.5\n  ) +\n  annotate(\n    \"text\", x = 1902, y = 0.515,\n    label = \"50% parity line\",\n    size = 3, hjust = 0, color = \"grey55\"\n  ) +\n  # Trend line\n  geom_line(color = line_col, linewidth = 1.4) +\n  # Points sized by appointment volume\n  geom_point(\n    aes(size = total),\n    color = line_col,\n    alpha = 0.85\n  ) +\n  # Carter annotation\n  annotate(\n    \"segment\",\n    x = 1975, xend = 1977, y = 0.19, yend = 0.133,\n    arrow = arrow(length = unit(0.2, \"cm\"), type = \"closed\"),\n    color = annot_col, linewidth = 0.5\n  ) +\n  annotate(\n    \"text\",\n    x = 1974, y = 0.205,\n    label = \"Carter (1977–81):\\nfirst major push\\nfor bench diversity\",\n    size = 3, hjust = 1, color = annot_col, lineheight = 1.2\n  ) +\n  # Obama annotation\n  annotate(\n    \"segment\",\n    x = 2012, xend = 2010, y = 0.43, yend = 0.405,\n    arrow = arrow(length = unit(0.2, \"cm\"), type = \"closed\"),\n    color = annot_col, linewidth = 0.5\n  ) +\n  annotate(\n    \"text\",\n    x = 2013, y = 0.44,\n    label = \"Obama (2009–17):\\n~41% of appointments\\nwere women\",\n    size = 3, hjust = 0, color = annot_col, lineheight = 1.2\n  ) +\n  scale_x_continuous(\n    breaks = seq(1900, 2020, by = 10),\n    labels = function(x) paste0(x, \"s\")\n  ) +\n  scale_y_continuous(\n    labels = scales::percent_format(accuracy = 1),\n    limits = c(0, 0.55),\n    breaks = seq(0, 0.5, 0.1)\n  ) +\n  scale_size_continuous(\n    range  = c(2, 9),\n    name   = \"Total appointments\\nin decade\",\n    breaks = c(100, 300, 500, 800)\n  ) +\n  labs(\n    title    = \"**The long road to a more diverse federal bench**\",\n    subtitle = \"Share of U.S. federal judicial appointments going to women, by decade (1900s–2020s).<br>\n    Point size reflects total appointment volume. Prior to the 1970s, women were virtually absent from the federal judiciary.\",\n    x        = NULL,\n    y        = \"Share of appointments (female)\",\n    caption  = \"Source: historydata R package / Federal Judicial Center | TidyTuesday 2025-06-10\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(\n    plot.title         = element_markdown(face = \"bold\", size = 17, margin = margin(b = 6)),\n    plot.subtitle      = element_markdown(color = \"grey40\", size = 11, lineheight = 1.3,\n                                          margin = margin(b = 12)),\n    plot.caption       = element_text(color = \"grey60\", size = 8.5, hjust = 0),\n    panel.grid.minor   = element_blank(),\n    panel.grid.major.x = element_blank(),\n    legend.position    = \"right\",\n    legend.title       = element_text(size = 9),\n    axis.text.x        = element_text(size = 10),\n    plot.margin        = margin(t = 10, r = 20, b = 10, l = 10)\n  )\n\np_hero\n```\n\n::: {.cell-output-display}\n![](2025-06-10-u-s-judges-and-the-historydata-r-package_files/figure-html/hero-viz-1.png){width=1152}\n:::\n:::\n\n\n\n## Supplementary: Racial Composition of Appointments (1960s–Present)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrace_pal <- paletteer::paletteer_d(\"dutchmasters::milkmaid\", n = 5)\n\nrace_plot_data <- race_by_decade %>%\n  filter(nom_decade >= 1960) %>%\n  mutate(\n    race_group = factor(\n      race_group,\n      levels = c(\"White\", \"African American\",\n                 \"Hispanic\", \"Asian American\", \"Other/Multiple\")\n    ),\n    nom_decade_label = paste0(nom_decade, \"s\")\n  )\n\ncat(sprintf(\"race_plot_data: %d rows\\n\", nrow(race_plot_data)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrace_plot_data: 26 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"race_plot_data empty\" = nrow(race_plot_data) > 0)\n\np_race <- race_plot_data %>%\n  ggplot(aes(x = nom_decade_label, y = pct, fill = race_group)) +\n  geom_col(position = \"stack\", width = 0.72) +\n  scale_fill_manual(\n    values = setNames(\n        as.character(race_pal),\n        c(\"White\", \"African American\", \"Hispanic\", \"Asian American\", \"Other/Multiple\")\n      )\n  ) +\n  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +\n  labs(\n    title    = \"Racial composition of federal judicial appointments, 1960s–2020s\",\n    subtitle = \"Share of appointments by reported race/ethnicity per decade\",\n    x        = NULL,\n    y        = \"Share of appointments\",\n    fill     = \"Race / ethnicity\",\n    caption  = \"Source: historydata R package / Federal Judicial Center | TidyTuesday 2025-06-10\\nNote: race categories as reported by the Federal Judicial Center; classification practices have evolved over time.\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title       = element_text(face = \"bold\", size = 14),\n    plot.subtitle    = element_text(color = \"grey45\", size = 10),\n    plot.caption     = element_text(color = \"grey60\", size = 8, hjust = 0),\n    panel.grid.major.x = element_blank(),\n    panel.grid.minor   = element_blank(),\n    legend.position  = \"right\"\n  )\n\np_race\n```\n\n::: {.cell-output-display}\n![](2025-06-10-u-s-judges-and-the-historydata-r-package_files/figure-html/race-viz-1.png){width=1056}\n:::\n:::\n\n\n\n# Final thoughts and takeaways\n\nThe federal bench has changed dramatically — but slowly. For roughly the first 180 years of the republic, the judiciary was the exclusive domain of white men. The data shows near-zero female representation through the 1960s. **The inflection point is the Carter administration (1977–81):** Carter made a deliberate, structured effort to diversify the bench, appointing women and minority judges at rates that had no historical precedent. Every subsequent president has maintained or extended that trajectory to varying degrees.\n\nBy the Obama era, women made up roughly 41% of judicial appointments — a figure that would have been unimaginable a generation earlier. The 2020s data, still accumulating, appears on track to push that share higher.\n\n::: {.callout-note}\n**Methodological caveat:** The `gender` and `race` fields reflect how the Federal Judicial Center classified judges, not self-identification. Early records in particular may be incomplete or inconsistently coded. The dramatic increase in non-white appointments post-1960 partly reflects better record-keeping as much as actual change — though the demographic shift in appointments since Carter is real and well-documented independently.\n:::\n\nThe race/ethnicity panel tells a complementary story: the white share of appointments has declined from near-100% to roughly 60–70% in recent decades, with Black and Hispanic judges making up a growing share. The trajectory is clear, even if parity remains distant.\n\nWhat the data can't capture is the compounding effect: federal judges serve for life. Every diverse appointment is a multi-decade presence on the bench. Carter's 1977–81 cohort was still issuing rulings into the 2010s. This is why presidential judicial legacies matter so much — they don't fade at the end of a term.\n\n\n\n::: {.cell}\n\n:::\n",
    "supporting": [
      "2025-06-10-u-s-judges-and-the-historydata-r-package_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}