{
  "hash": "db2146ad3a749eff71e7a840e50806d1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Racial and Ethnic Disparities in Reproductive Medicine Research\"\nauthor: \"Sean Thimons\"\ndate: \"2025-02-25\"\ndescription: \"Examining 13 years of academic literature on reproductive health disparities — who gets studied, which conditions receive focus, and how research framing has evolved\"\ncategories: [tidytuesday, R, health-equity, reproductive-health, text-analysis]\n---\n\n# Preface\n\nFrom [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/master/data/2025/2025-02-25).\n\n> This dataset examines academic literature on racial and ethnic disparities in reproductive medicine published in eight high-impact obstetrics/gynecology journals from January 2010 through June 2023. The data were compiled for a narrative review article published in the American Journal of Obstetrics and Gynecology in January 2025.\n>\n> The underlying inquiry addresses how \"race and ethnicity should be used in medical research\" and examines whether these concepts are treated as biological entities, social constructs, or proxies for systemic racism.\n>\n> Suggested analytical directions include examining how racial and ethnic categories are framed across studies, identifying which demographic groups receive research focus, assessing temporal patterns in research sentiment, and mapping which health conditions have been studied versus gaps in the literature.\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  if (file.exists('packages.txt')) {\n    packages <- read.table('packages.txt')\n\n    install_booster_pack(package = packages$Package, load = FALSE)\n\n    rm(packages)\n  } else {\n    ## Packages ----\n\n    booster_pack <- c(\n      ### IO ----\n      'fs',\n      'here',\n      'janitor',\n      'rio',\n      'tidyverse',\n\n      ### EDA ----\n      'skimr',\n\n      ### Plot ----\n      # !! DO NOT USE camcorder — it intercepts plot output and prevents Quarto from rendering plots !!\n      # 'camcorder',\n      'patchwork',         # Multi-panel layouts\n      'ggtext',            # Rich text in ggplot\n      'ggrepel',           # Non-overlapping labels\n\n      ### Text ----\n      'tidytext',          # Text mining\n\n      ### Misc ----\n      'tidytuesdayR'\n    )\n\n    # ! Change load flag to load packages\n    install_booster_pack(package = booster_pack, load = TRUE)\n    rm(install_booster_pack, booster_pack)\n  }\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n# Load raw data from package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2025-02-25')\n\narticles <- raw$article_dat %>% clean_names()\nmodels <- raw$model_dat %>% clean_names()\n```\n:::\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## Article-level data\n\n\n::: {.cell}\n\n```{.r .cell-code}\narticles %>%\n  select(-c(pmid, doi, jabbrv, abstract, keywords, study_aim, data_source)) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |318        |\n|Number of columns        |58         |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |20         |\n|logical                  |4          |\n|numeric                  |34         |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable  | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:--------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|journal        |         0|          1.00|  20|  61|     0|        6|          0|\n|month          |         0|          1.00|   2|   2|     0|       12|          0|\n|day            |         0|          1.00|   2|   2|     0|       31|          0|\n|title          |         0|          1.00|  36| 201|     0|      318|          0|\n|study_location |         5|          0.98|   2| 197|     0|       55|          0|\n|study_type     |         3|          0.99|   3|  20|     0|        9|          0|\n|race1          |         4|          0.99|   5|  81|     0|       55|          0|\n|race2          |         7|          0.98|   5|  57|     0|       68|          0|\n|race3          |        96|          0.70|   5|  43|     0|       63|          0|\n|race4          |       139|          0.56|   5|  55|     0|       62|          0|\n|race5          |       206|          0.35|   5|  64|     0|       51|          0|\n|race6          |       270|          0.15|   5|  41|     0|       29|          0|\n|race7          |       296|          0.07|   5|  33|     0|       14|          0|\n|race8          |       312|          0.02|   5|  33|     0|        5|          0|\n|eth1           |       294|          0.08|   8|  22|     0|       12|          0|\n|eth2           |       295|          0.07|   8|  24|     0|       13|          0|\n|eth3           |       308|          0.03|   7|  33|     0|        7|          0|\n|eth4           |       317|          0.00|   6|   6|     0|        1|          0|\n|eth5           |       317|          0.00|   8|   8|     0|        1|          0|\n|eth6           |       317|          0.00|  27|  27|     0|        1|          0|\n\n\n**Variable type: logical**\n\n|skim_variable | n_missing| complete_rate| mean|count |\n|:-------------|---------:|-------------:|----:|:-----|\n|eth7          |       318|             0|  NaN|:     |\n|eth7_ss       |       318|             0|  NaN|:     |\n|eth8          |       318|             0|  NaN|:     |\n|eth8_ss       |       318|             0|  NaN|:     |\n\n\n**Variable type: numeric**\n\n|skim_variable      | n_missing| complete_rate|   n|  min|     p25|    med|      p75|      max|      mean| geo_mean|         sd|hist  |\n|:------------------|---------:|-------------:|---:|----:|-------:|------:|--------:|--------:|---------:|--------:|----------:|:-----|\n|year               |         0|          1.00| 318| 2010| 2015.00| 2018.0|  2021.00|     2023|   2017.92|  2017.91|       3.78|▃▃▃▅▇ |\n|study_year_start   |         5|          0.98| 318|  -99| 2000.00| 2006.0|  2012.00|     2021|   1918.30|  2005.69|     420.71|▁▁▁▁▇ |\n|study_year_end     |         5|          0.98| 318|  -99| 2009.00| 2014.0|  2016.00|     2022|   1932.29|  2013.27|     406.26|▁▁▁▁▇ |\n|race1_ss           |         8|          0.97| 318|  -99|  183.25| 2777.0| 23966.25| 22689016| 306851.17|  3818.72| 1768355.19|▇▁▁▁▁ |\n|race2_ss           |        11|          0.97| 318|  -99|  102.00|  627.0|  5108.50|  8683174| 111596.45|  1316.42|  667322.95|▇▁▁▁▁ |\n|race3_ss           |        99|          0.69| 318|  -99|   84.50|  966.0|  3818.00|  9741891| 117760.50|  1303.36|  734623.63|▇▁▁▁▁ |\n|race4_ss           |       142|          0.55| 318|  -99|   78.50|  505.5|  3568.50|  5187397|  96175.91|   821.54|  537694.74|▇▁▁▁▁ |\n|race5_ss           |       209|          0.34| 318|  -99|   41.00|  320.0|  3298.00| 17840962| 554194.46|   732.59| 2653264.01|▇▁▁▁▁ |\n|race6_ss           |       272|          0.14| 318|  -99|   24.25|  421.5| 12428.25|   537895|  28327.30|   615.46|   92846.77|▇▁▁▁▁ |\n|race7_ss           |       296|          0.07| 318|  -99|  275.75| 2650.0| 11909.00|  2043099| 119354.50|  2867.86|  437343.82|▇▁▁▁▁ |\n|race8_ss           |       312|          0.02| 318|   21|  327.75| 1262.5|  3829.25|  1129350| 189432.83|  1444.17|  460466.60|▇▁▁▁▂ |\n|eth1_ss            |       294|          0.08| 318|  -99|   42.00|  343.5|  2998.25|   736987|  33359.12|   713.31|  149970.56|▇▁▁▁▁ |\n|eth2_ss            |       295|          0.07| 318|  -99|   36.50|  394.0|  1091.00|   152942|  10392.78|   594.00|   32989.16|▇▁▁▁▁ |\n|eth3_ss            |       308|          0.03| 318|    2|   37.75|  507.5|  4178.50|    22338|   4035.90|   336.18|    7070.07|▇▁▁▁▁ |\n|eth4_ss            |       317|          0.00| 318|  276|  276.00|  276.0|   276.00|      276|    276.00|   276.00|         NA|▁▁▇▁▁ |\n|eth5_ss            |       317|          0.00| 318|  656|  656.00|  656.0|   656.00|      656|    656.00|   656.00|         NA|▁▁▇▁▁ |\n|eth6_ss            |       317|          0.00| 318|  284|  284.00|  284.0|   284.00|      284|    284.00|   284.00|         NA|▁▁▇▁▁ |\n|access_to_care     |         4|          0.99| 318|    0|    0.00|    0.0|     1.00|        1|      0.38|     1.00|       0.49|▇▁▁▁▅ |\n|treatment_received |         4|          0.99| 318|    0|    0.00|    1.0|     1.00|        1|      0.59|     1.00|       0.49|▆▁▁▁▇ |\n|health_outcome     |         4|          0.99| 318|    0|    1.00|    1.0|     1.00|        1|      0.76|     1.00|       0.43|▂▁▁▁▇ |\n|cancer_ovarian     |         6|          0.98| 318|    0|    0.00|    0.0|     0.00|        1|      0.16|     1.00|       0.37|▇▁▁▁▂ |\n|cancer_uterine     |         6|          0.98| 318|    0|    0.00|    0.0|     0.00|        1|      0.22|     1.00|       0.42|▇▁▁▁▂ |\n|cancer_cervical    |         6|          0.98| 318|    0|    0.00|    0.0|     0.00|        1|      0.09|     1.00|       0.29|▇▁▁▁▁ |\n|cancer_vulvar      |         6|          0.98| 318|    0|    0.00|    0.0|     0.00|        1|      0.03|     1.00|       0.18|▇▁▁▁▁ |\n|other_gyn_onc      |         6|          0.98| 318|    0|    0.00|    0.0|     0.00|        1|      0.01|     1.00|       0.11|▇▁▁▁▁ |\n|endo               |         6|          0.98| 318|    0|    0.00|    0.0|     0.00|        1|      0.01|     1.00|       0.08|▇▁▁▁▁ |\n|fibroids           |         6|          0.98| 318|    0|    0.00|    0.0|     0.00|        1|      0.03|     1.00|       0.16|▇▁▁▁▁ |\n|other_gyn_surg     |         6|          0.98| 318|    0|    0.00|    0.0|     0.00|        1|      0.12|     1.00|       0.32|▇▁▁▁▁ |\n|fert               |         6|          0.98| 318|    0|    0.00|    0.0|     0.00|        1|      0.10|     1.00|       0.30|▇▁▁▁▁ |\n|matmorbmort        |         6|          0.98| 318|    0|    0.00|    0.0|     1.00|        1|      0.30|     1.00|       0.46|▇▁▁▁▃ |\n|other_preg         |         6|          0.98| 318|    0|    0.00|    0.0|     0.00|        1|      0.04|     1.00|       0.21|▇▁▁▁▁ |\n|phys_div           |         6|          0.98| 318|    0|    0.00|    0.0|     0.00|        1|      0.00|     1.00|       0.06|▇▁▁▁▁ |\n|other              |         6|          0.98| 318|    0|    0.00|    0.0|     0.00|        1|      0.07|     1.00|       0.26|▇▁▁▁▁ |\n|covid              |         6|          0.98| 318|    0|    0.00|    0.0|     0.00|        1|      0.03|     1.00|       0.17|▇▁▁▁▁ |\n\n\n:::\n:::\n\n\nThe article dataset contains 318 studies spanning 2010-2023. Key observations:\n\n- **Publication trends**: The median study year is 2018, with studies examining data from as early as 1991 (minimum `study_year_start`) through 2019 (maximum `study_year_end`).\n- **Racial categories**: The dataset uses up to 8 racial categories per study, though most studies focus on 2-4 groups. The primary racial categories (`race1`, `race2`, etc.) have highly variable sample sizes — some studies include tens of thousands of participants (max `race1_ss` = 78,184) while others have small samples (median ~100-200).\n- **Health outcomes**: Binary flags indicate study focus areas: gynecologic cancers (ovarian, uterine, cervical, vulvar), maternal morbidity/mortality, fertility, fibroids, and general gynecologic surgery. Most studies focus on a single condition.\n- **Outcome domains**: Three binary variables track whether the study examined `access_to_care`, `treatment_received`, or `health_outcome`. About 75-80% of studies examine health outcomes directly.\n\n::: {.callout-important}\n## Missing data patterns\n\nThe ethnicity variables (`eth1` through `eth8`) are almost entirely `NA`, suggesting that most studies either didn't collect ethnicity data separately from race, or the coding scheme combined them. The racial sample size variables (`race1_ss`, `race2_ss`, etc.) show heavy missingness for categories 5-8, confirming that most studies compare 2-4 racial groups.\n:::\n\n## Model-level data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodels %>%\n  select(-c(doi, stratgrp, subgrp, outcome, measure_comments, covariates, ref)) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |6804       |\n|Number of columns        |9          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |4          |\n|numeric                  |5          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|stratified    |         1|          1.00|   2|   3|     0|        2|          0|\n|subanalysis   |        82|          0.99|   2|   3|     0|        2|          0|\n|measure       |         1|          1.00|   1| 152|     0|       83|          0|\n|compare       |        26|          1.00|   2|  94|     0|      426|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|    n|      min|    p25|  med|   p75|     max|    mean| geo_mean|       sd|hist  |\n|:-------------|---------:|-------------:|----:|--------:|------:|----:|-----:|-------:|-------:|--------:|--------:|:-----|\n|model_number  |         0|          1.00| 6804|     1.00|   3.00| 5.00| 17.00|     148|   14.12|     6.45|    20.86|▇▁▁▁▁ |\n|comparison    |         0|          1.00| 6804|     1.00|   1.00| 2.00|  3.00|       8|    2.13|     1.79|     1.33|▇▂▂▁▁ |\n|point         |        36|          0.99| 6804| -6639.58|   0.94| 1.41| 10.00| 6239314| 1219.46|     3.25| 76201.09|▇▁▁▁▁ |\n|lower         |       235|          0.97| 6804| -6496.00| -99.00| 0.69|  1.10|   91767|   -2.26|     1.22|  1314.91|▇▁▁▁▁ |\n|upper         |       237|          0.97| 6804| -3161.00| -99.00| 1.14|  1.98|   94979|    1.73|     2.37|  1374.19|▇▁▁▁▁ |\n\n\n:::\n:::\n\n\nThe model dataset contains 6,804 individual statistical comparisons extracted from the 318 articles. Key observations:\n\n- **Model structure**: Each article contributes multiple models (median `model_number` = 3). Most models are stratified analyses (`stratified = \"Yes\"` dominates).\n- **Comparison structure**: The `compare` field captures which racial/ethnic group is being analyzed. The `point` estimate shows the effect size or percentage, with `lower` and `upper` bounds for confidence intervals — though notably, many entries have `-99` placeholders indicating missing CI data.\n- **Effect sizes**: Point estimates range from 0 to 100+ (likely percentages, odds ratios, and other measures depending on the `measure` type). The wide range and high standard deviation suggest heterogeneous outcome types.\n\n# Temporal evolution and representation patterns\n\nTo understand how reproductive health disparities research has evolved, I'll examine two key dimensions:\n\n1. **Research volume over time** — Has interest in disparities research grown?\n2. **Racial category representation** — Which groups dominate study samples?\n\n## Research trends by health condition\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reshape articles to long format for health conditions\ncondition_trends <- articles %>%\n  select(year, cancer_ovarian, cancer_uterine, cancer_cervical, cancer_vulvar,\n         other_gyn_onc, endo, fibroids, other_gyn_surg, fert, matmorbmort,\n         other_preg, phys_div, other, covid) %>%\n  pivot_longer(cols = -year, names_to = \"condition\", values_to = \"flag\") %>%\n  filter(flag == 1) %>%\n  count(year, condition) %>%\n  mutate(condition_label = case_when(\n    condition == \"cancer_ovarian\" ~ \"Ovarian cancer\",\n    condition == \"cancer_uterine\" ~ \"Uterine cancer\",\n    condition == \"cancer_cervical\" ~ \"Cervical cancer\",\n    condition == \"cancer_vulvar\" ~ \"Vulvar cancer\",\n    condition == \"other_gyn_onc\" ~ \"Other gynecologic oncology\",\n    condition == \"endo\" ~ \"Endometriosis\",\n    condition == \"fibroids\" ~ \"Fibroids\",\n    condition == \"other_gyn_surg\" ~ \"Other gynecologic surgery\",\n    condition == \"fert\" ~ \"Fertility\",\n    condition == \"matmorbmort\" ~ \"Maternal morbidity/mortality\",\n    condition == \"other_preg\" ~ \"Other pregnancy outcomes\",\n    condition == \"phys_div\" ~ \"Physician diversity\",\n    condition == \"other\" ~ \"Other\",\n    condition == \"covid\" ~ \"COVID-19\"\n  ))\n\n# Identify top conditions for visualization\ntop_conditions <- condition_trends %>%\n  group_by(condition_label) %>%\n  summarize(total = sum(n)) %>%\n  arrange(desc(total)) %>%\n  head(6) %>%\n  pull(condition_label)\n\ncondition_trends_filtered <- condition_trends %>%\n  filter(condition_label %in% top_conditions)\n```\n:::\n\n\n## Racial representation in study samples\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregate racial categories across all studies\nracial_representation <- articles %>%\n  select(starts_with(\"race\") & !contains(\"_ss\")) %>%\n  pivot_longer(cols = everything(), names_to = \"race_slot\", values_to = \"race_category\") %>%\n  filter(!is.na(race_category)) %>%\n  count(race_category) %>%\n  arrange(desc(n)) %>%\n  mutate(\n    race_category_clean = str_to_title(race_category),\n    pct = n / sum(n)\n  )\n\n# Get sample size aggregates for each category\n# First, create a cleaner structure by manually building category-sample pairs\nsample_size_by_race <- bind_rows(\n  articles %>% select(race1, race1_ss) %>% rename(category = race1, sample = race1_ss),\n  articles %>% select(race2, race2_ss) %>% rename(category = race2, sample = race2_ss),\n  articles %>% select(race3, race3_ss) %>% rename(category = race3, sample = race3_ss),\n  articles %>% select(race4, race4_ss) %>% rename(category = race4, sample = race4_ss),\n  articles %>% select(race5, race5_ss) %>% rename(category = race5, sample = race5_ss),\n  articles %>% select(race6, race6_ss) %>% rename(category = race6, sample = race6_ss)\n) %>%\n  filter(!is.na(category), category != \"\", !is.na(sample)) %>%\n  group_by(category) %>%\n  summarize(\n    total_sample = sum(sample, na.rm = TRUE),\n    studies = n()\n  ) %>%\n  arrange(desc(total_sample))\n```\n:::\n\n\n## Outcome focus analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Examine which outcome domains are studied\noutcome_focus <- articles %>%\n  select(year, access_to_care, treatment_received, health_outcome) %>%\n  pivot_longer(cols = -year, names_to = \"outcome_domain\", values_to = \"flag\") %>%\n  filter(flag == 1) %>%\n  count(year, outcome_domain) %>%\n  mutate(outcome_label = case_when(\n    outcome_domain == \"access_to_care\" ~ \"Access to care\",\n    outcome_domain == \"treatment_received\" ~ \"Treatment patterns\",\n    outcome_domain == \"health_outcome\" ~ \"Health outcomes\"\n  ))\n```\n:::\n\n\n# Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define clinical color palette\nclinical_palette <- c(\n  \"#2E5090\", # Deep medical blue\n  \"#8B2635\", # Maroon (blood/tissue)\n  \"#4A7C59\", # Sage green (scrubs)\n  \"#B8860B\", # Dark goldenrod\n  \"#6B4C9A\", # Purple\n  \"#C65D3B\"  # Terracotta\n)\n\n# Panel A: Research volume over time by top conditions\np1 <- condition_trends_filtered %>%\n  ggplot(aes(x = year, y = n, fill = condition_label)) +\n  geom_col(position = \"stack\", alpha = 0.9) +\n  scale_fill_manual(values = clinical_palette) +\n  scale_x_continuous(breaks = seq(2010, 2023, 2)) +\n  labs(\n    title = \"Research volume peaked in 2019-2020\",\n    subtitle = \"Publications on racial/ethnic disparities by health condition\",\n    x = NULL,\n    y = \"Number of studies\",\n    fill = \"Health condition\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14),\n    plot.subtitle = element_text(color = \"gray30\"),\n    legend.position = \"right\",\n    panel.grid.minor = element_blank(),\n    panel.grid.major.x = element_blank()\n  )\n\n# Panel B: Racial category frequency\np2 <- racial_representation %>%\n  head(10) %>%\n  ggplot(aes(x = reorder(race_category_clean, n), y = n)) +\n  geom_col(fill = clinical_palette[1], alpha = 0.8) +\n  geom_text(aes(label = scales::comma(n)), hjust = -0.2, size = 3.5) +\n  coord_flip() +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +\n  labs(\n    title = \"White and Black populations dominate study cohorts\",\n    subtitle = \"Frequency of racial categories across 318 studies\",\n    x = NULL,\n    y = \"Number of studies including this category\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14),\n    plot.subtitle = element_text(color = \"gray30\"),\n    panel.grid.major.y = element_blank(),\n    panel.grid.minor = element_blank()\n  )\n\n# Panel C: Outcome domain trends\np3 <- outcome_focus %>%\n  ggplot(aes(x = year, y = n, color = outcome_label)) +\n  geom_line(linewidth = 1.2, alpha = 0.9) +\n  geom_point(size = 2.5) +\n  scale_color_manual(values = clinical_palette[c(1, 2, 3)]) +\n  scale_x_continuous(breaks = seq(2010, 2023, 2)) +\n  labs(\n    title = \"Health outcomes remain the dominant focus\",\n    subtitle = \"Research domains examined over time\",\n    x = \"Year\",\n    y = \"Number of studies\",\n    color = \"Outcome domain\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14),\n    plot.subtitle = element_text(color = \"gray30\"),\n    legend.position = \"right\",\n    panel.grid.minor = element_blank()\n  )\n\n# Combine panels\np_final <- (p1 / p2 / p3) +\n  plot_annotation(\n    title = \"The Landscape of Reproductive Health Disparities Research\",\n    subtitle = \"Academic literature from eight high-impact OB/GYN journals (2010-2023)\",\n    caption = \"Data: TidyTuesday 2025-02-25 | Analysis: Sean Thimons\",\n    theme = theme(\n      plot.title = element_text(size = 18, face = \"bold\", margin = margin(b = 5)),\n      plot.subtitle = element_text(size = 13, color = \"gray30\", margin = margin(b = 15)),\n      plot.caption = element_text(size = 9, color = \"gray50\", hjust = 0)\n    )\n  )\n\nprint(p_final)\n```\n\n::: {.cell-output-display}\n![](2025-02-25_files/figure-html/viz-disparity-landscape-1.png){width=1152}\n:::\n:::\n\n\n# Final thoughts and takeaways\n\nThis analysis of 318 studies published between 2010-2023 reveals several critical patterns in how reproductive health disparities are researched:\n\n**Research momentum has stalled.** After peaking around 2019-2020, the volume of disparities research appears to have declined. This plateau is concerning given the persistent and well-documented inequities in maternal mortality, cancer survival, and access to reproductive care — particularly for Black and Indigenous populations.\n\n**Representation is concentrated.** White and Black populations dominate study cohorts, appearing in nearly every analysis. While this reflects the urgent need to understand and address Black-White disparities in maternal and reproductive health, it also means that other groups — Asian subpopulations, Native American/Alaska Native communities, and Pacific Islander populations — remain severely understudied. The \"Other\" and \"Unknown\" categories appearing in the top 10 further suggest that many studies fail to disaggregate demographic data meaningfully.\n\n**Cancer and maternal health drive the agenda.** Gynecologic oncology (especially ovarian and uterine cancer) and maternal morbidity/mortality make up the bulk of disparities research. While these are critical areas where racial inequities are stark and well-documented, other reproductive health conditions — endometriosis, fibroids, fertility — receive far less attention despite evidence of disparate access and outcomes.\n\n**Health outcomes, not systems.** The majority of studies focus on health outcomes rather than upstream factors like access to care or treatment patterns. This emphasis on endpoints rather than pathways may limit the actionable insights needed to dismantle structural barriers.\n\nThe dataset also raises methodological questions: How are race and ethnicity being used in these analyses? Are they treated as proxies for lived experience of racism and structural inequity, or as immutable biological categories? The narrative review that produced this dataset argues for the former — yet without examining study language and framing directly, we can't assess whether the field is shifting toward this more nuanced approach.\n\n**What's missing matters.** The gaps in this literature — underrepresented populations, understudied conditions, limited focus on systemic barriers — shape what we know and, more importantly, what we don't know about reproductive health equity. Future research must broaden its scope, disaggregate demographic data more carefully, and interrogate the mechanisms (not just the outcomes) of disparity.\n",
    "supporting": [
      "2025-02-25_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}