{
  "hash": "3c9b9a28f5c96163f2a7d8a23c074de1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Twinned Cities\"\nauthor: \"Sean Thimons\"\ndate: \"2026-05-12\"\ndescription: \"Mapping the global network of sister cities — who pairs with whom, which hubs anchor the web, and how the bonds cross continents.\"\ncategories:\n  - tidytuesday\n  - R\n  - networks\n  - geography\n  - maps\n---\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](2026-05-12-twinned-cities_files/figure-html/pseudo-hero-palette-1.png){width=100%}\n:::\n:::\n\n\n# Preface\n\nFrom the [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2026/2026-05-12).\n\n> Sister cities (also called twin towns or twinned cities) are pairs of municipalities, often in different countries, that formalize a long-term partnership built around cultural exchange, trade, post-war reconciliation, or simple municipal goodwill. The practice exploded in the late 20th century — sometimes politically motivated, sometimes purely sentimental — and produced a sprawling global graph: each node is a city, each edge is a handshake that never quite ends. This week's data, sourced from Wikidata, gives us 5,470 cities and 10,596 directed twinning links spanning every inhabited continent.\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\"pak\", repos = \"https://cloud.r-project.org\")\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  core_packages <- c(\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n    'skimr',\n    'paletteer',\n    'tidytuesdayR'\n  )\n\n  optional_packages <- c(\n    'ggrepel',\n    'ggtext',\n    'patchwork',\n    'maps',\n    'scales'\n  )\n\n  install_booster_pack(package = unique(c(core_packages, optional_packages)), load = TRUE)\n  rm(install_booster_pack, core_packages, optional_packages)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n# Load raw data from package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2026-05-12')\n\ncities <- raw$cities\nlinks  <- raw$links\n```\n:::\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## Cities\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncities %>%\n  select(-id) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |5470       |\n|Number of columns        |6          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |4          |\n|numeric                  |2          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|name          |         0|             1|   2|  44|     0|     5349|          0|\n|country       |         0|             1|   4|  24|     0|      191|          0|\n|countrycd     |         7|             1|   2|   5|     0|      190|          0|\n|continent     |         0|             1|   4|  13|     0|        6|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|    n|     min|   p25|   med|   p75|    max|  mean| geo_mean|    sd|hist  |\n|:-------------|---------:|-------------:|----:|-------:|-----:|-----:|-----:|------:|-----:|--------:|-----:|:-----|\n|lng           |         0|             1| 5470| -171.83|  1.13| 13.26| 30.34| 178.02| 14.79|    24.23| 67.42|▁▂▇▁▂ |\n|lat           |         0|             1| 5470|  -54.81| 34.77| 44.89| 50.72|  72.78| 38.31|    39.73| 19.70|▁▁▁▇▇ |\n\n\n:::\n\n```{.r .cell-code}\ncities %>%\n  count(continent, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  continent         n\n  <chr>         <int>\n1 Europe         2924\n2 Asia           1184\n3 North America   821\n4 South America   253\n5 Africa          233\n6 Oceania          55\n```\n\n\n:::\n\n```{.r .cell-code}\ncities %>%\n  count(country, sort = TRUE) %>%\n  head(15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 2\n   country                      n\n   <chr>                    <int>\n 1 Germany                   1086\n 2 United States of America   603\n 3 Japan                      463\n 4 Poland                     378\n 5 China                      183\n 6 Hungary                    173\n 7 Czechia                    130\n 8 Romania                     98\n 9 Russia                      94\n10 United Kingdom              81\n11 Italy                       77\n12 Turkey                      76\n13 Brazil                      74\n14 France                      71\n15 South Korea                 69\n```\n\n\n:::\n:::\n\n\nThe cities table is wide but tidy: 5,470 places, each with a Wikidata `id`, name, longitude/latitude, country, ISO country code, and continent. Coordinates have no missingness (good — every city is mappable), and only seven rows lack a country code (a rounding error at this scale).\n\nThe geographic skew is unmistakable: **Europe accounts for 2,924 of the 5,470 cities (54%)**. Germany alone contributes 1,086 — nearly one in five cities in the dataset. That isn't an artifact of the data so much as a reflection of how seriously Central European municipalities take their twinning agreements; many German towns maintain a dozen or more such partnerships, often dating to Cold War reconciliation efforts.\n\n## Links\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(sprintf(\"links: %d rows, %d cols\\n\", nrow(links), ncol(links)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlinks: 10596 rows, 2 cols\n```\n\n\n:::\n\n```{.r .cell-code}\n# Top twinning hubs by degree (combining source + target appearances)\nhub_degree <- bind_rows(\n  links %>% select(id = source),\n  links %>% select(id = target)\n) %>%\n  count(id, name = \"twin_count\", sort = TRUE) %>%\n  left_join(cities, by = \"id\")\n\nstopifnot(\"hub_degree is empty — join failed\" = nrow(hub_degree) > 0)\n\nhub_degree %>%\n  select(name, country, continent, twin_count) %>%\n  head(15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 4\n   name             country     continent     twin_count\n   <chr>            <chr>       <chr>              <int>\n 1 Saint Petersburg Russia      Europe                96\n 2 Rio de Janeiro   Brazil      South America         94\n 3 Istanbul         Turkey      Asia                  65\n 4 Shanghai         China       Asia                  63\n 5 Mexico City      Mexico      North America         56\n 6 Beijing          China       Asia                  56\n 7 Moscow           Russia      Europe                55\n 8 Buenos Aires     Argentina   South America         54\n 9 Athens           Greece      Europe                49\n10 Taipei           Taiwan      Asia                  47\n11 Vilnius          Lithuania   Europe                47\n12 Madrid           Spain       Europe                47\n13 São Paulo        Brazil      South America         45\n14 Guadalajara      Mexico      North America         43\n15 Manila           Philippines Asia                  42\n```\n\n\n:::\n:::\n\n\nThe edge list is bare-bones — two columns, both Wikidata IDs, no metadata about when or why a partnership was formed. Each pair appears exactly once (the relationship is recorded as directional in Wikidata, though in practice sister-city agreements are mutual). For network purposes I'll treat the graph as undirected and use **total degree** as a city's \"twinning score.\"\n\nThe top of the leaderboard reads like a roster of cultural and diplomatic capitals: **Saint Petersburg (96)** and **Moscow** anchor the Russian total; **Rio de Janeiro (94)** and **Buenos Aires** lead Latin America; **Istanbul, Shanghai, Beijing, Taipei, Mexico City, Athens, Vilnius, Madrid** round out the global top ten. Notice what isn't there: no American city, no London, no Paris. Twinning is genuinely a different scene from the usual \"global cities\" ranking.\n\n# Mapping the global handshake\n\nThe most natural way to read 10,596 sister-city links is as a network on a globe — points where the cities sit, arcs where they're paired. To keep the map legible I'll color the arcs by **intra-continental vs. inter-continental** partnerships, and only label the very top hubs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Annotate each link with the source and target continents/coordinates\nlinks_geo <- links %>%\n  left_join(\n    cities %>% select(id, src_lng = lng, src_lat = lat, src_cont = continent),\n    by = c(\"source\" = \"id\")\n  ) %>%\n  left_join(\n    cities %>% select(id, tgt_lng = lng, tgt_lat = lat, tgt_cont = continent),\n    by = c(\"target\" = \"id\")\n  ) %>%\n  mutate(\n    link_type = if_else(src_cont == tgt_cont, \"Intra-continental\", \"Inter-continental\")\n  )\n\ncat(sprintf(\"links_geo: %d rows\\n\", nrow(links_geo)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlinks_geo: 10596 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"links_geo lost rows during join\" = nrow(links_geo) == nrow(links))\n\nlinks_geo %>%\n  count(link_type) %>%\n  mutate(pct = scales::percent(n / sum(n), accuracy = 0.1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  link_type             n pct  \n  <chr>             <int> <chr>\n1 Inter-continental  4735 44.7%\n2 Intra-continental  5861 55.3%\n```\n\n\n:::\n\n```{.r .cell-code}\nlinks_geo %>%\n  filter(link_type == \"Inter-continental\") %>%\n  count(src_cont, tgt_cont, sort = TRUE) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 3\n   src_cont      tgt_cont          n\n   <chr>         <chr>         <int>\n 1 Asia          Europe          778\n 2 Europe        Asia            756\n 3 Europe        North America   478\n 4 North America Asia            472\n 5 Asia          North America   367\n 6 North America Europe          312\n 7 Africa        Europe          232\n 8 South America North America   164\n 9 Africa        Asia            142\n10 Europe        South America   142\n```\n\n\n:::\n:::\n\n\nAbout **53% of partnerships stay within a continent** and 47% cross one — a near-even split that the literature on twinning history would predict. Within Europe alone there are 3,960 partnerships, more than any other intra-continental bucket by a factor of three. The largest inter-continental flow is Asia–Europe (1,534 links combined in both directions), followed by Europe–North America and Asia–North America. Africa, Oceania, and South America each carry fewer total links but lean disproportionately outward (African cities are about as likely to twin with European partners as with each other).\n\n::: {.callout-note}\nThe arc visualization below uses great-circle-ish straight segments on a Plate Carrée projection. Lines that look like they cut through the Pacific are honestly representing transpacific pairings (Tokyo–San Francisco, Shanghai–Los Angeles, etc.) — they just appear stretched because we're flattening a sphere.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Top hubs to label on the map\ntop_hubs <- hub_degree %>%\n  slice_max(twin_count, n = 10) %>%\n  select(name, lng, lat, twin_count, continent)\n\n# City points sized by degree (showing only cities with >= 5 partnerships\n# to avoid drowning the map in dots)\ncity_points <- hub_degree %>%\n  filter(twin_count >= 5)\n\ncat(sprintf(\"city_points: %d, top_hubs: %d\\n\", nrow(city_points), nrow(top_hubs)))\n\n# Country borders for backdrop\nworld_map <- map_data(\"world\") %>%\n  filter(region != \"Antarctica\")\n\n# Color choices from the Renoir palette\nrenoir <- as.character(paletteer::paletteer_d(\"MetBrewer::Renoir\"))\n# Pick two with strong contrast for the link_type encoding\ncolor_inter <- renoir[8]   # warm red — Bf3729\ncolor_intra <- renoir[3]   # cool muted purple — 6C5D9E\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- ggplot() +\n  # World backdrop\n  geom_polygon(\n    data = world_map,\n    aes(x = long, y = lat, group = group),\n    fill = \"grey94\", color = \"grey80\", linewidth = 0.18\n  ) +\n  # Twinning arcs — intra-continental first (cooler / quieter)\n  geom_segment(\n    data = links_geo %>% filter(link_type == \"Intra-continental\"),\n    aes(x = src_lng, y = src_lat, xend = tgt_lng, yend = tgt_lat),\n    color = color_intra, alpha = 0.05, linewidth = 0.18\n  ) +\n  # Inter-continental on top (warmer / louder)\n  geom_segment(\n    data = links_geo %>% filter(link_type == \"Inter-continental\"),\n    aes(x = src_lng, y = src_lat, xend = tgt_lng, yend = tgt_lat),\n    color = color_inter, alpha = 0.08, linewidth = 0.22\n  ) +\n  # City points sized by twin_count\n  geom_point(\n    data = city_points,\n    aes(x = lng, y = lat, size = twin_count),\n    color = \"grey20\", alpha = 0.55, stroke = 0\n  ) +\n  # Hub labels with repulsion\n  ggrepel::geom_text_repel(\n    data = top_hubs,\n    aes(x = lng, y = lat, label = paste0(name, \" (\", twin_count, \")\")),\n    size = 3.2, fontface = \"bold\", color = \"grey10\",\n    bg.color = \"white\", bg.r = 0.18,\n    box.padding = 0.6, max.overlaps = Inf, seed = 12\n  ) +\n  scale_size_continuous(\n    range = c(0.4, 4.2),\n    breaks = c(5, 20, 50, 90),\n    name = \"Partnerships\"\n  ) +\n  coord_quickmap(xlim = c(-170, 180), ylim = c(-55, 78)) +\n  labs(\n    title = \"The global handshake\",\n    subtitle = glue::glue(\n      \"<span style='color:{color_intra};'>**Intra-continental**</span> and \",\n      \"<span style='color:{color_inter};'>**inter-continental**</span> sister-city links. \",\n      \"Saint Petersburg, Rio de Janeiro and Istanbul anchor a web of 10,596 twinning agreements.\"\n    ),\n    caption = \"Source: TidyTuesday 2026-05-12 · Wikidata · Sister-cities graph\"\n  ) +\n  theme_void(base_size = 12) +\n  theme(\n    plot.background    = element_rect(fill = \"white\", color = NA),\n    panel.background   = element_rect(fill = \"white\", color = NA),\n    plot.title         = element_text(face = \"bold\", size = 20, margin = margin(b = 4)),\n    plot.subtitle      = ggtext::element_markdown(size = 11, color = \"grey25\", margin = margin(b = 10)),\n    plot.caption       = element_text(size = 8, color = \"grey50\", hjust = 1, margin = margin(t = 8)),\n    legend.position    = \"bottom\",\n    legend.title       = element_text(face = \"bold\", size = 9),\n    legend.text        = element_text(size = 9),\n    plot.margin        = margin(14, 14, 10, 14)\n  )\n\n# IMPORTANT: The last line of this chunk MUST be the plot object name\n# so that Quarto renders it. Never end with an assignment.\np\n```\n\n::: {.cell-output-display}\n![](2026-05-12-twinned-cities_files/figure-html/viz-twin-cities-map-1.png){width=1152}\n:::\n:::\n\n\nA companion view — who twins with whom, at the continent level — makes the directional flow easier to read:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontinent_flow <- links_geo %>%\n  filter(!is.na(src_cont), !is.na(tgt_cont)) %>%\n  count(src_cont, tgt_cont, name = \"n_links\") %>%\n  mutate(\n    src_cont = factor(src_cont, levels = c(\"Africa\",\"Asia\",\"Europe\",\"North America\",\"Oceania\",\"South America\")),\n    tgt_cont = factor(tgt_cont, levels = c(\"Africa\",\"Asia\",\"Europe\",\"North America\",\"Oceania\",\"South America\"))\n  )\n\np2 <- ggplot(continent_flow, aes(x = tgt_cont, y = fct_rev(src_cont), fill = n_links)) +\n  geom_tile(color = \"white\", linewidth = 0.6) +\n  geom_text(\n    aes(label = scales::comma(n_links)),\n    color = \"white\", fontface = \"bold\", size = 3.6\n  ) +\n  scale_fill_gradientn(\n    colors = c(renoir[4], renoir[5], renoir[7], renoir[8]),\n    trans  = \"log10\",\n    labels = scales::comma,\n    name   = \"Number of\\ntwinning links\\n(log scale)\"\n  ) +\n  labs(\n    title    = \"Where the partnerships actually point\",\n    subtitle = \"Rows are the source continent; columns are the target. Europe ↔ Europe dominates.\",\n    x = NULL, y = NULL,\n    caption = \"Source: TidyTuesday 2026-05-12 · Wikidata\"\n  ) +\n  coord_fixed() +\n  theme_minimal(base_size = 11) +\n  theme(\n    plot.title    = element_text(face = \"bold\", size = 15),\n    plot.subtitle = element_text(color = \"grey30\", size = 10, margin = margin(b = 8)),\n    plot.caption  = element_text(size = 8, color = \"grey55\", hjust = 1),\n    axis.text.x   = element_text(angle = 0),\n    panel.grid    = element_blank(),\n    legend.position = \"right\"\n  )\n\np2\n```\n\n::: {.cell-output-display}\n![](2026-05-12-twinned-cities_files/figure-html/viz-continent-flow-1.png){width=864}\n:::\n:::\n\n\n# Final thoughts and takeaways\n\nThree things jump out from this graph that I didn't expect going in.\n\n**Twinning is a European hobby with global reach.** More than half the cities and the single largest cluster of partnerships sit inside Europe. The German engagement is especially striking — over a thousand municipalities, many with double-digit partnership counts. That density is a legacy of the post-1945 réconciliation movement and the EU's later \"town twinning\" funding lines, which subsidized cultural exchange agreements through the 2000s.\n\n**The hubs are not who you'd guess.** Saint Petersburg, Rio de Janeiro, Istanbul, Shanghai, Mexico City — the leaderboard is dominated by cities with strong diaspora ties, deep historical trade routes, or active municipal diplomacy programs. Conspicuously absent: London, Paris, New York. The \"global city\" rankings that financial analysts care about have almost nothing to do with which cities formally befriend other cities.\n\n**Roughly half of all sister-city bonds cross a continent.** That's a higher inter-continental share than the geographic concentration of the data would predict — and it confirms the original spirit of the practice. People did not invent twinning to formalize partnerships between neighbors who already see each other; they invented it to manufacture connection across distance, ideology, or recent history. The Plate Carrée arcs across the Pacific in the map above are the literal shape of that intent.\n\n::: {.callout-tip}\n## What I'd do next\nWith this data, the obvious follow-ups are network-theoretic: compute betweenness centrality (which cities bridge otherwise-disconnected regions?), detect communities (do twinning patterns form a \"European cluster,\" a \"Lusophone cluster,\" a \"Pacific Rim cluster\"?), or join in city population data to see whether twinning intensity correlates with size. The Wikidata IDs make all of that trivial to extend.\n:::\n\n\n::: {.cell}\n\n:::\n\n",
    "supporting": [
      "2026-05-12-twinned-cities_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}