{
  "hash": "7d0b87e3b8039b63353aecc0bf948986",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Nearby galaxies do not hide the same kinds of nuclei\"\nauthor: \"Sean Thimons\"\ndate: \"2026-08-11\"\ndescription: \"Palomar spectra show a sharp split between star-forming spiral nuclei and the LINER-heavy nuclei of early-type galaxies.\"\ncategories:\n  - tidytuesday\n  - R\n  - astronomy\n  - data-visualization\nexecute:\n  freeze: auto\n---\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](2026-08-11-palomar-spectroscopic-survey-nearby-galaxies_files/figure-html/pseudo-hero-palette-1.png){width=100%}\n:::\n:::\n\n\n# Preface\n\nFrom the [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2026/2026-08-11).\n\nThe Palomar survey put a slit across the centers of 486 bright nearby galaxies and measured their optical spectra. A spectrum can tell a blunt but useful story about a galaxy's nucleus. Young stars ionize gas one way. Accretion onto a black hole, shocks, and older stellar populations leave different ratios of oxygen, nitrogen, sulfur, and hydrogen lines.\n\nThe survey's classification labels are already in the file, so this is not a new classifier. I wanted to see how much the mix of labels changes with the host galaxy's visible morphology, then check that story against the classic BPT plane. The BPT diagram plots log([N II]/H-alpha) against log([O III]/H-beta). It is a diagnostic map, not a causal model.\n\n## Loading necessary packages\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(tidyverse)\nlibrary(tidytuesdayR)\nlibrary(skimr)\nlibrary(scales)\n\n`%ni%` <- Negate(`%in%`)\n```\n:::\n\n\n# Load raw data from package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load(\"2026-08-11\")\npalomar_survey <- raw$palomar_survey\npalomar_emission_lines <- raw$palomar_emission_lines\n```\n:::\n\n\n# Exploratory data analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\npalomar_survey %>%\n  select(activity_type, hubble_type, log_nii_ha, log_oiii_hb, velocity_dispersion_km_s) %>%\n  skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |486        |\n|Number of columns        |5          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |2          |\n|numeric                  |3          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|activity_type |        71|          0.85|   4|  10|     0|        5|          0|\n|hubble_type   |         0|          1.00|   1|  16|     0|      304|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable            | n_missing| complete_rate|   mean|    sd|    p0|   p25|    p50|    p75|   p100|hist  |\n|:------------------------|---------:|-------------:|------:|-----:|-----:|-----:|------:|------:|------:|:-----|\n|log_nii_ha               |        71|          0.85|   1.01|  0.85|  0.03|  0.38|   0.66|   1.48|   5.43|▇▃▁▁▁ |\n|log_oiii_hb              |        78|          0.84|   1.93|  2.58|  0.06|  0.45|   1.23|   2.20|  21.35|▇▁▁▁▁ |\n|velocity_dispersion_km_s |         5|          0.99| 124.99| 70.63| 17.50| 70.90| 116.30| 169.80| 335.30|▇▇▅▂▁ |\n\n\n:::\n\n```{.r .cell-code}\npalomar_survey %>%\n  count(activity_type, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  activity_type     n\n  <chr>         <int>\n1 H II            203\n2 LINER            94\n3 <NA>             71\n4 Transition       65\n5 Seyfert          52\n6 Absorption        1\n```\n\n\n:::\n:::\n\n\nThere are 486 galaxies in the survey, but 71 have no activity label in this version of the data. Among the 415 labelled nuclei, H II regions make up 203 cases, LINERs 94, transitions 65, and Seyferts 52. The labels come with a warning label of their own: 84 classifications are uncertain or very uncertain. I keep them in the descriptive plots because they are part of the published catalogue, but I do not treat a hard boundary between colored points as a law of nature.\n\n# Morphology changes the mix\n\n\n::: {.cell}\n\n```{.r .cell-code}\nactivity_levels <- c(\"H II\", \"Transition\", \"Seyfert\", \"LINER\")\nactivity_colors <- c(\n  \"H II\" = \"#A65141\",\n  \"Transition\" = \"#E7CDC2\",\n  \"Seyfert\" = \"#80A0C7\",\n  \"LINER\" = \"#394165\"\n)\n\nmorphology_mix <- palomar_survey %>%\n  filter(activity_type %in% activity_levels) %>%\n  mutate(\n    morphology = case_when(\n      str_detect(hubble_type, \"^E\") ~ \"Elliptical\",\n      str_detect(hubble_type, \"^S0\") ~ \"Lenticular\",\n      str_detect(hubble_type, \"^S\") ~ \"Spiral\",\n      str_detect(hubble_type, \"^I\") ~ \"Irregular\",\n      TRUE ~ \"Other\"\n    )\n  ) %>%\n  count(morphology, activity_type) %>%\n  group_by(morphology) %>%\n  mutate(share = n / sum(n)) %>%\n  ungroup() %>%\n  mutate(\n    morphology = factor(morphology, levels = c(\"Elliptical\", \"Lenticular\", \"Spiral\", \"Irregular\", \"Other\")),\n    activity_type = factor(activity_type, levels = activity_levels),\n    label = if_else(share >= 0.10, percent(share, accuracy = 1), \"\")\n  )\n\nmorphology_mix %>%\n  ggplot(aes(morphology, share, fill = activity_type)) +\n  geom_col(width = 0.72, color = \"#FCF9F0\", linewidth = 0.35) +\n  geom_text(\n    aes(label = label),\n    position = position_stack(vjust = 0.5),\n    color = \"#17252f\",\n    fontface = \"bold\",\n    size = 3.5\n  ) +\n  scale_fill_manual(values = activity_colors, name = \"Nuclear label\") +\n  scale_y_continuous(labels = percent_format(), expand = expansion(mult = c(0, 0.03))) +\n  labs(\n    title = \"Spiral nuclei are mostly H II, while LINER labels dominate early types\",\n    subtitle = \"Shares within each broad morphology group; only labelled galaxies are included\",\n    x = NULL,\n    y = \"Share of labelled nuclei\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    panel.grid.major.x = element_blank(),\n    panel.grid.minor = element_blank(),\n    plot.title = element_text(face = \"bold\"),\n    legend.position = \"top\"\n  )\n```\n\n::: {.cell-output-display}\n![Nuclear activity labels within broad visual morphology groups. Percentages use only the 415 galaxies with an activity label. The labels describe the nuclear spectrum; they do not establish the source of every line or a causal effect of morphology.](2026-08-11-palomar-spectroscopic-survey-nearby-galaxies_files/figure-html/fig-morphology-mix-1.png){#fig-morphology-mix width=960}\n:::\n:::\n\n\nThe contrast is large enough to see without statistical machinery. Of the 328 labelled spirals, 190 are H II nuclei, or 58%. The 25 labelled ellipticals point the other way: 19 are LINERs, or 76%. Lenticular galaxies sit between them, with LINER and transition labels together accounting for 77% of their labelled nuclei.\n\nThose groups are uneven. Seven irregulars and 25 ellipticals are not much material for a general claim. The spiral result carries more weight because it has 328 labelled galaxies. It also has an obvious observational caution: a visual Hubble type is a broad description of the host, while a nuclear spectrum comes from a small central aperture.\n\n# The diagnostic map behind the labels\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbpt_data <- palomar_survey %>%\n  filter(\n    activity_type %in% activity_levels,\n    !is.na(log_nii_ha),\n    !is.na(log_oiii_hb)\n  ) %>%\n  mutate(\n    morphology = case_when(\n      str_detect(hubble_type, \"^E\") ~ \"Elliptical\",\n      str_detect(hubble_type, \"^S0\") ~ \"Lenticular\",\n      str_detect(hubble_type, \"^S\") ~ \"Spiral\",\n      str_detect(hubble_type, \"^I\") ~ \"Irregular\",\n      TRUE ~ \"Other\"\n    ),\n    morphology = factor(morphology, levels = c(\"Elliptical\", \"Lenticular\", \"Spiral\", \"Irregular\", \"Other\")),\n    activity_type = factor(activity_type, levels = activity_levels)\n  )\n\nbpt_data %>%\n  ggplot(aes(log_nii_ha, log_oiii_hb, color = activity_type)) +\n  geom_vline(xintercept = -0.3, color = \"grey70\", linewidth = 0.35, linetype = \"22\") +\n  geom_hline(yintercept = 0, color = \"grey85\", linewidth = 0.35) +\n  geom_point(alpha = 0.72, size = 2.1) +\n  facet_wrap(~ morphology, ncol = 3) +\n  scale_color_manual(values = activity_colors, name = \"Published label\") +\n  labs(\n    title = \"The morphology result survives a look at the line-ratio plane\",\n    subtitle = \"Each point is a galaxy nucleus with both BPT coordinates\",\n    x = \"log([N II] / H-alpha)\",\n    y = \"log([O III] / H-beta)\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    panel.grid.minor = element_blank(),\n    plot.title = element_text(face = \"bold\"),\n    legend.position = \"top\"\n  )\n```\n\n::: {.cell-output-display}\n![BPT coordinates for 408 nuclei with both line ratios. The vertical guide at log([N II]/H-alpha) = -0.3 is only a visual reference, not a classification boundary used to create the catalog labels. Points are colored by the published activity label and faceted by broad morphology.](2026-08-11-palomar-spectroscopic-survey-nearby-galaxies_files/figure-html/fig-bpt-by-morphology-1.png){#fig-bpt-by-morphology width=960}\n:::\n:::\n\n\nThe BPT points do what the stacked bars suggested. H II nuclei in the spiral facet lean toward lower nitrogen-to-H-alpha ratios. LINER points occupy a different part of the plane and are common in the elliptical and lenticular facets. Seyferts overlap other labeled groups more than a simple two-cluster story would imply. That overlap is a useful reminder that the categories summarize line ratios and line profiles, not four sealed-off kinds of galaxies.\n\n# Final thoughts and takeaways\n\nThis small survey makes a strong descriptive point: nearby spiral galaxies and nearby early-type galaxies do not present the same menu of nuclear spectra. The clearest split is between H II labels in spirals and LINER labels in ellipticals and lenticulars. It does not tell us whether morphology caused that split, or whether every LINER line comes from the same physical process. The survey does give us a concrete place to start, with the raw line ratios still visible behind the catalog labels.\n",
    "supporting": [
      "2026-08-11-palomar-spectroscopic-survey-nearby-galaxies_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}