{
  "hash": "3252329c95dee1af6b63f4dfffbae01a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: The 2026 Winter Olympics\"\nauthor: \"Sean Thimons\"\ndate: \"2026-02-12\"\ndescription: \"Mapping the geographic pulse of the Milano-Cortina 2026 Winter Olympics — how 1,866 events spread across 13 venues and 6 host cities over 19 days.\"\ncategories: [tidytuesday, R, sports, olympics, geography]\n---\n\n\n\n# Preface\n\nFrom [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/blob/main/data/2026/2026-02-10/readme.md).\n\n> This week's dataset focuses on the Milano-Cortina 2026 Winter Olympics schedule. The data contains 1,866 Olympic events including competition and training sessions across 16 winter sports disciplines. The schedule spans February 4–22, 2026 and features timezone conversions, venue details, and medal event classifications.\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  if (file.exists('packages.txt')) {\n    packages <- read.table('packages.txt')\n\n    install_booster_pack(package = packages$Package, load = FALSE)\n\n    rm(packages)\n  } else {\n    ## Packages ----\n\n    booster_pack <- c(\n      ### IO ----\n      'fs',\n      'here',\n      'janitor',\n      'rio',\n      'tidyverse',\n\n      ### EDA ----\n      'skimr',\n\n      ### Plot ----\n      'camcorder',\n      'paletteer',\n      'patchwork',\n      'ggtext',\n      'ggrepel',\n\n      ### Reporting ----\n      'gt',\n\n      ### Misc ----\n      'tidytuesdayR'\n    )\n\n    # ! Change load flag to load packages\n    install_booster_pack(package = booster_pack, load = TRUE)\n    rm(install_booster_pack, booster_pack)\n  }\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2026-02-10')\n\nschedule <- raw$schedule %>%\n  clean_names() %>%\n  mutate(\n    date = as.Date(date),\n    is_medal_event = as.logical(is_medal_event),\n    is_training = as.logical(is_training),\n    estimated_start = as.logical(estimated_start),\n    start_datetime_local = as.POSIXct(start_datetime_local),\n    end_datetime_local = as.POSIXct(end_datetime_local),\n    start_datetime_utc = as.POSIXct(start_datetime_utc, tz = \"UTC\"),\n    end_datetime_utc = as.POSIXct(end_datetime_utc, tz = \"UTC\")\n  )\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## Schedule overview\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschedule %>%\n  select(\n    -session_code,\n    -event_code,\n    -discipline_code,\n    -venue_code,\n    -venue_slug,\n    -location_code,\n    -start_datetime_utc,\n    -end_datetime_utc\n  ) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |1866       |\n|Number of columns        |13         |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |5          |\n|Date                     |1          |\n|difftime                 |2          |\n|logical                  |3          |\n|POSIXct                  |2          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable     | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-----------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|discipline_name   |         0|          1.00|   4|  25|     0|       16|          0|\n|event_description |         0|          1.00|  10|  40|     0|      477|          0|\n|venue_name        |        63|          0.97|  17|  35|     0|       13|          0|\n|location_name     |         0|          1.00|  17|  30|     0|       30|          0|\n|day_of_week       |         0|          1.00|   6|   9|     0|        7|          0|\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|date          |         0|             1|2026-02-04 |2026-02-22 |2026-02-13 |       19|\n\n\n**Variable type: difftime**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|start_time    |         0|             1|28800 secs |81240 secs |51300 secs |      186|\n|end_time      |         0|             1|29880 secs |85200 secs |57240 secs |      254|\n\n\n**Variable type: logical**\n\n|skim_variable   | n_missing| complete_rate| mean|count               |\n|:---------------|---------:|-------------:|----:|:-------------------|\n|is_medal_event  |         0|             1| 0.18|FAL: 1522, TRU: 344 |\n|is_training     |         0|             1| 0.13|FAL: 1620, TRU: 246 |\n|estimated_start |         0|             1| 0.00|FAL: 1861, TRU: 5   |\n\n\n**Variable type: POSIXct**\n\n|skim_variable        | n_missing| complete_rate|min                 |max                 |median              | n_unique|\n|:--------------------|---------:|-------------:|:-------------------|:-------------------|:-------------------|--------:|\n|start_datetime_local |         0|             1|2026-02-04 11:30:00 |2026-02-22 14:10:00 |2026-02-13 19:00:00 |      487|\n|end_datetime_local   |         0|             1|2026-02-04 13:30:00 |2026-02-22 16:40:00 |2026-02-13 20:24:10 |      509|\n\n\n:::\n:::\n\n\n\nThe schedule contains 1866 total events across 16 disciplines and 14 venues. Events span from 2026-02-04 to 2026-02-22 — a 19-day window that includes both training and competition sessions.\n\nKey observations from the skim:\n\n- **Training vs. competition**: 246 training sessions and 1620 competition events\n- **Medal events**: 344 medal sessions out of the full schedule\n- **Venue concentration**: Some venues host hundreds of events (Cortina Curling Olympic Stadium alone accounts for a huge share), while others are more specialized\n\n## Host city extraction\n\nThe 2026 Games are uniquely distributed across northern Italy. Let's extract the host city from each venue name and see how the Games are geographically structured.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschedule <- schedule %>%\n  mutate(\n    host_city = case_when(\n      str_detect(venue_name, \"^Milano\") ~ \"Milano\",\n      str_detect(venue_name, \"^Cortina\") ~ \"Cortina d'Ampezzo\",\n      str_detect(venue_name, \"^Livigno\") ~ \"Livigno\",\n      str_detect(venue_name, \"^Predazzo\") ~ \"Predazzo\",\n      str_detect(venue_name, \"^Tesero\") ~ \"Tesero\",\n      str_detect(venue_name, \"^Anterselva\") ~ \"Anterselva\",\n      str_detect(venue_name, \"^Stelvio\") ~ \"Bormio\",\n      str_detect(venue_name, \"^Tofane\") ~ \"Cortina d'Ampezzo\",\n      TRUE ~ \"Other\"\n    )\n  )\n\nschedule %>%\n  filter(!is_training) %>%\n  count(host_city, sort = TRUE) %>%\n  mutate(pct = scales::percent(n / sum(n))) %>%\n  gt() %>%\n  cols_label(\n    host_city = \"Host City\",\n    n = \"Competition Events\",\n    pct = \"Share\"\n  ) %>%\n  tab_header(title = \"Competition events by host city\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"fgrusupoqe\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fgrusupoqe table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fgrusupoqe thead, #fgrusupoqe tbody, #fgrusupoqe tfoot, #fgrusupoqe tr, #fgrusupoqe td, #fgrusupoqe th {\n  border-style: none;\n}\n\n#fgrusupoqe p {\n  margin: 0;\n  padding: 0;\n}\n\n#fgrusupoqe .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fgrusupoqe .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fgrusupoqe .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fgrusupoqe .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fgrusupoqe .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fgrusupoqe .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fgrusupoqe .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fgrusupoqe .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fgrusupoqe .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fgrusupoqe .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fgrusupoqe .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fgrusupoqe .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fgrusupoqe .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fgrusupoqe .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fgrusupoqe .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fgrusupoqe .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fgrusupoqe .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fgrusupoqe .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fgrusupoqe .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fgrusupoqe .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fgrusupoqe .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fgrusupoqe .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fgrusupoqe .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fgrusupoqe .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fgrusupoqe .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fgrusupoqe .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fgrusupoqe .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fgrusupoqe .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fgrusupoqe .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fgrusupoqe .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fgrusupoqe .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fgrusupoqe .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fgrusupoqe .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fgrusupoqe .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fgrusupoqe .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fgrusupoqe .gt_left {\n  text-align: left;\n}\n\n#fgrusupoqe .gt_center {\n  text-align: center;\n}\n\n#fgrusupoqe .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fgrusupoqe .gt_font_normal {\n  font-weight: normal;\n}\n\n#fgrusupoqe .gt_font_bold {\n  font-weight: bold;\n}\n\n#fgrusupoqe .gt_font_italic {\n  font-style: italic;\n}\n\n#fgrusupoqe .gt_super {\n  font-size: 65%;\n}\n\n#fgrusupoqe .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fgrusupoqe .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fgrusupoqe .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fgrusupoqe .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fgrusupoqe .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fgrusupoqe .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fgrusupoqe .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fgrusupoqe .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fgrusupoqe div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Competition events by host city</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"host_city\">Host City</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">Competition Events</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"pct\">Share</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"host_city\" class=\"gt_row gt_left\">Cortina d'Ampezzo</td>\n<td headers=\"n\" class=\"gt_row gt_right\">567</td>\n<td headers=\"pct\" class=\"gt_row gt_right\">35.00%</td></tr>\n    <tr><td headers=\"host_city\" class=\"gt_row gt_left\">Milano</td>\n<td headers=\"n\" class=\"gt_row gt_right\">399</td>\n<td headers=\"pct\" class=\"gt_row gt_right\">24.63%</td></tr>\n    <tr><td headers=\"host_city\" class=\"gt_row gt_left\">Livigno</td>\n<td headers=\"n\" class=\"gt_row gt_right\">380</td>\n<td headers=\"pct\" class=\"gt_row gt_right\">23.46%</td></tr>\n    <tr><td headers=\"host_city\" class=\"gt_row gt_left\">Predazzo</td>\n<td headers=\"n\" class=\"gt_row gt_right\">70</td>\n<td headers=\"pct\" class=\"gt_row gt_right\">4.32%</td></tr>\n    <tr><td headers=\"host_city\" class=\"gt_row gt_left\">Tesero</td>\n<td headers=\"n\" class=\"gt_row gt_right\">68</td>\n<td headers=\"pct\" class=\"gt_row gt_right\">4.20%</td></tr>\n    <tr><td headers=\"host_city\" class=\"gt_row gt_left\">Other</td>\n<td headers=\"n\" class=\"gt_row gt_right\">57</td>\n<td headers=\"pct\" class=\"gt_row gt_right\">3.52%</td></tr>\n    <tr><td headers=\"host_city\" class=\"gt_row gt_left\">Bormio</td>\n<td headers=\"n\" class=\"gt_row gt_right\">46</td>\n<td headers=\"pct\" class=\"gt_row gt_right\">2.84%</td></tr>\n    <tr><td headers=\"host_city\" class=\"gt_row gt_left\">Anterselva</td>\n<td headers=\"n\" class=\"gt_row gt_right\">33</td>\n<td headers=\"pct\" class=\"gt_row gt_right\">2.04%</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.callout-note}\n## A distributed Games\n\nUnlike many Winter Olympics concentrated in a single mountain region, Milano-Cortina 2026 spreads across the Italian Alps and into the Po Valley. Milano hosts the ice sports (figure skating, speed skating, short track, hockey), while the mountain towns — Cortina, Livigno, Bormio — handle the snow and sliding disciplines. This geographic spread is a defining feature of these Games.\n:::\n\n# Venue Geography Analysis\n\n## Disciplines per venue\n\nEach venue is purpose-built or adapted for specific sports. Let's map which disciplines live where.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvenue_disciplines <- schedule %>%\n  filter(!is_training) %>%\n  count(venue_name, host_city, discipline_name, sort = TRUE)\n\nvenue_disciplines %>%\n  group_by(venue_name, host_city) %>%\n  summarise(\n    disciplines = paste(discipline_name, collapse = \", \"),\n    total_events = sum(n),\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(total_events)) %>%\n  gt() %>%\n  cols_label(\n    venue_name = \"Venue\",\n    host_city = \"City\",\n    disciplines = \"Disciplines\",\n    total_events = \"Events\"\n  ) %>%\n  tab_header(title = \"Venue utilization and discipline mapping\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"iukndxbqgv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#iukndxbqgv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#iukndxbqgv thead, #iukndxbqgv tbody, #iukndxbqgv tfoot, #iukndxbqgv tr, #iukndxbqgv td, #iukndxbqgv th {\n  border-style: none;\n}\n\n#iukndxbqgv p {\n  margin: 0;\n  padding: 0;\n}\n\n#iukndxbqgv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#iukndxbqgv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#iukndxbqgv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#iukndxbqgv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#iukndxbqgv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iukndxbqgv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iukndxbqgv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iukndxbqgv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#iukndxbqgv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#iukndxbqgv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#iukndxbqgv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#iukndxbqgv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#iukndxbqgv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#iukndxbqgv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#iukndxbqgv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#iukndxbqgv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#iukndxbqgv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#iukndxbqgv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#iukndxbqgv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iukndxbqgv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#iukndxbqgv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#iukndxbqgv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#iukndxbqgv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iukndxbqgv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#iukndxbqgv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#iukndxbqgv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iukndxbqgv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iukndxbqgv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#iukndxbqgv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iukndxbqgv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#iukndxbqgv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iukndxbqgv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iukndxbqgv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iukndxbqgv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iukndxbqgv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iukndxbqgv .gt_left {\n  text-align: left;\n}\n\n#iukndxbqgv .gt_center {\n  text-align: center;\n}\n\n#iukndxbqgv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#iukndxbqgv .gt_font_normal {\n  font-weight: normal;\n}\n\n#iukndxbqgv .gt_font_bold {\n  font-weight: bold;\n}\n\n#iukndxbqgv .gt_font_italic {\n  font-style: italic;\n}\n\n#iukndxbqgv .gt_super {\n  font-size: 65%;\n}\n\n#iukndxbqgv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#iukndxbqgv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#iukndxbqgv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#iukndxbqgv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#iukndxbqgv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#iukndxbqgv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#iukndxbqgv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#iukndxbqgv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#iukndxbqgv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"4\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Venue utilization and discipline mapping</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"venue_name\">Venue</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"host_city\">City</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"disciplines\">Disciplines</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"total_events\">Events</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Cortina Curling Olympic Stadium</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Cortina d'Ampezzo</td>\n<td headers=\"disciplines\" class=\"gt_row gt_left\">Curling</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">436</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Livigno Snow Park</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Livigno</td>\n<td headers=\"disciplines\" class=\"gt_row gt_left\">Snowboard, Freestyle Skiing</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">297</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Milano Ice Skating Arena</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Milano</td>\n<td headers=\"disciplines\" class=\"gt_row gt_left\">Short Track Speed Skating, Figure Skating</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">162</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Cortina Sliding Centre</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Cortina d'Ampezzo</td>\n<td headers=\"disciplines\" class=\"gt_row gt_left\">Bobsleigh, Luge, Skeleton</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">112</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Milano Santagiulia Ice Hockey Arena</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Milano</td>\n<td headers=\"disciplines\" class=\"gt_row gt_left\">Ice Hockey</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">88</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Livigno Aerials &amp; Moguls Park</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Livigno</td>\n<td headers=\"disciplines\" class=\"gt_row gt_left\">Freestyle Skiing</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">83</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Milano Speed Skating Stadium</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Milano</td>\n<td headers=\"disciplines\" class=\"gt_row gt_left\">Speed Skating</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">78</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Milano Rho Ice Hockey Arena</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Milano</td>\n<td headers=\"disciplines\" class=\"gt_row gt_left\">Ice Hockey</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">71</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Predazzo Ski Jumping Stadium</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Predazzo</td>\n<td headers=\"disciplines\" class=\"gt_row gt_left\">Ski Jumping, Nordic Combined</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">70</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Tesero Cross-Country Skiing Stadium</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Tesero</td>\n<td headers=\"disciplines\" class=\"gt_row gt_left\">Cross-Country Skiing, Nordic Combined</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">68</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Other</td>\n<td headers=\"disciplines\" class=\"gt_row gt_left\">Freestyle Skiing, Ice Hockey, Nordic Combined, Alpine Skiing</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">57</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Stelvio Ski Centre</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Bormio</td>\n<td headers=\"disciplines\" class=\"gt_row gt_left\">Alpine Skiing, Ski Mountaineering</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">46</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Anterselva Biathlon Arena</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Anterselva</td>\n<td headers=\"disciplines\" class=\"gt_row gt_left\">Biathlon</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">33</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Tofane Alpine Skiing Centre</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Cortina d'Ampezzo</td>\n<td headers=\"disciplines\" class=\"gt_row gt_left\">Alpine Skiing</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">19</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n## Medal density by venue\n\nNot all events are created equal. Some venues host dozens of rounds leading to a handful of medal moments; others are medal-dense. The **medal density** — the share of competition events that award medals — reveals which venues are built for the climactic moments.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvenue_medal_density <- schedule %>%\n  filter(!is_training) %>%\n  group_by(venue_name, host_city) %>%\n  summarise(\n    total_events = n(),\n    medal_events = sum(is_medal_event),\n    medal_density = medal_events / total_events,\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(medal_density))\n\nvenue_medal_density %>%\n  mutate(medal_density = scales::percent(medal_density, accuracy = 0.1)) %>%\n  gt() %>%\n  cols_label(\n    venue_name = \"Venue\",\n    host_city = \"City\",\n    total_events = \"Total Events\",\n    medal_events = \"Medal Events\",\n    medal_density = \"Medal Density\"\n  ) %>%\n  tab_header(title = \"Medal density across Olympic venues\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ipxifsssqt\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ipxifsssqt table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ipxifsssqt thead, #ipxifsssqt tbody, #ipxifsssqt tfoot, #ipxifsssqt tr, #ipxifsssqt td, #ipxifsssqt th {\n  border-style: none;\n}\n\n#ipxifsssqt p {\n  margin: 0;\n  padding: 0;\n}\n\n#ipxifsssqt .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ipxifsssqt .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ipxifsssqt .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ipxifsssqt .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ipxifsssqt .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ipxifsssqt .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ipxifsssqt .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ipxifsssqt .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ipxifsssqt .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ipxifsssqt .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ipxifsssqt .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ipxifsssqt .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ipxifsssqt .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ipxifsssqt .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ipxifsssqt .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ipxifsssqt .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ipxifsssqt .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ipxifsssqt .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ipxifsssqt .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ipxifsssqt .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ipxifsssqt .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ipxifsssqt .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ipxifsssqt .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ipxifsssqt .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ipxifsssqt .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ipxifsssqt .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ipxifsssqt .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ipxifsssqt .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ipxifsssqt .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ipxifsssqt .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ipxifsssqt .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ipxifsssqt .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ipxifsssqt .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ipxifsssqt .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ipxifsssqt .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ipxifsssqt .gt_left {\n  text-align: left;\n}\n\n#ipxifsssqt .gt_center {\n  text-align: center;\n}\n\n#ipxifsssqt .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ipxifsssqt .gt_font_normal {\n  font-weight: normal;\n}\n\n#ipxifsssqt .gt_font_bold {\n  font-weight: bold;\n}\n\n#ipxifsssqt .gt_font_italic {\n  font-style: italic;\n}\n\n#ipxifsssqt .gt_super {\n  font-size: 65%;\n}\n\n#ipxifsssqt .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ipxifsssqt .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ipxifsssqt .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ipxifsssqt .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ipxifsssqt .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ipxifsssqt .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ipxifsssqt .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ipxifsssqt .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ipxifsssqt div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Medal density across Olympic venues</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"venue_name\">Venue</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"host_city\">City</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"total_events\">Total Events</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"medal_events\">Medal Events</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"medal_density\">Medal Density</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Anterselva Biathlon Arena</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Anterselva</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">33</td>\n<td headers=\"medal_events\" class=\"gt_row gt_right\">33</td>\n<td headers=\"medal_density\" class=\"gt_row gt_right\">100.0%</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Tesero Cross-Country Skiing Stadium</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Tesero</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">68</td>\n<td headers=\"medal_events\" class=\"gt_row gt_right\">44</td>\n<td headers=\"medal_density\" class=\"gt_row gt_right\">64.7%</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Tofane Alpine Skiing Centre</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Cortina d'Ampezzo</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">19</td>\n<td headers=\"medal_events\" class=\"gt_row gt_right\">12</td>\n<td headers=\"medal_density\" class=\"gt_row gt_right\">63.2%</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Milano Speed Skating Stadium</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Milano</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">78</td>\n<td headers=\"medal_events\" class=\"gt_row gt_right\">42</td>\n<td headers=\"medal_density\" class=\"gt_row gt_right\">53.8%</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Stelvio Ski Centre</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Bormio</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">46</td>\n<td headers=\"medal_events\" class=\"gt_row gt_right\">24</td>\n<td headers=\"medal_density\" class=\"gt_row gt_right\">52.2%</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Cortina Sliding Centre</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Cortina d'Ampezzo</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">112</td>\n<td headers=\"medal_events\" class=\"gt_row gt_right\">35</td>\n<td headers=\"medal_density\" class=\"gt_row gt_right\">31.2%</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Milano Ice Skating Arena</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Milano</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">162</td>\n<td headers=\"medal_events\" class=\"gt_row gt_right\">42</td>\n<td headers=\"medal_density\" class=\"gt_row gt_right\">25.9%</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Predazzo Ski Jumping Stadium</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Predazzo</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">70</td>\n<td headers=\"medal_events\" class=\"gt_row gt_right\">18</td>\n<td headers=\"medal_density\" class=\"gt_row gt_right\">25.7%</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">NA</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Other</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">57</td>\n<td headers=\"medal_events\" class=\"gt_row gt_right\">14</td>\n<td headers=\"medal_density\" class=\"gt_row gt_right\">24.6%</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Livigno Aerials &amp; Moguls Park</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Livigno</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">83</td>\n<td headers=\"medal_events\" class=\"gt_row gt_right\">18</td>\n<td headers=\"medal_density\" class=\"gt_row gt_right\">21.7%</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Livigno Snow Park</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Livigno</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">297</td>\n<td headers=\"medal_events\" class=\"gt_row gt_right\">50</td>\n<td headers=\"medal_density\" class=\"gt_row gt_right\">16.8%</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Milano Santagiulia Ice Hockey Arena</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Milano</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">88</td>\n<td headers=\"medal_events\" class=\"gt_row gt_right\">4</td>\n<td headers=\"medal_density\" class=\"gt_row gt_right\">4.5%</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Cortina Curling Olympic Stadium</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Cortina d'Ampezzo</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">436</td>\n<td headers=\"medal_events\" class=\"gt_row gt_right\">8</td>\n<td headers=\"medal_density\" class=\"gt_row gt_right\">1.8%</td></tr>\n    <tr><td headers=\"venue_name\" class=\"gt_row gt_left\">Milano Rho Ice Hockey Arena</td>\n<td headers=\"host_city\" class=\"gt_row gt_left\">Milano</td>\n<td headers=\"total_events\" class=\"gt_row gt_right\">71</td>\n<td headers=\"medal_events\" class=\"gt_row gt_right\">0</td>\n<td headers=\"medal_density\" class=\"gt_row gt_right\">0.0%</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.callout-important}\n## Curling: the endurance sport of scheduling\n\nCortina Curling Olympic Stadium hosts a staggering 436 competition events — more than double any other venue — yet produces only 8 medal sessions (a medal density under 2%). Curling's round-robin format demands this marathon of matches, making it the most venue-intensive discipline by far.\n:::\n\n## Daily venue activity\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_venue <- schedule %>%\n  filter(!is_training) %>%\n  count(date, venue_name, host_city, name = \"events\")\n\n# Create ordered factor for venues grouped by city\nvenue_order <- schedule %>%\n  filter(!is_training) %>%\n  mutate(\n    city_order = factor(\n      host_city,\n      levels = c(\n        \"Milano\",\n        \"Cortina d'Ampezzo\",\n        \"Livigno\",\n        \"Bormio\",\n        \"Predazzo\",\n        \"Tesero\",\n        \"Anterselva\"\n      )\n    )\n  ) %>%\n  arrange(city_order, venue_name) %>%\n  pull(venue_name) %>%\n  unique()\n\ndaily_venue <- daily_venue %>%\n  mutate(venue_name = factor(venue_name, levels = rev(venue_order)))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!dir.exists(here::here('posts', '2026-02-12', 'output'))) {\n  dir.create(here::here('posts', '2026-02-12', 'output'), recursive = TRUE)\n}\n\ngg_record(\n  here::here('posts', '2026-02-12', 'output'),\n  device = \"png\",\n  width = 10,\n  height = 7,\n  units = \"in\",\n  dpi = 320\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Olympic-inspired color palette\nolympic_gradient <- c(\"#FFFFFF\", \"#0085C7\", \"#00247D\")\n\n# Key ceremony dates\nceremonies <- tibble(\n  date = as.Date(c(\"2026-02-06\", \"2026-02-22\")),\n  label = c(\"Opening\\nCeremony\", \"Closing\\nCeremony\")\n)\n\n# City labels for venue grouping\ncity_labels <- daily_venue %>%\n  distinct(venue_name, host_city) %>%\n  mutate(\n    venue_name = factor(venue_name, levels = levels(daily_venue$venue_name))\n  ) %>%\n  group_by(host_city) %>%\n  summarise(\n    y_pos = mean(as.numeric(venue_name)),\n    .groups = \"drop\"\n  )\n\n# Build the heatmap\np <- ggplot(daily_venue, aes(x = date, y = venue_name, fill = events)) +\n  geom_tile(color = \"white\", linewidth = 0.4) +\n  scale_fill_gradient2(\n    low = \"#FFFFFF\",\n    mid = \"#0085C7\",\n    high = \"#00247D\",\n    midpoint = 15,\n    name = \"Events\",\n    na.value = \"#F5F5F5\"\n  ) +\n  scale_x_date(\n    date_breaks = \"2 days\",\n    date_labels = \"%b %d\",\n    expand = expansion(mult = c(0.01, 0.05))\n  ) +\n  # Opening & closing ceremony markers\n  geom_vline(\n    data = ceremonies,\n    aes(xintercept = date),\n    linetype = \"dashed\",\n    color = \"#D4AF37\",\n    linewidth = 0.6\n  ) +\n  geom_label(\n    data = ceremonies,\n    aes(x = date, y = 0.5, label = label),\n    inherit.aes = FALSE,\n    fill = \"#D4AF37\",\n    color = \"white\",\n    fontface = \"bold\",\n    size = 2.5,\n    label.padding = unit(0.2, \"lines\"),\n    label.size = 0\n  ) +\n  # City group annotations on the right\n  annotate(\n    \"text\",\n    x = max(daily_venue$date) + 1.5,\n    y = city_labels$y_pos,\n    label = city_labels$host_city,\n    hjust = 0,\n    fontface = \"italic\",\n    size = 3,\n    color = \"#555555\"\n  ) +\n  coord_cartesian(clip = \"off\") +\n  labs(\n    title = \"The Geographic Pulse of Milano-Cortina 2026\",\n    subtitle = \"Daily competition events across 13 Olympic venues, grouped by host city\",\n    x = NULL,\n    y = NULL,\n    caption = \"Source: TidyTuesday 2026-02-10 · Milano-Cortina 2026 Winter Olympics Schedule\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 16, color = \"#00247D\"),\n    plot.subtitle = element_text(\n      size = 11,\n      color = \"#555555\",\n      margin = margin(b = 12)\n    ),\n    plot.caption = element_text(size = 8, color = \"#999999\", hjust = 0),\n    axis.text.y = element_text(size = 8),\n    axis.text.x = element_text(size = 8, angle = 45, hjust = 1),\n    legend.position = \"top\",\n    legend.title = element_text(size = 9),\n    legend.key.width = unit(1.5, \"cm\"),\n    panel.grid = element_blank(),\n    plot.margin = margin(10, 80, 10, 10)\n  )\n\np\n```\n\n::: {.cell-output-display}\n![](2026-02-12_files/figure-html/hero-heatmap-1.png){width=960}\n:::\n:::\n\n\n\n## Venue activity over time by city\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncity_daily <- schedule %>%\n  filter(!is_training) %>%\n  count(date, host_city, name = \"events\")\n\ncity_colors <- c(\n  \"Milano\" = \"#0085C7\",\n  \"Cortina d'Ampezzo\" = \"#D4AF37\",\n  \"Livigno\" = \"#009F3D\",\n  \"Bormio\" = \"#EE334E\",\n  \"Predazzo\" = \"#F4C300\",\n  \"Tesero\" = \"#FF8C00\",\n  \"Anterselva\" = \"#8B4513\"\n)\n\nggplot(city_daily, aes(x = date, y = events, color = host_city)) +\n  geom_line(linewidth = 1, alpha = 0.8) +\n  geom_point(size = 2) +\n  scale_color_manual(values = city_colors, name = \"Host City\") +\n  scale_x_date(date_breaks = \"2 days\", date_labels = \"%b %d\") +\n  labs(\n    title = \"Daily competition events by host city\",\n    subtitle = \"Milano sustains the highest event load throughout the Games\",\n    x = NULL,\n    y = \"Number of events\",\n    caption = \"Source: TidyTuesday 2026-02-10\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14, color = \"#00247D\"),\n    plot.subtitle = element_text(size = 10, color = \"#555555\"),\n    plot.caption = element_text(size = 8, color = \"#999999\"),\n    axis.text.x = element_text(angle = 45, hjust = 1),\n    legend.position = \"right\"\n  )\n```\n\n::: {.cell-output-display}\n![](2026-02-12_files/figure-html/city-timeseries-1.png){width=960}\n:::\n:::\n\n\n\n# Final thoughts and takeaways\n\nThe Milano-Cortina 2026 Winter Olympics are architecturally unique: rather than clustering events in a single alpine basin, these Games sprawl across the Italian Alps and down into the Po Valley. This analysis reveals several patterns in that geographic design:\n\n**Milano is the engine room.** With four venues hosting ice sports — figure skating, short track, speed skating, and two hockey arenas — Milano sustains the highest daily event count throughout the Games. The city's venues are active nearly every day from opening to closing ceremony.\n\n**Cortina's curling dominance is deceptive.** The Cortina Curling Olympic Stadium generates by far the most events of any venue, but its medal density is vanishingly low. The round-robin format means hundreds of sessions build to just a handful of medal moments — a sharp contrast to venues like the speed skating stadium or biathlon arena where a larger share of events produce medals.\n\n**Mountain venues are specialists.** The alpine and Nordic venues — Bormio, Predazzo, Tesero, Anterselva — each host one or two disciplines and operate on tighter, more concentrated schedules. Their activity windows are shorter but intense.\n\n**The mid-Games peak is universal.** Across nearly every venue, event density peaks around February 13–16, suggesting a deliberate scheduling strategy that builds momentum through the first week and then ramps into a climactic stretch before the closing ceremonies.\n\nThis geographic distribution presents both logistical challenges (athlete transport, spectator travel between cities separated by hours of mountain driving) and opportunities (multiple cities share the economic and cultural benefits of hosting). Whether this distributed model becomes a template for future Games remains to be seen.\n",
    "supporting": [
      "2026-02-12_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}