{
  "hash": "ff76fc638ca9c3d2a870bec3d4a6d2ef",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Australian Frogs\"\nauthor: \"Sean Thimons\"\ndate: \"2025-09-02\"\ndescription: \"Mapping the seasonal calling calendar of Australia's frogs using 136,000 citizen-science observations from the 2023 FrogID survey.\"\ncategories: [tidytuesday, R, ecology, citizen-science, australia, wildlife]\n---\n\n\n\n# Preface\n\nFrom the [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-09-02).\n\n> FrogID is a citizen science initiative allowing Australians to record and submit frog calls for expert identification. The 2023 dataset represents the sixth annual data release, contributing to over 30 scientific papers on frog ecology, taxonomy, and conservation since 2017. Australia hosts 257 native frog species found nowhere else on Earth — yet almost one in five species are threatened with extinction due to climate change, urbanisation, disease, and invasive species.\n\nSuggested research questions:\n\n- Which frog species are endemic to specific Australian regions?\n- Do different species exhibit distinct seasonal calling patterns?\n- Which species has the broadest geographic distribution versus the most limited range?\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  booster_pack <- c(\n    ### IO ----\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n\n    ### EDA ----\n    'skimr',\n\n    ### Plot ----\n    'paletteer',           # Color palette collection\n    'ggtext',              # Rich text (italic species names)\n    'ggrepel',             # Non-overlapping labels\n    'scales',              # Axis formatting\n\n    ### Misc ----\n    'tidytuesdayR'\n  )\n\n  install_booster_pack(package = booster_pack, load = TRUE)\n  rm(install_booster_pack, booster_pack)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2025-09-02')\n\nfrog_data  <- raw$frogID_data   # 136,621 citizen-science observation records\nfrog_names <- raw$frog_names    # 294-row taxonomic lookup (subfamily, common names)\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function returns count, min, p25, median, p75, max, mean, geometric mean, and standard deviation, plus an ASCII histogram.\n\n## frogID_data — occurrence records\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Drop identifier and recorder columns — not analytically useful\nfrog_data %>%\n  select(-occurrenceID, -eventID, -recordedBy) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |136621     |\n|Number of columns        |8          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |3          |\n|Date                     |1          |\n|difftime                 |1          |\n|numeric                  |3          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable  | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:--------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|scientificName |         0|             1|  12|  28|     0|      186|          0|\n|timezone       |         0|             1|   3|   8|     0|        6|          0|\n|stateProvince  |         0|             1|   8|  28|     0|        9|          0|\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|eventDate     |         0|             1|2023-01-01 |2023-11-09 |2023-08-21 |      313|\n\n\n**Variable type: difftime**\n\n|skim_variable | n_missing| complete_rate|min    |max        |median   | n_unique|\n|:-------------|---------:|-------------:|:------|:----------|:--------|--------:|\n|eventTime     |         0|             1|0 secs |86399 secs |14:08:33 |    49528|\n\n\n**Variable type: numeric**\n\n|skim_variable                 | n_missing| complete_rate|      n|    min|    p25|    med|    p75|      max|   mean| geo_mean|      sd|hist  |\n|:-----------------------------|---------:|-------------:|------:|------:|------:|------:|------:|--------:|------:|--------:|-------:|:-----|\n|decimalLatitude               |         0|             1| 136621| -43.60| -36.29| -33.73| -30.32|    -9.41| -32.57|      NaN|    5.50|▃▇▂▁▁ |\n|decimalLongitude              |         0|             1| 136621| 114.17| 145.21| 149.81| 151.58|   159.08| 146.11|   145.75|    9.66|▁▁▁▆▇ |\n|coordinateUncertaintyInMeters |         0|             1| 136621|   0.00|   4.84|  10.00|  24.31| 10000.00| 266.30|    14.21| 1511.12|▇▁▁▁▁ |\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# State distribution\ncat(\"=== Observations by State ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Observations by State ===\n```\n\n\n:::\n\n```{.r .cell-code}\nfrog_data %>% count(stateProvince, sort = TRUE) %>% print(n = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 2\n  stateProvince                    n\n  <chr>                        <int>\n1 New South Wales              58749\n2 Victoria                     32383\n3 Queensland                   23334\n4 Western Australia            10844\n5 South Australia               4158\n6 Tasmania                      2562\n7 Northern Territory            2380\n8 Australian Capital Territory  2082\n9 Other Territories              129\n```\n\n\n:::\n\n```{.r .cell-code}\n# Top observed species\ncat(\"\\n=== Top 15 Species ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Top 15 Species ===\n```\n\n\n:::\n\n```{.r .cell-code}\nfrog_data %>% count(scientificName, sort = TRUE) %>% head(15) %>% print(n = 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 2\n   scientificName                 n\n   <chr>                      <int>\n 1 Crinia signifera           33630\n 2 Limnodynastes peronii      17462\n 3 Litoria fallax              8572\n 4 Litoria peronii             8565\n 5 Limnodynastes tasmaniensis  7372\n 6 Litoria ewingii             6471\n 7 Litoria verreauxii          5824\n 8 Crinia parinsignifera       4339\n 9 Limnodynastes dumerilii     3289\n10 Litoria caerulea            3011\n11 Crinia glauerti             2673\n12 Adelotus brevis             2108\n13 Litoria adelaidensis        1820\n14 Litoria gracilenta          1619\n15 Litoria pyrina              1351\n```\n\n\n:::\n\n```{.r .cell-code}\n# Monthly rhythm\ncat(\"\\n=== Observations by Month ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Observations by Month ===\n```\n\n\n:::\n\n```{.r .cell-code}\nfrog_data %>%\n  mutate(month = month(eventDate, label = TRUE, abbr = TRUE)) %>%\n  count(month) %>%\n  print(n = 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 11 × 2\n   month     n\n   <ord> <int>\n 1 Jan   16715\n 2 Feb    8934\n 3 Mar    6569\n 4 Apr    7248\n 5 May    4190\n 6 Jun    6664\n 7 Jul    9658\n 8 Aug   15852\n 9 Sep   20509\n10 Oct   17288\n11 Nov   22994\n```\n\n\n:::\n:::\n\n\n\nThe `frogID_data` table contains **136,621 records** spanning January–November 2023, covering **186 unique species** across all Australian states and territories. A few immediate structural features stand out:\n\n- **New South Wales dominates the record count** (58,749 — 43% of all observations), likely reflecting both its large population of citizen scientists and the density of the FrogID app's user base along the eastern seaboard.\n- **Queensland leads in species richness** (96 unique species), consistent with its tropical biodiversity, even though NSW contributes far more raw observations.\n- **The seasonal signal is unmistakable.** November alone accounts for nearly 23,000 observations — over 16% of the annual total — while April–June are quietest. This spring peak reflects the southern hemisphere breeding season for most temperate species.\n- **Crinia signifera (Common Eastern Froglet)** accounts for 33,630 records — nearly 25% of all observations — making it by far the most-recorded species in this dataset.\n\n## frog_names — taxonomic lookup\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrog_names %>%\n  select(subfamily, tribe, scientificName, commonName) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |294        |\n|Number of columns        |4          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |4          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable  | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:--------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|subfamily      |         0|             1|   5|  13|     0|        5|          0|\n|tribe          |         0|             1|   8|  16|     0|        6|          0|\n|scientificName |         1|             1|   4|  39|     0|      292|          0|\n|commonName     |         0|             1|   1|  40|     0|      283|          0|\n\n\n:::\n\n```{.r .cell-code}\n# Subfamily breakdown\ncat(\"\\n=== Species count by subfamily ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n=== Species count by subfamily ===\n```\n\n\n:::\n\n```{.r .cell-code}\nfrog_names %>%\n  filter(str_detect(scientificName, \" \")) %>%  # binomial names only\n  count(subfamily, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  subfamily           n\n  <chr>           <int>\n1 \" Myobatrachid\"   139\n2 \" Hylid\"          101\n3 \" Microhylidae\"    24\n4 \" Ranid\"            1\n5 \" Toad\"             1\n```\n\n\n:::\n:::\n\n\n\nThe `frog_names` table is a 294-row taxonomic dictionary. Most entries belong to **Myobatrachidae** (ground frogs, endemic to Australia and New Guinea) and **Hylidae** (tree frogs). A handful of rows are genus-level entries without a species epithet — these need to be filtered out before joining to avoid many-to-many matches.\n\n# Seasonal Calling Phenology: When Do Australia's Frogs Sing?\n\nFrog calling is tightly coupled to breeding: males call to attract females, so call frequency spikes during the breeding season. In Australia, this creates a stark biogeographic divide:\n\n::: {.callout-note}\n**The north-south seasonal split.** Tropical frogs in Queensland and the Northern Territory breed during the wet season (November–April), triggered by monsoon rains. Temperate frogs in NSW, Victoria, and South Australia breed in spring and early summer (August–November), responding to warming temperatures. The FrogID data, collected across 2023, captures both signals simultaneously.\n:::\n\n## Species richness vs. observation effort by state\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstate_richness <- frog_data %>%\n  group_by(stateProvince) %>%\n  summarise(\n    n_species = n_distinct(scientificName),\n    n_obs     = n(),\n    .groups   = \"drop\"\n  ) %>%\n  arrange(desc(n_species))\n\ncat(\"Species richness and observation effort by state:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpecies richness and observation effort by state:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(state_richness)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 3\n  stateProvince                n_species n_obs\n  <chr>                            <int> <int>\n1 Queensland                          96 23334\n2 New South Wales                     70 58749\n3 Western Australia                   52 10844\n4 Northern Territory                  33  2380\n5 Victoria                            28 32383\n6 South Australia                     20  4158\n7 Australian Capital Territory        12  2082\n8 Tasmania                            11  2562\n9 Other Territories                    8   129\n```\n\n\n:::\n:::\n\n\n\nQueensland has 96 unique species — more than triple Victoria's 28 — yet NSW generates 2.5× more observations. This gap between *where frogs are* and *where people are looking* is the classic citizen-science sampling bias. The FrogID team explicitly accounts for this in their conservation analyses.\n\n## Constructing the seasonal calling calendar\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter frog_names to binomial species only to avoid genus-level many-to-many join\nfrog_names_sp <- frog_names %>%\n  filter(str_detect(scientificName, \" \")) %>%\n  select(scientificName, commonName) %>%\n  distinct(scientificName, .keep_all = TRUE)\n\n# Identify top 15 species by observation count\ntop15_species <- frog_data %>%\n  count(scientificName, sort = TRUE) %>%\n  head(15) %>%\n  pull(scientificName)\n\ncat(\"Top 15 species selected for heatmap:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTop 15 species selected for heatmap:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(top15_species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Crinia signifera\"           \"Limnodynastes peronii\"     \n [3] \"Litoria fallax\"             \"Litoria peronii\"           \n [5] \"Limnodynastes tasmaniensis\" \"Litoria ewingii\"           \n [7] \"Litoria verreauxii\"         \"Crinia parinsignifera\"     \n [9] \"Limnodynastes dumerilii\"    \"Litoria caerulea\"          \n[11] \"Crinia glauerti\"            \"Adelotus brevis\"           \n[13] \"Litoria adelaidensis\"       \"Litoria gracilenta\"        \n[15] \"Litoria pyrina\"            \n```\n\n\n:::\n\n```{.r .cell-code}\n# Build monthly proportion matrix for top 15 species\nmonthly_matrix <- frog_data %>%\n  filter(scientificName %in% top15_species) %>%\n  mutate(month_num = month(eventDate)) %>%\n  count(scientificName, month_num) %>%\n  group_by(scientificName) %>%\n  mutate(pct = n / sum(n)) %>%\n  ungroup()\n\n# Verify data integrity\ncat(sprintf(\"\\nmonthly_matrix: %d rows, %d cols\\n\", nrow(monthly_matrix), ncol(monthly_matrix)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nmonthly_matrix: 159 rows, 4 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Plot data has 0 rows\" = nrow(monthly_matrix) > 0)\n\n# Quick sanity check on proportions\ncat(\"Row sums per species (should all be ~1.0):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRow sums per species (should all be ~1.0):\n```\n\n\n:::\n\n```{.r .cell-code}\nmonthly_matrix %>%\n  group_by(scientificName) %>%\n  summarise(total_pct = sum(pct)) %>%\n  print(n = 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 2\n   scientificName             total_pct\n   <chr>                          <dbl>\n 1 Adelotus brevis                    1\n 2 Crinia glauerti                    1\n 3 Crinia parinsignifera              1\n 4 Crinia signifera                   1\n 5 Limnodynastes dumerilii            1\n 6 Limnodynastes peronii              1\n 7 Limnodynastes tasmaniensis         1\n 8 Litoria adelaidensis               1\n 9 Litoria caerulea                   1\n10 Litoria ewingii                    1\n11 Litoria fallax                     1\n12 Litoria gracilenta                 1\n13 Litoria peronii                    1\n14 Litoria pyrina                     1\n15 Litoria verreauxii                 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Determine peak calling month for each species (for ordering)\npeak_month <- monthly_matrix %>%\n  group_by(scientificName) %>%\n  slice_max(pct, n = 1, with_ties = FALSE) %>%\n  select(scientificName, peak_month = month_num)\n\n# Join common names\nmonthly_matrix <- monthly_matrix %>%\n  left_join(frog_names_sp, by = \"scientificName\") %>%\n  left_join(peak_month, by = \"scientificName\") %>%\n  mutate(\n    # Use common name where available; fall back to italicised scientific name\n    display_name = case_when(\n      !is.na(commonName) & commonName != \"—\" ~\n        paste0(commonName, \"\\n*\", scientificName, \"*\"),\n      TRUE ~\n        paste0(\"*\", scientificName, \"*\")\n    ),\n    # Order species by peak calling month\n    display_name = fct_reorder(display_name, peak_month),\n    month_abbr = factor(\n      month.abb[month_num],\n      levels = month.abb\n    )\n  )\n\ncat(\"\\nmonthly_matrix after join and mutate: \", nrow(monthly_matrix), \"rows\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nmonthly_matrix after join and mutate:  159 rows\n```\n\n\n:::\n:::\n\n\n\n# Visualisation: The Frog Calling Calendar\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Palette: scico::bamako (sequential, unused)\n# Low = dark navy/purple (quiet month), High = warm cream/gold (peak calling)\n\np <- ggplot2::ggplot(\n  monthly_matrix,\n  ggplot2::aes(x = month_abbr, y = display_name, fill = pct)\n) +\n  ggplot2::geom_tile(colour = \"white\", linewidth = 0.4) +\n  # Annotate the spring and wet-season peaks\n  ggplot2::annotate(\n    \"rect\",\n    xmin = 8.5, xmax = 11.5,\n    ymin = 0.5, ymax = 15.5,\n    fill = NA, colour = \"#F5D76E\", linewidth = 0.7, linetype = \"dashed\",\n    alpha = 0.5\n  ) +\n  ggplot2::annotate(\n    \"text\",\n    x = 10, y = 15.7,\n    label = \"Southern spring\\nbreeding season\",\n    colour = \"#F5D76E\", size = 3, fontface = \"bold\", hjust = 0.5\n  ) +\n  paletteer::scale_fill_paletteer_c(\n    \"scico::bamako\",\n    direction  = -1,\n    labels     = scales::label_percent(accuracy = 1),\n    name       = \"% of annual\\nobservations\",\n    guide      = ggplot2::guide_colorbar(\n      barwidth  = 0.6,\n      barheight = 8,\n      title.position = \"top\"\n    )\n  ) +\n  ggplot2::scale_x_discrete(expand = ggplot2::expansion(0, 0)) +\n  ggplot2::scale_y_discrete(expand = ggplot2::expansion(0, 0)) +\n  ggplot2::labs(\n    title    = \"When Australia's Frogs Call\",\n    subtitle = \"Monthly calling activity (as % of annual observations) for the 15 most-recorded species in the 2023 FrogID citizen-science survey.\\nSpecies ordered by peak calling month. Dashed box = southern hemisphere spring.\",\n    x        = NULL,\n    y        = NULL,\n    caption  = \"Source: FrogID 2023 Annual Data Release via TidyTuesday (2025-09-02) · Palette: scico::bamako\"\n  ) +\n  ggplot2::theme_minimal(base_size = 11) +\n  ggplot2::theme(\n    plot.title         = ggplot2::element_text(face = \"bold\", size = 17, margin = ggplot2::margin(b = 4)),\n    plot.subtitle      = ggtext::element_textbox_simple(\n                           size = 9, colour = \"grey40\",\n                           margin = ggplot2::margin(b = 12), lineheight = 1.3\n                         ),\n    plot.caption       = ggplot2::element_text(colour = \"grey55\", size = 7.5, margin = ggplot2::margin(t = 8)),\n    axis.text.y        = ggtext::element_markdown(size = 8.5, hjust = 1),\n    axis.text.x        = ggplot2::element_text(size = 9, face = \"bold\"),\n    panel.grid         = ggplot2::element_blank(),\n    legend.title       = ggplot2::element_text(size = 8),\n    legend.text        = ggplot2::element_text(size = 7.5),\n    plot.margin        = ggplot2::margin(12, 16, 12, 12)\n  )\n\np\n```\n\n::: {.cell-output-display}\n![](2025-09-02-australian-frogs_files/figure-html/hero-plot-heatmap-1.png){width=1056}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n# Final thoughts and takeaways\n\nThe heatmap makes a few things immediately clear:\n\n**1. Spring is frog season — for most species.** The dashed box covering August–November captures the peak calling period for the majority of the top-15 species. This aligns with the southern hemisphere spring, when temperatures warm and rains arrive across eastern Australia. *Crinia signifera* (Common Eastern Froglet), which alone accounts for 25% of all observations, is remarkably evenly spread across the year but shows a sharp November peak.\n\n**2. The tropical outliers stand out.** *Uperoleia* species and Queensland-heavy frogs (appearing lower in the ordered list) show relatively flat or early-year distributions, hinting at the wet-season breeding calendar of tropical Australia — though the citizen-science sampling bias toward NSW blunts this signal in the aggregate data.\n\n**3. Citizen science has a seasonality of its own.** The November surge isn't only frogs calling more — it's also people going outside more. Disentangling phenological signal from observer effort is a persistent challenge in FrogID analyses. The research team publishes annual corrections for this bias, which is partly why FrogID requires expert acoustic verification rather than relying solely on observer labels.\n\n**4. 186 species in a single year is remarkable — and not enough.** The 2023 dataset captures less than three-quarters of Australia's 257 native frog species. Many threatened species are either in remote areas with few citizen scientists or have such small remaining populations that detection is rare. The FrogID app is actively working to close this gap, but it also underlines why the 33,000+ *Crinia signifera* records coexist with species recorded only once or twice in the entire dataset.\n\n::: {.callout-tip}\n**For your own exploration:** The latitude and longitude fields in `frogID_data` are rich but deliberately coarsened (10,000m uncertainty buffers) for sensitive species. Even so, mapping species range limits — particularly the northern boundary of temperate species or the southern edge of tropical ones — against the calling calendar would be a compelling follow-up.\n:::\n",
    "supporting": [
      "2025-09-02-australian-frogs_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}