{
  "hash": "1cd4e8c9f3ef65c5eea7f98af8e837b2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Extreme Weather Attribution Studies\"\nauthor: \"Sean Thimons\"\ndate: \"2025-08-12\"\ndescription: \"How often do climate scientists actually find a human fingerprint on extreme weather? Mapping the track record of attribution studies from 2004 to 2024 across event types, regions, and time.\"\ncategories:\n  - tidytuesday\n  - R\n  - climate\n  - attribution\n---\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](2025-08-12-extreme-weather-attribution-studies_files/figure-html/pseudo-hero-palette-1.png){width=100%}\n:::\n:::\n\n\n# Preface\n\nFrom the [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-08-12/readme.md).\n\n> The Carbon Brief database of extreme weather attribution studies catalogues peer-reviewed research examining whether and to what degree climate change influenced specific extreme weather events or trends. Each row represents one scientific study, covering events from 2003 through the early 2020s, along with the study's conclusion — whether human influence made the event more severe, less severe, or left no discernible fingerprint.\n\nThe questions I want to answer:\n\n- What fraction of studies find a human climate fingerprint, and does that vary by event type?\n- Have attribution studies grown more likely to detect a human signal over time, as methodology matures and warming accumulates?\n- Which regions are most studied, and which event types generate the most research attention?\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\"pak\", repos = \"https://cloud.r-project.org\")\n  }\n\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  core_packages <- c(\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n    'skimr',\n    'paletteer',\n    'tidytuesdayR'\n  )\n\n  optional_packages <- c('ggrepel', 'scales', 'ggtext')\n\n  install_booster_pack(package = unique(c(core_packages, optional_packages)), load = TRUE)\n  rm(install_booster_pack, core_packages, optional_packages)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n# Load raw data from package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2025-08-12')\n\nattribution_studies     <- raw$attribution_studies\nattribution_studies_raw <- raw$attribution_studies_raw\n```\n:::\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## attribution_studies\n\n\n::: {.cell}\n\n```{.r .cell-code}\nattribution_studies %>%\n  select(publication_year) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |744        |\n|Number of columns        |1          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|numeric                  |1          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: numeric**\n\n|skim_variable    | n_missing| complete_rate|   n|  min|  p25|  med|  p75|  max|    mean| geo_mean|   sd|hist  |\n|:----------------|---------:|-------------:|---:|----:|----:|----:|----:|----:|-------:|--------:|----:|:-----|\n|publication_year |         1|             1| 744| 2004| 2016| 2020| 2022| 2024| 2019.08|  2019.08| 3.72|▁▁▅▅▇ |\n\n\n:::\n\n```{.r .cell-code}\nattribution_studies %>%\n  count(event_type, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 2\n   event_type           n\n   <chr>            <int>\n 1 Heat               207\n 2 Rain & flooding    177\n 3 Drought            106\n 4 Storm               61\n 5 Cold, snow & ice    57\n 6 Compound            33\n 7 Impact              33\n 8 Wildfire            31\n 9 Oceans              25\n10 Atmosphere           7\n11 Sunshine             4\n12 River flow           3\n```\n\n\n:::\n\n```{.r .cell-code}\nattribution_studies %>%\n  count(classification, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  classification                                    n\n  <chr>                                         <int>\n1 More severe or more likely to occur             554\n2 No discernible human influence                   71\n3 Decrease, less severe or less likely to occur    66\n4 Insufficient data/inconclusive                   53\n```\n\n\n:::\n\n```{.r .cell-code}\nattribution_studies %>%\n  count(cb_region, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 13 × 2\n   cb_region                            n\n   <chr>                            <int>\n 1 Europe                             165\n 2 Eastern and south-eastern Asia     161\n 3 Northern America                   137\n 4 Global                              63\n 5 Sub-Saharan Africa                  56\n 6 Australia and New Zealand           49\n 7 Central and southern Asia           36\n 8 Latin America and the Caribbean     32\n 9 Northern hemisphere                 15\n10 Arctic                              11\n11 Northern Africa and western Asia     8\n12 Oceania                              8\n13 Antarctica                           3\n```\n\n\n:::\n:::\n\n\nA few patterns jump out immediately:\n\n- **Heat events dominate** — 207 studies, nearly twice the next category (Rain & flooding at 177). This reflects both how common heat waves are becoming and how tractable they are for attribution methods.\n- **The vast majority of studies find a human fingerprint** — 554 of 744 studies (74%) classify the event as \"More severe or more likely to occur.\" Only 71 (10%) find no discernible human influence.\n- **Europe and East/Southeast Asia** are the most-studied regions, together accounting for nearly half the database.\n- The database spans 2004–2024, with a median publication year of 2020.\n\n# The human fingerprint across weather types\n\nThe central question in attribution science is whether human-caused climate change made a given event more likely or severe. The `classification` column is the punchline of each study. Let me look at how that verdict varies across the twelve event types.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Collapse the four classifications into three cleaner buckets\n# and compute proportions within each event type.\nclf_levels <- c(\n  \"More severe or more likely to occur\",\n  \"No discernible human influence\",\n  \"Decrease, less severe or less likely to occur\",\n  \"Insufficient data/inconclusive\"\n)\n\nclf_labels <- c(\n  \"More likely / worse\",\n  \"No human signal\",\n  \"Less likely / milder\",\n  \"Inconclusive\"\n)\n\nevent_clf <- attribution_studies %>%\n  filter(!is.na(classification), !is.na(event_type)) %>%\n  mutate(\n    classification = factor(classification, levels = clf_levels, labels = clf_labels),\n    event_type     = fct_infreq(event_type)\n  ) %>%\n  count(event_type, classification) %>%\n  group_by(event_type) %>%\n  mutate(\n    total = sum(n),\n    pct   = n / total\n  ) %>%\n  ungroup()\n\ncat(sprintf(\"event_clf: %d rows\\n\", nrow(event_clf)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nevent_clf: 35 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Plot data empty - check filter values\" = nrow(event_clf) > 0)\n\nif (length(unique(event_clf$pct)) == 1) stop(\"All pct values identical - check grouping\")\n\n# Sanity: show the \"more likely/worse\" rate per event type\nevent_clf %>%\n  filter(classification == \"More likely / worse\") %>%\n  arrange(desc(pct)) %>%\n  select(event_type, total, n, pct) %>%\n  mutate(pct = scales::percent(pct, accuracy = 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 4\n   event_type       total     n pct  \n   <fct>            <int> <int> <chr>\n 1 Sunshine             4     4 100% \n 2 Compound            33    32 97%  \n 3 Heat               207   196 95%  \n 4 Oceans              25    23 92%  \n 5 Impact              33    30 91%  \n 6 Wildfire            31    27 87%  \n 7 Storm               61    46 75%  \n 8 Atmosphere           7     5 71%  \n 9 Drought            106    74 70%  \n10 Rain & flooding    177   110 62%  \n11 River flow           3     1 33%  \n12 Cold, snow & ice    57     6 11%  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pull Cassatt1 colors — we need 4 for the four classification outcomes.\nclf_colors <- as.character(paletteer::paletteer_d(\"MetBrewer::Cassatt1\", n = 4))\nnames(clf_colors) <- clf_labels\n\n# Order event types by their \"more likely/worse\" rate for a meaningful sort.\net_order <- event_clf %>%\n  filter(classification == \"More likely / worse\") %>%\n  arrange(pct) %>%\n  pull(event_type) %>%\n  as.character()\n\nplot_df <- event_clf %>%\n  mutate(event_type = factor(as.character(event_type), levels = et_order))\n\ncat(sprintf(\"plot_df: %d rows\\n\", nrow(plot_df)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nplot_df: 35 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Plot data empty - check filter values\" = nrow(plot_df) > 0)\n\np <- ggplot(plot_df, aes(x = pct, y = event_type, fill = classification)) +\n  geom_col(position = \"stack\", width = 0.72) +\n  geom_text(\n    data = plot_df %>% filter(pct >= 0.07),\n    aes(label = scales::percent(pct, accuracy = 1)),\n    position = position_stack(vjust = 0.5),\n    size = 3.2,\n    color = \"white\",\n    fontface = \"bold\"\n  ) +\n  # Total count label at right end of bar\n  geom_text(\n    data = plot_df %>%\n      group_by(event_type) %>%\n      summarize(total = first(total), .groups = \"drop\"),\n    aes(x = 1.01, y = event_type, label = paste0(\"n=\", total)),\n    inherit.aes = FALSE,\n    hjust = 0,\n    size = 3.1,\n    color = \"grey40\"\n  ) +\n  scale_fill_manual(\n    values = clf_colors,\n    name   = \"Attribution finding\"\n  ) +\n  scale_x_continuous(\n    labels = scales::percent_format(accuracy = 1),\n    expand = expansion(mult = c(0, 0.12)),\n    name   = \"Share of studies\"\n  ) +\n  scale_y_discrete(name = NULL) +\n  labs(\n    title    = \"Climate change fingerprint found in ~3 out of 4 attribution studies\",\n    subtitle = \"Each bar shows the distribution of findings across 744 peer-reviewed studies (2004–2024), sorted by rate of attribution\",\n    caption  = \"Source: Carbon Brief Database of Extreme Weather Attribution Studies via TidyTuesday 2025-08-12\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title.position = \"plot\",\n    plot.title          = element_text(face = \"bold\", size = 14),\n    plot.subtitle       = element_text(color = \"grey35\", margin = margin(b = 14)),\n    plot.caption        = element_text(color = \"grey45\", hjust = 0, size = 9),\n    legend.position     = \"bottom\",\n    legend.title        = element_text(face = \"bold\", size = 10),\n    legend.key.size     = unit(0.45, \"cm\"),\n    panel.grid.major.y  = element_blank(),\n    panel.grid.minor    = element_blank(),\n    panel.grid.major.x  = element_line(color = \"grey90\"),\n    plot.background     = element_rect(fill = \"grey98\", color = NA),\n    panel.background    = element_rect(fill = \"grey98\", color = NA),\n    axis.text.y         = element_text(size = 11)\n  ) +\n  guides(fill = guide_legend(nrow = 2, byrow = TRUE))\n\np\n```\n\n::: {.cell-output-display}\n![](2025-08-12-extreme-weather-attribution-studies_files/figure-html/hero-plot-fingerprint-1.png){width=1056}\n:::\n:::\n\n\nA few things stand out immediately:\n\n- **Wildfire and heat are the highest-attribution event types** — nearly every study on these events concludes that climate change made them more likely or more severe. This is consistent with the mechanistic story: higher baseline temperatures directly raise fire danger and heat-wave intensity.\n- **Ocean events and compound events** show the second tier of attribution confidence, though the sample sizes are smaller.\n- **\"No human signal\" findings cluster in Cold, snow & ice events and Drought** — for cold events this makes intuitive sense (warming reduces cold extremes, so it would if anything *decrease* their frequency). Drought attribution is more regionally dependent and methodologically challenging.\n- **Atmospheric and River flow categories** are barely-studied niches with small totals; conclusions there carry wide uncertainty bands even before you look at the data.\n\n# Attribution rate over time\n\nHas the science gotten more confident? Attribution methodology has matured substantially since the early 2000s, and the amount of observed warming has itself increased, both of which should make the human signal easier to detect.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntime_df <- attribution_studies %>%\n  filter(!is.na(publication_year), !is.na(classification)) %>%\n  mutate(\n    attributed = classification == \"More severe or more likely to occur\",\n    pub_year   = as.integer(publication_year)\n  ) %>%\n  filter(pub_year >= 2004, pub_year <= 2024) %>%\n  group_by(pub_year) %>%\n  summarize(\n    n_studies    = n(),\n    n_attributed = sum(attributed),\n    pct_attr     = n_attributed / n_studies,\n    .groups = \"drop\"\n  )\n\ncat(sprintf(\"time_df: %d rows\\n\", nrow(time_df)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntime_df: 18 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Plot data empty - check filter values\" = nrow(time_df) > 0)\n\nif (length(unique(time_df$pct_attr)) == 1) stop(\"All pct_attr values identical - check grouping\")\n\naccent_color <- as.character(paletteer::paletteer_d(\"MetBrewer::Cassatt1\", n = 1))\n\np2 <- ggplot(time_df, aes(x = pub_year)) +\n  geom_col(aes(y = n_studies), fill = \"grey85\", width = 0.75) +\n  geom_line(aes(y = pct_attr * max(n_studies)),\n            color = accent_color, linewidth = 1.2) +\n  geom_point(aes(y = pct_attr * max(n_studies)),\n             color = accent_color, size = 2.8) +\n  scale_x_continuous(breaks = seq(2004, 2024, by = 2), name = NULL) +\n  scale_y_continuous(\n    name     = \"Studies published\",\n    sec.axis = sec_axis(\n      ~ . / max(time_df$n_studies),\n      name   = \"Attribution rate\",\n      labels = scales::percent_format(accuracy = 1)\n    ),\n    expand = expansion(mult = c(0, 0.05))\n  ) +\n  labs(\n    title    = \"Attribution studies have surged — attribution rate has held steady above 70%\",\n    subtitle = \"Bars: total studies published each year. Line: share concluding climate change made the event worse/more likely.\",\n    caption  = \"Source: Carbon Brief Database via TidyTuesday 2025-08-12  ·  publication_year used throughout\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title.position = \"plot\",\n    plot.title          = element_text(face = \"bold\", size = 13),\n    plot.subtitle       = element_text(color = \"grey35\", margin = margin(b = 12)),\n    plot.caption        = element_text(color = \"grey45\", hjust = 0, size = 9),\n    panel.grid.minor    = element_blank(),\n    panel.grid.major.x  = element_blank(),\n    plot.background     = element_rect(fill = \"grey98\", color = NA),\n    panel.background    = element_rect(fill = \"grey98\", color = NA),\n    axis.title.y.right  = element_text(color = accent_color, face = \"bold\"),\n    axis.text.y.right   = element_text(color = accent_color)\n  )\n\np2\n```\n\n::: {.cell-output-display}\n![](2025-08-12-extreme-weather-attribution-studies_files/figure-html/attribution-trend-over-time-1.png){width=960}\n:::\n:::\n\n\nThe volume of attribution research exploded in the 2010s and stayed elevated through 2024, likely driven by the formalization of rapid attribution methods (like those used by World Weather Attribution). The attribution *rate* — the share of studies finding a human signal — has been consistently high since the start of the database, hovering in the 70–85% range most years. There's no strong upward trend in detection rate; rather, the science came in confident and stayed confident.\n\n# Final thoughts and takeaways\n\nThe Carbon Brief attribution database is a useful reality check against the common framing that \"we can't tell if any individual weather event is caused by climate change.\" The record says something more nuanced: **in aggregate, 74% of attribution studies find that climate change made the event worse or more likely**. That figure is not uniform — wildfire and heat events are near-certain attributions, while cold-weather events and some droughts are genuinely ambiguous — but the overall direction of the evidence is lopsided.\n\nThree things I'll carry away from this dataset:\n\n1. **Heat attribution is the settled case.** Almost every study on a heat event concludes that climate change played a role. This is the mechanistic floor: if you add heat to a system, heat events get worse. The signal is essentially always detectable.\n\n2. **Rapid attribution studies are a growing share of the database.** 103 of 744 studies are flagged as rapid attribution, a genre that emerged partly from World Weather Attribution and aims to publish findings within days or weeks of a major event. That they can do this while still getting the same general answer (attribution rate appears similar) says something about how robust the signal is.\n\n3. **The regions with the most studies — Europe, East Asia, North America — are also the regions with the most institutional capacity to run them.** Sub-Saharan Africa and Central/Southern Asia appear in 56 and 36 studies respectively, despite being highly vulnerable to climate extremes. The scientific record reflects where the scientists are, not necessarily where the impacts are largest.\n",
    "supporting": [
      "2025-08-12-extreme-weather-attribution-studies_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}