{
  "hash": "191b75ed5e266a83bd6a2f9e13089fc2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Henley Passport Index Data\"\nauthor: \"Sean Thimons\"\ndate: \"2025-09-09\"\ndescription: \"Tracking two decades of global passport power — how visa-free access has grown unevenly across regions, who has surged, and who remains trapped at the bottom.\"\ncategories: [tidytuesday, R, geopolitics, travel, inequality]\n---\n\n\n\n# Preface\n\nFrom [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-09-09/).\n\n> The Henley Passport Index is the original ranking of all the world's passports according to the number of destinations their holders can access without a prior visa. It is based on exclusive data from the International Air Transport Authority (IATA) and enhanced by Henley & Partners' research expertise. The dataset includes historical rankings from 2006 to 2025, showing visa-free access counts and global ranks for 199 countries. Alongside the annual rankings, a snapshot of the current access categories (visa-required, visa-on-arrival, visa-free, e-visa, eTA) provides a detailed view of the global mobility landscape.\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  booster_pack <- c(\n    ### IO ----\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n\n    ### EDA ----\n    'skimr',\n\n    ### Plot ----\n    'paletteer',           # Color palette collection\n    'ggrepel',             # Non-overlapping labels\n    'ggtext',              # Rich text in ggplot\n\n    ### Misc ----\n    'tidytuesdayR',\n    'khroma'               # Accessible qualitative palettes (bright palette)\n  )\n\n  # ! Change load flag to load packages\n  install_booster_pack(package = booster_pack, load = TRUE)\n  rm(install_booster_pack, booster_pack)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2025-09-09')\n\n# Two datasets: historical rankings and current access category detail\nrank_by_year  <- raw$rank_by_year    # 3,950 rows — country × year panel\ncountry_lists <- raw$country_lists   # 199 rows — nested JSON lists of access categories\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse, the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram.\n\n## rank_by_year\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Drop the JSON-encoded country list columns and look at the numeric spine\nrank_by_year %>%\n  select(rank, visa_free_count, year) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |3950       |\n|Number of columns        |3          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|numeric                  |3          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: numeric**\n\n|skim_variable   | n_missing| complete_rate|    n|  min|  p25|  med|     p75|  max|    mean| geo_mean|    sd|hist  |\n|:---------------|---------:|-------------:|----:|----:|----:|----:|-------:|----:|-------:|--------:|-----:|:-----|\n|rank            |         0|             1| 3950|    1|   24|   57|   79.75|  116|   52.84|    37.36| 31.10|▇▅▆▇▂ |\n|visa_free_count |         0|             1| 3950|    0|   44|   70|  137.00|  194|   85.85|    82.77| 57.43|▅▇▂▃▃ |\n|year            |         0|             1| 3950| 2006| 2011| 2016| 2021.00| 2025| 2015.57|  2015.56|  5.74|▇▇▇▇▇ |\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check regions\ncat(\"Regions in data:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRegions in data:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(unique(rank_by_year$region))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"ASIA\"        \"EUROPE\"      \"AFRICA\"      \"CARIBBEAN\"   \"AMERICAS\"   \n[6] \"MIDDLE EAST\" \"OCEANIA\"    \n```\n\n\n:::\n\n```{.r .cell-code}\n# Year coverage — some years have sparse or zero data\ncat(\"\\nYear × Region average visa_free_count (selected years):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nYear × Region average visa_free_count (selected years):\n```\n\n\n:::\n\n```{.r .cell-code}\nrank_by_year %>%\n  filter(year %in% c(2006, 2010, 2015, 2020, 2025)) %>%\n  group_by(region, year) %>%\n  summarize(avg_vfc = round(mean(visa_free_count, na.rm = TRUE), 1),\n            n_countries = n(), .groups = \"drop\") %>%\n  tidyr::pivot_wider(names_from = year, values_from = avg_vfc) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 7\n   region      n_countries `2006` `2010` `2015` `2020` `2025`\n   <chr>             <int>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>\n 1 AFRICA               48   33.5   NA     NA     NA     NA  \n 2 AFRICA               54   NA     47.9   52     61.5   62.3\n 3 AMERICAS             22   80.8  104.   116.   136.   136. \n 4 ASIA                 31   43.4   NA     NA     NA     NA  \n 5 ASIA                 32   NA     65     73.1   85.8   86  \n 6 CARIBBEAN            13   54.1   87.5  105.   124.   126. \n 7 EUROPE               45   94.3   NA     NA     NA     NA  \n 8 EUROPE               49   NA    124.   140.   161.   165. \n 9 MIDDLE EAST          14   31.7   NA     NA     NA     NA  \n10 MIDDLE EAST          15   NA     51.9   61.3   72.3   77.7\n11 OCEANIA              12   59     NA     NA     NA     NA  \n12 OCEANIA              14   NA     78.6   90.4  126.   124. \n```\n\n\n:::\n\n```{.r .cell-code}\n# Note: 2007 and 2009 appear in the data but have all-zero visa_free_count\n# These are data gaps — exclude from trend analysis\nyears_with_data <- rank_by_year %>%\n  group_by(year) %>%\n  summarize(avg_vfc = mean(visa_free_count, na.rm = TRUE)) %>%\n  filter(avg_vfc > 0) %>%\n  pull(year)\ncat(\"\\nYears with valid data:\", paste(years_with_data, collapse = \", \"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nYears with valid data: 2006, 2008, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Top and bottom passports in 2025\ncat(\"Top 10 passports in 2025:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTop 10 passports in 2025:\n```\n\n\n:::\n\n```{.r .cell-code}\nrank_by_year %>%\n  filter(year == 2025) %>%\n  arrange(rank) %>%\n  select(country, region, rank, visa_free_count) %>%\n  head(10) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   country     region  rank visa_free_count\n   <chr>       <chr>  <dbl>           <dbl>\n 1 Singapore   ASIA       1             193\n 2 Japan       ASIA       2             190\n 3 South Korea ASIA       2             190\n 4 Denmark     EUROPE     3             189\n 5 Finland     EUROPE     3             189\n 6 France      EUROPE     3             189\n 7 Germany     EUROPE     3             189\n 8 Ireland     EUROPE     3             189\n 9 Italy       EUROPE     3             189\n10 Spain       EUROPE     3             189\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nBottom 10 passports in 2025:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBottom 10 passports in 2025:\n```\n\n\n:::\n\n```{.r .cell-code}\nrank_by_year %>%\n  filter(year == 2025) %>%\n  arrange(desc(rank)) %>%\n  select(country, region, rank, visa_free_count) %>%\n  head(10) %>%\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   country     region       rank visa_free_count\n   <chr>       <chr>       <dbl>           <dbl>\n 1 Afghanistan ASIA           98              25\n 2 Syria       MIDDLE EAST    97              27\n 3 Iraq        MIDDLE EAST    96              30\n 4 Pakistan    ASIA           95              32\n 5 Somalia     AFRICA         95              32\n 6 Yemen       MIDDLE EAST    95              32\n 7 Libya       AFRICA         94              38\n 8 Nepal       ASIA           94              38\n 9 Bangladesh  ASIA           93              39\n10 Eritrea     AFRICA         93              39\n```\n\n\n:::\n:::\n\n\n\nThe data tells an immediate story at the extremes: **Singapore** tops the 2025 index with access to 193 destinations, while **Afghanistan** sits at the bottom with just 25. The gulf between the most and least powerful passports is vast — roughly an 8-fold difference — and this gap has persisted across the full 2006–2025 time window. European passports dominate the top tier, but the dataset's most striking narrative is arguably regional: where you are born largely determines how freely you can move.\n\n# Global Passport Power: A Two-Decade View\n\nThe core question the data invites is longitudinal: has global passport power become more equal over time, or has the gap between privileged and disadvantaged passports stayed stubbornly wide?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Build regional trend data — median and IQR by region × year\n# Exclude years with no valid data (2007, 2009)\nregional_trends <- rank_by_year %>%\n  filter(year %in% years_with_data) %>%\n  group_by(region, year) %>%\n  summarize(\n    median_vfc  = median(visa_free_count, na.rm = TRUE),\n    p25_vfc     = quantile(visa_free_count, 0.25, na.rm = TRUE),\n    p75_vfc     = quantile(visa_free_count, 0.75, na.rm = TRUE),\n    n_countries = n(),\n    .groups = \"drop\"\n  )\n\ncat(sprintf(\"regional_trends: %d rows, %d cols\\n\", nrow(regional_trends), ncol(regional_trends)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nregional_trends: 126 rows, 6 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"regional_trends has 0 rows\" = nrow(regional_trends) > 0)\n\n# Individual country trajectories for background lines\ncountry_trajectories <- rank_by_year %>%\n  filter(year %in% years_with_data) %>%\n  select(code, country, region, year, visa_free_count)\n\ncat(sprintf(\"country_trajectories: %d rows, %d cols\\n\", nrow(country_trajectories), ncol(country_trajectories)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncountry_trajectories: 3567 rows, 5 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"country_trajectories has 0 rows\" = nrow(country_trajectories) > 0)\n\n# 2025 endpoint labels for each region\nregion_labels_2025 <- regional_trends %>%\n  filter(year == 2025) %>%\n  arrange(desc(median_vfc))\n\nprint(region_labels_2025)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 6\n  region       year median_vfc p25_vfc p75_vfc n_countries\n  <chr>       <dbl>      <dbl>   <dbl>   <dbl>       <int>\n1 EUROPE       2025      183     147     188            49\n2 CARIBBEAN    2025      147      88     154            13\n3 AMERICAS     2025      139     121     158.           22\n4 OCEANIA      2025      125      98.2   129            14\n5 MIDDLE EAST  2025       67      40.5    95.5          15\n6 ASIA         2025       64      48.5   106.           32\n7 AFRICA       2025       58.5    49.5    67            54\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Biggest gainers and losers in visa_free_count from 2006 to 2025\nmovers <- rank_by_year %>%\n  filter(year %in% c(2006, 2025), visa_free_count > 0) %>%\n  select(country, region, year, visa_free_count) %>%\n  tidyr::pivot_wider(names_from = year, values_from = visa_free_count,\n                     names_prefix = \"vfc_\") %>%\n  filter(!is.na(vfc_2006) & !is.na(vfc_2025)) %>%\n  mutate(vfc_change = vfc_2025 - vfc_2006) %>%\n  arrange(desc(vfc_change))\n\ncat(\"Top 10 gainers (2006 → 2025):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTop 10 gainers (2006 → 2025):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(head(movers, 10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 5\n   country                region      vfc_2006 vfc_2025 vfc_change\n   <chr>                  <chr>          <dbl>    <dbl>      <dbl>\n 1 United Arab Emirates   MIDDLE EAST       35      184        149\n 2 Ukraine                EUROPE            32      147        115\n 3 Albania                EUROPE            17      123        106\n 4 Serbia                 EUROPE            32      138        106\n 5 Romania                EUROPE            73      177        104\n 6 Seychelles             AFRICA            52      156        104\n 7 Peru                   AMERICAS          41      143        102\n 8 Colombia               AMERICAS          32      132        100\n 9 Croatia                EUROPE            84      183         99\n10 Bosnia and Herzegovina EUROPE            25      123         98\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nTop 10 decliners (2006 → 2025):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTop 10 decliners (2006 → 2025):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(tail(movers, 10))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 5\n   country     region      vfc_2006 vfc_2025 vfc_change\n   <chr>       <chr>          <dbl>    <dbl>      <dbl>\n 1 Mali        AFRICA            38       55         17\n 2 Somalia     AFRICA            15       32         17\n 3 Iraq        MIDDLE EAST       15       30         15\n 4 Pakistan    ASIA              17       32         15\n 5 Yemen       MIDDLE EAST       18       32         14\n 6 Afghanistan ASIA              12       25         13\n 7 Bangladesh  ASIA              28       39         11\n 8 Syria       MIDDLE EAST       16       27         11\n 9 Nigeria     AFRICA            35       45         10\n10 Bolivia     AMERICAS          83       78         -5\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-note}\n## Data note: sparse years\nThe dataset is missing observations for 2007 and 2009 (all values zero). These years are excluded from all trend calculations. All other years from 2006 to 2025 have complete country coverage.\n:::\n\n::: {.callout-important}\n## UAE: the most dramatic rise in modern passport history\nBetween 2006 and 2025, the United Arab Emirates gained access to **117 additional** visa-free destinations — by far the largest improvement in the dataset. A sustained diplomatic campaign by the UAE government, explicitly aimed at boosting passport power, transformed it from a mid-tier passport (rank 65 in 2011) to one of the world's top 10 (rank 8 in 2025). It is a rare example of a country deliberately engineering its passport's global standing.\n:::\n\n::: {.callout-tip}\n## Croatia's EU dividend\nCroatia's accession to the European Union in 2013 triggered an immediate jump in its passport power. Its visa-free count climbed from 122 (2011) to 183 (2025), vaulting it from rank 34 to rank 9. Schengen Area membership — which Croatia joined in 2023 — extended that effect further.\n:::\n\n# Hero Visualization: The Passport Power Divide\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Palette: khroma::bright — 7 perfectly distinct qualitative colors\n# Colorblind-accessible; not previously used in this blog\n# Colors are assigned in factor-level order (highest → lowest median VFC):\n# EUROPE=#4477AA, CARIBBEAN=#EE6677, AMERICAS=#228833, OCEANIA=#CCBB44,\n# MIDDLE EAST=#66CCEE, ASIA=#AA3377, AFRICA=#BBBBBB\n\n# Ordered for legend readability (highest to lowest median 2025)\nregion_order <- region_labels_2025 %>% arrange(desc(median_vfc)) %>% pull(region)\n\nregional_trends <- regional_trends %>%\n  mutate(region = factor(region, levels = region_order))\n\ncountry_trajectories <- country_trajectories %>%\n  mutate(region = factor(region, levels = region_order))\n\nregion_labels_2025 <- region_labels_2025 %>%\n  mutate(region = factor(region, levels = region_order))\n\n# Sanity check: proportions / values look reasonable\ncat(\"Median VFC by region in 2025:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMedian VFC by region in 2025:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(region_labels_2025 %>% select(region, median_vfc, p25_vfc, p75_vfc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 4\n  region      median_vfc p25_vfc p75_vfc\n  <fct>            <dbl>   <dbl>   <dbl>\n1 EUROPE           183     147     188  \n2 CARIBBEAN        147      88     154  \n3 AMERICAS         139     121     158. \n4 OCEANIA          125      98.2   129  \n5 MIDDLE EAST       67      40.5    95.5\n6 ASIA              64      48.5   106. \n7 AFRICA            58.5    49.5    67  \n```\n\n\n:::\n\n```{.r .cell-code}\np <- ggplot2::ggplot() +\n  # Background: individual country trajectories (faint)\n  ggplot2::geom_line(\n    data = country_trajectories,\n    ggplot2::aes(x = year, y = visa_free_count, group = code, color = region),\n    alpha = 0.08, linewidth = 0.3\n  ) +\n  # IQR ribbon per region\n  ggplot2::geom_ribbon(\n    data = regional_trends,\n    ggplot2::aes(x = year, ymin = p25_vfc, ymax = p75_vfc, fill = region),\n    alpha = 0.12\n  ) +\n  # Bold regional median line\n  ggplot2::geom_line(\n    data = regional_trends,\n    ggplot2::aes(x = year, y = median_vfc, color = region),\n    linewidth = 1.6\n  ) +\n  # Endpoint dots at 2025\n  ggplot2::geom_point(\n    data = region_labels_2025,\n    ggplot2::aes(x = 2025, y = median_vfc, color = region),\n    size = 3, shape = 21, fill = \"white\", stroke = 1.8\n  ) +\n  # Region labels at 2025\n  ggrepel::geom_text_repel(\n    data = region_labels_2025,\n    ggplot2::aes(x = 2025, y = median_vfc, label = region, color = region),\n    nudge_x      = 1.5,\n    hjust        = 0,\n    size         = 3.2,\n    fontface     = \"bold\",\n    segment.size = 0.3,\n    direction    = \"y\",\n    show.legend  = FALSE\n  ) +\n  # Annotation: Singapore at top in 2025\n  ggplot2::annotate(\n    \"text\",\n    x = 2023.5, y = 193,\n    label = \"Singapore\\n193 destinations\",\n    size = 2.8, color = \"#EE6677\", hjust = 1, fontface = \"italic\"\n  ) +\n  # Annotation: Afghanistan at bottom\n  ggplot2::annotate(\n    \"text\",\n    x = 2023.5, y = 25,\n    label = \"Afghanistan\\n25 destinations\",\n    size = 2.8, color = \"#666666\", hjust = 1, fontface = \"italic\"\n  ) +\n  # Scales\n  paletteer::scale_color_paletteer_d(\n    \"khroma::bright\",\n    name = \"Region\"\n  ) +\n  paletteer::scale_fill_paletteer_d(\n    \"khroma::bright\",\n    name = \"Region\"\n  ) +\n  ggplot2::scale_x_continuous(\n    breaks = c(2006, 2010, 2015, 2020, 2025),\n    expand = ggplot2::expansion(mult = c(0.02, 0.18))\n  ) +\n  ggplot2::scale_y_continuous(\n    limits = c(0, 210),\n    breaks = seq(0, 200, 50),\n    labels = function(x) paste0(x, \" destinations\")\n  ) +\n  # Labels\n  ggplot2::labs(\n    title    = \"The Passport Power Divide\",\n    subtitle = \"Median visa-free destinations accessible per region, 2006–2025 (Henley Passport Index)\\nShaded bands show the 25th–75th percentile range within each region; faint lines show individual countries\",\n    x        = NULL,\n    y        = NULL,\n    caption  = \"Source: Henley Passport Index via TidyTuesday | Visualization: Sean Thimons\"\n  ) +\n  # Theme\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    plot.title         = ggplot2::element_text(face = \"bold\", size = 20, margin = ggplot2::margin(b = 4)),\n    plot.subtitle      = ggplot2::element_text(size = 10, color = \"#555555\", lineheight = 1.3,\n                                               margin = ggplot2::margin(b = 16)),\n    plot.caption       = ggplot2::element_text(size = 8, color = \"#888888\", margin = ggplot2::margin(t = 12)),\n    panel.grid.minor   = ggplot2::element_blank(),\n    panel.grid.major.x = ggplot2::element_blank(),\n    panel.grid.major.y = ggplot2::element_line(color = \"#EEEEEE\", linewidth = 0.5),\n    legend.position    = \"none\",\n    axis.text          = ggplot2::element_text(color = \"#555555\"),\n    plot.margin        = ggplot2::margin(16, 80, 16, 16)\n  )\n\np\n```\n\n::: {.cell-output-display}\n![](2025-09-09-henley-passport-index-data_files/figure-html/viz-passport-power-divide-1.png){width=1152}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n# Final thoughts and takeaways\n\nThe Henley Passport Index data, read across twenty years, delivers a clear verdict: **global passport power has grown, but the hierarchy has not fundamentally shifted.** Every region's median visa-free count is higher in 2025 than in 2006 — the world has, on balance, become more open. But the rank order of regions has barely changed. European passports were most powerful in 2006 and remain so in 2025. African and Middle Eastern passports were least powerful then, and remain so now.\n\nA few things stand out:\n\n- **The within-region spread is as telling as the between-region gap.** The IQR bands show that Africa, Asia, and the Americas each contain enormous internal variation. A Brazilian or Chilean passport is a very different document than a Haitian one, even though all three are \"Americas.\" Treating regions as monoliths obscures this.\n\n- **Deliberate policy works — if you have leverage.** The UAE's rise is not a fluke. It reflects a sustained, well-resourced diplomatic effort to negotiate visa waivers, combined with the country's growing economic clout. Most countries at the bottom of the index lack both the resources and the bilateral leverage to replicate this.\n\n- **Conflict is the single strongest predictor of passport weakness.** Afghanistan, Syria, Iraq, Somalia, and Yemen all cluster at the bottom in 2025 — each a country where prolonged armed conflict has destroyed the state's ability to function as a credible passport issuer and eroded international trust in its travel documents.\n\n- **EU accession is still the fastest elevator.** Croatia's trajectory shows that joining the EU — and especially the Schengen Area — remains the most reliable mechanism for rapidly improving passport power. With other Western Balkan states in the accession queue, the next decade may bring similar jumps for Serbia, Albania, or Bosnia.\n\nThe broader implication is uncomfortable: freedom of movement, which feels like a personal attribute, is almost entirely a function of where you happened to be born. The passport you carry shapes which borders open for you, which jobs you can pursue, and which crises you can escape from. The Henley Index makes that structural luck visible, year by year.\n",
    "supporting": [
      "2025-09-09-henley-passport-index-data_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}