{
  "hash": "a1e362cbfea3d805d46258c0d1c9d330",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Salmonid Mortality Data\"\nauthor: \"Sean Thimons\"\ndate: \"2026-03-17\"\ndescription: \"Norway raises the world's salmon — and loses hundreds of millions of them every year. Six years of aquaculture mortality data reveal a counterintuitive seasonal rhythm and an industry operating at staggering scale.\"\ncategories: [tidytuesday, R, aquaculture, ecology, Norway]\n---\n\n\n\n# Preface\n\nFrom the [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2026/2026-03-17).\n\n> This week's data comes from the Norwegian Directorate of Fisheries\n> (Fiskeridirektoratet), tracking monthly mortality statistics for Atlantic\n> salmon (*Salmo salar*) and rainbow trout (*Oncorhynchus mykiss*) in\n> Norwegian aquaculture from 2020 through 2025. Two tables are provided:\n> `monthly_losses_data` records the absolute count of fish lost each month\n> by cause (dead, discarded, escaped, other), and `monthly_mortality_data`\n> records the monthly mortality *rate* (median and interquartile range\n> across individual aquaculture sites) by region. Norway produces roughly\n> two-thirds of the world's farmed Atlantic salmon, making this one of the\n> most consequential datasets in global food production.\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  booster_pack <- c(\n    ### IO ----\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n\n    ### EDA ----\n    'skimr',\n\n    ### Plot ----\n    'paletteer',           # Color palette collection\n    'patchwork',           # Multi-panel layouts\n    'ggrepel',             # Non-overlapping labels\n    'scales',              # Axis formatting\n\n    ### Misc ----\n    'tidytuesdayR'\n  )\n\n  install_booster_pack(package = booster_pack, load = TRUE)\n  rm(install_booster_pack, booster_pack)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2026-03-17')\n\nlosses   <- raw$monthly_losses_data\nmortality <- raw$monthly_mortality_data\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## monthly_losses_data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlosses %>%\n  select(-species, -date, -geo_group, -region) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |2808       |\n|Number of columns        |5          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|numeric                  |5          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|    n| min|     p25|      med|       p75|     max|      mean|  geo_mean|        sd|hist  |\n|:-------------|---------:|-------------:|----:|---:|-------:|--------:|---------:|-------:|---------:|---------:|---------:|:-----|\n|losses        |         0|             1| 2808|   0| 2158.25| 202551.0| 520828.75| 9253842| 443774.15| 120847.93| 922958.83|▇▁▁▁▁ |\n|dead          |         0|             1| 2808|   0| 1839.25| 176452.0| 434446.25| 7947877| 378946.48| 104454.43| 786700.43|▇▁▁▁▁ |\n|discarded     |         0|             1| 2808|   0|    0.00|   5936.5|  20301.50|  442950|  21374.84|  10833.97|  47902.38|▇▁▁▁▁ |\n|escaped       |         0|             1| 2808|   0|    0.00|      0.0|      0.00|   38638|    154.71|     37.69|   1922.66|▇▁▁▁▁ |\n|other         |         0|             1| 2808|   0|    0.00|    528.0|  10749.25| 3130475|  43298.13|   3606.53| 176226.26|▇▁▁▁▁ |\n\n\n:::\n:::\n\n\n\nThe `losses` dataset spans **2,808 rows** covering January 2020 through December 2025 for two species (salmon and rainbow trout) across three geographic groupings: individual production areas (`area`, numbered 1–13), Norwegian counties (`county`), and the national total (`country`). There are no missing values anywhere.\n\nThe distribution of `losses` is heavily right-skewed (the histogram shows mass at the lower end with a long right tail), reflecting the enormous difference in farm density across regions — some areas contain far more active sites than others. The `dead` column dominates total losses; `escaped` and `other` are orders of magnitude smaller, visible only in their maxima.\n\n## monthly_mortality_data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmortality %>%\n  select(median, q1, q3) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |1788       |\n|Number of columns        |3          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|numeric                  |3          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|    n|  min|  p25|  med|  p75|   max| mean| geo_mean|   sd|hist  |\n|:-------------|---------:|-------------:|----:|----:|----:|----:|----:|-----:|----:|--------:|----:|:-----|\n|median        |         0|             1| 1788| 0.14| 0.45| 0.59| 0.77|  2.89| 0.64|     0.59| 0.27|▇▃▁▁▁ |\n|q1            |         0|             1| 1788| 0.08| 0.22| 0.29| 0.38|  1.72| 0.32|     0.29| 0.15|▇▂▁▁▁ |\n|q3            |         0|             1| 1788| 0.24| 0.88| 1.22| 1.64| 11.90| 1.34|     1.20| 0.73|▇▁▁▁▁ |\n\n\n:::\n:::\n\n\n\nThe `mortality` dataset provides **1,788 rows** of monthly mortality *rates* — the percentage of standing stock that perishes each month — with median, first quartile, and third quartile across sites within each reporting unit. Rates range from 0.14% to 2.89% with a mean of 0.64%. The wide IQR (q1 ≈ 0.27%, q3 ≈ 1.30%) reflects genuine heterogeneity across farms: some operations run tight, others face chronic mortality challenges.\n\n::: {.callout-note}\n## What the mortality rate measures\n\nThe monthly mortality rate is expressed as a percentage of the fish present at\nthe start of the month. A rate of 0.6% means that for every 1,000 fish in the\nsea cage, roughly 6 die during that month. At industrial scale — Norwegian salmon\nfarms hold hundreds of millions of fish simultaneously — even a small shift in\nthis rate translates to millions of additional deaths.\n:::\n\n# Industrial Scale: The Arithmetic of Aquaculture Loss\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# National salmon losses only\nnational_salmon <- losses %>%\n  filter(species == \"salmon\", geo_group == \"country\")\n\ncat(sprintf(\"national_salmon: %d rows, %d cols\\n\", nrow(national_salmon), ncol(national_salmon)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnational_salmon: 72 rows, 9 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Empty data\" = nrow(national_salmon) > 0)\n\n# Annual totals\nannual_totals <- national_salmon %>%\n  mutate(year = format(date, \"%Y\")) %>%\n  group_by(year) %>%\n  summarise(\n    total_losses  = sum(losses,    na.rm = TRUE),\n    total_dead    = sum(dead,      na.rm = TRUE),\n    total_discard = sum(discarded, na.rm = TRUE),\n    total_escaped = sum(escaped,   na.rm = TRUE),\n    total_other   = sum(other,     na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\n# Reshape for stacked bar chart\nannual_long <- annual_totals %>%\n  select(year, Dead = total_dead, Discarded = total_discard,\n         Escaped = total_escaped, Other = total_other) %>%\n  pivot_longer(-year, names_to = \"cause\", values_to = \"count\") %>%\n  mutate(\n    cause = factor(cause, levels = c(\"Other\", \"Escaped\", \"Discarded\", \"Dead\")),\n    count_m = count / 1e6\n  )\n\ncat(sprintf(\"annual_long: %d rows, %d cols\\n\", nrow(annual_long), ncol(annual_long)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nannual_long: 24 rows, 4 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Empty stacked data\" = nrow(annual_long) > 0)\n\n# Palette: MetBrewer::Hokusai2 — 6 qualitative colors, wave/water inspired\n# (Hokusai3 was used 2025-09-30; Hokusai2 is fresh)\ncause_colors <- c(\n  Dead      = \"#3B4988FF\",   # deep ocean blue\n  Discarded = \"#7EC5D1FF\",   # pale teal\n  Escaped   = \"#4CA57EFF\",   # sea green\n  Other     = \"#CCC18CFF\"    # sand/kelp\n)\n\np_bars <- annual_long %>%\n  ggplot2::ggplot(ggplot2::aes(x = year, y = count_m, fill = cause)) +\n  ggplot2::geom_col(width = 0.7) +\n  ggplot2::scale_fill_manual(\n    values = cause_colors,\n    guide  = ggplot2::guide_legend(reverse = TRUE)\n  ) +\n  ggplot2::scale_y_continuous(\n    labels = scales::label_number(suffix = \"M\"),\n    expand = ggplot2::expansion(mult = c(0, 0.05))\n  ) +\n  ggplot2::labs(\n    title    = \"~66 million Norwegian salmon are lost every year\",\n    subtitle = \"Annual salmon losses in Norwegian aquaculture by cause, 2020–2025\",\n    x        = NULL,\n    y        = \"Fish (millions)\",\n    fill     = \"Cause of loss\",\n    caption  = \"Source: Norwegian Directorate of Fisheries via TidyTuesday 2026-03-17\"\n  ) +\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    plot.title         = ggplot2::element_text(face = \"bold\", size = 16),\n    plot.subtitle      = ggplot2::element_text(color = \"#444444\", size = 11),\n    panel.grid.major.x = ggplot2::element_blank(),\n    panel.grid.minor   = ggplot2::element_blank(),\n    legend.position    = \"right\"\n  )\n\np_bars\n```\n\n::: {.cell-output-display}\n![](2026-03-17-salmonid-mortality-data_files/figure-html/loss-composition-1.png){width=672}\n:::\n:::\n\n\n\nNorway lost between **60 and 71 million salmon per year** over this period — rising from 60.3M in 2020 to a peak of 71.4M in 2023, then easing slightly toward 67.5M in 2025. The breakdown is striking: **~85% die outright**, roughly 5% are discarded (culled for health reasons before death), a small fraction escape into the wild, and the remainder are attributed to \"other\" causes (primarily fish removed for slaughter ahead of schedule due to disease pressure).\n\n::: {.callout-important}\n## Escaped fish: a small count, a large ecological concern\n\nJust 127,762 salmon escaped into Norwegian waters over six years — a fraction of a percent of total losses. But escaped farmed salmon are genetically distinct from wild populations, and even small numbers can interbreed with wild Atlantic salmon, diluting local adaptations that wild fish have developed over millennia. Norway has strict reporting requirements precisely because the impact-per-fish of escapes vastly exceeds that of mortality.\n:::\n\n# The Winter Mortality Paradox\n\nConventional intuition might suggest that warm summer waters — stressful for cold-water salmonids — would drive peak mortality. Norwegian data tells the opposite story.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Seasonal averages for salmon at country level\nseasonal_salmon <- mortality %>%\n  filter(species == \"salmon\", geo_group == \"country\") %>%\n  mutate(month = as.integer(format(date, \"%m\")))\n\nseasonal_avg <- seasonal_salmon %>%\n  group_by(month) %>%\n  summarise(\n    avg_median = mean(median, na.rm = TRUE),\n    avg_q1     = mean(q1,     na.rm = TRUE),\n    avg_q3     = mean(q3,     na.rm = TRUE),\n    .groups    = \"drop\"\n  )\n\ncat(\"Seasonal mortality averages (Norway, salmon):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeasonal mortality averages (Norway, salmon):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(seasonal_avg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 4\n   month avg_median avg_q1 avg_q3\n   <int>      <dbl>  <dbl>  <dbl>\n 1     1      0.677  0.323  1.56 \n 2     2      0.68   0.312  1.52 \n 3     3      0.732  0.34   1.64 \n 4     4      0.663  0.302  1.42 \n 5     5      0.568  0.255  1.37 \n 6     6      0.425  0.192  1.06 \n 7     7      0.393  0.177  0.925\n 8     8      0.467  0.23   1.08 \n 9     9      0.523  0.267  1.19 \n10    10      0.532  0.265  1.19 \n11    11      0.532  0.262  1.18 \n12    12      0.632  0.312  1.39 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"\\nPeak month: %s (%.3f%%)\\n\",\n  month.abb[seasonal_avg$month[which.max(seasonal_avg$avg_median)]],\n  max(seasonal_avg$avg_median)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPeak month: Mar (0.732%)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"Trough month: %s (%.3f%%)\\n\",\n  month.abb[seasonal_avg$month[which.min(seasonal_avg$avg_median)]],\n  min(seasonal_avg$avg_median)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrough month: Jul (0.393%)\n```\n\n\n:::\n:::\n\n\n\nMarch carries the highest average mortality (0.73%), while July is the lowest (0.39%) — a near-doubling of mortality rate from summer to late winter. In Norwegian aquaculture this is well understood: winter and spring are peak periods for sea lice infestations and for the bacterial pathogen *Pasteurella*, both of which thrive in cold, dense cage conditions. Summer months bring better water circulation, lower lice pressure, and the physiological boost of longer daylight.\n\n# The Hero Visualization: Six Years of Salmon Mortality\n\nThe most revealing view of this dataset isn't a single year or a single region — it's the repeating seasonal wave, seen six times, charting whether Norwegian aquaculture is getting better or worse at keeping its fish alive.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prepare data: salmon, country level, with year and month columns\nsalmon_cycle <- mortality %>%\n  filter(species == \"salmon\", geo_group == \"country\") %>%\n  mutate(\n    month = as.integer(format(date, \"%m\")),\n    year  = factor(format(date, \"%Y\"))\n  ) %>%\n  arrange(year, month)\n\ncat(sprintf(\"salmon_cycle: %d rows, %d cols\\n\", nrow(salmon_cycle), ncol(salmon_cycle)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsalmon_cycle: 72 rows, 9 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"Empty plot data\" = nrow(salmon_cycle) > 0)\n\n# Sanity check proportions\ncat(sprintf(\"Mortality range: %.2f%% – %.2f%%\\n\",\n  min(salmon_cycle$median), max(salmon_cycle$median)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMortality range: 0.34% – 0.85%\n```\n\n\n:::\n\n```{.r .cell-code}\n# Palette: MetBrewer::Hokusai2\n# Great Wave–inspired palette. Six colors for six years.\n# Not used previously (Hokusai3 used 2025-09-30, Hokusai2 is fresh).\nyear_pal <- paletteer::paletteer_d(\"MetBrewer::Hokusai2\")\ncat(\"Hokusai2 colors:\", as.character(year_pal), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHokusai2 colors: #ABC9C8FF #72AEB6FF #4692B0FF #2F70A1FF #134B73FF #0A3351FF \n```\n\n\n:::\n\n```{.r .cell-code}\n# Annotation: highlight the summer trough and winter peak\nanno_low  <- data.frame(month = 7,  y = 0.20, label = \"Summer trough\\n(sea lice pressure drops)\")\nanno_high <- data.frame(month = 3,  y = 1.05, label = \"Winter–spring peak\\n(lice & bacterial outbreaks)\")\n\np_hero <- salmon_cycle %>%\n  ggplot2::ggplot(ggplot2::aes(\n    x = month, y = median,\n    color = year, fill = year, group = year\n  )) +\n  # IQR ribbon\n  ggplot2::geom_ribbon(\n    ggplot2::aes(ymin = q1, ymax = q3),\n    alpha = 0.12, color = NA\n  ) +\n  # Median line\n  ggplot2::geom_line(linewidth = 1.1) +\n  # Points at each month\n  ggplot2::geom_point(size = 2.2) +\n  # Annotations\n  ggplot2::annotate(\n    \"text\",\n    x = 7.3, y = 0.23,\n    label = \"Summer trough\\n(sea lice pressure drops)\",\n    hjust = 0, size = 3.2, color = \"#444444\", lineheight = 1.1\n  ) +\n  ggplot2::annotate(\n    \"segment\",\n    x = 7.1, xend = 7.05, y = 0.30, yend = 0.38,\n    color = \"#444444\", linewidth = 0.5,\n    arrow = ggplot2::arrow(length = ggplot2::unit(0.08, \"inches\"), type = \"closed\")\n  ) +\n  ggplot2::annotate(\n    \"text\",\n    x = 3.3, y = 1.05,\n    label = \"Winter–spring peak\\n(bacterial outbreaks, lice)\",\n    hjust = 0, size = 3.2, color = \"#444444\", lineheight = 1.1\n  ) +\n  ggplot2::annotate(\n    \"segment\",\n    x = 3.2, xend = 3.05, y = 0.98, yend = 0.83,\n    color = \"#444444\", linewidth = 0.5,\n    arrow = ggplot2::arrow(length = ggplot2::unit(0.08, \"inches\"), type = \"closed\")\n  ) +\n  ggplot2::scale_x_continuous(\n    breaks = 1:12,\n    labels = month.abb,\n    expand = ggplot2::expansion(add = c(0.3, 1.8))\n  ) +\n  ggplot2::scale_y_continuous(\n    labels = scales::label_number(suffix = \"%\"),\n    breaks = seq(0.2, 1.0, by = 0.2),\n    limits = c(0.1, 1.1)\n  ) +\n  ggplot2::scale_color_manual(values = as.character(year_pal)) +\n  ggplot2::scale_fill_manual(values  = as.character(year_pal)) +\n  ggplot2::labs(\n    title    = \"Norwegian salmon die in winter, not summer\",\n    subtitle = paste0(\n      \"Monthly median mortality rate (%) for Atlantic salmon in Norwegian aquaculture, 2020–2025.\\n\",\n      \"Shaded bands show the interquartile range across aquaculture sites. Country-level aggregate.\"\n    ),\n    x        = NULL,\n    y        = \"Monthly mortality rate (%)\",\n    color    = NULL,\n    fill     = NULL,\n    caption  = \"Source: Norwegian Directorate of Fisheries via TidyTuesday 2026-03-17\"\n  ) +\n  ggplot2::theme_minimal(base_size = 13) +\n  ggplot2::theme(\n    plot.title         = ggplot2::element_text(face = \"bold\", size = 18, margin = ggplot2::margin(b = 5)),\n    plot.subtitle      = ggplot2::element_text(color = \"#555555\", size = 11, lineheight = 1.3),\n    plot.caption       = ggplot2::element_text(color = \"#888888\", size = 9),\n    legend.position    = \"top\",\n    legend.direction   = \"horizontal\",\n    legend.text        = ggplot2::element_text(size = 11),\n    panel.grid.minor   = ggplot2::element_blank(),\n    panel.grid.major.x = ggplot2::element_blank(),\n    axis.text.x        = ggplot2::element_text(size = 11),\n    plot.margin        = ggplot2::margin(12, 16, 12, 12)\n  )\n\np_hero\n```\n\n::: {.cell-output-display}\n![](2026-03-17-salmonid-mortality-data_files/figure-html/hero-seasonal-cycle-1.png){width=1056}\n:::\n:::\n\n\n\nEach colored line traces the seasonal mortality cycle for a single calendar year. The **wave shape is consistent**: mortality rises to a plateau in winter and early spring, collapses in midsummer, then recovers through autumn. Year-to-year, the level of the wave shifts — **2023 and 2024 carried notably higher winter mortality** than 2020, with January 2023 reaching a median of 0.85% (more than double the July trough). By 2025, rates appear to be moderating.\n\n\n\n::: {.cell}\n\n:::\n\n\n\n# Final thoughts and takeaways\n\nNorwegian aquaculture is an industrial enterprise at a scale most people find difficult to visualize. Between 2020 and 2025, Norwegian fish farms lost roughly **396 million Atlantic salmon** at the country level — not to fishing nets, but to mortality inside the cages. That is more salmon than the entire wild Atlantic salmon population by many orders of magnitude.\n\nThree findings from this data stand out:\n\n**1. Winter is deadlier than summer for farmed salmon.** The seasonal mortality curve peaks in January–March and hits its low in June–August. This reflects the biology of *Lepeophtheirus salmonis* (sea lice), which reproduces more slowly in cold water but accumulates across the winter, and the spring recurrence of bacterial diseases like *Pasteurella*. The pattern is so consistent that Norwegian fish health authorities use it as a baseline; a year where the winter peak is unusually high signals an industry-wide problem.\n\n**2. 2021–2024 saw elevated winter mortality.** Looking at the seasonal cycles, 2020 was the mildest year. From 2021 onward, the winter plateaus climbed — reaching a peak in January 2023 (0.85% median mortality) and January–February 2024. The 2025 data suggests a return toward lower levels, but it is one year and too early to call a trend.\n\n**3. Dead fish vastly outnumber every other loss category.** Discarded fish (culled alive for welfare or disease management), escaped fish, and other losses together account for fewer than 15% of total losses. The dominant story is simply: fish die in the cages. Reducing that mortality is not only an ethical priority but an economic one — at 2024 spot prices, 70 million salmon represent several billion dollars in unrecoverable biomass.\n\nThe escaped fish figure, though small in absolute terms, deserves separate scrutiny. Each escaped farmed salmon carries genes selected for growth in captivity rather than survival in the wild, and interbreeding with wild Atlantic salmon — already under pressure from overfishing and habitat loss — can reduce the adaptive fitness of wild populations for generations.\n\nNorwegian aquaculture has made real progress on sea lice resistance, vaccination protocols, and smolt health over the past decade. This dataset captures a moment where the industry's losses remain massive in absolute terms, but the seasonal pattern — predictable, biological, partially manageable — at least tells us where to look.\n",
    "supporting": [
      "2026-03-17-salmonid-mortality-data_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}