{
  "hash": "d47426e88088fa020f4e0d81fd010d90",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: European Parenting Leave Policies\"\nauthor: \"Sean Thimons\"\ndate: \"2026-06-02\"\ndescription: \"Half a century of paid parental leave entitlements across 21 European countries — who treats new parents most generously, and how the policy mix has shifted from short maternity windows to long shared parental terms.\"\ncategories:\n  - tidytuesday\n  - R\n  - policy\n  - europe\n  - labor\n---\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](2026-06-02-european-parenting-leave-policies_files/figure-html/pseudo-hero-palette-1.png){width=100%}\n:::\n:::\n\n\n# Preface\n\nFrom [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2026/2026-06-02).\n\n> The European Parenting Leave Policies (EPLP) dataset captures the legal duration and design of statutory maternity, paternity, and parental leave for 21 European countries from 1970 through 2024. Each row represents one country-year, with detailed fields for leave duration (in weeks), wage replacement rates, caps, eligibility, and which parent may claim each entitlement. The data was compiled by Daniela Rohrbach-Schmidt and colleagues and reflects the policy as legislated, not actual take-up.\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n{\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\"pak\", repos = \"https://cloud.r-project.org\")\n  }\n\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  core_packages <- c(\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n    'skimr',\n    'paletteer',\n    'tidytuesdayR'\n  )\n\n  optional_packages <- c('ggtext', 'ggrepel', 'scales', 'MetBrewer')\n\n  install_booster_pack(package = unique(c(core_packages, optional_packages)), load = TRUE)\n  rm(install_booster_pack, core_packages, optional_packages)\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n# Load raw data from package\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2026-06-02')\n\neplp <- raw$eplp %>% janitor::clean_names()\n```\n:::\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## EPLP\n\n\n::: {.cell}\n\n```{.r .cell-code}\neplp %>%\n  select(country, year, mat_m_ld_bb, mat_m_ld_ab, co_ld, par1_ld, par2_ld, par3_ld) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |1155       |\n|Number of columns        |8          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |1          |\n|numeric                  |7          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|country       |         0|             1|   2|   2|     0|       21|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|    n|  min|  p25|     med|     p75|     max|    mean| geo_mean|    sd|hist  |\n|:-------------|---------:|-------------:|----:|----:|----:|-------:|-------:|-------:|-------:|--------:|-----:|:-----|\n|year          |         0|             1| 1155| 1970| 1983| 1997.00| 2011.00| 2024.00| 1997.00|  1996.94| 15.88|▇▇▇▇▇ |\n|mat_m_ld_bb   |         0|             1| 1155|    0|    0|    0.00|    6.00|    8.70|    2.38|     4.43|  3.07|▇▂▁▂▂ |\n|mat_m_ld_ab   |         0|             1| 1155|    0|    0|    6.00|    8.00|   20.00|    5.00|     6.33|  4.54|▇▆▁▁▁ |\n|co_ld         |         0|             1| 1155|    0|    0|    0.00|    2.00|   28.00|    1.37|     1.70|  3.12|▇▁▁▁▁ |\n|par1_ld       |         0|             1| 1155|    0|    0|   25.71|   48.80|  186.71|   36.17|    44.49| 46.66|▇▂▁▁▁ |\n|par2_ld       |         0|             1| 1155|    0|    0|    0.00|   13.04|  186.71|   20.42|    46.89| 41.77|▇▁▁▁▁ |\n|par3_ld       |         0|             1| 1155|    0|    0|    0.00|   26.33|   98.36|   13.42|    29.59| 20.80|▇▂▁▁▁ |\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCountries (n =\", length(unique(eplp$country)), \"):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCountries (n = 21 ):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(sort(unique(eplp$country)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"AT\" \"BE\" \"CZ\" \"DE\" \"DK\" \"EE\" \"ES\" \"FI\" \"FR\" \"GR\" \"HU\" \"IE\" \"IT\" \"LT\" \"NL\"\n[16] \"NO\" \"PL\" \"SE\" \"SI\" \"SK\" \"UK\"\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nYear coverage:\", min(eplp$year), \"to\", max(eplp$year), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nYear coverage: 1970 to 2024 \n```\n\n\n:::\n:::\n\n\nThe frame is a balanced country-year panel: 21 countries × 55 years = 1,155 rows, with no missing country or year. Leave-duration variables (in weeks) are uniformly observed across the panel. The eligibility/cap fields are sparser — the codebook uses `-98` for \"not applicable\" rather than `NA`, which would mislead a naive `mean()` if we used those columns directly.\n\nThe leave-duration columns split cleanly into three policy buckets:\n\n- **Maternity** (`mat_m_ld_bb`, `mat_m_ld_ab`) — weeks of mother-only leave before and after birth.\n- **Co/paternity** (`co_ld`) — short leave reserved for the second parent.\n- **Parental** (`par1_ld`, `par2_ld`, `par3_ld`) — successive tiers of paid parental leave that may be shared, transferred, or earmarked depending on country.\n\n::: {.callout-note}\nThe codebook draws a careful distinction between *maternity* (medical leave around childbirth, mother-only) and *parental* (child-care leave, often shareable). Many casual comparisons of \"how much leave does country X offer\" collapse the two; this dataset lets us keep them separate.\n:::\n\n# How generous is paid parental leave across Europe?\n\nThe headline question this dataset invites is the obvious one: in 2024, who actually offers the most paid leave, and what is it made of? A single \"total weeks\" number hides the policy design — a country with 40 weeks of mother-only maternity leave is doing something very different from one with 40 weeks of shareable parental leave. So the story has to be told as a decomposition, not a scalar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleave_2024 <- eplp %>%\n  filter(year == 2024) %>%\n  transmute(\n    country,\n    Maternity     = mat_m_ld_bb + mat_m_ld_ab,\n    `Co / paternity` = co_ld,\n    `Parental I`  = par1_ld,\n    `Parental II` = par2_ld,\n    `Parental III` = par3_ld\n  )\n\nstopifnot(\"leave_2024 has 0 rows\" = nrow(leave_2024) > 0)\n\nleave_2024_long <- leave_2024 %>%\n  pivot_longer(-country, names_to = \"leave_type\", values_to = \"weeks\") %>%\n  mutate(\n    leave_type = factor(\n      leave_type,\n      levels = c(\"Maternity\", \"Co / paternity\",\n                 \"Parental I\", \"Parental II\", \"Parental III\")\n    )\n  )\n\ncountry_totals <- leave_2024_long %>%\n  group_by(country) %>%\n  summarise(total_weeks = sum(weeks), .groups = \"drop\") %>%\n  arrange(desc(total_weeks))\n\ncountry_totals %>% print(n = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 21 × 2\n   country total_weeks\n   <chr>         <dbl>\n 1 AT            222. \n 2 DE            171. \n 3 LT            154. \n 4 EE            140  \n 5 SE            115. \n 6 PL             86  \n 7 SI             78.6\n 8 FI             78.3\n 9 UK             78  \n10 IT             75.3\n11 DK             66  \n12 FR             64.4\n13 NO             64  \n14 BE             48.8\n15 SK             42  \n16 GR             36.4\n17 NL             34  \n18 IE             26  \n19 HU             25.2\n20 ES             22  \n21 CZ             16  \n```\n\n\n:::\n:::\n\n\nAustria sits at the top with roughly 222 weeks of statutory paid leave — about **4.3 years** if a household uses every tier. Germany, Lithuania, and Estonia round out a generous quartet, all built on long parental-leave tiers stacked on top of relatively short maternity windows. At the other end, the Czech Republic, Spain, Ireland, and the Netherlands sit below 35 weeks, leaning hard on maternity and short paternity rather than extended parental terms.\n\n## The 2024 picture, decomposed\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncountry_order <- country_totals$country\n\npalette_cols <- as.character(\n  paletteer::paletteer_d(\"MetBrewer::Java\", n = 5)\n)\n\nannot_top    <- country_totals %>% slice(1)\nannot_bottom <- country_totals %>% slice(n())\n\np <- leave_2024_long %>%\n  mutate(country = factor(country, levels = rev(country_order))) %>%\n  ggplot(aes(x = weeks, y = country, fill = leave_type)) +\n  geom_col(width = 0.78, color = \"white\", linewidth = 0.25) +\n  geom_text(\n    data = country_totals %>%\n      mutate(country = factor(country, levels = rev(country_order))),\n    aes(x = total_weeks + 4, y = country,\n        label = sprintf(\"%.0f wk\", total_weeks)),\n    inherit.aes = FALSE,\n    hjust = 0, size = 3.1, color = \"grey25\"\n  ) +\n  scale_fill_manual(values = palette_cols, name = NULL) +\n  scale_x_continuous(\n    breaks = seq(0, 240, 52),\n    labels = c(\"0\", \"1 yr\", \"2 yrs\", \"3 yrs\", \"4 yrs\"),\n    expand = expansion(mult = c(0, 0.12))\n  ) +\n  labs(\n    title = \"Austria offers more than four years of paid leave; Czechia barely four months\",\n    subtitle = \"Statutory weeks of paid leave by type, 2024 — 21 European countries\",\n    x = NULL,\n    y = NULL,\n    caption = \"Source: TidyTuesday 2026-06-02 · European Parenting Leave Policies (EPLP)\\nBars stack maternity (mother-only), co/paternity, and three tiers of parental leave.\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14,\n                              margin = margin(b = 4)),\n    plot.subtitle = element_text(color = \"grey35\",\n                                 margin = margin(b = 14)),\n    plot.caption = element_text(color = \"grey45\", hjust = 0,\n                                margin = margin(t = 12)),\n    panel.grid.major.y = element_blank(),\n    panel.grid.minor   = element_blank(),\n    panel.grid.major.x = element_line(color = \"grey90\"),\n    legend.position = \"top\",\n    legend.justification = \"left\",\n    legend.key.size = unit(0.5, \"cm\"),\n    axis.text.y = element_text(face = \"bold\"),\n    plot.margin = margin(14, 18, 12, 14)\n  )\n\np\n```\n\n::: {.cell-output-display}\n![](2026-06-02-european-parenting-leave-policies_files/figure-html/hero-stacked-1.png){width=960}\n:::\n:::\n\n\n::: {.callout-tip}\n## Reading the stacks\n\nThe same total bar length can come from very different policy mixes. Compare **Poland** (a thick maternity block, almost no parental tiers) with **Estonia** (essentially zero maternity, but two long parental tiers either parent can take). Two countries, similar total weeks, opposite philosophies of who the leave is *for*.\n:::\n\n# How did we get here?\n\nThe 2024 cross-section is a snapshot. The panel structure also lets us watch the policy mix evolve. Across the panel, the share of total leave that comes from *parental* tiers (rather than mother-only maternity) has risen steadily since the early 1990s — that is the structural story of European leave policy over the last three decades.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshare_over_time <- eplp %>%\n  transmute(\n    country, year,\n    maternity = mat_m_ld_bb + mat_m_ld_ab,\n    parental  = par1_ld + par2_ld + par3_ld,\n    copat     = co_ld\n  ) %>%\n  group_by(year) %>%\n  summarise(\n    maternity = mean(maternity),\n    parental  = mean(parental),\n    copat     = mean(copat),\n    .groups = \"drop\"\n  ) %>%\n  pivot_longer(-year, names_to = \"leave_type\", values_to = \"weeks\") %>%\n  mutate(\n    leave_type = recode(\n      leave_type,\n      maternity = \"Maternity\",\n      copat     = \"Co / paternity\",\n      parental  = \"Parental (all tiers)\"\n    ),\n    leave_type = factor(\n      leave_type,\n      levels = c(\"Parental (all tiers)\", \"Maternity\", \"Co / paternity\")\n    )\n  )\n\ntrend_cols <- palette_cols[c(3, 1, 2)]\n\np2 <- share_over_time %>%\n  ggplot(aes(x = year, y = weeks, fill = leave_type)) +\n  geom_area(alpha = 0.92, color = \"white\", linewidth = 0.25) +\n  scale_fill_manual(values = trend_cols, name = NULL) +\n  scale_x_continuous(breaks = seq(1970, 2024, 10),\n                     expand = expansion(mult = c(0, 0))) +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +\n  labs(\n    title = \"Parental leave overtook maternity leave as Europe's main entitlement\",\n    subtitle = \"Average weeks of statutory paid leave across 21 European countries, 1970–2024\",\n    x = NULL,\n    y = \"Average weeks (panel mean)\",\n    caption = \"Source: TidyTuesday 2026-06-02 · European Parenting Leave Policies (EPLP)\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 13),\n    plot.subtitle = element_text(color = \"grey35\",\n                                 margin = margin(b = 12)),\n    plot.caption = element_text(color = \"grey45\", hjust = 0,\n                                margin = margin(t = 10)),\n    panel.grid.minor = element_blank(),\n    legend.position = \"top\",\n    legend.justification = \"left\"\n  )\n\np2\n```\n\n::: {.cell-output-display}\n![](2026-06-02-european-parenting-leave-policies_files/figure-html/trend-share-1.png){width=960}\n:::\n:::\n\n\nIn 1970 the average European country in this panel offered roughly **12 weeks** of paid leave, almost all of it medical maternity leave reserved for mothers. By 2024 the average has grown past **70 weeks**, and the bulk of that growth is parental leave — entitlements that are increasingly designed to be transferable, shareable, or earmarked for the second parent. Co-leave (the small sliver at the top of each year) is a more recent invention, barely visible before the 2000s.\n\n# Final thoughts and takeaways\n\nA few things stand out once the leave duration is decomposed rather than reported as a single \"weeks of leave\" headline:\n\n- **Long totals are mostly parental, not maternity.** The countries at the top of the 2024 ranking — Austria, Germany, Lithuania, Estonia — got there by stacking long parental-leave tiers, not by extending maternity leave. Maternity (mother-only, medical) has stayed in the 12–20 week range almost everywhere for thirty years.\n- **The \"second parent\" is finally in the policy text.** Co-leave/paternity was a rounding error in 1990 and is a small but persistent component by 2024. The shift toward leave that *either* parent can claim is even larger than the appearance of dedicated paternity weeks.\n- **Policy on the books ≠ policy on the ground.** This dataset is statutory entitlement, not take-up. A country that legislates 100 weeks of parental leave at a low replacement rate may see very different real behavior than one that offers 40 weeks at full pay. The `*_rr` (replacement rate) and `*_cap` fields in this panel are the natural next stop for anyone wanting to weight the durations by how usable the leave actually is.\n- **The convergence is partial.** Despite three decades of EU-level coordination, the spread between the most and least generous countries in 2024 is still enormous — Austria offers more than thirteen times the paid weeks Czechia does. Whatever harmonization pressure exists, it has not flattened the distribution.\n\nFor a household weighing where in Europe to start a family, the headline \"weeks of leave\" is the wrong number to compare. The right comparison is the *mix*: how much is reserved for the birthing parent, how much can be shared, how much is paid at what rate, and how much of it is realistically taken. This dataset is a clean foundation for that more careful comparison.\n",
    "supporting": [
      "2026-06-02-european-parenting-leave-policies_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}