name: Gitleaks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Change the minute per repo to stagger scheduled runs.
    - cron: "13 9 * * 1"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    name: Gitleaks
    uses: seanthimons/baseline/.github/workflows/gitleaks.yaml@df028b5dcb494da6209f447183823492e6a44ac2 # v1.1.0
    secrets:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
