name: Gitleaks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Change the minute per repo to stagger scheduled runs.
    - cron: "13 9 * * 1"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    name: Gitleaks
    uses: seanthimons/baseline/.github/workflows/gitleaks.yaml@733a6e4554870ab2fa8dd7495fa67bea029bb38c # v1.3.0
    secrets:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
