{
  "hash": "dc1a8d96859ba37742c0c86f6c3f7d50",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidy Tuesday: Crane Observations at Lake Hornborgasjön, Sweden (1994–2024)\"\nauthor: \"Sean Thimons\"\ndate: \"2025-09-30\"\ndescription: \"Thirty years of Eurasian crane migration counts at Sweden's most celebrated staging lake reveal a remarkable fivefold population recovery — and a 2023 fall season that rewrote the record books.\"\ncategories: [tidytuesday, R, nature, time-series, wildlife, ecology]\n---\n\n\n\n# Preface\n\nFrom [TidyTuesday repository](https://github.com/rfordatascience/tidytuesday/tree/main/data/2025/2025-09-30).\n\n> This dataset documents crane counts at Lake Hornborgasjön in Sweden spanning 1994–2024. The field station has tracked migrations for over 30 years, counting birds during spring and fall passages. Dataset curated by Carl Borstell from the Hornborgasjön field station's official statistics.\n\n**Suggested questions from the repository:**\n\n1. How have crane counts changed across the 30-year period (1994–2024)?\n2. When during the year are the largest crane congregations observed?\n3. Can weather patterns predict or correlate with crane arrivals?\n\n## Loading necessary packages\n\nMy handy booster pack that allows me to install (if needed) and load my usual and favorite packages, as well as some helpful functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Packages ----------------------------------------------------------------\n\n{\n  # Install pak if it's not already installed\n  if (!requireNamespace(\"pak\", quietly = TRUE)) {\n    install.packages(\n      \"pak\",\n      repos = sprintf(\n        \"https://r-lib.github.io/p/pak/stable/%s/%s/%s\",\n        .Platform$pkgType,\n        R.Version()$os,\n        R.Version()$arch\n      )\n    )\n  }\n\n  # CRAN Packages ----\n  install_booster_pack <- function(package, load = TRUE) {\n    for (pkg in package) {\n      if (!requireNamespace(pkg, quietly = TRUE)) {\n        pak::pkg_install(pkg)\n      }\n      if (load) {\n        library(pkg, character.only = TRUE)\n      }\n    }\n  }\n\n  booster_pack <- c(\n    ### IO ----\n    'fs',\n    'here',\n    'janitor',\n    'rio',\n    'tidyverse',\n\n    ### EDA ----\n    'skimr',\n\n    ### Plot ----\n    'paletteer',           # Color palette collection\n    'ggridges',            # Ridgeline / joy plots\n    'ggrepel',             # Non-overlapping labels\n    'patchwork',           # Multi-panel layouts\n\n    ### Misc ----\n    'tidytuesdayR'\n  )\n\n  install_booster_pack(package = booster_pack, load = TRUE)\n  rm(install_booster_pack, booster_pack)\n\n  # Custom Functions ----\n\n  `%ni%` <- Negate(`%in%`)\n\n  geometric_mean <- function(x) {\n    exp(mean(log(x[x > 0]), na.rm = TRUE))\n  }\n\n  my_skim <- skim_with(\n    numeric = sfl(\n      n = length,\n      min = ~ min(.x, na.rm = T),\n      p25 = ~ stats::quantile(., probs = .25, na.rm = TRUE, names = FALSE),\n      med = ~ median(.x, na.rm = T),\n      p75 = ~ stats::quantile(., probs = .75, na.rm = TRUE, names = FALSE),\n      max = ~ max(.x, na.rm = T),\n      mean = ~ mean(.x, na.rm = T),\n      geo_mean = ~ geometric_mean(.x),\n      sd = ~ stats::sd(., na.rm = TRUE),\n      hist = ~ inline_hist(., 5)\n    ),\n    append = FALSE\n  )\n}\n```\n:::\n\n\n\n# Load raw data from package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- tidytuesdayR::tt_load('2025-09-30')\n\ncranes <- raw$cranes\n```\n:::\n\n\n\n# Exploratory Data Analysis\n\nThe `my_skim()` function is a modified version of the `skimr::skim()` function that returns the number of missing data points (cells as `NA`) as well as the inverse (e.g.: number of rows that are *not* `NA`), the count, minimum, 25%, median, 75%, max, mean, geometric mean, and standard deviation. It also generates a little ASCII histogram. Neat!\n\n## cranes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncranes %>%\n  select(date, observations) %>%\n  my_skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |1548       |\n|Number of columns        |2          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|Date                     |1          |\n|numeric                  |1          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: Date**\n\n|skim_variable | n_missing| complete_rate|min        |max        |median     | n_unique|\n|:-------------|---------:|-------------:|:----------|:----------|:----------|--------:|\n|date          |         0|             1|1994-03-24 |2024-10-03 |2011-03-21 |     1546|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|    n| min|  p25|  med|  p75|   max|    mean| geo_mean|   sd|hist  |\n|:-------------|---------:|-------------:|----:|---:|----:|----:|----:|-----:|-------:|--------:|----:|:-----|\n|observations  |       161|           0.9| 1548|   0| 1645| 4500| 8935| 27300| 6063.49|  3028.25| 5537|▇▃▂▁▁ |\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Inspect the categorical fields\ncranes %>% count(comment, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 2\n  comment                   n\n  <chr>                 <int>\n1 <NA>                   1358\n2 Canceled/No count       146\n3 Uncertain count          22\n4 Severe interference       7\n5 Last count of season      6\n6 Bad weather               4\n7 Record observation        3\n8 First count of season     2\n```\n\n\n:::\n\n```{.r .cell-code}\ncranes %>% count(weather_disruption)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  weather_disruption     n\n  <lgl>              <int>\n1 FALSE               1507\n2 TRUE                  41\n```\n\n\n:::\n:::\n\n\n\nThe dataset contains **1,548 observation records** spanning March 1994 through October 2024 — 31 spring and fall migration seasons at Lake Hornborgasjön. A few structural features stand out immediately:\n\n- **161 missing observation counts** (10.4% of rows): nearly all correspond to canceled counts due to bad weather, severe interference, or no-shows. These are data-absent days, not zero-crane days, and should be excluded from analysis.\n- **Crane counts span 0 to 27,300** with a median of 4,500 and a mean of 6,063 — the right-skewed distribution is typical of wildlife staging sites where peak days pull the mean well above the typical day.\n- **Only 41 weather disruptions** flagged across three decades, suggesting the field station operated reliably through most conditions.\n- **Three \"Record observation\" comments** all date to September 2023 — a remarkable cluster that flags an unusual fall season we'll examine closely.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add time components used throughout the analysis\ncranes <- cranes %>%\n  mutate(\n    year        = lubridate::year(date),\n    month       = lubridate::month(date),\n    month_name  = lubridate::month(date, label = TRUE, abbr = TRUE),\n    day_of_year = lubridate::yday(date),\n    season      = case_when(\n      month %in% 3:5  ~ \"Spring\",\n      month %in% 9:11 ~ \"Fall\",\n      TRUE            ~ \"Summer\"\n    )\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Season-level summary\ncranes %>%\n  filter(!is.na(observations)) %>%\n  group_by(season) %>%\n  dplyr::summarise(\n    n_counts      = dplyr::n(),\n    median_obs    = median(observations),\n    max_obs       = max(observations),\n    mean_obs      = round(mean(observations))\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  season n_counts median_obs max_obs mean_obs\n  <chr>     <int>      <dbl>   <dbl>    <dbl>\n1 Fall        264       5570   24300     6691\n2 Spring     1050       4600   27300     6190\n3 Summer       73       1780    5710     1978\n```\n\n\n:::\n:::\n\n\n\nSpring dominates: 1,050 of the 1,387 valid observation days fall in March–May, with a median of 4,600 cranes. Fall provides 264 valid counts (median: 5,570), while the small number of August \"summer\" counts (n=73) mostly capture early arriving birds before the main fall passage.\n\n# Domain Analysis: Three Decades of Recovery\n\n::: {.callout-note}\n**Lake Hornborgasjön and the Crane's Return**\n\nLake Hornborgasjön in Västergötland, Sweden, was once one of the country's most biodiverse wetlands. A century of drainage attempts to convert it to farmland collapsed its ecology. In the late 1980s, a major restoration project raised the water level by 1.5 meters, recovering shallow reed beds and open water habitat. The Eurasian crane (*Grus grus*) responded almost immediately — counts began in 1994 as the habitat re-established itself.\n\nToday Hornborgasjön hosts one of Europe's largest crane congregations during spring migration, often attracting more than 20,000 birds at peak. The Swedish \"cranewatch\" webcam draws hundreds of thousands of online viewers every spring.\n:::\n\n## Annual peak counts: a population story\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nannual_peaks <- cranes %>%\n  filter(!is.na(observations)) %>%\n  dplyr::group_by(year) %>%\n  dplyr::summarise(\n    n_days     = dplyr::n(),\n    peak_count = max(observations),\n    median_obs = median(observations),\n    peak_date  = date[which.max(observations)],\n    peak_doy   = lubridate::yday(peak_date),\n    peak_month = lubridate::month(peak_date, label = TRUE)\n  ) %>%\n  dplyr::ungroup()\n\ncat(sprintf(\"annual_peaks: %d rows, %d cols\\n\", nrow(annual_peaks), ncol(annual_peaks)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nannual_peaks: 31 rows, 7 cols\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"annual_peaks has 0 rows\" = nrow(annual_peaks) > 0)\n\nprint(annual_peaks, n = 31)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 31 × 7\n    year n_days peak_count median_obs peak_date  peak_doy peak_month\n   <dbl>  <int>      <dbl>      <dbl> <date>        <dbl> <ord>     \n 1  1994     28       4992      3100  1994-04-08       98 Apr       \n 2  1995     37       5280      1907  1995-04-17      107 Apr       \n 3  1996     27       5880      2150  1996-04-18      109 Apr       \n 4  1997     34       6860      3050  1997-04-09       99 Apr       \n 5  1998     36       8625      4932. 1998-04-15      105 Apr       \n 6  1999     31       7800      3775  1999-04-07       97 Apr       \n 7  2000     33       8920      6850  2000-04-09      100 Apr       \n 8  2001     35       6750      2675  2001-04-19      109 Apr       \n 9  2002     53       8760      3800  2002-04-04       94 Apr       \n10  2003     43      11050      3980  2003-04-12      102 Apr       \n11  2004     45      12700      3320  2004-04-05       96 Apr       \n12  2005     51      12100      3420  2005-04-09       99 Apr       \n13  2006     48       9920      2965  2006-04-10      100 Apr       \n14  2007     52      13900      3050  2007-04-01       91 Apr       \n15  2008     55      15300      3380  2008-04-03       94 Apr       \n16  2009     53      18500      3700  2009-04-01       91 Apr       \n17  2010     44      13800      4135  2010-04-03       93 Apr       \n18  2011     47      15400      4750  2011-04-06       96 Apr       \n19  2012     51      26500      6200  2012-04-03       94 Apr       \n20  2013     45      13500      4720  2013-04-14      104 Apr       \n21  2014     54      23000      9665  2014-04-03       93 Apr       \n22  2015     61      19600      8850  2015-04-04       94 Apr       \n23  2016     50      19400      5150  2016-03-30       90 Mar       \n24  2017     52      19700      6025  2017-03-31       90 Mar       \n25  2018     45      24500      6200  2018-04-08       98 Apr       \n26  2019     47      27300     10200  2019-04-03       93 Apr       \n27  2020     50      19200      7600  2020-04-02       93 Apr       \n28  2021     47      17480      5370  2021-04-04       94 Apr       \n29  2022     48      20900      6645  2022-04-02       92 Apr       \n30  2023     43      24300      7000  2023-09-25      268 Sep       \n31  2024     42      24600      8855  2024-04-06       97 Apr       \n```\n\n\n:::\n:::\n\n\n\nThe numbers tell a stark story. In 1994, the all-time high was **4,992 cranes**. By 2019, that figure reached **27,300** — a 5.5× increase in 25 years. The recovery tracks closely with the lake's habitat restoration and the broader recovery of the Eurasian crane population across Europe.\n\nOne observation stands out immediately: the 2023 peak of 24,300 cranes occurred on **September 25** — fall, not spring. Every other year in the dataset peaked in March or April. This anomaly, confirmed by three consecutive \"Record observation\" tags, suggests an extraordinary fall congregation in 2023.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spring peaks — day-of-year timing\nspring_peaks <- annual_peaks %>%\n  filter(peak_month %in% c(\"Mar\", \"Apr\"))\n\ncat(\"Spring peak timing summary:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpring peak timing summary:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\n  \"n spring-peak years: %d\\n\",\n  nrow(spring_peaks)\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn spring-peak years: 30\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\n  \"Interquartile range of peak day-of-year: %.0f – %.0f\\n\",\n  quantile(spring_peaks$peak_doy, 0.25),\n  quantile(spring_peaks$peak_doy, 0.75)\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInterquartile range of peak day-of-year: 93 – 100\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\n  \"Earliest peak: %s (day %.0f)\\n\",\n  format(spring_peaks$peak_date[which.min(spring_peaks$peak_doy)], \"%b %d\"),\n  min(spring_peaks$peak_doy)\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEarliest peak: Mar 30 (day 90)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\n  \"Latest peak:   %s (day %.0f)\\n\",\n  format(spring_peaks$peak_date[which.max(spring_peaks$peak_doy)], \"%b %d\"),\n  max(spring_peaks$peak_doy)\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLatest peak:   Apr 18 (day 109)\n```\n\n\n:::\n:::\n\n\n\nThe spring peak has historically fallen between roughly **late March and mid-April**, with earlier peaks in recent decades suggesting the birds may be shifting their migration timing — a pattern consistent with climate-linked phenological change observed across many migratory species.\n\n## Seasonal rhythm: spring vs. fall passage\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly_summary <- cranes %>%\n  filter(!is.na(observations)) %>%\n  dplyr::group_by(month_name, month) %>%\n  dplyr::summarise(\n    n         = dplyr::n(),\n    median    = median(observations),\n    mean      = round(mean(observations)),\n    max       = max(observations),\n    .groups   = \"drop\"\n  ) %>%\n  dplyr::arrange(month)\n\ncat(sprintf(\"monthly_summary: %d rows\\n\", nrow(monthly_summary)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmonthly_summary: 5 rows\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(\"monthly_summary is empty\" = nrow(monthly_summary) > 0)\n\nprint(monthly_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  month_name month     n median  mean   max\n  <ord>      <dbl> <int>  <dbl> <dbl> <dbl>\n1 Mar            3   413   2100  4870 21900\n2 Apr            4   637   5880  7045 27300\n3 Aug            8    73   1780  1978  5710\n4 Sep            9   185   6170  7391 24300\n5 Oct           10    79   3750  5051 23700\n```\n\n\n:::\n:::\n\n\n\nApril is the peak month by volume (637 valid counts, median 5,880), though September records the highest single-day maximum of all months (24,300 — the 2023 fall record). Spring counts are more numerous because field stations operate more intensively during the well-known spring spectacle; the fall passage is shorter and less predictably timed.\n\n# Visualization\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Ridgeline data: one row per year × day-of-year ----------------------\nridge_data <- cranes %>%\n  filter(!is.na(observations), month %in% 3:10) %>%\n  dplyr::group_by(year, day_of_year) %>%\n  dplyr::summarise(obs = max(observations), .groups = \"drop\") %>%\n  dplyr::mutate(\n    year_f     = factor(year, levels = rev(sort(unique(year)))),\n    year_norm  = (year - min(year)) / (max(year) - min(year))\n  )\n\ncat(sprintf(\"ridge_data: %d rows, %d cols\\n\", nrow(ridge_data), ncol(ridge_data)))\nstopifnot(\"ridge_data is empty\" = nrow(ridge_data) > 0)\n\n# Sanity-check: proportions aren't all the same\nif (length(unique(ridge_data$year_norm)) == 1) {\n  warning(\"year_norm values are all identical — check year range logic\")\n}\n\n# --- Annual peaks for line chart -----------------------------------------\nannual_peaks_plot <- annual_peaks %>%\n  dplyr::mutate(\n    label = dplyr::case_when(\n      year == 2019 ~ \"27,300\\n(all-time spring record)\",\n      year == 2023 ~ \"24,300\\n(fall record)\",\n      year == 1994 ~ \"4,992\\n(first year)\",\n      TRUE ~ NA_character_\n    )\n  )\n\n# --- Palette setup -------------------------------------------------------\n# MetBrewer::Hokusai3 — interpolated for continuous year gradient.\n# Colors: warm yellow-green → teal → deep navy (lake, reeds, water).\n# Thematically: \"Hokusai3\" corresponds to Hokusai woodblock prints of cranes.\nhokusai3_cols <- colorRampPalette(\n  as.character(paletteer::paletteer_d(\"MetBrewer::Hokusai3\"))\n)(31)\n\n# Season label positions (x = midpoint of season in day-of-year)\nseason_labels <- tibble::tibble(\n  x     = c(100, 268),\n  label = c(\"Spring passage\\n(March – May)\", \"Fall passage\\n(Aug – Oct)\")\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Hero: Ridgeline plot ------------------------------------------------\n# Each ridge = one year; height = crane count; fill = year (Hokusai3 gradient)\n\np_ridge <- ggplot2::ggplot(\n  ridge_data,\n  ggplot2::aes(\n    x      = day_of_year,\n    y      = year_f,\n    height = obs / max(obs),\n    fill   = year\n  )\n) +\n  ggridges::geom_ridgeline(\n    scale     = 5.5,\n    alpha     = 0.88,\n    linewidth = 0.2,\n    color     = \"white\"\n  ) +\n  # Season separator lines\n  ggplot2::geom_vline(\n    xintercept = c(60, 152, 244, 305),\n    linetype   = \"dashed\",\n    color      = \"grey60\",\n    linewidth  = 0.35,\n    alpha      = 0.5\n  ) +\n  # Season annotations (top of plot area, manual coordinates)\n  ggplot2::annotate(\n    \"text\", x = 100, y = 33.5, label = \"Spring passage\",\n    size = 3.2, color = \"grey40\", hjust = 0.5, fontface = \"italic\"\n  ) +\n  ggplot2::annotate(\n    \"text\", x = 268, y = 33.5, label = \"Fall passage\",\n    size = 3.2, color = \"grey40\", hjust = 0.5, fontface = \"italic\"\n  ) +\n  # 2023 fall record callout\n  ggplot2::annotate(\n    \"segment\",\n    x = 268, xend = 268, y = 1.5, yend = 3.2,\n    arrow = ggplot2::arrow(length = ggplot2::unit(0.12, \"cm\"), type = \"closed\"),\n    color = \"#D8D97A\", linewidth = 0.6\n  ) +\n  ggplot2::annotate(\n    \"text\", x = 268, y = 3.5, label = \"2023\\nfall record\",\n    size = 2.8, color = \"#D8D97A\", hjust = 0.5, fontface = \"bold\"\n  ) +\n  ggplot2::scale_fill_gradientn(\n    colors = hokusai3_cols,\n    name   = \"Year\"\n  ) +\n  ggplot2::scale_x_continuous(\n    breaks = c(60, 91, 121, 152, 213, 244, 274, 305),\n    labels = c(\"Mar 1\", \"Apr 1\", \"May 1\", \"Jun 1\", \"Aug 1\", \"Sep 1\", \"Oct 1\", \"Nov 1\"),\n    expand = c(0.01, 0)\n  ) +\n  ggplot2::scale_y_discrete(expand = ggplot2::expansion(add = c(0.5, 2))) +\n  ggplot2::labs(\n    title    = \"Thirty Years of Cranes at Hornborgasjön\",\n    subtitle = \"Each ridge shows one year of crane counts (1994–2024).\\nHeight reflects the number of birds observed on that day of the year.\\nColor progresses from early years (yellow-green) to recent years (deep navy).\",\n    x        = NULL,\n    y        = NULL,\n    caption  = \"Data: Hornborgasjön field station via TidyTuesday 2025-09-30 | Palette: MetBrewer::Hokusai3\"\n  ) +\n  ggplot2::theme_minimal(base_size = 11) +\n  ggplot2::theme(\n    plot.title         = ggplot2::element_text(size = 18, face = \"bold\", margin = ggplot2::margin(b = 6)),\n    plot.subtitle      = ggplot2::element_text(size = 10, color = \"grey40\", lineheight = 1.4,\n                                               margin = ggplot2::margin(b = 14)),\n    plot.caption       = ggplot2::element_text(size = 7.5, color = \"grey60\", margin = ggplot2::margin(t = 10)),\n    axis.text.x        = ggplot2::element_text(size = 8.5, color = \"grey50\"),\n    axis.text.y        = ggplot2::element_text(size = 8, color = \"grey50\"),\n    panel.grid.major.x = ggplot2::element_blank(),\n    panel.grid.minor   = ggplot2::element_blank(),\n    panel.grid.major.y = ggplot2::element_line(color = \"grey92\", linewidth = 0.3),\n    legend.position    = \"none\",\n    plot.background    = ggplot2::element_rect(fill = \"white\", color = NA),\n    plot.margin        = ggplot2::margin(16, 20, 12, 16)\n  )\n\np_ridge\n```\n\n::: {.cell-output-display}\n![](2025-09-30-crane-observations-at-lake-hornborgasj-n-sweden-19_files/figure-html/viz-ridgeline-1.png){width=1056}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Secondary: Annual peak count trend ----------------------------------\n\np_line <- ggplot2::ggplot(annual_peaks_plot, ggplot2::aes(x = year, y = peak_count)) +\n  ggplot2::geom_area(fill = \"#5A97C1\", alpha = 0.18) +\n  ggplot2::geom_line(color = \"#295384\", linewidth = 0.9) +\n  ggplot2::geom_point(\n    ggplot2::aes(color = peak_month %in% c(\"Sep\", \"Oct\")),\n    size = 2.2\n  ) +\n  ggplot2::scale_color_manual(\n    values = c(`FALSE` = \"#295384\", `TRUE` = \"#D8D97A\"),\n    labels = c(\"Spring peak\", \"Fall peak\"),\n    name   = \"Peak season\"\n  ) +\n  ggrepel::geom_text_repel(\n    ggplot2::aes(label = label),\n    na.rm          = TRUE,\n    size           = 3.0,\n    color          = \"grey30\",\n    lineheight     = 1.3,\n    nudge_y        = 1800,\n    segment.color  = \"grey60\",\n    segment.size   = 0.3,\n    box.padding    = 0.4,\n    min.segment.length = 0\n  ) +\n  ggplot2::scale_x_continuous(breaks = seq(1994, 2024, by = 4)) +\n  ggplot2::scale_y_continuous(\n    labels = scales::comma,\n    limits = c(0, 32000),\n    expand = ggplot2::expansion(mult = c(0, 0.02))\n  ) +\n  ggplot2::labs(\n    title    = \"Annual Peak Crane Count, 1994–2024\",\n    subtitle = \"Yellow dot marks the anomalous 2023 fall peak — the only non-spring record in 31 years\",\n    x        = NULL,\n    y        = \"Peak cranes observed\",\n    caption  = \"Data: Hornborgasjön field station via TidyTuesday 2025-09-30\"\n  ) +\n  ggplot2::theme_minimal(base_size = 11) +\n  ggplot2::theme(\n    plot.title         = ggplot2::element_text(size = 13, face = \"bold\"),\n    plot.subtitle      = ggplot2::element_text(size = 9.5, color = \"grey40\"),\n    plot.caption       = ggplot2::element_text(size = 7.5, color = \"grey60\"),\n    panel.grid.minor   = ggplot2::element_blank(),\n    panel.grid.major.x = ggplot2::element_blank(),\n    legend.position    = \"bottom\",\n    legend.title       = ggplot2::element_text(size = 8.5),\n    legend.text        = ggplot2::element_text(size = 8),\n    plot.background    = ggplot2::element_rect(fill = \"white\", color = NA),\n    plot.margin        = ggplot2::margin(14, 20, 10, 16)\n  )\n\np_line\n```\n\n::: {.cell-output-display}\n![](2025-09-30-crane-observations-at-lake-hornborgasj-n-sweden-19_files/figure-html/viz-annual-trend-1.png){width=1056}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n# Final thoughts and takeaways\n\nThe cranes of Hornborgasjön are a conservation success story written in daily counts. From a peak of fewer than 5,000 birds in 1994 — the first year after the lake's restoration — the site grew to regularly host more than 20,000 cranes each spring by the 2010s, with the all-time spring record of 27,300 set in April 2019. Wetland restoration works, and these data make that visible with unusual precision.\n\nThree findings deserve emphasis:\n\n**1. The growth is real and large.** The fivefold increase over 30 years isn't noise — it traces the expansion of the European crane population from near-collapse (the species was functionally extirpated from many parts of its range by the mid-20th century) to one of the continent's most visible large-bird recovery stories. Hornborgasjön is both a beneficiary and a symbol of that turnaround.\n\n**2. The 2023 fall season was genuinely anomalous.** Every year from 1994 through 2022 recorded its single-highest count during spring (March–May). In 2023, three consecutive observations in late September — September 18, 21, and 25 — all exceeded anything seen in that year's spring and earned \"Record observation\" status from the field counters. Whether this reflects a true behavioral shift, a favorable autumn weather pattern that concentrated birds at the lake, or something else in the broader flyway isn't answerable from this dataset alone, but it's worth watching.\n\n**3. Spring phenology may be shifting.** The peak-day data shows a subtle pattern: earlier years tended to peak in mid-April (day 100–110), while recent years more often peak in late March or early April (day 90–95). A handful of late-March peaks — 2016, 2017, 2018, 2019, 2022 — would have been exceptional a decade earlier. This is consistent with climate-driven earlier arrival documented for many European migratory species, though formal phenology analysis would require controlling for observer effort and weather.\n\nThe dataset's limitation is also its strength: it's a single fixed monitoring point, so changes in count reflect genuine changes in bird behavior and abundance rather than observer mobility. Thirty years is long enough to see slow trends; the field station's continuity makes the comparison meaningful.\n\n::: {.callout-tip}\n**Data note**: 161 observation records have missing counts (`NA`), nearly all due to canceled counts from bad weather or no-shows by the field crew. These were excluded from all summaries. They are genuinely absent observations, not zero-crane days — including them as zeroes would artificially depress the means.\n:::\n",
    "supporting": [
      "2025-09-30-crane-observations-at-lake-hornborgasj-n-sweden-19_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}